### ISSUE TITLE
Add support for Dagger Integration

### ISSUE THREAD

**Issue by dalewking** [excilys/androidannotations#1013]
This is not a duplicate of issue #510. That one deals with just allowing Dagger and Android Annotations to coexist. This issue is for adding actual code to support dagger injections to the generated subclasses.

Using dagger with Android presents a slight problem in that Android creates objects like Activities and Fragments so Dagger needs help to do the injection. The naive way to do this is override onCreate and get the objectGraph and tell it to inject on the object. This has a code smell because the object that is being injected has to get a reference to the object that does the injecting. You would also like to not have to add boilerplate to your code to do injection.

There are various libraries that try to solve this by creating superclasses to extend from (e.g. https://github.com/adennie/fb-android-dagger) which handle the injection in the super class. I have ran into issues with this however that you might have your own base class you want to use. You could have your base class extend the injecting base class, but then if you have a class that has no injections you get an error at runtime unless you declare in a module that it will inject the class that actually needs no injections.

What I would like to see is for Android Annotations processor to see if the class being enhanced (e.g. an Activity) has any fields annotated with @Inject and if so generate code in the generated class to do the dagger injection. If it has not Inject fields do nothing.

The question then is how does that code do the injection. It has to get an object graph from somewhere to do the injection. That would require additional support and there are many ways to go. One way would be to have an annotation that can be added to the Application object that has a value that is an array of modules. Or you could just look for a class that is annotated with an EBean annotation that implements an interface with a method that returns an Object graph.

For bonus you could support a getModules method on the object that returns additional modules to add to the application one that provides modules scoped to the object. See https://github.com/adennie/fb-android-dagger for an implementation like this.

**Comment by WonderCsabo** [comment]
Unfortunately this cannot be really implemented in AA. Actually this problem is more like with Dagger, and not AndroidAnnotations. I created a [wiki page](https://github.com/excilys/androidannotations/wiki/DaggerIntegration), which describes how to do this in the usual way (calling the injector manually).
If you have better ideas which overcome the issue pointed out by @yDelouis , feel free to share it. Also, we have the plugin architecture now, so any new annotation can be added by creating an AA plugin. :)
