### ISSUE TITLE
Support animation in Activity intent builder

### ISSUE THREAD

**Issue by dalewking** [excilys/androidannotations#1029]
Related to #1027 and sort of an alternative to it.

Since API level 5 you could follow a call to startActivity or finish with a call to overridePendingTransitions to control the animation of the entering and exiting activities. Would be nice if this were supported in the fluent intent builder generated for activities.

I see 2 ways to go with this. First you can have the start methods return an object that implements a withAnimation method so you might have this:

    MyActivity_.intent(this).start().withAnimation(enterAnimation, exitAnimation);

Alternatively, it could be separate methods called before start that save the values for use after starting the activity as in this:

    MyActivity_.intent(this).withEntryAnimation(in).withExitAnimation(out).start();

While the second flows better and does not rely on knowing the order of parameters it potentially could be confusing. If you instead of start called get to get the intent the animation calls did nothing. Its possible to prevent this with additional types, but that is a bit more work on AA coders.

**Comment by WonderCsabo** [comment]
This is no longer blocked by #1039.

**Comment by j1c1m1b1** [comment]
Will this happen anytime soon?

**Comment by dodgex** [comment]
@j1c1m1b1 the PR is available, but develop is currently frozen until the plugin system is ready. if you want this now, you could fork AA and merge the [PR](https://github.com/excilys/androidannotations/issues/1469) and use a custom build until it is released or at least in the official snapsots.

**Comment by WonderCsabo** [comment]
Actually forking is not needed, it is enough to just clone the repo, do the merge and build. But hopefully the plugin system will be ready soon, and the outstanding PRs can be merged.

**Comment by WonderCsabo** [comment]
Implemented, @j1c1m1b1 you can use the 4.0-SNAPSHOT version.
