### ISSUE TITLE
@OptionsItem doesn't allow subclasses to override menu item handling 

### ISSUE THREAD

**Issue by jacobtabak** [excilys/androidannotations#1067]
The generated code for onOptionsItemSelected calls your superclass's onOptionsItemSelected() before the subclass, removing your ability to override functionality in the subclass.  I believe the only workaround is to override onOptionsItemSelected() in your activity (rather than use @OptionsItem annotation) because I don't think there's a way to achieve the same goal using AndroidAnnotations.

Here's the generated code.  My base activity class handles android.R.id.home.

```
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == android.R.id.home) {
            onHomeTapped();
            return true;
        }
        return false;
    }
```

**Comment by WonderCsabo** [comment]
Implemented.
