### ISSUE TITLE
@Deprecated propagation

### ISSUE THREAD

**Issue by geovanisouza92** [excilys/androidannotations#1068]
Hello guys,

I've using AA a lot, and it speedup development in awesome way.

Today, I'd decided to deprecate some ```@Extra```'s and ```@FragmentArg```'s to upgrade some Activity/Fragment API's.

So I think that could be useful annotate the ```@Extra``` field with ```@Deprecated``` and then, the ```IntentBuilder``` method receive this annotation too. For example:

```java
public class SomeFragment extends Fragment {
    @FragmentArg long mSomeArg;
    // ...
}

// SomeFragment usage

fragment = SomeFragment_.builder().mSomeArg(value).build();
```

When I change my API:

```java
public class SomeFragment extends Fragment {
    @Deprecated @FragmentArg long mSomeArg;
    @FragmentArg long mNewArg;
    // ...
}
```

The IDE can help me to upgrade showing the deprecated methods, like:

fragment = SomeFragment_.builder().~~mSomeArg(value)~~.build();

What you think about this?

**Comment by WonderCsabo** [comment]
Closing in favor of #1432.
