### ISSUE TITLE
Issue with Spring 2.0

### ISSUE THREAD

**Issue by westito** [excilys/androidannotations#1140]
```java
/**
* Create a new instance of the {@link RestTemplate} using default settings.
 * Default {@link HttpMessageConverter}s are initialized.
 * @since 2.0 registers a default set of {@link HttpMessageConverter}s
*/
```
Spring 2.0 registers default converters. My converter will be the last, so default GSON captures everything, not my extended one.

Solving: RestTemplate(boolean registerDefaultConverters) use the new constructor with false in generated code.

I also post an issue to spring, to change the default constructor for backward compatibilitiy

**Comment by WonderCsabo** [comment]
Finally implemented.
