### ISSUE TITLE
Override @OptionsMenu declared from super classes.

### ISSUE THREAD

**Issue by mathieudebrito** [excilys/androidannotations#1156]
Hi there, It would be cool to be able to override OptionsMenu declared from super classes.
It would be really appreciated especially for stacked fragments.
```java
@EActivity
@OptionsMenu(value=R.menu.my_menu, override=true)
public class MyFragment extends Fragment {
  // ...
}
```
Should produce : 
```java
@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
  menu.clear();
  inflater.inflate(my.package.R.menu.rides_menu, menu);
  super.onCreateOptionsMenu(menu, inflater);
}
```
Best

**Comment by WonderCsabo** [comment]
@yDelouis i started implementing the feature and just realized that @mathieudebrito is talking about two things:

* not adding menus from *parent* classes
* cleaning the menu before inflation (so it removes the menu from *other* classes)

I implemented the second case. Should we add another parameter? I mean `override`, which could only add menus from the leaf class.

However, this starts to be too complicated. :confused:

**Comment by mathieudebrito** [comment]
Hi @WonderCsabo, from my point of view, the main idea is to be able to clean the menu before inflating the one that specifies the cleaning options.

It's true that `@OptionsMenu(value=menuResId, override=true)` is misleading. It should be used to override a menu from the superclass.

In my case, `@OptionsMenu(value=menuResId, cleanBeforeInflate=true)` would clean the menu before inflating the new one. So even if a superclass inflated a menu, only the current leaf should be able to display its menu.

```java
@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
  super.onCreateOptionsMenu(menu, inflater);
  menu.clear();
  inflater.inflate(menuResId, menu);
}
```

**Comment by WonderCsabo** [comment]
@mathieudebrito 

> So even if a superclass inflated a menu, only the current leaf should be able to display its menu.

Let's assume we have the following classes:

```java
@EActivity
@OptionsMenu(R.menu.parent)
public class Parent extends Activity {

}

@EActivity
@OptionsMenu(R.menu.child)
public class Child extends Parent {

}
```
the following method will be generated for `Child`:
```java
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(R.menu.parent, menu);
        menuInflater.inflate(R.menu.child, menu);
        return super.onCreateOptionsMenu(menu);
    }
```
So all menus will be added from parent classes' `@OptionsMenu` annotation, and `cleanBeforeInflate` will not help this.

**Comment by mathieudebrito** [comment]
@WonderCsabo You are right, I made a mistake in my comment. Only `override=true` should prevent from displaying parent's menu.


As you said, there are 2 main ideas here : 
#### Override the parent's menu from a child fragment / child activity
`overrideParent=true` should not inflate parent's menu
```java
@EActivity
@OptionsMenu(R.menu.parent)
public class Parent extends Activity {

}

@EActivity
@OptionsMenu(R.menu.child, overrideParent=true)
public class Child extends Parent {

}
```
Should generate : 
```java
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    MenuInflater menuInflater = getMenuInflater();
    menuInflater.inflate(R.menu.child, menu);
    return true; // do not call super.onCreateOptionsMenu(menu, inflater);
}
```

#### Clean menu before inflating a new one
`cleanBeforeInflate=true` should simply clear the menu before inflating it.

```java
@EFragment
@OptionsMenu(R.menu.frg_one)
public class FragmentOne extends Fragment {

}

@EFragment
@OptionsMenu(R.menu.frg_two, cleanBeforeInflate=true)
public class FragmentTwo extends Fragment {

}
```

Should generate : 
```java

 // Fragment One
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    // Usual implementation
}

 // Fragment Two
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    menu.clear();
    MenuInflater menuInflater = getMenuInflater();
    menuInflater.inflate(R.menu.frg_two, menu);
    return true; // or super.onCreateOptionsMenu(menu, inflater);
}
```

**Comment by WonderCsabo** [comment]
I have just one comment:

> return true; // do not call super.onCreateOptionsMenu(menu, inflater);

Maybe this is a third concept actually, since it prevents adding menus from the conventional method. And this also makes impossible for the annotated class to have an entry point for modifying the menu, so this maybe is a bad idea.

**Comment by mathieudebrito** [comment]
@WonderCsabo In this case, we want to override the parent's menu so it does make sense to do not call the super class, right ? When `overrideParent` is not present, we should call `super.onCreateOptionsMenu(menu, inflater);`

**Comment by mathieudebrito** [comment]
Hi, guys, how is this issue going on ?
I still need to override the `onCreateOptionsMenu` method in each fragment T_T

**Comment by WonderCsabo** [comment]
@yDelouis do we want to add the two flags as suggested in https://github.com/excilys/androidannotations/issues/1156#issuecomment-69502841?

**Comment by yDelouis** [comment]
Why not.

**Comment by WonderCsabo** [comment]
@mathieudebrito feel free to contribute, then.

**Comment by WonderCsabo** [comment]
It seems it is too complicated to implement in a compile-time manner.
