### ISSUE TITLE
Add requestFactory in @Rest wiki page

### ISSUE THREAD

**Issue by yDelouis** [excilys/androidannotations#1189]
There is no documentation about how to inject a requestFactory in rest template in the wiki.
We should add a paragraph in the `@Rest` page.

**Comment by WonderCsabo** [comment]
@yDelouis can you add this? I did not use a custom request factory yet. If you create the JavaDoc i can copy it to the wiki.

**Comment by yDelouis** [comment]
I added a paragraph in the wiki. We should add it in the javadoc.
There is nothing particular to write about this. This works just like interceptors.

**Comment by WonderCsabo** [comment]
Thanks! I added it to the JavaDoc.
