### ISSUE TITLE
Order of bean injection in init_() method changes randomly

### ISSUE THREAD

**Issue by WarrenFaith** [excilys/androidannotations#1193]
Using AA 3.1

Is there any way to ensure a specific order of bean injections in the AA method init_()? We are facing some nasty NPE because of dependencies that could be easily resolved when the injection would be done in a specific order.

**Comment by WarrenFaith** [comment]
I made a test project in AS. Can be downloaded here: https://www.dropbox.com/s/4a8xdbqqfbhia7p/AATestCase.zip?dl=0

There are 3 beans that are used in the activity. Use "Build" -> "Rebuild" in AS and check the generated Activity_::init_() method, you will see random order of the beans.

**Comment by WonderCsabo** [comment]
Thanks for your time, creating the test case. However, you said the changing order causes problems in your application. This example does not suffer from such a problem, am i right? Can you create an example which does?

**Comment by WarrenFaith** [comment]
I should have made some notes...
Anyway the project was quite complex (and I am not really able to reproduce it) and we run into the issue, that the order of the beans instance creation was important. Because of the random order there we randomly got NPEs when accessing methods of a bean.

Even though I can't recreate the issue, can you somehow enforce the order within the init_() methods based on the order of the bean annotation?

**Comment by WonderCsabo** [comment]
We cannot enforce it, unfortunately.
