### ISSUE TITLE
Introduce possibility to change GENERATION_SUFFIX

### ISSUE THREAD

**Issue by chpasha** [excilys/androidannotations#1209]
I would be nice to be able to use a generation suffix other then "underscore" - for classes only of course, class members can have the current one. The quick and dirty solution could be to configure it via compilerArgs and OptionsHelper. The better (but more complicated) would be to configure it on class level with AA annotations - e.g @EBean(suffix="Impl") which will produce MyBeanImpl instead of MyBean_ . I know it sounds stupid but it would be great to have more canonical class names inside some reusable lib. What do you think?

**Comment by WonderCsabo** [comment]
Implemented.
