### ISSUE TITLE
Integrate EventBus to AA?

### ISSUE THREAD

**Issue by jiongxuan** [excilys/androidannotations#1237]
Hi, I'm a big fan of AA. I am very grateful that you have made this great open source project!

I had been using [EventBus](https://github.com/greenrobot/EventBus) (not Otto) to deliver a variety of messages. But AA official only recommended Otto wip-2.0. I learned that the author of this version is **no longer maintained**. And EventBus project has been ongoing maintenance.

If EventBus able to use the form **Annotations**, what happens?

Look at the [EventBus official documents](https://github.com/greenrobot/EventBus/blob/master/HOWTO.md). EventBus.register and unregister need to be declared in onStart and onStop respectively, and use up more trouble. 

If we can:

```java
@EActivity
public class DetailActivity extends Activity {

    @Subscribe(SubscribeThread.MAIN)
    public void onNetworkChanged(NetworkChangedEvent event) {
        ....
    }
}
```

Instead:
```java
@EActivity
public class DetailActivity extends Activity {

    public void onStart() {
        super.onStart();
        EventBus.getDefault().register(this);
    }

    public void onStop() {
        super.onStop();
        EventBus.getDefault().unregister(this);
    }

    public void onEvent(NetworkChangedEvent event) {
        ....
    }
}
```
Better?

**I am willing to contribute their part to write this code.** But the premise is that we will need this.

My English not so good. I hope you can understand what I mean.

Thanks a million!

EDIT: According to @WonderCsabo suggestion, remove the "@Bus" annotation in comment.

**Comment by WonderCsabo** [comment]
It seems `Otto` will [walk parent classes soon](https://github.com/square/otto/pull/135). It means we can remove our integration code.

**Comment by dodgex** [comment]
it seems they plan to add annotations to EventBus.
see https://github.com/greenrobot/EventBus/issues/126 and https://github.com/greenrobot/EventBus/pull/130

**Comment by WonderCsabo** [comment]
I am closing this one. EventBus has annotations now. We could still automatically register a bus, but i think that should be moved to a base class, also in that case the client can customize it. It would not remove too much boilerplate.

I suggest to go ahead and try out the annotation support in EventBus, it is great and fast!
