### ISSUE TITLE
Suggest to add "OnKeyXXX" Annotations

### ISSUE THREAD

**Issue by jiongxuan** [excilys/androidannotations#1238]
Which examples looks better?

General:
```java
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.KEYCODE_BACK) {
            return true;
        }

        return super.onKeyDown(keyCode, event);
    }
```

AA which i want to:
```java
    @KeyDown(KeyEvent.KEYCODE_BACK)
    public boolean onPressedBack() {
        return true;
    }
```
**(Same as Key Up/Long Press/Shortcut etc.)**
Support "dispatch" parameters.

Compared with the [EventBus](https://github.com/excilys/androidannotations/issues/1237) I mentioned previously, this looks easier to write, and more practical.
What do you think?

**Comment by WonderCsabo** [comment]
Finally implemented.
