### ISSUE TITLE
onSurfaceCreated or onSurfaceTextureAvailable is never called when using androidannotations

### ISSUE THREAD

**Issue by Maliblu** [excilys/androidannotations#1301]
Hey, first of all thanks a lot for the androidannotations! I am using it a lot in my app, but I have real trouble with surfaceViews and textureViews.

I want to play a background video on the splash screen of my app where users login.

I am using this code sample (http://www.binpress.com/tutorial/video-cropping-with-texture-view/21) and it works fine when I'm not using androidannotations. However, when I'm using androidannotations, the functions onSurfaceCreated for SurfaceView and onSurfaceTextureAvailable are never called. How can I make this work with androidannotations? Thanks a lot.

**Comment by WonderCsabo** [comment]
No answer since a week, i am closing the issue. Please feel free to reopen if you have news on this.
