### ISSUE TITLE
REST on BaseAdapter: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by pewh** [excilys/androidannotations#1304]
My scenario is load REST API (from @Rest) from server & load to BaseAdapter.

When I run it, no data is loaded & it just throw to exception message `Can't create handler inside thread that has not called Looper.prepare()` (see that I use Log.e to trace error exception message). Below is my code:

**Product.java**

    public class Product {
        private int id;
        private String name;
        private String imageUrl;
        private int availableStock;
        private double purchasingPrice;
        private double sellingPrice;

        public Product() {}

        ... hide getter & setter for brevity
    }

**ProductAPI.java**

    @Rest(rootUrl = "http://192.168.42.154:1337/api/v1", converters = {GsonHttpMessageConverter.class, MappingJacksonHttpMessageConverter.class })
    public interface ProductAPI extends RestClientErrorHandling {

        @Get("/products")
        List<Product> getProducts();

    }

**ProductListAdapter .java**

    public class ProductListAdapter extends BaseAdapter {
    
        List<Product> products;
    
    
        public ProductListAdapter(List<Product> products) {
            this.products = products;
        }
    
        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
    
            if (convertView == null) {
                convertView = LayoutInflater.from(parent.getContext())
                        .inflate(R.layout.grid_product, parent, false);
            }
    
            String imageUrl = "http://lorempixel.com/800/600/sports/" + String.valueOf(position + 1);
            convertView.setTag(imageUrl);
    
            ImageView image = (ImageView) convertView.findViewById(R.id.image);
            Picasso.with(convertView.getContext())
                    .load(imageUrl)
                    .into(image);
    
    
            TextView name = (TextView) convertView.findViewById(R.id.name);
            name.setText(getItem(position).toString());
    
            return convertView;
        }
    
        @Override
        public int getCount() {
            return products.size();
        }
    
        @Override
        public Object getItem(int position) {
            return products.get(position);
        }
    
        @Override
        public long getItemId(int position) {
            return products.indexOf(getItem(position));
        }
    }

**HomeActivity.java**

    @EActivity(R.layout.activity_home)
    @OptionsMenu(R.menu.main)
    public class HomeActivity extends BaseActivity {
    
        List<Product> products;
        ProductListAdapter adapter;
    
        @ViewById
        DrawerLayout drawer;
    
        @ViewById
        GridView gridView;
    
        @Bean
        CustomRestErrorHandler restErrorHandler;
    
        @RestService
        ProductAPI productAPI;
    
        @Background
        void searchProducts() {
            try {
                products = productAPI.getProducts();
                initAdapter();
                Log.d("test", String.valueOf(products.size()));
            } catch (Exception e) {
                Log.d("test", e.getMessage());
            }
        }

        @UiThread
        void initAdapter() {
            adapter = new ProductListAdapter(products);
        }
    
        @AfterViews
        void initDrawer() {
            setActionBarIcon(R.drawable.ic_ab_drawer);
            drawer.setDrawerShadow(R.drawable.drawer_shadow, Gravity.START);
            productAPI.setRestErrorHandler(restErrorHandler);
        }
    
        @AfterViews
        void bindAdapter() {
            searchProducts();
    
            gridView.setAdapter(adapter);
            gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
                    String url = (String) view.getTag();
                    Map<String,String> intents = new HashMap<>();
    
                    intents.put("productName", adapter.getItem(i).toString());
                    intents.put("DetailActivity:image", url);
    
                    DetailActivity_.launch(HomeActivity.this, view.findViewById(R.id.image), intents);
                }
            });
        }
    }

Below is the response from `http://192.168.42.154:1337/api/v1/products`:

    [
      {
        "name": "Product 1",
        "imageUrl": "0d47e87c-ec21-4aa5-a051-cdd051d4f1e9.png",
        "availableStock": 23,
        "purchasingPrice": 135000,
        "sellingPrice": 150000,
        "id": 1,
        "createdAt": "2015-01-05T13:00:14.212Z",
        "updatedAt": "2015-01-05T13:00:14.212Z"
      },
      {
        "name": "Product 2",
        "imageUrl": "02cc5c02-2654-4d6c-ab96-e4179b2bb967.jpg",
        "availableStock": 7,
        "purchasingPrice": 45000,
        "sellingPrice": 60000,
        "id": 2,
        "createdAt": "2015-01-05T13:00:40.451Z",
        "updatedAt": "2015-01-05T13:00:40.451Z"
      }
    ]

**Stacktrace when app is loaded:**

	01-07 08:36:24.232  14504-14522/com.pewh.test E/com.pewh.test: Can't create handler inside thread that has not called Looper.prepare()

Am I do something wrong? :/

**Comment by WonderCsabo** [comment]
I answered on Stackoverflow.

**Comment by pewh** [comment]
Thanks, @WonderCsabo. Your code is work. Sorry for my impatience :)

SO link: http://stackoverflow.com/questions/27793557/androidannotations-using-rest-with-baseadapter-throw-cant-create-handler-insid

**Comment by WonderCsabo** [comment]
No problem.
