### ISSUE TITLE
Android Annotation fragment setUserVisibleHint method don't invoke ？

### ISSUE THREAD

**Issue by huangsanm** [excilys/androidannotations#1305]
HI，I rewrite setUserVisibleHint method fragment inside
but, the method don't have invoke?
or
How to make view initialization time in fragment？
have some good suggest？
thank you!

**Comment by WonderCsabo** [comment]
I do not understand. Can you please clarify?

**Comment by WonderCsabo** [comment]
Can you post more code? What does not get invoked?

**Comment by huangsanm** [comment]
hi，this is my fragment
@EFragment(R.layout.fragment_channel)
public class ChannelFragment extends Fragment implements ViewPager.OnPageChangeListener{

    private MainTabActivity mActivity;

    @ViewById(R.id.channel_horizontal)
    HorizontalScrollView mHorizontalScrollView;
    @ViewById(R.id.channel_channel)
    RadioGroup mChannelRadioGroup;
    @ViewById(R.id.channel_pager)
    ViewPager mNewsViewPager;
    @ViewById(R.id.channel_cursor)
    ImageView mCursorImageView;
    //private int mOffset;
    //private int mPreviousPage;

    @SystemService LayoutInflater mInflater;

    //缓存上次选中的tag
    private int mViewID;

    private List<Channel> mChannelList;
    private List<Fragment> mFragmentList;
    private NewsFragmentPagerAdapter mFragmentPagerAdapter;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mActivity = (MainTabActivity) getActivity();

        mFragmentList = new ArrayList<>();
        mFragmentPagerAdapter = new NewsFragmentPagerAdapter(mActivity.getSupportFragmentManager(), mFragmentList);

        mChannelList = new ArrayList<>();
    }

//this method don't invoking
    @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        if (isVisibleToUser) {
            mActivity.log("dddddddddddddd");
        }
    }

    @AfterViews void buildComponent(){
        setViewPagerScrollSpeed();
        mChannelList.clear();
        mChannelList.add(new Channel(1, "要闻"));
        mChannelList.add(new Channel(2, "科技"));
        mChannelList.add(new Channel(3, "娱乐"));
        mChannelList.add(new Channel(4, "数码"));
        mChannelList.add(new Channel(6, "汽车"));
        mChannelList.add(new Channel(7, "军事"));
        mChannelList.add(new Channel(8, "电影"));
        mChannelList.add(new Channel(9, "头条"));
        mChannelList.add(new Channel(10, "焦点"));
        mChannelList.add(new Channel(11, "本地"));

        mNewsViewPager.setOnPageChangeListener(this);
        mNewsViewPager.setAdapter(mFragmentPagerAdapter);
        //mNewsViewPager.setOffscreenPageLimit(3);

        addChannelItem(mChannelList);
    }

    private void addChannelItem(List<Channel> list){
        if(list != null){
            final int size = list.size();
            mFragmentList.clear();
            mFragmentPagerAdapter.notifyDataSetChanged();
            mChannelRadioGroup.removeAllViews();
            for (int i = 0; i < size; i++) {
                Channel c = list.get(i);
                mChannelRadioGroup.addView(createChannelRadioButton(c, i), i);
            }

            for(int i = 0; i < size; i ++){
                //初始化fragment
                mFragmentList.add(new NewsFragment_());
                mFragmentPagerAdapter.notifyDataSetChanged();
            }

            ((RadioButton) mChannelRadioGroup.findViewById(0)).setChecked(true);
        }
    }

    private RadioButton createChannelRadioButton(Channel c, final int index){
        final RadioButton childView = (RadioButton) mInflater.inflate(R.layout.news_channel_item, null);
        childView.setText(c.getName());
        childView.setTag(c.getId());
        childView.setId(index);
        childView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mNewsViewPager.setCurrentItem(index);
            }
        });
        return childView;
    }


    @Override
    public void onPageSelected(int position) {
        View childView = mChannelRadioGroup.findViewById(position);
        //执行点击事件
        childView.performClick();
        int childWidth = childView.getMeasuredWidth();
        int left = childView.getLeft();
        int scrollWidth = left + childWidth / 2 - mActivity.getScreenWidth() / 2;
        mHorizontalScrollView.smoothScrollTo(scrollWidth, 0);

        /*final int width = childView.getMeasuredWidth();
        mOffset = width;
        mCursorImageView.getLayoutParams().width = width;
        final int scrollX = mHorizontalScrollView.getScrollX();
        float formXDelta = 0f;
        float toXDelta = 0f;
        if(scrollWidth > 0){
            formXDelta = mOffset * mPreviousPage - scrollWidth;
            toXDelta = mOffset * position - scrollWidth;
        }else{
            formXDelta = mOffset * mPreviousPage;
            toXDelta = mOffset * position;
        }
        Animation animation = new TranslateAnimation(formXDelta, toXDelta, 0, 0);
        mPreviousPage = position;
        animation.setFillAfter(true);
        animation.setDuration(100);
        mCursorImageView.startAnimation(animation);*/
    }

    @Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

    }

    @Override
    public void onPageScrollStateChanged(int state) {

    }

    private void setViewPagerScrollSpeed(){
        try {
            Field mScroller = ViewPager.class.getDeclaredField("mScroller");
            mScroller.setAccessible(true);
            FixedSpeedScroller scroller = new FixedSpeedScroller( mNewsViewPager.getContext( ) );
            mScroller.set( mNewsViewPager, scroller);
        }catch(NoSuchFieldException e){

        }catch (IllegalArgumentException e){

        }catch (IllegalAccessException e){

        }
    }
}

**Comment by WonderCsabo** [comment]
What do you mean that it is not invoking? I think you should invoke that method from somewhere, it is not invoked by the system automatically.

**Comment by huangsanm** [comment]
HI，I look fragment dev guide, found this:
"Set a hint to the system about whether this fragment's UI is currently visible
      to the user. This hint defaults to true and is persistent across fragment instance
      state save and restore."

    public void setUserVisibleHint(boolean isVisibleToUser) {
        if (!mUserVisibleHint && isVisibleToUser && mState < STARTED) {
            mFragmentManager.performPendingDeferredStart(this);
        }
        mUserVisibleHint = isVisibleToUser;
        mDeferStart = !isVisibleToUser;
    }

**Comment by huangsanm** [comment]
thanks!
