### ISSUE TITLE
roboguice url was old in wiki

### ISSUE THREAD

**Issue by LittleKey** [excilys/androidannotations#1306]
The `roboguice` repository url was old in wiki FAQ

[How do you compare to RoboGuice] (https://github.com/excilys/androidannotations/wiki/FAQ#compare-roboguice)

its jump to google code, but `roboguice` repo was moved on github

`https://github.com/roboguice/roboguice/`

sorry sir, i'm not good at English...:)

**Comment by WonderCsabo** [comment]
Thanks for the notification! I updated the URL.
