### ISSUE TITLE
The onPrepareOptionsMenu method may be called before Bean-objects injection.

### ISSUE THREAD

**Issue by maximzhemerenko** [excilys/androidannotations#1308]
Usually onPrepareOptionsMenu method is called after all bean-objects have been injected, but in Android 4.1.1, 4.1.2 and possibly in other versions it happens vice versa.
This unexpected behavior may cause NullPointerException.

Method init_(Bundle savedInstanceState) (in generated class that extends Activity or Fragment) calls setHasOptionsMenu(true), which may have different implementations in various Android versions.
In this case it calls onPrepareOptionsMenu method immediately, but in Android 4.2+ versions onPrepareOptionsMenu call is postponed.
That's why it would be better to improve AndroidAnnotations lib to exclude calling onPrepareOptionsMenu method before bean-objects (and others) are injected.

In development we are using AndroidAnnotations version of 3.2.

**Comment by WonderCsabo** [comment]
I think we only use `setHasOptionsMenu()` in generated `Fragment`s.

> That's why it would be better to improve AndroidAnnotations lib to exclude calling onPrepareOptionsMenu method before bean-objects (and others) are injected.

This is not clear. What are you proposing exactly?

**Comment by maximzhemerenko** [comment]
At this time we have this autogenerated code (for Fragment): 
```
private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
        setHasOptionsMenu(true); // !!!
        adapter = PhotoListViewAdapter_.getInstance_(getActivity());
        authManager = AuthManager_.getInstance_(getActivity());
        alertDialogHelper = AlertDialogHelper_.getInstance_(getActivity());
        restoreSavedInstanceState_(savedInstanceState);
        initData();
}
```
In our opinion we should call `setHasOptionsMenu(true)` method in last turn after all data have been initialized.
Something like that:
```
private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
        adapter = PhotoListViewAdapter_.getInstance_(getActivity());
        authManager = AuthManager_.getInstance_(getActivity());
        alertDialogHelper = AlertDialogHelper_.getInstance_(getActivity());
        restoreSavedInstanceState_(savedInstanceState);
        initData();
	
        setHasOptionsMenu(true);  // !!!
}
```
Then it would be safe to use any class' fields in the `onPrepareOptionsMenu()` method in various Android versions.

**Comment by WonderCsabo** [comment]
So basically you want to use the AA injected fields in `onPrepareOptionsMenu()`?

**Comment by maximzhemerenko** [comment]
Yes, you are right.

**Comment by privettoli** [comment]
I also want this feature. How to manage my menus.

**Comment by WonderCsabo** [comment]
Unfortunately we only guarantee that injected fields are available from the `@AfterInject` annotated method and so on.

However, we can move the processing order to inject the fields first. Just by moving the handlers in the `AnnotationHandlers` class. @yDelouis WDYT?

**Comment by yDelouis** [comment]
I'm okay with changing the order of the handlers.

**Comment by WonderCsabo** [comment]
Implemented.
