### ISSUE TITLE
@Trace problems

### ISSUE THREAD

**Issue by kurak38** [excilys/androidannotations#1311]
Hi,
I have some problems with configuring @Trace.
One thing is that it would be nice to add default values for properties described here https://github.com/excilys/androidannotations/wiki/CustomizeAnnotationProcessing

So I had to add "trace true" to enable logging when using @Trace. 
However adding "logLevel TRACE" gives me an error:
Error:(54, 0) Could not find property 'TRACE' on project ':app'.

Specifying tag and level in code:
 @Trace(tag = "MyTag", level = Log.DEBUG)
results in no trace log at all.

I was only able to make it working with just "@Trace" annotation and "trace true" apt argument. And what I want to do is to change the level from INFO to DEBUG.
Also question: is it possible to redirect the output of that @Trace to file?

AA version 3.2
Android Studio 1.0.2
Android-Apt 1.4

**Comment by WonderCsabo** [comment]
> However adding "logLevel TRACE" gives me an error:
Error:(54, 0) Could not find property 'TRACE' on project ':app'.

The example in the wiki page is incorrect. You have to use a string, so add `'` around `TRACE`, like:
```groovy
logLevel 'TRACE'
```

However, `logLevel` has nothing to do with `@Trace`, it is for the logging messages which are printed during annotation processing.

> Also question: is it possible to redirect the output of that @Trace to file?

No, but we already have a feature request for customizing the `@Trace` logger #1200.

**Comment by WonderCsabo** [comment]
I fixed the example in the wiki page. For redirecting output, see the referenced issue.
