### ISSUE TITLE
Package generated rest client in independent reusable jar file.

### ISSUE THREAD

**Issue by mnesarco** [excilys/androidannotations#1314]
It would be great if I can package my Rest client classes in an independent jar to be redistributed among several teams. Is it possible? By this way I can create my own redistributable backend api sdk.

**Comment by WonderCsabo** [comment]
I am pretty sure there are maven as well gradle plugins to package only a subset of your generated classes to another jar. For example, check out [this](http://blog.sonatype.com/2010/01/how-to-create-two-jars-from-one-project-and-why-you-shouldnt/#.VMJwti7VeVA).

**Comment by WonderCsabo** [comment]
BTW, if you want to redistribute that, i strongly suggest to move it to another module as the referenced post says. Please note that AA can work with Android library projects, and you can still package an AAR or jar from it.

**Comment by WonderCsabo** [comment]
I am closing this issue, because it is not directly related to this project, but the build / packaging tool of your project.
