### ISSUE TITLE
@SharedPref Bug's must be written documentation

### ISSUE THREAD

**Issue by YoonSung** [excilys/androidannotations#1315]
At First, Thanks for this excellent Android Annotation Library. It helps me who is a newbie to Android annotation. A lot.

But I had an proposal on your Library document.

I read document cookbook, but I faced a bug on Unexpected SharedPreference Annotation.

I spent 4 hours to figure it out and solve the problem. 

Finally I found this link. (https://github.com/excilys/androidannotations/wiki/FAQ#import)

For your information and others who could face the same problem as mine, I think it would better be written on your document.

(to https://github.com/excilys/androidannotations/wiki/SharedPreferencesHelpers)

**Comment by WonderCsabo** [comment]
@YoonSung i am sorry that you have problems with this, and i am glad that you finally resolved that. However, please note that this is not `@SharedPref` specific, unfortunately it can apply to any generated class. So i do not suggest to add that link to the `@SharedPref` wiki. The good news is, this bug has been fixed in Eclipse Luna.

**Comment by YoonSung** [comment]
In case of my problem, 
the error did not occur only when the class declared @Shared 
and the classes using declared class are all in the same package.

Also, I am using Android Studio instead of Eclipse now. Is there any suggestion for me?

Thanks for your kind answer :)

**Comment by WonderCsabo** [comment]
Please provide your code.

**Comment by YoonSung** [comment]
Oh. I found Solution. I had to use appropriate repackaging and right declaration (import *)
Error is disappear.

@WonderCsabo Thanks a lot :)
