### ISSUE TITLE
Checkable Custom Views

### ISSUE THREAD

**Issue by j1c1m1b1** [excilys/androidannotations#1316]
I've been working with annotations for some time and it works really well. However I created a custom view that is going to be displayed multiple times through an adapter, that fills a list view. The views are correctly displayed within the list view, but my problem is that my custom view is checkable. 

I set the listview's choice mode to be SINGLE_CHOICE and my custom view implements checkable, but nothing happens when I click the view. I even made a click listener for the custom view within the getView(...) method of my adapter, but the event never triggers.

Am I doing something wrong or annotations doesn't support checkable views yet?

I thank you beforehand for your answers.

**Comment by WonderCsabo** [comment]
I do not think this is caused by us. However can you provide some code?

**Comment by j1c1m1b1** [comment]
OK, here goes some code:

# Address View (Custom View Group)

`@EViewGroup(R.layout.layout_address)`
`public class AddressView extends LinearLayout implements Checkable{`

    @ViewById
    TextView tvAddressName;

    @ViewById
    TextView tvAddress;

    @ViewById
    RadioButton check;

    @ViewById
    ImageView ivOptions;

    @ViewById
    ImageView ivDefault;

    public AddressView(Context context) {
        super(context);
    }

    public void bind(String addressName, String address, boolean isDefault, boolean isSelected)
    {
        /*
        tvAddress = (TextView)findViewById(R.id.tvAddress);

        tvAddressName = (TextView)findViewById(R.id.tvAddressName);

        check = (RadioButton)findViewById(R.id.check);

        ivOptions = (ImageView)findViewById(R.id.ivOptions);

        ivDefault = (ImageView)findViewById(R.id.ivDefault);
        */

        tvAddress.setText(address);

        tvAddressName.setText(addressName);

        check.setChecked(isSelected);

        if(isDefault)
        {
            ivDefault.setVisibility(VISIBLE);
        }
        else
        {
            ivDefault.setVisibility(INVISIBLE);
        }
  
    }

    @Override
    public void setChecked(boolean checked) {
        check.setChecked(checked);
    }

    @Override
    public boolean isChecked()
    {
        return check.isChecked();
    }

    @Override
    public void toggle() {
        check.setChecked(!isChecked());
    }

    @Click(R.id.ivOptions)
    void edit()
    {
        Toast.makeText(getContext(), "Edit", Toast.LENGTH_SHORT).show();
    }` adkjasldja

# Custom View Layout

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="?android:attr/listPreferredItemHeightLarge"
    android:background="@drawable/tile_back_wood_light"
    android:orientation="vertical"
    android:clickable="true"
    android:focusable="true"
    android:focusableInTouchMode="true"
    android:descendantFocusability="blocksDescendants">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="4dp"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <RadioButton
                android:focusable="false"
                android:id="@+id/check"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginLeft="16dp"
                android:layout_marginStart="16dp"
                android:layout_weight="1"
                android:button="@drawable/check"
                />
            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginLeft="16dp"
                android:layout_marginStart="16dp"
                android:layout_weight="3"
                android:focusable="false"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/tvAddressName"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:ellipsize="end"
                    android:textIsSelectable="false"
                    android:focusable="false"
                    android:paddingLeft="8dp"
                    android:paddingStart="8dp"
                    android:singleLine="true"
                    android:text="Trabajo"
                    android:textColor="@android:color/white"
                    android:textStyle="bold"/>

                <TextView
                    android:id="@+id/tvAddress"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="16dp"
                    android:drawableLeft="@drawable/geo"
                    android:drawableStart="@drawable/geo"
                    android:ellipsize="end"
                    android:focusable="false"
                    android:textIsSelectable="false"
                    android:gravity="center_vertical"
                    android:singleLine="true"
                    android:text="Calle 90 # 19a - 30"
                    android:textColor="@android:color/white"/>

            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="2"
                android:orientation="vertical">

                <ImageView
                    android:id="@+id/ivOptions"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="end"
                    android:focusable="false"
                    android:layout_marginEnd="8dp"
                    android:layout_marginRight="8dp"
                    android:background="@drawable/ic_options"
                    android:contentDescription="@string/app_name"
                    />

                <ImageView
                    android:id="@+id/ivDefault"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_margin="8dp"
                    android:focusable="false"
                    android:background="@drawable/ic_default"
                    android:contentDescription="@string/app_name"
                    android:visibility="invisible"
                    />

            </LinearLayout>

        </LinearLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="24dp"
            android:layout_gravity="top"
            android:focusable="false"
            android:background="@drawable/separator"
            />
    </FrameLayout>

</LinearLayout>
```

The fragment that has the list view has the line : `listAddresses.setChoiceMode(ListView.CHOICE_MODE_SINGLE);`
I've tried making the views no focusable and not clickable without success. I don't know what else to do.  Thank you for your help and your response.

**Comment by WonderCsabo** [comment]
This problem is not related to AA at all. I think what i did was setting `CHOICE_MODE_NONE`, and adding a click listener to the outer view.

But please go to stackoverflow or other forums, since this is not a place to discuss plain Android problems. Thanks. (Unfortunately you may have to remove annotations from your example code, so anybody can understand your question.)

**Comment by j1c1m1b1** [comment]
Thanks a lot for your answer, I will definitely double check my implementation.
