### ISSUE TITLE
doc. image missing

### ISSUE THREAD

**Issue by YoungjaeKim** [excilys/androidannotations#1317]
The  image at link missing:  
https://github.com/excilys/androidannotations/wiki/Enhance%20custom%20views#why-should-i-use-custom-components-

**Comment by WonderCsabo** [comment]
Yeah, we are aware of the problem #1160 . Unfortunately i cannot find the image anywhere.

**Comment by dodgex** [comment]
maybe we should remove it then. same for the link about merge tag on that site.

**Comment by WonderCsabo** [comment]
@pyricau maybe you have that image somewhere?

**Comment by WonderCsabo** [comment]
I replaced the images with links. Thanks for reporting!
