### ISSUE TITLE
Add support for @Export annotation on methods

### ISSUE THREAD

**Issue by codmajik** [excilys/androidannotations#1318]
It would be very helpful if you guys can add @Export annotation support which just exports a function and its annotations to the generated class. 

This would make it possible to use AA with third party and in-house libraries that requires runtime annotation processing.

Example:
Using tinybus with AA

````java
@EActivity
public class MainActivity extends Activity {
    private TinyBus mBus;

    ...

    @Export
    @Subscribe
    public void onShakeEvent(ShakeEvent event) {
        // device has been shaken
    }
}

```` 

should produce
 ````java

public class MainActivity_ extends MainActivity {
    ...

    @Subscribe
    public void onShakeEvent(ShakeEvent event) {
          super.onShakeEvent(event);
    }
}

````

**Comment by WonderCsabo** [comment]
Actually we already do the same for `Otto`.
Also if we override a method, we also copy the annotations from the annotated method.

The only problem if the library only reads annotations from the lead class (that's the case with `Otto` and i guess with `tinybus` also). I think these libraries should query the superclasses, too, which is a reasonable feature, since in OOP design, you could use superclasses even without AA.

So i am not sure we should add this feature. Implementing this would be easy though. @yDelouis, @DayS, @dodgex WDYT?

**Comment by dodgex** [comment]
i too think that the libraries should scan superclasses.

i'd not implement this in the AA core but rather as plugin.

**Comment by yDelouis** [comment]
I agree with @dodgex.

**Comment by beworker** [comment]
The main reason why `tinybus` doesn't scan superclasses is the runtime performance loss, which is inevitable is this case. Some kind of design-time annotation propagation would really help to keep performance intact. We would also have apps running less complex code, which helps to optimize battery consumption.

**Comment by dodgex** [comment]
@beworker sure. but if AA starts to support all 3rd party libs that check annotations but not in superclasses our code would fast become messy.

as mentioned earlier, we can support this in the future but the plugin system has to be finished that such features can be implemented as plugin and not core part of AA.

**Comment by beworker** [comment]
@codmajik alternatively you can use inner event handlers. In this case you don't need to export activity methods at all.

```java
@EActivity
public class MainActivity extends Activity {
    private TinyBus mBus;

    private Object mEventHandlers = new Object() {
        @Subscribe
        public void onShakeEvent(ShakeEvent event) {
            // device has been shaken
        }
        ... more subscribers
    };

    @Override
    protected void onStart() {
        super.onStart();
        mBus.register(mEventHandlers);
    }
   
   ...
}
```

**Comment by WonderCsabo** [comment]
I am wondering, if we add this, we can drop our `Otto` support. However, it would be inconvenient for `Otto` users. On the other hand, `Otto` should have get class hierarchy walking soon, so we will able to drop support anyway.

**Comment by dodgex** [comment]
@WonderCsabo i do not think if we should add support. we should focus on getting the plugin system ready so that we (or the TinyBus project) can provide this as plugins. 

And for now one can use the workaround that @beworker suggested.

**Comment by WonderCsabo** [comment]
I am closing this for now. This can be implemented as a plugin by anyone, if needed.
