### ISSUE TITLE
Add Support to @LayoutRes in View fields

### ISSUE THREAD

**Issue by rafaeltoledo** [excilys/androidannotations#1319]
Would be great if I can declare a View field, annotate it with @LayoutRes(R.layout.some_layout) and get it auto inflated.

**Comment by WonderCsabo** [comment]
Sorry, but i do not think it would be a good idea. All our annotations are used to "inject" something which already exists. This would create a new object instead. Also, we inject reusable things, but inflating a new View to the field does not makes much sense. Also, when you inflate something, you should provide the parent View, which is not possible in this case.

**Comment by WonderCsabo** [comment]
Since there are no further comments, i am closing this for now. Feel free to reopen if you have anything to share.
