### ISSUE TITLE
Generate shared preference name as a constant

### ISSUE THREAD

**Issue by zsoltk** [excilys/androidannotations#1322]
Right now Prefs are generated this way for a @SharedPref with UNIQUE scope:

```java
public final class AccountPrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public AccountPrefs_(Context context) {
        super(context.getSharedPreferences("AccountPrefs", 0));
        this.context_ = context;
    }
```

The shared preference name is in a magic string. Even https://github.com/excilys/androidannotations/wiki/SharedPreferencesHelpers suggest I should create a constant where I need to use it. But this design is fragile. If you need to change the scope from UNIQUE to something else, the generated magic string will change, too, and client code will not know about it.

Proposal: why not generate the name right there in a constant like this, so that it can be referenced from the outside:

```java
public final class AccountPrefs_
    extends SharedPreferencesHelper
{
    public static final String NAME = "AccountPrefs";

    private Context context_;

    public AccountPrefs_(Context context) {
        super(context.getSharedPreferences(NAME, 0));
        this.context_ = context;
    }
```

**Comment by WonderCsabo** [comment]
I do not think it is a magic string in this case. The JavaDoc says for `UNIQUE`:

> The name of the SharedPreference will be the name of the annotated interface.

Therefore, you can safely use:

```java
getPreferenceManager().setSharedPreferencesName(AccountPrefs.class.getSimpleName());
```

However, your proposition is still more convenient, and reasonable and even more useful for the other cases. Wanna contribute?

**Comment by zsoltk** [comment]
Sure, I'd like to!

**Comment by WonderCsabo** [comment]
We are waiting for your PR, then. :smile:  If you need any information about contributing, do not hesitate asking in the [mailing list](https://groups.google.com/forum/#!forum/androidannotations).

**Comment by zsoltk** [comment]
The problem here is that scopes `ACTIVITY` and `ACTIVITY_DEFAULT` generate their names runtime, using the injected Context object. Generating a static string this way is not possible.

To step back a little and have an argument with myself: my main intention at the posting of this issue was to alleviate using classnames as strings in PreferenceActivity / PreferenceFragment classes binding them to the correctly named prefs.

However, at closer inspection this only makes sense when using `UNIQUE` scope, as:
* `ACTIVITY` & `ACTIVITY_DEFAULT` are intended to be used inside of their enclosing Activity, and you don't want to use them in a PreferenceActivity / PreferenceFragment, or anywhere outside of it
* `APPLICATION_DEFAULT` doesn't need a name at all.

Using a string with `UNIQUE` scope has the only danger of not following the change if inside of SharedPrefHandler the name generation logic would *ever* change from `AccountPrefs.class.getSimpleName()` to anything else. Which I guess is pretty unlikely, isn't it? 

It would still look better to me to use the very same constant inside and outside of the generated class, but all the hassle seems like an unnecessary overkill.

What do you think?

**Comment by WonderCsabo** [comment]
Your reasoning seems to be correct.

However, i still think we could move the name to a constant, it only needs a small patch.

**Comment by WonderCsabo** [comment]
Thinking again, this is indeed an overkill, i am closing this issue.
