### ISSUE TITLE
@InstanceState Bundle bundle makes StackOverflowError

### ISSUE THREAD

**Issue by YoungjaeKim** [excilys/androidannotations#1324]
When we code as below, it generates as follows,
```
	@InstanceState
	Bundle mBundle;

```
```
    @Override
    public void onSaveInstanceState(Bundle bundle) {
        super.onSaveInstanceState(bundle);
        bundle.putBundle("mBundle", mBundle);
    }
```

But, accidently when we code as below,
```
	@InstanceState
	Bundle bundle;
```
AA generates as below, as you expected.
```
    @Override
    public void onSaveInstanceState(Bundle bundle) {
        super.onSaveInstanceState(bundle);
        bundle.putBundle("bundle", bundle);
    }
```

This makes StackOverflowError due to infinite loop to do writeToParcel job, similar to the issue shown in the link: http://stackoverflow.com/a/15787218/361100

It would be good to throw an error when `@InstanceState` has variable named `bundle`.

**Comment by WonderCsabo** [comment]
Thanks for the detailed bug report.

Actually we do not have to invalidate this completely normal code, we can fix this two ways:

* Adding an explicit `this` before the field reference: `bundle.putBundle("bundle", this.bundle)`. This is the safest way, however the generated code will contain unnecessary `this`s.
* Changing the parameter name to `bundle_` to make sure there is no collision.

@yDelouis @dodgex WDYT? I would vote for the second.

**Comment by yDelouis** [comment]
Both look good to me. 
The first seems cleaner.
The second easier (but the developper won't be able to use `bundle_` as the name of the field.)

**Comment by dodgex** [comment]
vote for the first.

no matter what name the parameter is, there is always a chance for such a collision in the second case.

**Comment by YoungjaeKim** [comment]
Thanks for the quick response.
I may not have voting ticket, but support first one.

**Comment by WonderCsabo** [comment]
@dodgex i decided to go with `bundle_`. Actually we used this method all across AA codebase. Users generally do not (and should not) use that field name, since it is against the Java coding conventions. We can assume they do not use it in practice. :)

**Comment by dodgex** [comment]
@WonderCsabo i'm fine with this. you asked, i answered.

**Comment by WonderCsabo** [comment]
OK, and thanks.

**Comment by YoungjaeKim** [comment]
:+1:

**Comment by YoungjaeKim** [comment]
may I close this issue then?

**Comment by WonderCsabo** [comment]
@YoungjaeKim It will be closed automatically once the pull request is merged.

**Comment by YoungjaeKim** [comment]
@WonderCsabo  Ok. got it. thanks for your quick fix. thanks.

**Comment by dodgex** [comment]
btw... @WonderCsabo `since it is against the Java coding conventions` one could use that against your decision :stuck_out_tongue_winking_eye:
