### ISSUE TITLE
@EIntentService IntentBuilder's chaining of @ServiceActions is misleading

### ISSUE THREAD

**Issue by saschoar** [excilys/androidannotations#1326]
When you have annotated your `IntentService` with [`@EIntentService`](
https://github.com/excilys/androidannotations/wiki/Enhance-IntentServices) and have annotated multiple methods with `@ServiceAction`, you can use the IntentBuilder like this:

`MyService_.intent(context).myServiceActionOne().myServiceActionTwo().start();`

However, only the last action (`myServiceActionTwo()` in this case) will be executed, because the intent data is replaced. Please consider adding a hint to the documentation.

**Comment by WonderCsabo** [comment]
It would be better to return an object from these action methods which only
has a start() method. This way we can enforce the correct usage at compile
time.

**Comment by WonderCsabo** [comment]
@yDelouis, @dodgex WDYT?

**Comment by dodgex** [comment]
i think `start()` and `get()` and maybe similar. but only those related to the actual intent for this related action.

**Comment by yDelouis** [comment]
I'm okay with your proposal, @WonderCsabo. I hope it won't be too hard to implement.

**Comment by WonderCsabo** [comment]
The implementation is problematic, so i updated the doc and leave the builder as it is.
