### ISSUE TITLE
OnActivityResult @Extra paremeter problem

### ISSUE THREAD

**Issue by mseroczynski** [excilys/androidannotations#1331]
I've tried to follow examples you've provided here https://github.com/excilys/androidannotations/wiki/OnActivityResult

    @OnActivityResult(PICK_CAR_REQUEST)
    public void onResult(@Extra(value = Intents.Extras.CAR_MODEL_ID) String carModelId) { }

When i'm trying to compile this code Android Studio 1.1 yells "'@Extra' not applicable to parameter".

**Comment by WonderCsabo** [comment]
I think you are using the [`@Extra`](https://github.com/excilys/androidannotations/wiki/Extras) annotation, instead of `@OnActivityResult.Extra`.

**Comment by mseroczynski** [comment]
Yeah, just figured it out and came back here to delete the post or sth but, damn, help came so fast, thanks ;)

**Comment by WonderCsabo** [comment]
You are welcome.

> Please next time for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
