### ISSUE TITLE
Getting original Intent when using @EIntentService

### ISSUE THREAD

**Issue by SimenB** [excilys/androidannotations#1332]
Hi!

This is probably just me misunderstanding how to use it...

I have a class annotated with `@EIntentService`. In that, I have a method annotated with `@ServiceAction` with the parameter `final Intent intent`.

What I'd like to get as parameter is the original intent, but what AA generates tries to find an intent called intent within Extras.

```java
@Override
public void onHandleIntent(Intent intent) {
    GcmIntentService_.super.onHandleIntent(intent);
    String action = intent.getAction();
    if (ACTION.equals(action)) {
        Bundle extras = intent.getExtras();
        if (extras!= null) {
            Intent intentExtra = extras.getParcelable(INTENT_EXTRA);
            super.action(intentExtra);
            return ;
        }
    }
}
```

How can I get the method to be called using the original intent instead of one inside Extras?

The reason I want to use `@EIntentService` is to use DI.

Either way, thanks for an absolutely fantastic library!

**Comment by WonderCsabo** [comment]
`@ServiceAction` is a convenient way to remove boilerplate regarding the `Intent` processing. All method parameters of a `@ServiceAction` annotated method are interpreted as extras. If you want the original `Intent`, just override `onHandleIntent`, and do whatever you want with it. Actually yo do not have to use `@ServiceAction` at all.

**Comment by SimenB** [comment]
`onHandleIntent` gets overriden in the generated code. Like I said, I'd like to be able to use DI, and without annotating the `IntentService` I can't do that. At least from my understanding.

Using `@EBean` doesn't work either

**Comment by WonderCsabo** [comment]
Two things:

* `onHandleIntent` only gets overridden if you have `@ServiceAction` methods
* even if its gets overridden, it will call your implementation (as you can see in your pasted code)

**Comment by SimenB** [comment]
Ahhhhh. Of course. Like I suspected, the problem was just me being stupid. Thanks for the help :smile:
