### ISSUE TITLE
Feature Request add @Patch to RestClient

### ISSUE THREAD

**Issue by bperin** [excilys/androidannotations#1333]
I found myself needing to send patch requests and it seems like a pretty straight forward thing and dont want to use a different rest client but can't figure out a hack yet. Any suggestions?

Spring Android https://github.com/spring-projects/spring-android has patch support as of 2.0.0-snapshot

**Comment by WonderCsabo** [comment]
We do not support 2.0.0, yet. See #1140.

**Comment by bperin** [comment]
Can you think of a hack? I tried taking my generated apiclient code and making it a regular non generated class and put the method as patch but spring framework still throws an error

03-02 16:23:52.463: W/System.err(3129): org.springframework.web.client.ResourceAccessException: I/O error on PATCH request for "xxx": Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]; nested exception is java.net.ProtocolException: Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]

I also tried to create my own annotation
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.METHOD)
public @interface Patch {
    String value();
}


but it fails in build

**Comment by WonderCsabo** [comment]
Unfortunetaly that will not work.

I think you got your first error because you are trying to use `PATCH` with Spring for Android 1.0.0 which is not supported there. If you trying to update to 2.0.0, it will fail because we do not generate correct code.

Adding an annotation does nothing, you have to also add a corresponding processor.

**Comment by WonderCsabo** [comment]
This is a valid request, but it is blocked by #1140.

**Comment by WonderCsabo** [comment]
This is no longer blocked. Contributions are welcome!

**Comment by bperin** [comment]
Ill revisit this

**Comment by WonderCsabo** [comment]
BTW, i do not really know PATCH. What is the request type and response type in this case? Just like POST?

**Comment by WonderCsabo** [comment]
Implemented.
