### ISSUE TITLE
how to use MyService_..stop();

### ISSUE THREAD

**Issue by sd6352051** [excilys/androidannotations#1334]
This is my code
``` java
@Override
    public void onResume() {
        super.onResume();
        MessageService_.intent(this).start();
    }

    @Override
    public void onPause() {
        super.onPause();
        MessageService_.intent(this).stop();
    }
``` 

I can't stop service,MessageService_.intent(this).stop();Invalid

I use AA v3.2

Thanks

**Comment by WonderCsabo** [comment]
What is exactly the problem you got?

**Comment by sd6352051** [comment]
I want to stop the service. i use MyService_.stop() can't stop,  MyService_.stop() seemed doesn't work

**Comment by WonderCsabo** [comment]
The `stop()` method just calls [`Context.stopService()`](http://developer.android.com/reference/android/content/Context.html#stopService%28android.content.Intent%29), so it must be something on your end.

**Comment by sd6352051** [comment]
Thanks.：）
