### ISSUE TITLE
Documentation should note android API changes

### ISSUE THREAD

**Issue by nenick** [excilys/androidannotations#1336]
The example at https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle contains the part

> // If you're using Android NBS flavors you should use the following line instead of hard-coded packageName
>        // resourcePackageName android.defaultConfig.packageName

With `'com.android.tools.build:gradle:1.1.0'` the `packageName` changed to `applicationId`

**Comment by WonderCsabo** [comment]
According to [this](http://tools.android.com/tech-docs/new-build-system/applicationid-vs-packagename) doc, i think we need the `packagename`, and not the `applicaitonId`:

> The package that is used in your source code to refer to your R class, and to resolve any relative activity/service registrations, continues to be called the "package"

**Comment by WonderCsabo** [comment]
However, it seems the `packaname` is not available anymore in the DSL. It is possible the get it someway?

**Comment by dodgex** [comment]
`resourcePackageName android.defaultConfig.applicationId` is the correct one.

the default config one is the one used for R generation. if it is not set, the `package` set in `<manifest>` is used.

**Comment by WonderCsabo** [comment]
@dodgex are you sure? I just tried it, i set `applicationId` to something, and `package` in the manifest to another thing. The `package` one was used to generate the `R` file.

Also the documentation says:

> The package that is used in your source code to refer to your R class, and to resolve any relative activity/service registrations, continues to be called the "package".

**Comment by dodgex** [comment]
hmf. yeah. i was sure i have unset my package attribute in the manfest. but instead i used the same value for `applicationId` and `package` in the xml.

**Comment by WonderCsabo** [comment]
I opened a [topic](https://groups.google.com/forum/#!topic/adt-dev/ZyPiXZdANbw) on adt-dev, hopefully we get an answer soon.

**Comment by WonderCsabo** [comment]
I decided to use `android.defaultConfig.applicationId`.

**Comment by WonderCsabo** [comment]
Guys, i think `resourcePackageName` is not needed at all actually, since we extract it from the manifest. I guess it is always present in the manifest, right?
