### ISSUE TITLE
Can't use with Android Studio

### ISSUE THREAD

**Issue by lvthanh101** [excilys/androidannotations#1337]
Hi all,

Can you suggest me how to setup androidannotations for Android Studio Ide?

Thanks

**Comment by WonderCsabo** [comment]
Everything is written in defail [here](https://github.com/excilys/androidannotations/wiki/Configuration). Also, we have an [example project])https://github.com/excilys/androidannotations/tree/develop/examples/gradle) which can be imported to AS without further config.

**Comment by lvthanh101** [comment]
Thanks @WonderCsabo, it worked
