### ISSUE TITLE
@SeekBarTouchStop naming convention is wrong

### ISSUE THREAD

**Issue by niusounds** [excilys/androidannotations#1339]
These codes cannot generate correct class.

```xml
<SeekBar
    android:id="@+id/seekBar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" />
```

and

```java
@SeekBarTouchStop
void seekBarSeekBarTouchStopped() {
}
```
---
This works fine.

```java
@SeekBarTouchStop
void seekBarSeekBarTouchStoped() {
}
```

It should be named with "Stopped" suffix.

thanks.

**Comment by WonderCsabo** [comment]
You are right. Wanna contribute?

BTW, fixing this is a breaking change, and only will be available in a stable release in version 4.0.
