### ISSUE TITLE
Unable to use along with lambdaj

### ISSUE THREAD

**Issue by jskswamy** [excilys/androidannotations#1340]
There seems to be an issue when using the android annotations with lambdaj. 

![compilation error](https://cloud.githubusercontent.com/assets/232449/6596150/66211156-c817-11e4-83a1-a9f7119b26bb.png)

This issue can be easily reproduced just by adding dependency for lambdaj in app.gradle file `compile 'com.googlecode.lambdaj:lambdaj:2.3.3'`

**Comment by WonderCsabo** [comment]
I do not really think this is problem is AA related. We just generate source code at compile time, we do not has to do anything with the compiled bytecode.
Also, from the stacktrace, it seems to be that the problem is with the JFlexLexer class.

**Comment by jskswamy** [comment]
I am able to use lambdaj without AA and vice versa but not able to use these two things together.

**Comment by jskswamy** [comment]
@WonderCsabo I agree it has nothing to do with AA, sorry for raising an invalid defect
