### ISSUE TITLE
ProGuard configuration need to be updated

### ISSUE THREAD

**Issue by timurgilfanov** [excilys/androidannotations#1341]
Hi!

I try to build my app with ProGuard but have many warnings until I suppress it with:

-dontwarn org.androidannotations.**
-dontwarn com.sun.codemodel.util.SingleByteEncoder

Application seems to be working after build with ProGuard. May be update this page in docs?

https://github.com/excilys/androidannotations/wiki/ProGuard

**Comment by dodgex** [comment]
could you post the warnings? and maybe your build config? i belive there is something wrong on your side.

**Comment by timurgilfanov** [comment]
First few warnings:

Warning:org.androidannotations.AndroidAnnotationProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor
Warning:org.androidannotations.helper.AnnotationArrayParamExtractor: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:org.androidannotations.helper.AnnotationParamExtractor: can't find superclass or interface javax.lang.model.util.SimpleAnnotationValueVisitor6
Warning:com.sun.codemodel.util.SingleByteEncoder: can't find referenced class sun.nio.cs.Surrogate$Parser
Warning:com.sun.codemodel.util.SingleByteEncoder: can't find referenced class sun.nio.cs.Surrogate
Warning:com.sun.codemodel.util.SingleByteEncoder: can't find referenced class sun.nio.cs.Surrogate$Parser
Warning:com.sun.codemodel.util.SingleByteEncoder: can't find referenced class sun.nio.cs.Surrogate
Warning:com.sun.codemodel.util.SingleByteEncoder: can't find referenced class sun.nio.cs.Surrogate$Parser
Warning:org.androidannotations.AndroidAnnotationProcessor: can't find referenced class javax.annotation.processing.AbstractProcessor
Warning:org.androidannotations.AndroidAnnotationProcessor: can't find referenced class javax.annotation.processing.ProcessingEnvironment
Warning:org.androidannotations.AndroidAnnotationProcessor: can't find referenced class javax.annotation.processing.RoundEnvironment

Full [build log] (https://drive.google.com/open?id=0BzIAkcbwt1QjV2pyNkRuaFNMdTA&authuser=0)
My [ProGuard config] (https://drive.google.com/open?id=0BzIAkcbwt1QjeDMyb25DT1Q4eE0&authuser=0)

**Comment by WonderCsabo** [comment]
I am afraid you are packaging the processor itself into your application. This is incorrect, since the processor is only needed at compile time, it is totally unnecessary to put it into the APK.

**Comment by timurgilfanov** [comment]
How to avoid packaging the processor into application?

I use Gradle with configs:
apply plugin: 'android-apt'
...
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName 'org.reactivephone'
    }
}
...
dependencies {
...
    apt 'org.androidannotations:androidannotations:3.2'
    compile 'org.androidannotations:androidannotations:3.2'
}

**Comment by WonderCsabo** [comment]
```groovy
dependencies {
    apt "org.androidannotations:androidannotations:3.2"
    compile "org.androidannotations:androidannotations-api:3.2"
}
```

**Comment by timurgilfanov** [comment]
Only 4 warnings now:

Warning: org.androidannotations.api.rest.RestClientHeaders: can't find referenced class org.springframework.http.HttpAuthentication
Warning: org.androidannotations.api.rest.RestClientSupport: can't find referenced class org.springframework.web.client.RestTemplate
Warning: org.androidannotations.api.rest.RestClientSupport: can't find referenced class org.springframework.web.client.RestTemplate
Warning: org.androidannotations.api.rest.RestErrorHandler: can't find referenced class org.springframework.core.NestedRuntimeException

**Comment by WonderCsabo** [comment]
That is why you are getting those warnings. Since you are not using the REST API, you do not have the optional Spring for Android jar in your classpath, that is why ProGuard shows these warnings. They are totally fine and expected.

**Comment by timurgilfanov** [comment]
Ok, I just add to suppress this
-dontwarn org.androidannotations.api.rest.**

**Comment by akashjindal6264** [comment]
I am facing the same issue, when I just dontwarn the same, but it is not making any server call.
