### ISSUE TITLE
ViewById new feature

### ISSUE THREAD

**Issue by himamis** [excilys/androidannotations#1344]
My problem is that I have a ViewGroup that offers an API of e.g. open/close and two other ViewGroups that want to use that. The only way I can inject it is by a setter. So it would be nice for ViewGoups created with @EBViewGroup, to be able to inject other views found in the activity.

**Comment by WonderCsabo** [comment]
Unfortunely i do not understand clearly your proposal. Can you elaborate per our contributing guidelines? We already show [that](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by WonderCsabo** [comment]
No answer since weeks, i am closing this. Please reopen if you have something to share.
