### ISSUE TITLE
Annotating a field with @EBean crashes the processor

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1346]
The following code
```
@EBean
public class MyBean {

	@EBean // using @EBean instead of @Bean by coincidence
	MyOtherBean injected;
}
```
results in this stacktrace:

java.lang.ClassCastException: org.eclipse.jdt.internal.compiler.apt.model.VariableElementImpl cannot be cast to javax.lang.model.element.TypeElement
	at org.androidannotations.handler.BaseGeneratingAnnotationHandler.isInnerClass(BaseGeneratingAnnotationHandler.java:52)
	at org.androidannotations.handler.BaseGeneratingAnnotationHandler.validate(BaseGeneratingAnnotationHandler.java:40)
	at org.androidannotations.handler.EBeanHandler.validate(EBeanHandler.java:41)
	at org.androidannotations.handler.BaseAnnotationHandler.validate(BaseAnnotationHandler.java:114)

This is because we are casting to `TypeElement` when checking whether it is an inner class, but the annotated element is clearly not a type, but a variable.
We should check first whether the annotated element is a class at all.

**Comment by WonderCsabo** [comment]
This problem only happens in Eclipse, it seems it tries to call annotation processing on the class even if it has other compilation errors (like using a type targeted annotation on a field like in the example above).
The question is, should we handle this @yDelouis @dodgex ?

**Comment by yDelouis** [comment]
We should handle this, if it's not too complicated.

**Comment by dodgex** [comment]
same as @yDelouis

**Comment by WonderCsabo** [comment]
Okay then, i have a fix in my mind, i will implement it soon.

**Comment by WonderCsabo** [comment]
Actually this way a bug in the Eclipse Java compiler, which is now fixed.
