### ISSUE TITLE
Multiple @AfterViews method is performed in the order it? Or random performed?

### ISSUE THREAD

**Issue by qinxianyuzou** [excilys/androidannotations#1349]
@AfterViews
    protected void initUI() {
        // TODO Auto-generated method stub
    }

 @AfterViews
    protected void setUI() {
        // TODO Auto-generated method stub
    }

These two methods is performed in the order it? Or random performed?

==================================
My English is not good, may express not very good, I hope you can understand, very sorry

**Comment by dodgex** [comment]
as written [here](https://github.com/excilys/androidannotations/wiki/%40AfterXXX-call-order) all methods annotated with the same `@After*` method are executed in a random order that may change with each build so you should **not** rely on an order for those methods

**Comment by qinxianyuzou** [comment]
I have learned, thanks @dodgex

**Comment by WonderCsabo** [comment]
Thanks @dodgex for the explanation and also for the great doc! :+1:

**Comment by WonderCsabo** [comment]
@qinxianyuzou 

> Please next time for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
