### ISSUE TITLE
couldn't find androidmanifest.xml file

### ISSUE THREAD

**Issue by JenyaKirmiza** [excilys/androidannotations#1350]
I'm using android studio. gradle 1.0.0. I've tried 3.1, 3.2 and get the same mistake.

**Comment by WonderCsabo** [comment]
Please review our contribution guide, and add much more detail.

Also, if you think it is not a bug, you may want to use our support channels instead of the bug tracker.

**Comment by JenyaKirmiza** [comment]
I tried two way - via gradle - using you guide and via .jar file. The androidannotions is seen in android studio. I can import easily the android annotations commands, but when i press play, it gives me build error mentioned above

**Comment by WonderCsabo** [comment]
Are you sure you added this part?

```groovy
...
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        ...
  }
}
}
```

**Comment by parmalazs** [comment]
please attach your build.gradle file

**Comment by JenyaKirmiza** [comment]
ok. guys i got it working. i removed support library and it worked. dont't know why. anyway thanks

**Comment by WonderCsabo** [comment]
@JenyaKirmiza you may have to re-add the support library, so this is not a solution. Also, i do not see how the support lib can be related to this problem.

**Comment by JenyaKirmiza** [comment]
i don't need the support library, but it was added after creating new project by android studio. I don't know why, but after this changes it worked

**Comment by WonderCsabo** [comment]
Okay.

> Please next time for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by taar1** [comment]
I have the same problem but can't solve it.
When I add:
<pre>
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
    }
}
</pre>

to my app's build.gradle file I get this error:
Error:(46, 0) Gradle DSL method not found: 'apt()'
Possible causes:<ul><li>The project 'Cheat-Database' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li></ul>

and when I remove the apt{} party I get the error:
Error:Could not find the AndroidManifest.xml file, going up from path [C:\Users\Dominik\Workspaces\Android\Cheat-Database\app\build\intermediates\classes\debug] found using dummy file [] (max atempts: file:///C:/Users/Dominik/Workspaces/Android/Cheat-Database/app/build/intermediates/classes/debug/dummy1434797594630)

I do have it in my dependencies:
<pre>
dependencies {
...
    compile 'org.androidannotations:androidannotations:3.3.1'
}
</pre>

Any ideas what I'm doing wrong? 
Thanks

**Comment by WonderCsabo** [comment]
The problem is you did not add the `android-apt` plugin to your buildscript. Please read the [example script](https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle) more carefully (you have to add it in the buildscript dependencies and apply the plugin as well).

**Comment by WonderCsabo** [comment]
Also, you should use `apt` scope/configuration for the `org.androidannotations:androidannotations:3.3.1` artifact. Check out the example script.

**Comment by taar1** [comment]
Thanks for the quick help. The missing "android-apt" was actually the problem.
However, following the example in the link you sent me caused another problem. MoPub could not be built anymore. After trying different settinss I found out that if I use:
<pre>
repositories {
        mavenCentral()
    }
</pre>

I get the problem with MoPub. If I switch back to jcenter() the problem disappears.

So my setting is now like this (and it works):
<pre>
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.+'
    }
}
allprojects {
    repositories {
        jcenter()
    }
}
</pre>

**Comment by WonderCsabo** [comment]
Actually, you can add more repositories.
```groovy
repositories {
  mavenCentral()
  jcenter()
}
```

The example is just a quick-start, you have to adopt it to your needs of course, add repositories and dependencies etc what you need.

**Comment by taar1** [comment]
Oh I wasn't aware of this. Just added it and it works great. Thanks!
