### ISSUE TITLE
ViewById with generics - creates syntax errors in generated class

### ISSUE THREAD

**Issue by malcooke** [excilys/androidannotations#1351]
What steps will reproduce the problem?

Declare something as follows with a generic eg
@ViewById(R.id.phrasetype)
 FloatingLabelItemChooser<ContentValues> phraseTypeSpinner;

This creates syntax errors in the generated class eg bad import and casting error

import com.marvinlabs.widget.floatinglabel.itemchooser.FloatingLabelItemChooser<android.content.ContentValues>;
...
phraseTypeSpinner = ((ContentValues>) hasViews.findViewById(uk.co.myApp.android.R.id.phrasetype));

What version of the product are you using? On what operating system?

3.2, Windows, Android Studio

**Comment by WonderCsabo** [comment]
I am confused because there is no generics in the code. Where do you use generic types?

**Comment by malcooke** [comment]
Apologies- seems to have been cut out when submitting because I simply used cut n paste: 
Here is what it should be:

```
@ViewById(R.id.phrasetype)
FloatingLabelItemChooser<ContentValues> phraseTypeSpinner;
```


Which then causes the syntax  error originally described in the generated class.

**Comment by parmalazs** [comment]
I also  noticed this problem  when  I used  the floatinglabel  widgets
library with Butterknife.

malcooke <notifications@github.com> ezt írta (időpont: 2015. márc. 24., K
16:12):

**Comment by WonderCsabo** [comment]
Yeah, i just tried it, and it is indeed a bug. Thanks for reporting. We will try to fix this, but until then you can use an (ugly) workaround by just using raw types instead of adding type arguments (just like in the code in the original post).

**Comment by WonderCsabo** [comment]
@Artyomcool any change you can look at it? Just some hints on how to fix it is also a help, if you do not have time for coding.

**Comment by WonderCsabo** [comment]
@parmalazs yeah, i think it comes from the same problem. However that problem is even harder to fix in ButterKnife, because they are using string concatenation to generate code.

**Comment by Artyomcool** [comment]
Yep, I'll look into this in a few days.

**Comment by WonderCsabo** [comment]
@Artyomcool i fixed this, see the referenced PR. However a rewiew would not hurt.
