### ISSUE TITLE
help me.     android.support.v7.app.ActionBarActivity

### ISSUE THREAD

**Issue by scodemao** [excilys/androidannotations#1354]
Something went wrong: Unexpected error in AndroidAnnotations 3.2! You should check if there is already an issue about it on https://github.com/excilys/
 androidannotations/search?q=org.eclipse.jdt.internal.compiler.problem.AbortCompilation&type=Issues If none exists, please open a new one with the following content 
 and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure). Java version: javac 1.7.0_45 Javac 
 processors options: phase=BUILD Stacktrace: org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type android.support.annotation.Nullable cannot 
 be resolved. It is indirectly referenced from required .class files at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.protectedHandle(ProblemHandler.java:247) at 
 org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:129) at 
 org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:324) at 
 org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2397) at 
 org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:4750) at 
 org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:67) at 
 org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:249) at 
 org.eclipse.jdt.internal.compiler.lookup.UnresolvedAnnotationBinding.getAnnotationType(UnresolvedAnnotationBinding.java:24) at 
 org.eclipse.jdt.internal.compiler.apt.model.AnnotationMirrorImpl.getAnnotationType(AnnotationMirrorImpl.java:96) at 
 org.androidannotations.model.ModelExtractor.extractAnnotations(ModelExtractor.java:95) at 
 org.androidannotations.model.ModelExtractor.extractAncestorsAnnotations(ModelExtractor.java:84) at 
 org.androidannotations.model.ModelExtractor.extract(ModelExtractor.java:45) at 
 org.androidannotations.AndroidAnnotationProcessor.extractAnnotations(AndroidAnnotationProcessor.java:197) at 
 org.androidannotations.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:163) at 
 org.androidannotations.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:113) at 
 org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139) at 
 org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121) at 
 org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159) at 
 org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134) at 
 org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:896) at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:496) at 
 org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:403) at 
 org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:341) at 
 org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:340) at 
 org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:146) at 
 org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:278) at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:197) at 
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239) at 
 org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295) at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351) 
 at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374) at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143) at 
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by dodgex** [comment]
> The type android.support.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files 

It seems you need the `support-annotations` dependency. Add this to your gradle depenency block: `compile 'com.android.support:support-annotations:22.0.0'` where `22.0.0` should be the same as the other support library verions you use (altough you should always use the latest)

**Comment by WonderCsabo** [comment]
@dodgex she is using Eclipse, so i guess there is no gradle here.

@scodemao @dodgex is right, you have to add that library to your classpath.

**Comment by scodemao** [comment]
@WonderCsabo   adt-bundle-mac ▸ sdk ▸ extras ▸ android ▸ support/android-support-annotations.jar  this one?

**Comment by dodgex** [comment]
@scodemao yeah. thats the correct one

**Comment by scodemao** [comment]
@dodgex  @WonderCsabo  3Q it works for me

**Comment by WonderCsabo** [comment]
You are welcome.

> Please next time for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
