### ISSUE TITLE
Generated code property

### ISSUE THREAD

**Issue by arnaudruffin** [excilys/androidannotations#1356]
Hi everyone. Thanks again for your framework, I am a big fan.

I understand from the LICENSE.txt files that the source code of androidannotation and androidannotation-lib is licensed under apache v2.

But what about the generated code? I would say that it is proprietary but have no idea where to find this information (nothing specified in the LICENSE.txt file, nothing in generated code header. 

Can somebody help me on this?

Thanks

**Comment by WonderCsabo** [comment]
This is a good question. Actually i think we never declared anywhere what license the generated code has. Do you know what is the convention in case of code generators?

**Comment by arnaudruffin** [comment]
I am no specialist. But I discussed it with a colleague and he pointed me to [the exemple of bison] (http://www.gnu.org/software/bison/manual/html_node/Conditions.html). My understanding is that the generated code is considered under the same license as the code generator. In the case of Bison they added an specific exception when they realized that they were preventing people from using bison for proprietary software (GPL license).

According to my colleague most compilers and interpreters (often GPL) face the same issue and add exceptions to their licences so that generated code (assembly) be free of use.

I think you should decide wether you wish the generated code is also Apache V2 or if the developper is free to distribute that work under terms of his own choice (bison's choice). It won't make a lot of difference for the developper as the app still has to package the androidannotation-lib jar and so will have to mention using androidannotation and its license when going public.

Anyway, we should add something in the LICENSE.txt to clarify that. We could also add it in the comments at the top of every generated file.

[Here is how the exception is stated in bison's licence] (http://spdx.org/licenses/GPL-2.0-with-bison-exception)

What do you think?

**Comment by pyricau** [comment]
http://www.wtfpl.net/ ?

**Comment by arnaudruffin** [comment]
love the spirit... :)

On Thu, Mar 26, 2015 at 4:29 PM, Pierre-Yves Ricau <notifications@github.com

**Comment by WonderCsabo** [comment]
@pyricau nice to see you here. :)

@arnaudruffin wanna contribute as to add those exception to the LICENSE.txt file and also to the generated file prolog?

**Comment by arnaudruffin** [comment]
Ok, why not.

If I'm right I would have to :
- update LICENSE.txt file
- update the  content of the comment on top of generated classes (in org.androidannotations.generation.CodeModelGenerator)

I think we should let src/etc/header.txt as is, because other files are not concerned.

**Comment by WonderCsabo** [comment]
Exactly, thanks.
