### ISSUE TITLE
HI, My Fragment using AA, But How to get Activity in Fragment

### ISSUE THREAD

**Issue by huangsanm** [excilys/androidannotations#1360]
HI, My Fragment using AA, But How to get Activity in Fragment?

**Comment by ktomek** [comment]
Hi @huangsanm 

On fragment object you have getActivity() method.
https://developer.android.com/reference/android/support/v4/app/Fragment.html#getActivity()

**Comment by WonderCsabo** [comment]
@huangsanm #768 already proposes to add an annotation to inject the `Activity` into the `Fragment`. Currently you have to go the old way as @ktomek suggested.

**Comment by huangsanm** [comment]
thank you for @WonderCsabo and @ktomek 
I using AA in my project,of course On fragment object you have getActivity() method.
but is get null.
here my code:
@EFragment(R.layout.fragment_discuss)
public class DiscussFragment extends Fragment {

    private Activity mActivity;
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mActivity = (CarCircleActivity) getActivity();
    }

this is create fragment.
 DiscussFragment discuss = DiscussFragment_.builder().mGameID("-1").build();

**Comment by dodgex** [comment]
do you add the fragment to your activity?

you can read how to use fragments here: http://developer.android.com/guide/components/fragments.html

**Comment by yDelouis** [comment]
You should set the `Activity` in `onAttach`. There you'll be sure the `Activity` is not null.

**Comment by WonderCsabo** [comment]
@yDelouis `onAttach` actually runs before `onCreate`.

**Comment by huangsanm** [comment]
@dodgex  Yes added.
