### ISSUE TITLE
Can not use @EApplication for abstract base classes

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1363]
Given there is a class:

``` java
@EApplication
public abstract class BaseApplication extends Application {
}
```

Then I cannot use it as a base class because:
AA will notice & abort because BaseApplication can not be found within the AndroidManifest.xml.

It would be nice if the behaviour is similar to EFragment & EActivity.

**Comment by WonderCsabo** [comment]
I totally agree.

**Comment by WonderCsabo** [comment]
Implemented.
