### ISSUE TITLE
RecyclerView with multi layout

### ISSUE THREAD

**Issue by NodensN** [excilys/androidannotations#1365]
I'm faced with an memory issue, whenever I create RecyclerView with a single layout everything works fine, but if i use multiple layout I quickly get OOM (Out Of Memory) and the device shuts down.

My implamentation is inspired by the following (Part RecyclerView and ViewHolder) : https://github.com/excilys/androidannotations/wiki/Adapters-and-lists

I think the problem comes from the fact that I inject a generic "View" instead of "typed View"

My case : RecyclerViewAdapterBase>, View>

RecyclerViewAdapterBase>, FeedPhotoView, FeedStatusView> ???

Someone have an idea ? 

ViewWrapper :
https://gist.github.com/NodensN/ed7803e86773bb41f6c1

Abstract Adapter : 
https://gist.github.com/NodensN/e9d6649c9a7239453a8e

Adapter : 
https://gist.github.com/NodensN/abb855c0f610fc38d6f6

**Comment by WonderCsabo** [comment]
I also saw your post in the mailing list. I prefer usage questions not discussed in the bug tracker, but let's continue here for now for convenience.

The problem maybe lies in the [`onBindViewHolder`](https://gist.github.com/NodensN/abb855c0f610fc38d6f6#file-feedadapter-java-L27) method. It seems you are creating new views in it. You should not do so, but instead update the `View` created by `onBindViewHolder`. The whole idea of the `RecyclerView` is to not create new `Views` every time a row is updated, but instead re-use old ones in a circular fashion. However i just saw that if you are using the item type correctly, those branches should not be executed at all. Your [`getItemViewType`](https://gist.github.com/NodensN/abb855c0f610fc38d6f6#file-feedadapter-java-L49) method just returns the position actually, which means every row has different view type.

**Comment by NodensN** [comment]
Thank's I solved it !!! wrong getItemViewType usage ;)
