### ISSUE TITLE
Add a new processing option: minSdkVersion

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1367]
`minSdkVersion` and co. are moved from the *AndroidManifest.xml* file to *build.gradle*. Unfortunetaly it is not feasible to parse the *build.gradle* file. But we need these properties in some cases to generate properly (for example when we generate the `EActivity` `IntentBuilder`). So that is why we could introduce a new processing option for this.

**Comment by dodgex** [comment]
with `androidManifestFile variant.outputs[0].processResources.manifestFile`  in `apt.arguments`

you get these manifest files

```
****************************
variant: debug
manifest: .\application\build\intermediates\manifests\full\debug\AndroidManifest.xml
****************************
****************************
variant: release
manifest:  .\application\build\intermediates\manifests\full\release\AndroidManifest.xml
****************************
```

those are processed and complete. including the `<uses-sdk />` entry.

**Comment by WonderCsabo** [comment]
You are right, i should have realize that myself. Cool, we do not need these processing options, then!
