### ISSUE TITLE
Using @Rest to get image

### ISSUE THREAD

**Issue by schengen** [excilys/androidannotations#1374]
Hi

I am having some difficulty trying to Get a [png/image] using the Rest interface. Is it possible?

**Comment by WonderCsabo** [comment]
Please for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by WonderCsabo** [comment]
@schengen just to make it clear: we watch those channels too, so you do not have to worry that you will not get answers if you post on those.

**Comment by schengen** [comment]
I understand, sorry for the inconvenience.

**Comment by WonderCsabo** [comment]
There is absolutely no problem. So please open a ticket on one of those channels.
