### ISSUE TITLE
Interface for classes with .builder() method

### ISSUE THREAD

**Issue by miszmaniac** [excilys/androidannotations#1385]
Hi, 

It would be great to add interface for classes with static builder() method. 
Now when you're in need for builder, the only possibility is to write something ugly like:
```java
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    public @interface FragmentBuilder {
        Class<? extends org.androidannotations.api.builder.FragmentBuilder> value();
    }
```
And also annotation looks ugly: 
```java
@BaseFragmentTest.FragmentBuilder(MyFragment_.FragmentBuilder_.class)
```
Simple interface like hasBuilder would solve this ugliness:)

**Comment by WonderCsabo** [comment]
I am maybe tired, but i really do not understand what do you want to achieve. Please write a clear feature request per the contribution guidelines.

**Comment by miszmaniac** [comment]
I was writing espresso 2.1 tests. Our apps rely mostly on fragments so every test has to be prepend with opening specified fragment. 
As we heavily use annotations it sounded like good thing to specify fragment under test in annotation.
If there was hasBuilder interface at class, I could use annotation like: 
```java @FragmentUnderTest(MyFragment_.class)```
and not loose static typing. 

It could be also used in DrawerNavigations, where you have to specify many fragments to something like MenuItem objects. In this case it would be possible to pass MyFragment_.class, and get builder().build() inside MenuItem.

**Comment by WonderCsabo** [comment]
So you want androidannotations to generate Fragment subclasses in this way?
```java
@FragmentBuilder(MyFragment_.Builder)
public class MyFragment_ extends MyFragment {

 // ...
}
```

**Comment by miszmaniac** [comment]
Ok actually I forgot that you can't make static method in interface.  
So this can't be done in way I was thinking:
```java 
public final class MyFragment_ extends ...MyFragment implements HasBuilder, HasViews ... 
```
I don't think it could be done in any other nice way not using Java8 features.
