### ISSUE TITLE
@Parcel

### ISSUE THREAD

**Issue by andrewlord1990** [excilys/androidannotations#1386]
There are libraries out there that can auto-generate a Parcelable version of your class, for the purposes of passing it between activities / fragments.

It seems like this functionality would work better if it was part of Android Annotations, as the the Parcelling code could go in the extended class.

```
@EBean
@Parcel
public class ExampleParcelable {
    String name;
    int age;
}
```

Android Annotations could put the parceling code in the generated class `ExampleParcelable_`. Then, when the variable is injected into the `@Extra` or `@FragmentArg`, the variable would be correctly unparceled by Android.

**Comment by WonderCsabo** [comment]
I totally agree. This is already considered and we have a WIP
implementation. Please search the issues.

**Comment by andrewlord1990** [comment]
I apologise, I tried searching and for some reason didn't notice it. I will close my duplicate issue.

**Comment by WonderCsabo** [comment]
We already opened #301 for this. Please read that for details.
