### ISSUE TITLE
JRebel and hot swapping broke

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1389]
> I already mentioned this in 997247d, but i did not get any responses, also it is more public to open an issue for this.

@yDelouis @dodgex 997247d and 9de0be80 was a bad idea. It broke AA usage with JRebel and the debugger hot swap. Actually this entry is needed:
```xml
<factorypathentry kind="PLUGIN" id="org.androidannotations" enabled="true" runInBatchMode="false"/>
```

So the debugger and JRebel can figure out the code is used from the first eclipse instance. *.factorypath* generated by `m2e-apt`just adds the extenal jar from maven repo.

So i think we have two options:
* readding this file and *.settings/org.eclipse.jdt.apt.core.prefs* (these files do not have to be updated, only if a new annotation processing option is needed or we are switching to a newer version of codemodel (or add a totally new dependency)
* add a note in the wiki, that the generated .factorypath should be changed if one wants to use hot swap debugging (this is great because we do not add redundant IDE files, but it is inconveient if someone wanna use hot swap because the checkouts will rewrite the files)

WDYT?

**Comment by dodgex** [comment]
Taking these [comments](https://github.com/excilys/androidannotations/pull/1384#issuecomment-96373624) i vote for Option 2.

**Comment by WonderCsabo** [comment]
@dodgex @yDelouis 

I think there is another problem with this. When you start the second instance `<factorypathentry kind="PLUGIN"` made sure you are using the latest version of AA which you just edited in the first Eclipse. With the new generated entry, you will just use whatever version is in the local Maven repo. This will cause serious problems if you do not realize that, because the processor does not do what you wrote. If you realize this, you still always have to `mvn install` the project before running the second Eclipse, and also if you make bigger changes in the code.

**Comment by WonderCsabo** [comment]
Personally i think we should re-add the .factorypath file. The whole plugin thing (MANIFEST.MF, build.properties, plugin.xml, eclipse-dependencies project) are created to make this work, and we just killed it by not adding one new file.

**Comment by yDelouis** [comment]
I'm okay with re-adding the file since it helps without bringing any drawbacks.

**Comment by WonderCsabo** [comment]
I updated the contribution wiki (m2e-apt no longer needs to be installed in Eclipse).

**Comment by WonderCsabo** [comment]
I added more info about JRebel in the [wiki](https://github.com/excilys/androidannotations/wiki/InstallingEnvironment), i really encource everybody to use it, speeds up development, really convenient :sunglasses: . I would love to enable this kind of developement in IntelliJ, but i am not sure it can be done because of the lack of an IDE incremental compiler.
