### ISSUE TITLE
Drop ActionBarSherlock support

### ISSUE THREAD

**Issue by yDelouis** [excilys/androidannotations#1390]
ActionBarSherlock is [deprecated](https://github.com/JakeWharton/ActionBarSherlock#deprecated) since the release of AppCompat.
I think we should remove the support of this library in 4.0.

**Comment by yDelouis** [comment]
I'm stupid, I searched among issues for `ActionBar` and `Sherlock` but not for `ActionBarSherlock`.
I close this issue since it's a duplicate of #1376.

**Comment by WonderCsabo** [comment]
No problem. :)
