### ISSUE TITLE
Rest interceptors wiki documentation

### ISSUE THREAD

**Issue by simopete** [excilys/androidannotations#1391]
Hi! 
I'm creating a Rest API with AA and I have to use interceptors. When I watched the wiki sites about [Rest API](https://github.com/excilys/androidannotations/wiki/Rest%20API) and [Authenticated Rest Client](https://github.com/excilys/androidannotations/wiki/Authenticated-Rest-Client) I have seen usage of interceptors. 
But it was not clear when I use `Rest` `interceptors` parameter the interceptor is used as `Bean` object or not. 
I already know if interceptor is `EBean` then it is used as `Bean` and inject it. 
On the bottom of the second wiki side I have seen the reference which should be changed. Also the Rest API site should be changed. The referenced issue is #661.

**Comment by WonderCsabo** [comment]
I updated the wiki and the JavaDoc. Thanks for reporting!
