### ISSUE TITLE
RuntimeException with @PreferenceScreen

### ISSUE THREAD

**Issue by Noiseapps** [excilys/androidannotations#1392]
Hi,
I've tried to implement the preference screen in my app today and stumbled upon this bug (or am I doing something wrong?) 

I have created a xml file with preferences, and annotated the activity : 
``` java
@PreferenceScreen(R.xml.preferences)
@EActivity
public class SettingsActivity extends PreferenceActivity {
}
``` 
and it gives me the error:

```    
Caused by: java.lang.RuntimeException: This should be called after super.onCreate.
            at android.preference.PreferenceActivity.requirePreferenceManager(PreferenceActivity.java:1439)
            at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1511)
            at package.name.SettingsActivity_.init_(SettingsActivity_.java:38)
            at package.name.SettingsActivity_.onCreate(SettingsActivity_.java:32)
            at android.app.Activity.performCreate(Activity.java:5990)
```

I guess the problem is in the generated class:

``` java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState); // that line should be after onCreate (line 32)
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        addPreferencesFromResource(xml.preferences); // line 38
    }
``` 

Is there anyone who can confirm the bug or indicate my mistake (I did everything as in the wiki section, so I think all should be fine)
Cheers!

**Comment by dodgex** [comment]
For me with a PreferenceFragment instead of PreferenceActivity it works. 

@WonderCsabo any ideas?

**Comment by WonderCsabo** [comment]
This is a bug unfortunately. Actually we have a running [test](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/preference/PreferenceScreenActivityTest.java) for this which passes, but it seems Robolectric have a different implementation than real Android code...

This should be fixed. Nonetheless i also encourage the usage of `PreferenceFragment`, because this way is deprecated (and also `PreferenceFragment` are working now with AA :smile:  ).

**Comment by Noiseapps** [comment]
Ok, thanks for the quick response :-) 

anyways, since there is no PreferenceFragment in the support library, how can I use it in the ActionBarActivity?

**Comment by WonderCsabo** [comment]
I do not know why, but the Android folks still not provide a backport of `PreferenceFragment` in the support library. The good news is that there is an [unofficial version](https://github.com/kolavar/android-support-v4-preferencefragment) if it. Bad news is: we do not support the `android.support.v4.preference.PreferenceFragment` class... But i think we should (which also adds a forward support of the official one if Google releases it). Please open a new issue for that.

**Comment by WonderCsabo** [comment]
@yDelouis @dodgex there are three issues raised about our new preference API today. Fixing these is easiy fortunetaly. Should we create a hotfix release? Maybe it makes sense, because the next big release will be 4.0 with breaking changes.

**Comment by dodgex** [comment]
I think we should fix those. I think it is not a good idea to keep them longer than necessary.

**Comment by yDelouis** [comment]
Yes, we should create a fix release (3.3.1).

**Comment by WonderCsabo** [comment]
I opened #1396 for the problem described in https://github.com/excilys/androidannotations/issues/1392#issuecomment-98825938.

**Comment by WonderCsabo** [comment]
I opened PRs for these three problems. @yDelouis @dodgex @athkalia @Noiseapps can you test them?

@yDelouis after you review these we can release a hotfix.

**Comment by WonderCsabo** [comment]
@yDelouis according to [this](https://github.com/excilys/androidannotations/wiki/Releasing#releasing-a-bugfix-version), we should not merge these fixes into `develop`, but to a hotfix branch which comes from master. Makes [sense](http://nvie.com/posts/a-successful-git-branching-model/) of course.

**Comment by dodgex** [comment]
@Noiseapps when minSdk is 11+ you can use the default [PreferenceFragment](http://developer.android.com/reference/android/preference/PreferenceFragment.html) even with `ActionBarActivity` or the new `AppCompatActivity`

**Comment by WonderCsabo** [comment]
@dodgex bad idea. :cry:  It will break the backstack and possibly other things (at runtime).

**Comment by yDelouis** [comment]
@WonderCsabo, you're right, theses PRs should be merge in a hotfix branch.

**Comment by WonderCsabo** [comment]
Side-note: I opened a [ticket](http://b.android.com/172052) in the Android bug tracking system for the problem i just mentioned @dodgex.

**Comment by WonderCsabo** [comment]
Fixed.
