### ISSUE TITLE
PreferenceChange annotation that is triggered after the preference changes, not before?

### ISSUE THREAD

**Issue by athkalia** [excilys/androidannotations#1393]
Hello,

I am wondering if there's a way to trigger @PreferenceChange after the change in the preference has occured, not before. The thing is that I am trying to use this annotation in conjuction with @SharedPref.
The values that are saved in the Preferences file, defined in the @SharedPref marked interface are not  the newest ones when @PreferenceChange is triggered. 

Example:

A checkbox on the preferences screen that stores a boolean in the 

public interface Settings{

    @DefaultRes(keyRes = R.string.checkbox_preference_key,value=true)
    boolean myBooleanPreference();
}

 @PreferenceChange(R.string.checkbox_preference_key)
    void checkboxPressed(Preference preference, Object newValue) {
        final boolean myBoolean= settings.myBooleanPreference().get();
    }

At the beggining the value of the boolean SharedPreference is true. When i press on the checkbox, and checkboxPressed() is triggered, the "newValue" field is false, but the "myBoolean" field still displays true, which makes this impossible to work with, as I am using the stored value in many cases instead of passing the newValue around in method calls.

In my custom solution I used to implement SharedPreferences.OnSharedPreferenceChangeListener to have the desired results.

**Comment by WonderCsabo** [comment]
So you do not like the current solution because you have to pass `newValue` instead of just calling `settings.myBooleanPreference().get()` again and again?

**Comment by athkalia** [comment]
Yes : > There's a reason I am saving the value in the sharedPreferences, I want it to be in sync always, and with this solution it isn't. I am using this value in many different places, and in some cases in different threads. Fetching it from the sharedPreferences seems to be cleaner. Isn't the  SharedPreferences.OnSharedPreferenceChangeListener doing the same thing, but after the Preference Change ?

**Comment by athkalia** [comment]
I could just start my method like this:


@PreferenceChange(R.string.checkbox_preference_key)
void checkboxPressed(Preference preference, Object newValue) {
settings.myBooleanPreference().put(newValue);
...
...
}

but this is more of a hack

**Comment by athkalia** [comment]
Also as a sidenote, you are supporting a Boolean parameter on the @PreferenceChange annotation (but not mentioned in documentation), and you are not supporting Set<String> parameter (but is reported in the documentation.) Finally the Long parameter is not supported (and correctly not reported in the documentation).

**Comment by WonderCsabo** [comment]
I agree this is a hack, and also makes an unnecessary IO call.

There are several reasons why i chose `Preference.OnPreferenceChangeListener` instead of `SharedPreferences.OnSharedPreferenceChangeListener`:

* you can get a chance to modify the value added by the user
* the listener actually belongs to the `Preference` object. The other listener belongs to the whole `SharedPreferences`, and gets notified after any preference is changed.
* code generation is easier, as the result of the previous statement

**Comment by athkalia** [comment]
Fair enough, I think I'll go with the hack for now, as passing the new value would probably introduce all sorts of trouble for me. Thank you for your time.

**Comment by WonderCsabo** [comment]
The sidenote is totally correct. Actually i wanted to support `Set<String>`, but i have made a mistake in the implementation (raw `Set` is valid, `Set<String>` is not). I totally forgot `Long`. Maybe there are others? Should we allow all types in `SharedPreferences` get methods? Please open a new issue for that.

**Comment by athkalia** [comment]
I'll open a new ticket, I think that's it,  Double is not supported by @SharedPref  so I don't care all that much.
