### ISSUE TITLE
@PreferenceChange minor parameter related changes

### ISSUE THREAD

**Issue by athkalia** [excilys/androidannotations#1394]
You are supporting a Boolean parameter on the @PreferenceChange annotation (but not mentioned in documentation), and you are not supporting a

     Set<String>  

parameter (but is reported in the documentation, you probably only meant to say that Set is supported) Finally the Long parameter is not supported (and correctly not reported in the documentation).
Maybe while you are at it you can also change @SharedPref to support Double, and also make @PreferenceChange support doubles?

**Comment by WonderCsabo** [comment]
What `Preference` uses a `Long` value? I quickly read throught the `Preference` subclasses in the `android.preference` package:

`EditTextPreference`: `String`
`ListPreference` : `String`
`MultiSelectListPreference` : `Set<String>`
`CheckBoxPreference` : `Boolean`

Of course one could use other subclasses from libraries or own code, which use different values.

**Comment by athkalia** [comment]
I am always keeping in mind your @SharedPref annotation.
In my implementation I have linked a ListPreference to have longs and store it:

@SharedPref(value = SharedPref.Scope.UNIQUE)
public interface Settings {

    @DefaultRes(keyRes = R.string.list_preference_key,value = 60000)
    long automatedFollowSignalsInterval();

}

and the xml:


   <ListPreference android:key="@string/list_preference_key"
                        android:title="Title"
                        android:dialogTitle="Dialog Title"
                        android:entries="@array/entries"
                        android:entryValues="@array/entry_values"
                        android:defaultValue="60000"/>

and the 2 arrays:


   <string-array name="entries">
        <item>1 minute</item>
        <item>5 minutes</item>
        <item>20 minutes</item>
        <item>1 hour</item>
        <item>3 hours</item>
        <item>6 hours</item>
        <item>24 hours</item>
    </string-array>

    <string-array name="entry_values">
        <item>60000</item>
        <item>300000</item>
        <item>1200000</item>
        <item>3600000</item>
        <item>10800000</item>
        <item>21600000</item>
        <item>86400000</item>
    </string-array>

**Comment by WonderCsabo** [comment]
These are not longs, these are strings. You will have a `String` object as the `newValue` parameter. Looking at the code, `ListPreference` is only capable of storing `String`s actually.

Our `@SharedPref` only works for you because we parse the string to a long (#503). Maybe we should do it here, too (it is little bit more compliated then in `SharedPref`?

**Comment by athkalia** [comment]
Ah, I just noticed now that you mentioned it. Well it wouldn't be too bad to have unless it's difficult to implement

**Comment by WonderCsabo** [comment]
OK, i can think of this generated code if the there:

```java
@PreferenceChange
void myPreferenceChanged(Integer value) {
   // TODO
}

if (newValue instaceof String) {
   int value = Integer.parseInt(newValue);
   myPreferenceChanged(preference, value)
   // this will throw a `NumberFormatException` if the String does not store an int, that is OK
} else if (newValue instaceOf Integer) {
   myPreferenceChanged(preference, (Integer) value)  
} else {
  throw new NumberFormatException("only can convert strings to numbers")
}
```

This ugly snippet is only generated if the parameter type is `Integer`, `Float`, `Double` or `Long`.
```

**Comment by WonderCsabo** [comment]
OK, actually this branch

`else if (newValue instaceOf Integer) {`

will be never used with the android default `Preference` class implementations. I am not sure we should prepare for other ones, since they could use any type.

**Comment by WonderCsabo** [comment]
Fixed.
