### ISSUE TITLE
@PreferenceXXX should work with support-v4 PreferenceFragment

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1396]
I do not know why, but the Android folks still not provide a backport of `PreferenceFragment` in the support library. The good news is that there is an [unofficial version](https://github.com/kolavar/android-support-v4-preferencefragment) if it. Bad news is: we do not support the `android.support.v4.preference.PreferenceFragment` class... But i think we should (which also adds a forward support of the official one if Google releases it).

**Comment by WonderCsabo** [comment]
Fixed.

**Comment by dodgex** [comment]
Looks like there is an official Version now : https://plus.google.com/+AndroidDevelopers/posts/9kZ3SsXdT2T

**Comment by WonderCsabo** [comment]
Cool! We should just add `android.support.v7.preference.PreferenceFragmentCompat` as a supported class, and it should work, shouldn't it?

**Comment by dodgex** [comment]
I don't know, i just scrolled through g+ and saw that post. Did not even read the Post.
