### ISSUE TITLE
@Rest Post doesn't send POST data

### ISSUE THREAD

**Issue by bartbergmans** [excilys/androidannotations#1400]
I'm trying to send data to my API using @Post method.

    @Rest(rootUrl = "http://url.com/api", converters = {
            MappingJackson2HttpMessageConverter.class,
            StringHttpMessageConverter.class,
            ByteArrayHttpMessageConverter.class,
            FormHttpMessageConverter.class })
    @Accept(MediaType.APPLICATION_JSON)
    public interface RESTClient {
    
        @Post("/user/edit-userdata/{id}")
        Settings updateProfile(User user, int id);
    
    }

My User class:

    package eu.shareforce.smartworker.Models;
    
    import com.fasterxml.jackson.annotation.JsonInclude;
    
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public class User {
        private int id;
        private int organisation_id;
        private int location_id;
        private boolean active;
        public String firstname;
        private String lastname;
        private String email;
        private String password;
        private String phonenumber;
    
        public int getId() {
            return id;
        }
    
        public void setId(int id) {
            this.id = id;
        }
    
        public int getOrganisation_id() {
            return organisation_id;
        }
    
        public void setOrganisation_id(int organisation_id) {
            this.organisation_id = organisation_id;
        }
    
        public int getLocation_id() {
            return location_id;
        }
    
        public void setLocation_id(int location_id) {
            this.location_id = location_id;
        }
    
        public boolean isActive() {
            return active;
        }
    
        public void setActive(boolean active) {
            this.active = active;
        }
    
        public String getFirstname() {
            return firstname;
        }
    
        public void setFirstname(String firstname) {
            this.firstname = firstname;
        }
    
        public String getLastname() {
            return lastname;
        }
    
        public void setLastname(String lastname) {
            this.lastname = lastname;
        }
    
        public String getEmail() {
            return email;
        }
    
        public void setEmail(String email) {
            this.email = email;
        }
    
        public String getPassword() {
            return password;
        }
    
        public void setPassword(String password) {
            this.password = password;
        }
    
        public String getPhonenumber() {
            return phonenumber;
        }
    
        public void setPhonenumber(String phonenumber) {
            this.phonenumber = phonenumber;
        }
    }

How I call the method:

        User user = new User();
        user.setFirstname(email.getText().toString());
        user.setLastname(email.getText().toString());
        user.setEmail(email.getText().toString());
        if(!password.getText().toString().equals("<EMPTY_PASSWORD>")) {
            user.setPassword(email.getText().toString());
        }
        user.setPhonenumber(email.getText().toString());
        Settings settings = client.updateProfile(user, 1);

When I log the incoming POST data on my server I get an empty array. If I send POST data to the same page using Postman (Chrome extension) the date shows up in the log.

**Comment by WonderCsabo** [comment]
What is your AA version, and what is your Spring Android RestTemplate version? Did you try to serialize locally to make sure Jackson works well?

> the date shows up in the log

What date? You are posting a whole JSON (User) object.

**Comment by bartbergmans** [comment]
I am using AA version 3.2. These are my dependencies:

        apt "org.androidannotations:androidannotations:$AAVersion"
        compile "org.androidannotations:androidannotations-api:$AAVersion"
        compile(
                [group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: "$JacksonVersion"],
                [group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: "$JacksonVersion"],
                [group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: "$JacksonVersion"]
        )
        compile 'com.mcxiaoke.volley:library:1.0.6'
        compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'

I dit not try to serialize locally (yet). I ment data, not date, sorry. When I make a own request (from my browser) I see the POST data I just sent but when I make the same request in my app I see an empty POST array.

**Comment by bartbergmans** [comment]
I serialized it locally using Jackson and that works. It gives me a JSON string:

    {"active":false,"email":"my@mail.com","firstname":"Bart","id":0,"lastname":"Bergmans","location_id":0,"organisation_id":0,"phonenumber":"555"}

**Comment by WonderCsabo** [comment]
Thanks. Can I ask you to create a simple example project with the same
dependencies so we can test it?

**Comment by bartbergmans** [comment]
Yeah, sure.

**Comment by bartbergmans** [comment]
I made a sample project with the same dependencies but still the same result. Empty POST request to my API.

**Comment by WonderCsabo** [comment]
Please share the project.

**Comment by bartbergmans** [comment]
How do I share a project?

**Comment by WonderCsabo** [comment]
Create a GitHub project for example?

**Comment by bartbergmans** [comment]
https://github.com/bartbergmans/SampleProject

**Comment by WonderCsabo** [comment]
Thanks! You posted the real url in the project, rewrite the commit if that
is sensitive information.

I am AFK but the, code looks OK to me, I will test it at home later today.

**Comment by bartbergmans** [comment]
Thanks, changed the url. Final url will be different anyway.

Thanks for the help!

**Comment by WonderCsabo** [comment]
Well, i told you to rewrite the commit, not add a new one. Actually now you
highlighted the url. ;)

**Comment by bartbergmans** [comment]
Yeah, doesn't matter. The URL is going to be different anyway :P

**Comment by WonderCsabo** [comment]
The client-side code is perfectly fine. The correct request is created then sent. I added a commit to your sample, to log outgoing requests.
You should debug the server-side, or the network in between.

**Comment by bartbergmans** [comment]
Why are other requests working then?

**Comment by WonderCsabo** [comment]
I do not know, but the client-side in your sample project is OK. Try it yourself.

**Comment by bartbergmans** [comment]
I found the problem. I don't receive the POST request because the content-type is 'application/json;charset=UTF-8'. Is there a way to change the content-type?

**Comment by dodgex** [comment]
@bartbergmans i think you could override the `MappingJackson2HttpMessageConverter` with one that provides another content-type. but maybe you want to allow your server to receive POST data with that content-type?

**Comment by WonderCsabo** [comment]
:+1: @dodgex 

@bartbergmans you can do something like this:
```java
class CustomJacksonConverter extends MappingJackson2HttpMessageConverter {

	public CustomJacksonConverter () {
		setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON);
	}
}
```

And use `CustomJacksonConverter` in the `converters` parameter, instead of `MappingJackson2HttpMessageConverter`. The other solution is implementing `RestClientSupport` with your client interface, then call

```java
List<HttpMessageConverter<?>> converters = client.getRestTemplate().getMessageConverters();
// iterate over and find MappingJackson2HttpMessageConverter
converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
```

But i also suggest to accept the mediatype with the encoding set on the server side.
