### ISSUE TITLE
Code generation for Generic Type wrong

### ISSUE THREAD

**Issue by gnuhel** [excilys/androidannotations#1402]
I have this annotated class

```java
@EBean(scope = EBean.Scope.Singleton)
public class HrWebServiceTask<T> extends Task<HrRequest, HrResponse<T>> {

	@RestService
	HrRestClient<T> restClient;

	@Override
	protected HrResponse<T> run(HrRequest request) throws Exception {
		return restClient.doRequest(request);
	}
}
```

and it generates following code

`
    private void init_() {
        restClient = new HrRestClient<T>_(context_);
        rootContext = context_;
        createTaskRegistry();
    }
`

I get a compiler error for the code at `restClient = new HrRestClient<T>_(context_);`
Shouldn't it be

`restClient = new HrRestClient_<T>(context_);`

**Comment by WonderCsabo** [comment]
This is indeed a bug, thanks for reporting!

@Artyomcool, i think we cannot solve this by just calling `APTCodeModelHeper.typeMirrorToJClass()`, because the generated type is not yet present, so we cannot get the `TypeMirror` in the first place. I think it is impossible to add type arguments to the constructor call, is it? So we just should use the raw constructor?

**Comment by Artyomcool** [comment]
Sorry, but the code makes no sence for me. This been is a singleton, right? So, who is suppose to define the T? AA just can't do that.
But the same problem could be faced with simple beans too. In this case we will be able to resolve a type, I think.

**Comment by Artyomcool** [comment]
I mean, if the bean is a singleton, it can have only one instance, so it can have only one T across the app.

**Comment by WonderCsabo** [comment]
@Artyomcool i quickly created this, WDTY?

```java
TypeMirror fieldTypeMirror = element.asType();
TypeMirror erasedFieldTypeMirror = processingEnv.getTypeUtils().erasure(fieldTypeMirror);
String interfaceName = erasedFieldTypeMirror.toString();

String generatedClassName = interfaceName + classSuffix();

JClass clazz = refClass(generatedClassName);

DeclaredType type = (DeclaredType) fieldTypeMirror;

for (TypeMirror param : type.getTypeArguments()) {
	JClass bounds = codeModelHelper.typeMirrorToJClass(param, holder);
	clazz = clazz.narrow(bounds);
}
```

**Comment by Artyomcool** [comment]
Sorry, code to complex to get the idea without a context ))

**Comment by WonderCsabo** [comment]
OK, i will create a PR soon.

**Comment by Artyomcool** [comment]
Oh, I see. Looks like there is a problem with resolving generic, that are not directly defined, e.g. in the extending class

**Comment by Artyomcool** [comment]
Please, don't rush with PR, look at my comments first. There is nothing you can do with singletons.

**Comment by WonderCsabo** [comment]
Actually, the same problem is here inside a non-generic bean.

**Comment by Artyomcool** [comment]
Oh, you are talking about handling '''@RestService''', aren't you? But in the case of trivial beans, we can use existing helpers, right?

**Comment by WonderCsabo** [comment]
There are two helpers here:

`typeMirrorToJClass`: we cannot get the `TypeMirror` because the type does not exist yet
`generifyStaticHelper`: `JClass` is not `JGenerifiable`

So we should add that narrow solution which i proposed.

**Comment by Artyomcool** [comment]
What exactly type is not exists? There is a problem with your solution:
'''
@SomeComponent
class A extends B<SomeType> { ... }

class B<T> {
  @RestService
  SomeGenericField<T> field;
}
'''

I'm not sure (i didn't reach a pc yet), but your solution shouldn't work.

**Comment by WonderCsabo** [comment]
https://github.com/WonderCsabo/androidannotations/tree/1402_RestServiceGeneric

**Comment by WonderCsabo** [comment]
The generated `GenericClient_` does not exist at the time of annotation processing, so we cannot use its `TypeMirror`.

**Comment by gnuhel** [comment]
@Artyomcool 
you are right with Singleton. I haven't thought about it. But you can leave remove `(scope = EBean.Scope.Singleton)`

or should I use `@RestService HrRestClient_<T> restClient;` instead?

I can  only try it on Monday again.

**Comment by WonderCsabo** [comment]
@gnuhel You are using it right. The generation has a bug, but i think i have a fix already. You should never reference the generated types only if there is no other solution (for example in manifest, or generated shared preferences).

**Comment by Artyomcool** [comment]
@WonderCsabo, don't you think, that @gnuhel still should remove a singleton scope?

**Comment by WonderCsabo** [comment]
> or should I use @RestService HrRestClient_<T> restClient; instead?

i was responding to this question.

**Comment by gnuhel** [comment]
@Artyomcool @WonderCsabo 
So it is a bug? Can I expect a fix soon?

**Comment by WonderCsabo** [comment]
it is a bug, as i wrote 4 hours ago and also check out the label. :wink: If you are really eager to see it, you can build [this](https://github.com/WonderCsabo/androidannotations/tree/1402_RestServiceGeneric) (WIP) branch. Hopefully this will be merged soon, so you can use it in a SNAPSHOT release, but i cannot see now when it will be fixed in a next stable release.

**Comment by gnuhel** [comment]
Cool thank you

**Comment by WonderCsabo** [comment]
Fixed.
