### ISSUE TITLE
AA cookbook document as PDF

### ISSUE THREAD

**Issue by KingAndroid** [excilys/androidannotations#1407]
I love AA crazily.
I want to download AA docuement so that I can use it while I work without internet.
Could you please send me full documents pdf?
Or even all md files?

Thanks for your kind support and hard work.
Your sincerely.
ZhengLu

**Comment by WonderCsabo** [comment]
Maybe it is not obvious, but the wiki is just a simple git repository, you can clone it and transform the .md files to whatever format you want. You can check out [here](https://github.com/excilys/androidannotations/wiki/HowToEditWiki) how to clone the wiki.
Furthermore, our [JavaDoc](http://search.maven.org/remotecontent?filepath=org/androidannotations/androidannotations-api/3.3/androidannotations-api-3.3-javadoc.jar) is very detailed (but not as much as the wiki), so you can use it offline. Just unzip the jar and open the *index.html* file.

**Comment by WonderCsabo** [comment]
> Please next time for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
