### ISSUE TITLE
Upgrade to Checkstyle 6.5 and enable usage of Eclipse-CS plugin

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1412]
This is something i already proposed here https://github.com/excilys/androidannotations/pull/1384#issuecomment-96373624.

So basically when the user imports the projects into Eclipse, the Eclipse Checkstyle config is automatically generated. Lines violating the Checkstyle rules will be shown in the editor:

![untitled](https://cloud.githubusercontent.com/assets/480485/7554163/6ecffa26-f71d-11e4-891d-ff0cd81aa493.png)

The user can create the formatter profile as well with two clicks, or even the auto save profile.

The only problem is that Eclipse-CS cannot generate formatter profile using tabs... There are two options to solve this:

* convert the whole codebase tow use spaces (which is recommended), but this needs an ugly big commit
* do not generate formatter profile with Eclipse-CS, but export the correct profile to XML, and save it to the repo. Users can import it into the workspace if they want.

After any of these options, we can drop the .settings folders regarding the formatter settings.

**Comment by WonderCsabo** [comment]
@yDelouis WDYT?

**Comment by yDelouis** [comment]
I'm okay for upgrading the checkstyle plugin.
And I prefer the second solution.
