### ISSUE TITLE
Inject a Menu

### ISSUE THREAD

**Issue by KleinerHacker** [excilys/androidannotations#1413]
If I want to use menu groups with id to change visibility of items between activity state changes I cannot use android annotations because I need the <code>Menu</code> instance to call method <code>setGroupVisibile</code>. There is a way to get the menu via android annotations like:
<pre>
@EActivity
@OptionsMenu(R.menu.my_menu)
public class MyActivity extends Activity {
    @OptionMenu
    protected Menu menu;

   ....

   private void toggleState() {
      menu.setGroupVisibile(R.id.mnu_my_menu_grp_my_group1, false);
      menu.setGroupVisibile(R.id.mnu_my_menu_grp_my_group2, true);
   }
}
</pre>

My current work arround is to override the onCreateOptionsMenu method:
<pre>
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        this.optionsMenu = menu;
        return super.onCreateOptionsMenu(menu);
    }
</pre>

**Comment by WonderCsabo** [comment]
So actually you want to inject the `Menu` with `@InjectMenu` (or sg) just like `MenuItem` with `@OptionsMenuItem`?

**Comment by KleinerHacker** [comment]
Yes, but an annotation with this functionality does not exists.

**Comment by WonderCsabo** [comment]
I know. :wink:

I think this should be a useful feature. @yDelouis @dodgex WDYT?

**Comment by dodgex** [comment]
this could indeed be usefull.

**Comment by WonderCsabo** [comment]
Thanks! 

@KleinerHacker i am marking this as an enhancement, but this is the end of our queue now. Contributions are welcome.

**Comment by WonderCsabo** [comment]
Implemented.
