### ISSUE TITLE
upload file error

### ISSUE THREAD

**Issue by sd4324530** [excilys/androidannotations#1414]
I want to upload file like this:
this is the rest interface:
 @Post("/uploadResource")
    @Accept(MediaType.MULTIPART_FORM_DATA)
    String uploadResource(MultiValueMap<String, Object> params) throws RestClientException;

this is my test code:
MultiValueMap<String, Object> params = new LinkedMultiValueMap<>();
params.add("data", model.toJsonString());
params.add("files", new FileSystemResource(file));
String response = this.resourceRestService.uploadResource(params);

the server's error was this:
java.lang.RuntimeException: java.io.IOException: Posted content type isn't multipart/form-data

**Comment by dodgex** [comment]
while i'm not a RestTemplate PRO and not even using it anymore i'll try to help. ;)

first of all: do you have the `FormHttpMessageConverter` added to the list of converters on your  interfaces `@Rest` annotation?

**Comment by sd4324530** [comment]
And before this error the file was 1MB for example,
but after this error it became to 0B.

**Comment by sd4324530** [comment]
`FormHttpMessageConverter` was added to the list of converters, it was the same error.
and the androidannotations's cookbook has no example for upload file

**Comment by dodgex** [comment]
after https://github.com/excilys/androidannotations/issues/1415 has been opened i think you both might have the same problem, so i ask you too:

are you using spring-android 1.x or 2.x? if 1.x have you tried the latest 2.x milestone? As of AndroidAnnotations 3.3 there is support for 2.x maybe this broke 1.x support in this case.

**Comment by WonderCsabo** [comment]
@sd4324530 you are using the `@Accept` annotation in a wrong way. You want to upload a request with multi-part form data, i guess that is why you added the `@Accept(MediaType.MULTIPART_FORM_DATA)` annotation. This annotation is actually can be used to *accept* restricted content-type data *from the server*. The content-type of the outgoing data is defined by the used converter, there is no need (and no option) to add any annotation for that.
You should use `FormHttpMessageConverter` to send multi-part post data. I think you are not using it at runtime.

Please post your whole `@Rest` annotated interface, your AA and Spring Android versions.

**Comment by sd4324530** [comment]
@WonderCsabo Thank you so mach!
