### ISSUE TITLE
Rest API enhancement

### ISSUE THREAD

**Issue by sytolk** [excilys/androidannotations#1416]
rootUrl can be array of mirror Rest services like:
```
@Rest(rootUrl = {"http://company.com/ajax/services","http://company2.com/ajax/services", ...}
```
after RestClientException - for example the first Rest service is down its possible to switch to the next rootUrl form array

**Comment by WonderCsabo** [comment]
Please note we are just a wrapper around Spring Android RestTemplate. I
think it does not provide this feature.

**Comment by sytolk** [comment]
Spring Android RestTemplate not provide this feature but this can be done in AA with recursive function like this:

```java
protected List<Servers> sockets;

public Boolean setDestination(Integer regionId) {
        return setDestination(regionId, 0);
    }

private Boolean setDestination(Integer regionId, int recursion) {
        String url = getBaseUrl() + "/" + destinationURL;
        try {
                HttpEntity<Integer> requestEntity = new HttpEntity<Integer>(regionId, requestHeaders);
                ResponseEntity<Boolean> responseEntity = restTemplate.exchange(url, HttpMethod.PUT, requestEntity, Boolean.class);
                return responseEntity.getBody();
        } catch (RestClientException e) {
            setSocketInactive(currentSocket);
            recursion++;
            if (haveSocketActive() && recursion < sockets.size()) return setDestination(regionId, recursion);
        }
        return null;
    }
```

**Comment by WonderCsabo** [comment]
Yeah, we *could* implement this directly in AA, but i am not sure we *should*. We are just a wrapper around the Android API, and the RestTemplate API in this case, we provide a more convenient way to use them, but we do not add new features to them. If we are starting to do that, we break this level of abstraction, move logic from the core APIs to AA, and we have to deal with bugs and problems about them. We should not do that, sorry. So if you want this feature, first make a request to upstream.

(BTW, your code would be cleaner in an iterative solution, in my opinion.)

**Comment by sytolk** [comment]
Ok maybe you are right. But do you thing that hardcoded URLs from AA annotations can be usable if I want to make with AA this functionality 
```
@Rest(rootUrl = "http://company.com/ajax/services"
```
I will prefer to use Spring Rest Template rather that wrapper around it. With AA for example I cannot change rootUrl.

(I have copy this function from my project with Spring Rest Template maybe with iteration code will be cleaner but for this example only :)

**Comment by WonderCsabo** [comment]
In AA, we always support the general case, and also only the features which are in the wrapped library. So yeah, we will stick with the static root URL. However, if your root url changes between production or debug etc, you can use Gradle flavors or build types  to change the static constant containing the root url.

You can still use AA `@Rest` even with your mirror feature.

1. You can create a fork of AA, change the `rootUrl` param in `@Rest` to be an array, then change the `RestHandler` to generate the desired code.
2. In AA 4.0, we will (hopefully) support plugins. You can create a new annotation, for example `@Mirrors`, create a code generator for it, and use the normal AA with that.
3. You can create a custom `ClientHttpReqestInterceptor` and use it with current AA:

```java
public class MirroringRequestInterceptor implements ClientHttpRequestInterceptor {
	List<URI> uris; // your mirrors
	ClientHttpRequestFactory factory; // inject the factory

	@Override
	public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {
		for (URI uri: uris) {
			ClientHttpRequest delegate = factory.createRequest(uri, request.getMethod());
			delegate.getHeaders().putAll(request.getHeaders());
			ClientHttpResponse response = execution.execute(delegate, body);
			if (response != null) { // use a proper condition
				return response;
			}
		}

		throw new RuntimeException(); // use better exception or error handling
	}
}
```
Then [inject](https://github.com/excilys/androidannotations/wiki/Rest%20API#interceptors) this interceptor into your `@Rest` interface.

**Comment by sytolk** [comment]
Thanks I will wait for AA 4.0-RELEASE and try this :+1:
