### ISSUE TITLE
Use ContextCompat to retrieve drawables

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1422]
Given I'm injecting a drawable into my fragment like that:

```
@DrawableRes(R.drawable.bg_button_with_stroke_orange)
protected Drawable backgroundDrawable;
```

Then Android Annotations generates this code:

```
private void init_() {
    Resources resources_ = context_.getResources();
    backgroundDrawable = resources_.getDrawable(drawable.bg_button_with_stroke_orange);
}
```

Which then generates this compiler warning for `targetSdk=22` builds:

```
TheClass_.java:33: warning: [deprecation] getDrawable(int) in Resources has been deprecated
        backgroundDrawable = resources_.getDrawable(drawable.bg_button_with_stroke_orange);
```

Instead, AndroidAnnoations should, given the class [ContextCompat](https://developer.android.com/reference/android/support/v4/content/ContextCompat.html) is available, generate this:

```
private void init_() {
    backgroundDrawable = ContextCompat.getDrawable(context_, drawable.bg_button_with_stroke_orange);
}
```

Benefits:
* Obviously, the compiler warning would be gone
* More importantly, the theme will be applied to the drawable on Lollipop+ devices

**Comment by WonderCsabo** [comment]
Seems reasonable. Wanna contribute?

**Comment by ened** [comment]
Would *love* to take care of it. Just no time right now. Keep it here for tracking, first.

**Comment by ened** [comment]
Having that said, @WonderCsabo how could one actually check if the class is available? We'd have to add the "compile" scope into the annotation processing scope (`apt`) and check there. Is that even possible?

**Comment by WonderCsabo** [comment]
We can just check wether it is on the classpath and that is working already. We do not know anything whether it will be really packaged into the app or not, but we expect it will. We already do [this kind of check](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ActivityIntentBuilder.java#L210) when we generate the `Activity` builders.

**Comment by WonderCsabo** [comment]
@ened i forgot that we should handle the cases when `ContextCompat` is not available.

*minSdkVersion => 21 && ContextCompat is not available*:
```java
backgroundDrawable = context.getDrawable();
```
*minSdkVersion < 21 && compileSdkVersion >=21 && ContextCompat is not available*:
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
  backgroundDrawable = context.getDrawable();
} else {
  backgroundDrawable = resources_.getDrawable();
}
```

Can you implement that?

**Comment by ened** [comment]
Would that check be done during compile time or in a runtime switch?  Probably generate the code like you showed it, right?

**Comment by WonderCsabo** [comment]
Yeah the generate that  code, the compile time conditional is in italic.

**Comment by ened** [comment]
Ok cool. Is there another component that's doing such a check?

**Comment by WonderCsabo** [comment]
You can look at ActivityIntentBuilder. Minsdkversion is available in our
AndroidManifest API, compileSdkVersion is not, so you have to check that
the Context.getDrawable method is available or not (like
ActivityIntentBuilder.hasActivityOptions).

**Comment by ened** [comment]
Now I got something like this:

```
    private void init_(Bundle savedInstanceState) {
        if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
            myDrawable = this.getDrawable(drawable.myDrawable);
        } else {
            myDrawable = resources_.getDrawable(drawable.myDrawable);
        }
        Resources resources_ = this.getResources();
    }
```

But I can't find out why the resources_ variable is initialized AFTER the usage. :)

Heres the code that generates it:

``` 
			} else if (element.getAnnotation(DrawableRes.class) != null && !hasContextWithGetDrawableMethod() && hasGetDrawableInContext() && !hasContextCompatInClasspath()) {
				createCallWithIfGuard(holder, ref(fieldName), methodBody, idRef);
```

```
	private void createCallWithIfGuard(EComponentHolder holder, JFieldRef ref, JBlock methodBody, JFieldRef idRef) {
		JConditional guardIf = methodBody._if(holder.classes().BUILD_VERSION.staticRef("SDK_INT").gte(holder.classes().BUILD_VERSION_CODES.staticRef("LOLLIPOP")));
		JBlock ifBlock = guardIf._then();
		ifBlock.assign(ref, holder.getContextRef().invoke("getDrawable").arg(idRef));

		JBlock elseBlock = guardIf._else();
		elseBlock.assign(ref, holder.getResourcesRef().invoke("getDrawable").arg(idRef));
	}
```

@WonderCsabo Spontaneous idea?

**Comment by ened** [comment]
OK I found it. Just had to get a hold of the resourcesRef earlier. PR coming. :)
