### ISSUE TITLE
@ReceiverAction.Extra for @Receiver in services, activities and fragments

### ISSUE THREAD

**Issue by ray1984** [excilys/androidannotations#1423]
I'd like to use @ReceiverAction.Extra not only BroadcastReceiver, but also in services, activities and fragments.
Example,
```java
@Receiver(actions = {Intent.ACTION_HEADSET_PLUG})
public void onHeadphonesPlug(@ReceiverAction.Extra int state) {
    //some code
}
```
instead of 
```java
@Receiver(actions = {Intent.ACTION_HEADSET_PLUG})
public void onHeadphonesPlug(Intent intent) {
    int state = intent.getIntExtra("state", -1);

    //some code
}
```

**Comment by WonderCsabo** [comment]
You can already do that, just use [`@Receiver.Extra`](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/annotations/Receiver.java#L153).

The documentation is missing this annotation, both JavaDoc and the wiki.

**Comment by ray1984** [comment]
Thanks a lot!

**Comment by WonderCsabo** [comment]
OK, the [wiki](https://github.com/excilys/androidannotations/wiki/Receiving-intents#parameters) has some info on this, but it should display an example, too. The JavaDoc totally misses the parameter info and the example.

**Comment by ray1984** [comment]
Should I close the issue, or will you do it yourself after documentation correction?

**Comment by WonderCsabo** [comment]
I will close it. However, you can also contribute to the documentation. :wink:

**Comment by WonderCsabo** [comment]
JavaDoc updated in 9209819, wiki also updated.
