### ISSUE TITLE
after clean project xxFragment_ import was error

### ISSUE THREAD

**Issue by chenzj-king** [excilys/androidannotations#1425]
In Eclipse.after clean my project.In SomeActivity who i use the xxFragment_.the import is error.but i was very unimaginable.when i remove the import and ctrl+shift+o to import it again.it was OK.when i debug my appliction is was nothing.but when i want to export my application.it will clean project and it will can't export a normal apk.can you help me to deal with the problem

**Comment by WonderCsabo** [comment]
Did you read [this](https://github.com/excilys/androidannotations/wiki/FAQ#wiki-import)?

**Comment by chenzj-king** [comment]
thanks.It has been resolved.
