### ISSUE TITLE
@Extra default values & setIntent

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1429]
Given I have a class like this:

``` java
@EActivity
public class VideoPlayer extends Activity {
    @Extra
    protected long videoId = -1;

    @Extra
    protected Uri uri = null;

    @Override
    protected void onResume() {
        if(videoId != -1) {
            // Load the video by id
        } else if(uri != null) {
            // Load video by URI
        }
    }
}
```

Then, I can receive the first intent with (videoId: 1), no problem.
While the video player is active, I want to be able to receive further control actions, say the user is using some nifty HTTP remote control like DLNA. I'd add a `onNewIntent` method:

``` java
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        setIntent(intent);
    }
```
Next stop after `onNewIntent` is onResume.

So when the user is now sending a URI instead of a ID, the previous value for `videoId` will not be touched and the logic outline above breaks.

In order to have a clear status, I need to add those 2 lines before the `setIntent` call.

``` java
    // We need to reset the object.
    videoId = -1;
    videoPath = null;
```

That's because the generated AA code is this:

``` java
    if (extras_.containsKey(VIDEO_ID_EXTRA)) {
        videoId = extras_.getLong(VIDEO_ID_EXTRA);
    }
```

But, it could/should be this:
``` java
    if (extras_.containsKey(VIDEO_ID_EXTRA)) {
        videoId = extras_.getLong(VIDEO_ID_EXTRA);
    } else {
        videoId = -1;
    }
```

And to make this work, we could add a new attribute to the `@Extra` annotation, called `defaultValue`. 

Or, we figure a way to read the default value (on field declaration).

Thoughts?

**Comment by WonderCsabo** [comment]
You can use the `@AfterExtras` annotation, to get rid of the `onNewIntent` boilerplate.

Adding a default parameter to the `@Extra` annotation is very complicated. There are several types which can be used with extras, so we would have to provide different parameters or different annotations. But we could not add a default value for `Object`s.

In AA, we always support the most common, simplest scenario, and it is true for `@Extra`. For other cases like this, you have to add some boilerplate like you currently do. BTW, can't you solve it from the side of the intent sender?

**Comment by ened** [comment]
`@AfterExtras` => good idea, but as `onNewIntent()` won't call `setIntent()` anyway, I'll keep it there.

For the default parameters, I also understand it. 

From sender-side.. not really. In the video player example above, the intent could come from anywhere. I might have a helper method to build the intent, though. Thanks, let's close the ticket then.

**Comment by WonderCsabo** [comment]
With `@AfterExtras` `onNewIntent` will indeed call `setIntent()`.

**Comment by ened** [comment]
Hm, this won't solve my particular problem though. The function annotated with `@AfterExtras` can't take a Intent as argument (so I cannot handle logic based on Intent.containsExtra).

**Comment by WonderCsabo** [comment]
You can retrieve the `Intent` with `getIntent()` actually.

**Comment by ened** [comment]
Ouch! OK sure that makes all sense now. Sorry & thanks.
