### ISSUE TITLE
@StringRes problem 

### ISSUE THREAD

**Issue by Senemix29** [excilys/androidannotations#1433]
Hi,
Why i got this error "cannot find symbol method value()" 
at line @StringRes(R.string.flavor) ?

I already imported android.support.annotation.StringRes, but i have no clue why this is happening.

@EActivity(R.layout.activity_main)
public class MainActivity extends Activity {
    @StringRes(R.string.flavor)
    String flavor;
[...]
}

**Comment by zhakid** [comment]
you import the wrong one!
Need to import 
org.androidannotations.annotations.res.StringRes;

**Comment by WonderCsabo** [comment]
@zhakid is correct. @Senemix29 all AA annotations are in the `org.androidannotations.annotations` namespace, and you should import those.

> Please next time for usability questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
