### ISSUE TITLE
@ItemClick for RecyclerView

### ISSUE THREAD

**Issue by ray1984** [excilys/androidannotations#1434]
Now, if you want to use RecyclerView, and you need in OnItemSelectListener for it, you should set onClickListener for each viewholder. I suppose that it is not trivial task, but it would be very useful.

**Comment by WonderCsabo** [comment]
The problem is there is no official Android method / listener for it AFAIK, so we would have to write a completely new API for the `RecyclerView`, and this project is not about doing that. I think we may choose a third party lib, maybe the most popular, which supports this feature, and then generate calls to it.

**Comment by dodgex** [comment]
as there is [no support](https://github.com/excilys/androidannotations/issues/1210) for RecylcerView at all, i don't think that there is a chance for this.

**Comment by WonderCsabo** [comment]
@dodgex we did not create an `@EViewHolder` annotation, because it is not necessary, but we can still create a `@RecyclerViewItemClick` annotation (in theory). Why would do two things rule out each other?

**Comment by dodgex** [comment]
mhm. maybe i thought the wrong way. my bad, sorry.

**Comment by WonderCsabo** [comment]
You do not need to be sorry at all! Every opinion matters, and everybody can be wrong, even the project collaborators. So, why do you think we should not / cannot create it (apart from the issue i said in my first comment)?

**Comment by dodgex** [comment]
my first thought was that this is something that has to be done inside the a RecyclerView compontent. then came your "veto". then i thought, "hm should be possible as he said".

but while writing this answer & checking how i implemented click/long click for my RecyclerView i' again not sure how could implement this.

actualy i'm a bit confused right now. :D not sure why, but i did not even use the suggested way for RV with AA as mentioned in the above linked issue. 

but what i did to bind the events: in my `ViewHolder` i bound those events to the `View` that is passed to the constructor, passing this (the ViewHolder) as the handler and from there i forwarded the call to my own handler interface with `itemClickHandler.onItemClick(items.get(getPosition()));` as argument to have the clicked item in the handler...

**Comment by ray1984** [comment]
Google has provided Android M for developers. Maybe it has selectListener for RecyclerView. It might meen that it will appear in support library. Or you can copy their way

**Comment by WonderCsabo** [comment]
Do you have a reference for that?

**Comment by WonderCsabo** [comment]
I could not find any libraries which implements RecyclerView item click listener, so it is currently not possible for AA. Please comment if you know about such a lib.

**Comment by zsoltk** [comment]
Hello, I just found this:

http://www.littlerobots.nl/blog/Handle-Android-RecyclerView-Clicks/

What do you think?

**Comment by WonderCsabo** [comment]
Nice class. However i am not sure we want to include it in our API. However currently there is no way. @yDelouis what is your opinion?

**Comment by dodgex** [comment]
@WonderCsabo sounds like a nice plugin. :)

**Comment by WonderCsabo** [comment]
@dodgex unfortunately the plugin system only supports adding new annotations, not extending existing ones.

**Comment by dodgex** [comment]
well the plugin could add `@RecyclerViewItemClick` as you suggested above.

**Comment by WonderCsabo** [comment]
Yeah, you are right, i forgot what i said three months ago. While i would love to extend the standard `@ItemClick` with `RecyclerView` support, i see no other way than adding a new annotation in a plugin.
