### ISSUE TITLE
@Extra won't recognize a Parcelable if a parent implements it

### ISSUE THREAD

**Issue by zsoltk** [excilys/androidannotations#1437]
With classes like:

```java
class BaseFoo implements Parcelable {
}

class Foo extends BaseFoo {
}
```

This works:
```java
@EActivity
class SomeActivity extends Activity {
  @Extra
  BaseFoo baseFoo;
}
```

But this won't:
```java
@EActivity
class SomeActivity extends Activity {
  @Extra
  Foo foo;
}
```

Well of course you could put `implements Parcelable` on `Foo` as well, but in my case both `BaseFoo` and `Foo` are generated classes, and then you must create another superfluous wrapper around `Foo` just to make it work.

**Comment by WonderCsabo** [comment]
I just tried your example with JDT and javac, too, and i cannot reproduce this error. Actually this problem cannot happen according to our code.

**Comment by zsoltk** [comment]
It might be my mistake then, overlooking something, but it's consistent. Actual conditions: I'm trying to pass a class generated by SquiDB as an `@Extra`. 

Something along the lines of:
```java
@TableModelSpec(className = "Foo", tableName = "foo")
public class FooSpec {
    // ...
}
```

SquiDB then generates:
``` java
public class Foo extends TableModel {
    // ...
}
```

Where ```TableModel``` is a SquiDB class extending another one, ```AbstractModel```, which implements ```Parcelable```.

If I try to pass in ```Foo``` as an ```@Extra```, I get the following error:

> Unrecognized type. Please let your attribute be primitive or implement Serializable or Parcelable

Which clearly comes from ```ValidatorHelper```.
 
If, however, I pass in ```AbstractModel``` as the ```@Extra``` just for curiosity, build finishes with no problem. This happens consistently.

**Comment by zsoltk** [comment]
Ok, I tried to pass in ```TableModel``` (which also does not implement ```Parcelable``` in itself), and build finished without problems.

Now it seems like the real problem has to do something with ```Foo``` being an APT generated class, while all the other classes are not. Care to dig deeper? :) Thanks!

**Comment by WonderCsabo** [comment]
Well, it is not easy to work with multiple processor at once, there can be several problems. I am afraid the problem is your table class is generated in the same round, and the type actually cannot be found by AA. Can you create a minimal example project?

**Comment by zsoltk** [comment]
Sure: https://github.com/zsoltk/aa-1437

Now that with this minimal project gradle build messages are kept to a minimum, I also see 

> Error:(11, 5) error: cannot find symbol class Foo

just before 

> Unrecognized type. Please let your attribute be primitive or implement Serializable or Parcelable

I overlooked that at first, but it's there in my original example, too. I think you are right with the diagnose, but can anything be done?

**Comment by WonderCsabo** [comment]
Yeah, unfortunately my diagnose was correct. We already have a proposition to solve these kind of issues: #402. However it would need an architectural change from us, so i do not know when or will it happen. So i suggest to apply workarounds.

**Comment by zsoltk** [comment]
Ok, thanks :)
