### ISSUE TITLE
Add form / multipart parameters from method parameters

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1438]
In `Retrofit` we can do sg like this:
```java
@FormUrlEncoded
@POST("/user/edit")
User updateUser(@Field("first_name") String first, @Field("last_name") String last);

restClient.updateUser("Csaba", "Kozák");
```

However in AA, we have to do this:

```java
@Post("/user/edit")
User updateUser(MultiValueMap<String, String> formData);

MultiValueMap<String, String> formData = new LinkedMultiValueMap<>();
formData.add("first_name", "Csaba");
formData.add("last_name", "Kozák");
restClient.updateUser(formData);
```

It would be nice to add the `@Field` annotation to AA. Actually it can be used for form-urlencoded and multipart requests, too, since both are handled the same way in `FormHttpMessageConverter` (added to the map).

**Comment by WonderCsabo** [comment]
@yDelouis @dodgex thoughts?

**Comment by dodgex** [comment]
while i switched to Retrofit long time ago, i still think that this might be nice to have for those using AA/RestTemplate. :)

**Comment by yDelouis** [comment]
Why not.

**Comment by WonderCsabo** [comment]
Great!

@dodgex if you are missing functionality from our REST client, feel free to open feature requests/contribute.

**Comment by dodgex** [comment]
@WonderCsabo the only feature i miss is the Retrofit support. ;) I had some problems with RestTemplate that pushed me to to the switch.
