### ISSUE TITLE
Executing custom code with an annotation

### ISSUE THREAD

**Issue by n0k** [excilys/androidannotations#1449]
Hi,

I was wondering if it is possible to execute custom code for an annotation e.g. a custom method in onCreate of an Activity. Is there a way to do this with the 3.3.1 release or would a custom annotation need to be written for this?

Thanks!

**Comment by dodgex** [comment]
I think you want to use something like [`@AfterInject`](https://github.com/excilys/androidannotations/wiki/Injecting-Views#afterviews) or [`@AfterViews`](https://github.com/excilys/androidannotations/wiki/Enhance-custom-classes#executing-code-after-dependency-injection)

**Comment by n0k** [comment]
I want to execute the code within onCreate of an Activity at runtime. If I understand correctly code annotated by @AfterInject or @AfterViews are executed at build time.

**Comment by dodgex** [comment]
no. they are called at runtime. methods with `@AfterInject` are called during onCreate (currently even [before](https://github.com/excilys/androidannotations/issues/1450) the onCreate of your class is called). `@AfterInject` methods will be called after your activities layout is set. that means after you call `setContentView` or if you have set your layout through your `@EActivity` annotation this is called at some point (shortly) after your `onCreate`

**Comment by dodgex** [comment]
you can see what happens if you open the class that gets generated by AA. If your Activity is called `MainActivity` the generated one can be found as `MainActivity_` there you can see what happens and when your methods get called

**Comment by n0k** [comment]
Thanks for the information @dodgex . I should have clairified further - in my scenario I have some code that I want to inject in the Activity's onCreate without actually modifying the Activity i.e. just adding the annotation as is done with @EActivity(R.id.someview). I'm guessing that is only possible by adding a new annotation to AA.

**Comment by dodgex** [comment]
yeah, that is only possible by a new annotation, but that would require the [plugin api](https://github.com/excilys/androidannotations/issues/957) to ready or until that you could either add that code to your `onCreate`or use a method annotated with either `@AfterInject` or `@AfterViews`

**Comment by WonderCsabo** [comment]
@n0k currently, you have to build your custom AA for this. We plan to release the plugin API in 4.0, as @dodgex says.
