### ISSUE TITLE
generated init_() called before super.onCreate

### ISSUE THREAD

**Issue by dodgex** [excilys/androidannotations#1450]
I just saw that the `init_()` method is called before `super.onCreate(...)`.

Is that actually wanted?

**Comment by dodgex** [comment]
btw, same for `@EFragment`, `@EActivity` and `@EService`.

while i see one benefit: having everything (but views) ready when the `onCreate` of your class is called
i also see one (possible) issue: when one does stuff in an `@AfterInject` method that requires/assumes  e.g. the activities `onCreate` to be run/done

**Comment by WonderCsabo** [comment]
I think this is definitely intentional. If you cannot setup in `@AfterInject` just use `@AfterViews` or override `onCreate()` etc.

**Comment by dodgex** [comment]
ok. i have no issues with that. just saw that when looking at the generated code today :)

**Comment by ravladiat** [comment]
"I think this is definitely intentional. If you cannot setup in @AfterInject just use @AfterViews or override onCreate() etc."
Could you explain the reason? And what will fail if the super.onCreate() will be called before init_() method?

**Comment by dodgex** [comment]
`init_` is called before `super.onCreate()` to do the initial basic injections so that lots of injected stuff (iirc everything that is not a view) is already available in your own `onCreate()`.
