### ISSUE TITLE
@ViewById and @Click not working in Services implementing HasViews with WindowManager

### ISSUE THREAD

**Issue by LouisCo** [excilys/androidannotations#1462]
Hi!
I am building an app using [WindowManager](http://www.piwai.info/chatheads-basics/) in a Service. (yes, this WindowManager guide is from AA creator himself) To make the code slimmer, I used AA , implemented HasViews and notified OnViewChangedListener. I made a TestService to check `@UiThread` and `@Background` behavior in Services with Views in WindowManager, but at compile time, I got an error telling me `@ViewById` only works in annotated Activities, Fragments, ViewGroups, Views and Beans:
> Error:(47, 5) error: @org.androidannotations.annotations.ViewById can only be used in a class annotated with @org.androidannotations.annotations.EActivity, @org.androidannotations.annotations.EViewGroup, @org.androidannotations.annotations.EView, @org.androidannotations.annotations.EBean, @org.androidannotations.annotations.EFragment.

This is an annoying limitation :(

Here's my simple code:

**TestService.java**
``` java

import android.app.Service;
import android.content.Intent;
import android.graphics.PixelFormat;
import android.os.Handler;
import android.os.IBinder;
import android.os.Messenger;
import android.util.Log;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.TextView;

import org.androidannotations.annotations.Background;
import org.androidannotations.annotations.Click;
import org.androidannotations.annotations.EService;
import org.androidannotations.annotations.SystemService;
import org.androidannotations.annotations.UiThread;
import org.androidannotations.annotations.ViewById;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;

import static android.view.ViewGroup.LayoutParams.WRAP_CONTENT;
import static android.view.WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL;
import static android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED;
import static android.view.WindowManager.LayoutParams.TYPE_PHONE;

@EService
public class TestService extends Service implements HasViews{

    public static final String LOG_TAG = TestService.class.getSimpleName();

    private final Messenger mMessenger = new Messenger(new Handler());

    @SystemService
    WindowManager windowManager;

    @SystemService
    LayoutInflater inflater;

    private View window;

    @ViewById
    Button uiFreezeButton, bgFreezeButton;

    @Click
    void uiFreezeButtonClicked() {
        freezeUI();
    }

    @Click
    void bgFreezeButtonClicked() {
        freezeBG();
    }

    @UiThread
    void freezeUI() {
        try {
            Thread.sleep(6000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Background
    void freezeBG() {
        try {
            Thread.sleep(6000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Override
    public IBinder onBind(Intent intent) {
        // TODO: Return the communication channel to the service.
        return mMessenger.getBinder();
    }

    @Override
    public void onCreate() {
        super.onCreate();
        setupWindow();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        windowManager.removeView(window);
    }

    @UiThread
    void setupWindow() {
        WindowManager.LayoutParams layoutParams = new WindowManager.LayoutParams(
                WRAP_CONTENT, WRAP_CONTENT,
                TYPE_PHONE, FLAG_SHOW_WHEN_LOCKED | FLAG_NOT_TOUCH_MODAL, PixelFormat.TRANSLUCENT
        );
        layoutParams.gravity = Gravity.TOP | Gravity.LEFT;
        layoutParams.x = 0;
        layoutParams.y = 100;

        window = inflater.inflate(R.layout.windowmanager_test, null);

        windowManager.addView(window, layoutParams);

        ((OnViewChangedListener) this).onViewChanged(this); //Notify AA to inject views
    }

    @Override
    public View findViewById(int id) {
        return window.findViewById(id);
    }
}
```

**windowmanager_test.xml**
``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <SeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/seekBar"
        android:layout_gravity="center_horizontal" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="\@UiThread"
        android:id="@+id/uiFreezeButton"
        android:layout_gravity="center_horizontal" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="\@Background"
        android:id="@+id/bgFreezeButton"
        android:layout_gravity="center_horizontal" />
</LinearLayout>
```

Could the next library version include a fix for this please ? I would be very grateful as it will save me hours of work on multiple projects, and probably the same for others.

**Comment by WonderCsabo** [comment]
Well, this is a design decision. You should not use any `View`s in `Service`s, since they are logic and/or background work objects, which should not manipulate the view hierarchy directly. Actually the `Service` is not associated with a view hierarchy at all, so there is no way to retrieve the view ( i know you hacked around it with `HasViews` and `WindowManager` but that was a bad idea, i am sorry).

Also, `@Click` cannot be used in `Services` for the same reason.

**Comment by LouisCo** [comment]
I don't agree, Views can be used in Services as AA creator itself showed on this article: http://www.piwai.info/chatheads-basics/
Facebook Messenger and many other apps use WindowManager, and there's a reason WindowManager is in Android. I don't understand why you don't want to help floating apps building  simpler. If I want to make a floating currency and units convertor for example so it's easy to make calculations while browsing the web on a smartphone or buying something in a shop app, you think it should be harder than making it not floating ?

See the app below. it couldn't work without WindowManager and Services, and AA could probably make it's code more maintainable, so it could get Material Design more sooner (ok, maybe they won't work on it anymore, but it could help other developers trying to make Android a better platform with these awesome apps)
![Floating Calculator app screenshot] (https://lh3.googleusercontent.com/616XKmFqohaX6f5x5KtyG1a8rIZZqMmObbNHdgwh6TIX=w362-h643-no)

I hope you understand why using WindowManager in a Service isn't a bad idea, and how AA could make it a great idea. 

PS: Thank you for replying so fast :)

**Comment by WonderCsabo** [comment]
Hmm, i also read that blog post long time ago. :)

I did not tell you there is a bad idea to use `WindowManager`. I told you it's a bad idea to use it this way with AA `HasView`s.

If i were you, i would create a custom `ViewGroup` with `@EVIewGroup`, and add it in the `Service` via `WindowManager`. Then you can use all the view-related annotations inside your custom `ViewGroup`. I think my point i still true: you should not use `Views` inside the `Service` directly, this is only a layer to instantiate your view and also the other logic maybe.

But this is only my opinion and i can be wrong. :) @yDelouis @dodgex WDYT?

**Comment by WonderCsabo** [comment]
@LouisCo btw, `HasViews` is not meant to be used by clients, it is part of AAs implementation for creating injections, along with `OnViewChangedNotifier`.

**Comment by LouisCo** [comment]
@WonderCsabo I didn't thought about using an annotated ViewGroup, I'll try this, it could help making the code easier to read. For now, as I'm at work (alternating android developer student), I tried with old implementation, and I'm glad to see that `UiThread` and `@Background` annotations works as expected :) I will finally get rid of all these `Handler(s)` to switch between UI thread and work thread !

**Comment by LouisCo** [comment]
@WonderCsabo I used HasViews once to hack AA and get `@ViewById`  work in a RecyclerView ViewHolder. I have some ideas on how to update AA to prevent me from using HasViews in RecyclerView.ViewHolders if you're interested in ;)

**Comment by WonderCsabo** [comment]
Please open a new issue for that. But did you read [this](https://github.com/excilys/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder)?

**Comment by yDelouis** [comment]
@LouisCo, I agree with @WonderCsabo that you should create a custom `ViewGroup` annotated with `@EViewGroup` and use `@ViewById` and `@Click` inside this `ViewGroup`.
I don't want to allow the usage of view related annotations in class which are not related to views (like `Service`). More so as, I think that these annotations should not be supported for `@EBean`. @WonderCsabo, @dodgex ?

**Comment by LouisCo** [comment]
@WonderCsabo 
Yes, I read it after I hacked it, so i smiled a bit, When I have time to explain how i could work well, I'll open a new issue

**Comment by LouisCo** [comment]
@yDelouis Please, don't remove support for Views related annotations in `@EBean` beacause one my apps rely on it to hack RecyclerView ViewHolders, and probably other apps rely on it

**Comment by WonderCsabo** [comment]
@LouisCo i am closing this issue. Please reopen if my proposed solution does not work for you, or you think it should be improved.

For `@EBean` and view-related annotations, we will discuss it in another issue.
