### ISSUE TITLE
Multi database support request  in the @OrmLiteDao annotation

### ISSUE THREAD

**Issue by sirkalmi** [excilys/androidannotations#1463]
Example implementation:
https://github.com/j256/ormlite-examples/tree/master/android/HelloAndroidTwoDbs

**Comment by WonderCsabo** [comment]
I think it would be more useful to add a feature request to `OrmLite`, to `OpenHelperManager` to support multiple helpers at the same time. That logic is really corresponds to that class.

**Comment by WonderCsabo** [comment]
There is already a proposition and @j256 is willing to add it the `OrmLite`. Please refer to https://github.com/j256/ormlite-android/issues/35.
