### ISSUE TITLE
@WindowFeature and support library

### ISSUE THREAD

**Issue by camillebeaumont** [excilys/androidannotations#1464]
The `@WindowFeature` annotation create `requestWindowFeature(x)` in the `init_()` function even if the activity use the support library (instead of using `supportRequestWindowFeature(x)`)

**Comment by WonderCsabo** [comment]
Good catch! Wanna contribute?

**Comment by camillebeaumont** [comment]
Ok why not. I Find out how to do it.
However, I have an issue. `supportRequestWindowFeature` is from `ActionBarActivity` and not from `FragmentActivity` and unfortunately there is no appcompat-v7 library on Maven central, only the v4 support library. So I can't make a 
Any clues ?

**Comment by WonderCsabo** [comment]
This is not a problem at all. It means we cannot test it in the functional test, but we can in the compile-time test (by adding a fake `ActionBarActivity`). You can generate arbitrary code. :) Check out [this](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/generation/ActivityIntentFragmentTest.java) test, which adds `Fragment` to the classpath. The added classes must be in *src/test/resources*, like [this](https://github.com/excilys/androidannotations/tree/develop/AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/generation).

If you have further questions, do not hesitate to ask..

**Comment by WonderCsabo** [comment]
BTW, you *also*  have to check `AppCompatActivity`, since `ActionBarActivity` is deprecated.

**Comment by camillebeaumont** [comment]
Yes, of course ! I think of this minute ;)

**Comment by WonderCsabo** [comment]
@camillebeaumont did you manage to make progress on this one?

**Comment by WonderCsabo** [comment]
Implemented.
