### ISSUE TITLE
RestClient code generation issue

### ISSUE THREAD

**Issue by mdurieux** [excilys/androidannotations#1465]
i try to create a simple restClient 

here is my RestClient Code :+1: 

@Rest(rootUrl = "https://www.azerty.com/soa/stock/service/stock",converters = { ProductMessageConverter.class, StringHttpMessageConverter.class })
public interface MyRestClient {
    @Get("/all")
    ProductList getAll();

    
    @Delete("/id/{id}")
    void deleteById(Integer id);
 }

When building the project I got this error :

Error:(40, 25) error: reference to exchange is ambiguous
both method <T#1>exchange(String,HttpMethod,HttpEntity<?>,Class<T#1>,Map<String,?>) in RestTemplate and method <T#2>exchange(String,HttpMethod,HttpEntity<?>,ParameterizedTypeReference<T#2>,Map<String,?>) in RestTemplate match
where T#1,T#2 are type-variables:
T#1 extends Object declared in method <T#1>exchange(String,HttpMethod,HttpEntity<?>,Class<T#1>,Map<String,?>)
T#2 extends Object declared in method <T#2>exchange(String,HttpMethod,HttpEntity<?>,ParameterizedTypeReference<T#2>,Map<String,?>)

And I see this class is generated by Android-annotation :

public final class MyRestClient_
    implements MyRestClient
{

    private String rootUrl;
    private RestTemplate restTemplate;

    public MyRestClient_(Context context) {
        rootUrl = "https://www.azerty.com/soa/stock/service/stock";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new ProductMessageConverter());
        restTemplate.getMessageConverters().add(new StringHttpMessageConverter());
    }

    @Override
    public ProductList getAll() {
        return restTemplate.exchange(rootUrl.concat("/all"), HttpMethod.GET, null, ProductList.class).getBody();
    }

    @Override
    public void deleteById(Integer id) {
        {
            HashMap<String, Object> urlVariables = new HashMap<String, Object>();
            urlVariables.put("id", id);
//ERROR IS BECAUSE OF THE NEXT LINE            
restTemplate.exchange(rootUrl.concat("/id/{id}"), HttpMethod.DELETE, null, null, urlVariables);
        }
    }

}

**Comment by WonderCsabo** [comment]
I guess you are using Spring for Android 2.0. We only support that from AA version 3.3. What is the AA version you are using?

**Comment by mdurieux** [comment]
3.2

**Comment by WonderCsabo** [comment]
Please update to 3.3.1, it should solve your issue.

**Comment by mdurieux** [comment]
Thx a lot. It seems better now!
Regards,

Marc

**Comment by mdurieux** [comment]
Thanks for your quick support :
http://stackoverflow.com/questions/30776529/android-annotation-rest-client-code-generation-error

2015-06-11 12:22 GMT+02:00 Csaba Kozák <notifications@github.com>:

> Closed #1465 <https://github.com/excilys/androidannotations/issues/1465>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/excilys/androidannotations/issues/1465#event-328344073>
> .
>



-- 

With kindest regards - Met vriendelijke groeten -  Très Cordialement  -
Sehr freundlichen Grüßen

Marc Durieux

Hive-x
Square de Meeûs 38-40 - 1000 Bruxelles
m: +32 477 83 27 28
e: mdurieux@hive-x.com <marc.durieux@hive-x.com>
w: https://hive-x.com

**Comment by WonderCsabo** [comment]
You should have use the android-annotations tag, I am subscribed.

**Comment by mdurieux** [comment]
done and thanks again

2015-06-11 12:29 GMT+02:00 Csaba Kozák <notifications@github.com>:

> You should have use the android-annotations tag, I am subscribed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/excilys/androidannotations/issues/1465#issuecomment-111079865>
> .
>



-- 

With kindest regards - Met vriendelijke groeten -  Très Cordialement  -
Sehr freundlichen Grüßen

Marc Durieux

Hive-x
Square de Meeûs 38-40 - 1000 Bruxelles
m: +32 477 83 27 28
e: mdurieux@hive-x.com <marc.durieux@hive-x.com>
w: https://hive-x.com
