### ISSUE TITLE
Sending file with REST

### ISSUE THREAD

**Issue by bartbergmans** [excilys/androidannotations#1471]
What is the best way to send a file using the RestService? I have an image that I have to send to the server. 

The API expects the following POST data:

    image -> image I want to send
    description -> text
    title -> text

Can I just send an object with the needed values to achieve this?

    class NewImage {
        private Bitmap image;
        private String description;
        private String title;
    }

**Comment by WonderCsabo** [comment]
Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

As you already did [here](http://stackoverflow.com/questions/30891163/sending-images-with-androidannotations-restservice).
