### ISSUE TITLE
Open a Gitter room for AA

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1474]
[Gitter](http://gitter.im/) is a chatting service. It would nice if we could open a room, so users and developers can discuss ideas and problems.

**Comment by WonderCsabo** [comment]
@yDelouis WDYT?

**Comment by yDelouis** [comment]
I think there is some cases where a chat would be more convenient. Is it possible to create rooms by topic ?

**Comment by WonderCsabo** [comment]
I try to create a room for AA, then find out. :)

**Comment by WonderCsabo** [comment]
[Here](https://gitter.im/excilys/androidannotations) is the room. It is not possible create topics unfortunetly, but it is still a good place to discuss development and help users.

**Comment by WonderCsabo** [comment]
Actually, [we can create topics](https://gitter.im/excilys/androidannotations#createroom) as new rooms.

**Comment by WonderCsabo** [comment]
@yDelouis can we put the gitter to the readme badge and close this issue?

**Comment by yDelouis** [comment]
Yes.
