### ISSUE TITLE
@Background, @UiThread not working on Fragment

### ISSUE THREAD

**Issue by ltduc** [excilys/androidannotations#1475]
Dear, Team!

On a class extend android.support.v4.app.Fragment:
+ I used  @Background(delay = 10000) but not delay
+ I used  @UiThread to update UI then it not working

Please help me!

Thanks.

**Comment by WonderCsabo** [comment]
Please add more information as outlined in the [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue), you could see the link for it on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new). What do you mean it is not working? What is the code you want to execute, etc.

**Comment by ltduc** [comment]
Dear WonderCsabo!

I used follow to try code:

@EFragment
public class CheckinFragment extends BaseFragment {
    public CheckinFragment() {
    }

    public static CheckinFragment newInstance() {
        CheckinFragment fragment = new CheckinFragment();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setHasOptionsMenu(true);

        doInUiThreadAfterTwoSeconds();
    }

    @UiThread(delay = 10000)
    void doInUiThreadAfterTwoSeconds() {
        getBaseActivity().showProgress(false);
    }
}

Method doInUiThreadAfterTwoSeconds executed immediatel rather delay 10000.

**Comment by WonderCsabo** [comment]
I think the problem is that you are not using the generated `Fragment`, but the annotated one, which does not have the enhancements. Your `newInstance()` method is incorrect, it should return an instance of `CheckinFragment_`. Moreover, that method is completely unnecessary as is, you could use `CheckinFragment_,builder().build()` to create a new instance.

**Comment by ltduc** [comment]
Dear, WonderCsabo!
I did it.

Thank you for helping me!
Thank you very much!

**Comment by WonderCsabo** [comment]
Great, although please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by ltduc** [comment]
Dear, WonderCsabo!
I have understood.

Thanks!
