### ISSUE TITLE
Copy non-AA annotations in method parameters

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1479]
We already copy non-AA annotations to extended classes and overridden methods, but we also have to copy the annotations to the method parameters in overridden methods.

**Comment by WonderCsabo** [comment]
@yDelouis WDYT?

**Comment by yDelouis** [comment]
If it simple ok. It it's hard, let's wait for someone to ask it.

**Comment by WonderCsabo** [comment]
I am stupid, we already do that. I added a small test 10f833a0.
