### ISSUE TITLE
Java version: 1.7 Javac processors options: phase=BUILD Stacktrace: java.lang.NullPointerException 	at org.eclipse.jdt.apt.core.internal.AptCompilationParticipant.addJava6GeneratedFile(AptCompilationParticipant.java:272)

### ISSUE THREAD

**Issue by currymonkey** [excilys/androidannotations#1482]
hi ,i just add some static varibles in code
error below:
![image](https://cloud.githubusercontent.com/assets/9698496/8369649/7ac2dbcc-1bef-11e5-9a6b-801a23338414.png)

**Comment by WonderCsabo** [comment]
Please add detailed information per the [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue), as we link that on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

What is your Eclipse and JDT versions? What is your AA version? What is you exact code you added when it crashed? What is the whole stacktrace? Etc.

**Comment by WonderCsabo** [comment]
No response after 10 days, i am closing this. Please reopen if you have anything to share.
