### ISSUE TITLE
Use annotation with Google + Login 

### ISSUE THREAD

**Issue by hearbeathorror** [excilys/androidannotations#1483]
Hi,

I would like to add google plus login in my application, and i have been using annotations for most of the things, i would like to know if it is possible to make use of annotations for GooglePlus login. I tried going through links on stackoverflow but i seem not to get anything for the same. Please assist.

Thanks

**Comment by dodgex** [comment]
there are no special annotations related to Google+ Login. could you explain what exactly you expect form android annotations to do for you?

**Comment by hearbeathorror** [comment]
I was wondering if it is possible to use annotations with the methods:
 - onConnectionFailed
 - onConnectionDisconnected
- onDisconnected

But i think i need to really figure out why i need annotations then in that case , some to handle UIThread related work and Background related checks. (where the progress dialog is shown may be)

**Comment by dodgex** [comment]
no, there are no annotations to handle this callbacks, but you can create methods (with @UiThread or @Background if needed) and call them from the callbacks you add the default way. i do not think that we are gonna add special annotations for google+ login. maybe in the future as plugin if the system for that is done.

**Comment by WonderCsabo** [comment]
@dodgex is right.

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by hearbeathorror** [comment]
@dodgex - Thanks for the guidance il try that .
@WonderCsabo - I tried checking the posts there but dint arrive at anything so posted here.  Thank you too.

**Comment by WonderCsabo** [comment]
@hearbeathorror you should ask questions on stackowerflow, the AA team is monitoring those questions and answer them very quickly.
