### ISSUE TITLE
Parcelable generic argument doesn't work in @FragmentArg 

### ISSUE THREAD

**Issue by pashky** [excilys/androidannotations#1484]
Hi, I'm experiencing some trouble with generated code, if @EFragment is generic.

For example, if I have following declaration:
```java
@EFragment
public class ChoiceDialog<PayloadType extends Parcelable> extends Fragment {
    @FragmentArg 
    PayloadType payload;
     ...
}
```

Generated build then still tries to put Serializable into bundle:
```java
        public ChoiceDialog_.FragmentBuilder_ payload(PayloadType callbackData) {
            args.putSerializable(PAYLOAD_ARG, callbackData);
            return this;
        }
```

I hope it's possible to find out upper bound from generics declaration and fix it, so it will put correct type. I'm fairly okay to revert to `PayloadType extends Serializable` in my case, which would work as putSerializable seems to be default, but still it would be nice to see it fixed in future.

**Comment by WonderCsabo** [comment]
This should be already fixed by #1445. Please check out the latest 4.0-SNAPSHOT version.

**Comment by pashky** [comment]
Wow, that was quick. I'll check it out, thanks!

**Comment by WonderCsabo** [comment]
@pashky i am assuming the latest 4.0-SNAPSHOT version is working for you. I am closing this issue. Please reopen if you still experience problems.
