### ISSUE TITLE
In @UiThread I get this exception "android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views." Why? 

### ISSUE THREAD

**Issue by LuizGadao** [excilys/androidannotations#1485]
See this image.

![annotation_exception](https://cloud.githubusercontent.com/assets/3384999/8477154/627017d4-209e-11e5-8661-38cb9bab8b57.jpg)

**Comment by WonderCsabo** [comment]
Interesting. From the stack trace, it seems `@UiThread` did not generate the call to the `Handler`. Are you sure you are using the correct AA `@org.androidannotations.UiThread` annotation?

**Comment by LuizGadao** [comment]
Thank you my friend.

The AndroidStudio auto-import it: "import android.support.annotation.UiThread" and I not checked it.

I change it and it's work fine.

**Comment by LuizGadao** [comment]
Thank you my friend.

The AndroidStudio auto-import it: "import android.support.annotation.UiThread" and I not checked it.

I change it and it's work fine.
