### ISSUE TITLE
can not use the guava eventBus at  activity

### ISSUE THREAD

**Issue by foxundermoon** [excilys/androidannotations#1486]
my guava version is 18
i'm register event at   method with 	@AfterViews
but can not dispatch my Subscribe method at my activity class。

**Comment by WonderCsabo** [comment]
I think this is a known problem. The subscriber methods are at the level of the annotated class, but the bus is registered itself in the level of the generated class. This way the subscriber methods are never called when an event is posted. I suggest to use the `Otto` library, which also has the same issue with AA, but our [integration](https://github.com/excilys/androidannotations/wiki/OttoIntegration) solves it. Alternatively, you can use greenrobot's [EventBus](https://github.com/greenrobot/EventBus).

**Comment by WonderCsabo** [comment]
No response since 4 days, i am closing this issue. Please feel free to reopen if you have anything to share.
