### ISSUE TITLE
can not use id symbol as the field of Eactivity class. 

### ISSUE THREAD

**Issue by foxundermoon** [excilys/androidannotations#1487]
if i use 'id' symbol will  compile error.

**Comment by WonderCsabo** [comment]
Please add more information per the [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue), which is already referenced on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new). For example your code, AA version, etc.

**Comment by dodgex** [comment]
i think it is more or less the same issue as https://github.com/excilys/androidannotations/issues/1323

**Comment by WonderCsabo** [comment]
good point @dodgex, but let's wait for @foxundermoon to clarify this issue.

**Comment by WonderCsabo** [comment]
I realized I cannot reproduce the problem raised in the referenced issue:https://github.com/excilys/androidannotations/issues/1323#issuecomment-119746379

What is the exact problem here?

**Comment by WonderCsabo** [comment]
OK, i managed to reproduce the problem there. I am closing this in favor of #1323. @foxundermoon feel free to reopen, if you think this is not a duplicate. Thanks.
