### ISSUE TITLE
In the latest version of the SDK compiler error

### ISSUE THREAD

**Issue by liumouren** [excilys/androidannotations#1494]
build tools : 21.1.2
sdk tools : 24.3.3
support : 22.2.0
respostory : 15
gradle version : 1.2.3

In the above environment, the operation will be reported the following error

注: Resolve log file to E:\WorkSpace\MyApplication\AndroidStudio\build\generated\source\apt\aiya_000000\androidannotations.log

注: Initialize AndroidAnnotations 3.3.1 with options {androidManifestFile=E:\WorkSpace\MyApplication\AndroidStudio\build\intermediates\manifests\full\aiya_000000\debug\AndroidManifest.xml}

androidannotations.log

11:03:04.134 [Task worker Thread 2] INFO  o.a.AndroidAnnotationProcessor:83 - Initialize AndroidAnnotations 3.3.1 with options {androidManifestFile=E:\WorkSpace\MyApplication\AndroidStudio\build\intermediates\manifests\full\aiya_000000\debug\AndroidManifest.xml}
11:03:04.202 [Task worker Thread 2] INFO  o.a.AndroidAnnotationProcessor:107 - Start processing for 29 annotations on 901 elements
11:03:04.464 [Task worker Thread 2] ERROR o.a.AndroidAnnotationProcessor:267 - Something went wrong: Unexpected error in AndroidAnnotations 3.3.1!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=com.sun.tools.javac.code.Symbol%24CompletionFailure&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.8.0_11
Javac processors options: androidManifestFile=E:\WorkSpace\MyApplication\AndroidStudio\build\intermediates\manifests\full\aiya_000000\debug\AndroidManifest.xml
Stacktrace: com.sun.tools.javac.code.Symbol$CompletionFailure: �Ҳ���android.support.v4.app.DialogFragment$DialogStyle�����ļ�

11:03:04.465 [Task worker Thread 2] INFO  o.a.p.TimeStats:81 - Time measurements: [Whole Processing = 262 ms], 
11:03:04.465 [Task worker Thread 2] INFO  o.a.AndroidAnnotationProcessor:121 - Finish processing

**Comment by WonderCsabo** [comment]
You are not using the latest version actually. Please update to
AndroidAnnotations 3.3.2, which has a fix of this issue. For details,
please see #1435.

**Comment by liumouren** [comment]
Has been resolved, thank you very much.

**Comment by WonderCsabo** [comment]
No problem.
