### ISSUE TITLE
How use a custom SharedPreferences instance in SharedPreferencesHelper?

### ISSUE THREAD

**Issue by tebitoq** [excilys/androidannotations#1495]
Hi, I'm tried extending my class UserPreferences_ for inject a custom instance of SharedPreferences in SharedPreferencesHelper , someone know how I can do that?

regards

**Comment by WonderCsabo** [comment]
All generated classes are marked as `final`, so it is impossible to inherit from them. This is intentional, because inheriting from generated classes is a very bad idea, it can case nasty compilation errors, and a design flaw anyways. But what custom instance do you want to inject? :S

**Comment by tebitoq** [comment]
I want inject a instance from this [library] (https://github.com/scottyab/secure-preferences) !!

**Comment by WonderCsabo** [comment]
I am afraid you can't. But you can apply cryptographic functions to to values returned by the AA preferences helper.

**Comment by tebitoq** [comment]
What do you mean ?  encode before save with AA?

**Comment by WonderCsabo** [comment]
Yeah, and decode when get with AA.

**Comment by tebitoq** [comment]
Ok, thank you!
