### ISSUE TITLE
BUILD FAILED - AA - 3.3.2  Sup - 22.2

### ISSUE THREAD

**Issue by Adam-Fresko** [excilys/androidannotations#1496]
Android annotations 3.3.2
Support 22.2
Build tools 22.0.1

So i migrated from 3.x to 3.3.2 in order to support 22.2 support lib

When i roll back to AA - 3.2 and Sup - 22.1.1 it build just fine

Am i just blind or there is no error in the log?

Attached log
https://drive.google.com/file/d/0Bz0DOIxBPY9pWE9SYk03dDJiWms/view?usp=sharing

**Comment by dodgex** [comment]
there are 3 AA errors
```
11:41:20.172 [Daemon worker Thread 4] ERROR o.a.h.AnnotationHelper:128 - @org.androidannotations.annotations.EIntentService annotated element should have only one constructor
11:41:20.172 [Daemon worker Thread 4] WARN  o.a.p.ModelValidator:69 - Element EIntentServiceHandler unvalidated by 
11:41:20.172 [Daemon worker Thread 4] ERROR o.a.h.AnnotationHelper:128 - @org.androidannotations.annotations.EIntentService annotated element should have only one constructor
11:41:20.173 [Daemon worker Thread 4] WARN  o.a.p.ModelValidator:69 - Element EIntentServiceHandler unvalidated by 
11:41:20.173 [Daemon worker Thread 4] ERROR o.a.h.AnnotationHelper:128 - @org.androidannotations.annotations.EIntentService annotated element should have only one constructor
11:41:20.173 [Daemon worker Thread 4] WARN  o.a.p.ModelValidator:69 - Element EIntentServiceHandler unvalidated by 
```

**Comment by Adam-Fresko** [comment]
Is that something i can fix on my side?

**Comment by dodgex** [comment]
sure. three of your for (com.webikeonline.network.AddressDataService, com.webikeonline.network.SyncService, com.webikeonline.network.UpdateService, com.webikeonline.tracker.NotificationControllerService) IntentService classes that are annotated with `@EIntentService` have more than one constructor.

**Comment by Adam-Fresko** [comment]
Was this requirement added in 3.3? Its builds nice and dandy with 3.2

**Comment by WonderCsabo** [comment]
This was added in 3.3, as you could see it in the [changelog](https://github.com/excilys/androidannotations/wiki/ReleaseNotes#bug-fixes-2).

**Comment by WonderCsabo** [comment]
I am closing this one. Please reopen if you have problems @Adam-Fresko .
