### ISSUE TITLE
How to confige AndroidAnnotations in AndroidStudio 

### ISSUE THREAD

**Issue by lizhidu** [excilys/androidannotations#1497]

**Comment by WonderCsabo** [comment]
This is explained in detail on the [wiki](https://github.com/excilys/androidannotations/wiki/Configuration#gradle).

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
