### ISSUE TITLE
How to use annotation rest service to upload a zip file.

### ISSUE THREAD

**Issue by wangxingge** [excilys/androidannotations#1498]
How to use annotation rest service to upload a zip file.
I need to use which converter?
I use MultiValueMap<String, Object> upload a image file before, but seem it's not working when upload a zip file.

**Comment by WonderCsabo** [comment]
For file upload, you should use a multipart POST request as written [here](https://github.com/excilys/androidannotations/wiki/Rest%20API#post).

**Comment by wangxingge** [comment]
MultiValueMap<String, Object> values = new LinkedMultiValueMap<String, Object>();
values.add("cover", new FileSystemResource(localEditStory.StoryCoverVer));
values.add("name", "中文");

My problem is : I found default content-type is IOS8895-1,but I need to set it to UTF8.
in FormHttpMessageConverter.writePart haven't got a content type, so when convert write content use default content type.

How to change the default content type or make my partEntity has the content-type?

Thanks for your help.

**Comment by wangxingge** [comment]
My requirement was upload zip and name to my server.

And parameter name could be chinese charset, when FormHttpMessageConverter convert the String value, it will used base class content type as current entity content type.
So my question is how to change this parameter content type.

**Comment by WonderCsabo** [comment]
You can try this:

```java
public class CustomFormHttpMessageConverter extends FormHttpMessageConverter {
    
    public CustomFormHttpMessageConverter() {
        setCharset(Charset.forName("UTF-8"));
    }
}

@Rest(converters = CustomFormHttpMessageConverter.class, ...)
public interface YourRestClient {
    //...
}
```

**Comment by WonderCsabo** [comment]
No response, i am closing this. Please reopen if you experience bugs.
