### ISSUE TITLE
Compile problem when a method annotated with @UIThread call another method annotated with @UIThread

### ISSUE THREAD

**Issue by DaviddeMiguel** [excilys/androidannotations#1500]
I don't know if anyone experienced the same problem, but I was 3 ours trying to figure out what was happening and the looks like you cannot call a method annotated with @UIThread from a method annotated with the same annotation.
The bigger problem in my case was that AA didn't show me any exception related with that problem.

**Comment by yDelouis** [comment]
Could you post your code and the generated code to show what does not compile ?

**Comment by WonderCsabo** [comment]
This issue is confusing. The title speaks about a compile problem, but the description is speaking about a missing exception (which is a runtime thing). Moreover I am pretty sure you can simply call this kind of method. 

Please add more information.

**Comment by WonderCsabo** [comment]
No answer since 8 days, i am closing this issue. Please reopen if you have anything to share.
