### ISSUE TITLE
Optimisation: Remove doubled findViewById calls

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1501]
Given I have a class like this:

    @EFragment
    public class VolumeDialog extends DialogFragment {
        @ViewById
        SeekBar volumeSeekBar;

        @SeekBarProgressChange
        protected void volumeSeekBar(final int progress, final boolean fromUser) {
        }
    }

Then AA generates code like this:

    public final class VolumeDialog_
        extends com.company.VolumeDialog
        implements HasViews, OnViewChangedListener
    {
        @Override
        public void onViewChanged(HasViews hasViews) {
            volumeSeekBar = ((SeekBar) hasViews.findViewById(com.company.R.id.volumeSeekBar));
            {
                final SeekBar view = ((SeekBar) hasViews.findViewById(com.company.R.id.volumeSeekBar));
                if (view!= null) {
                    view.setOnSeekBarChangeListener(new OnSeekBarChangeListener() {

                        @Override
                        public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                            VolumeDialog_.this.volumeSeekBar(progress, fromUser);
                        }

                        @Override
                        public void onStartTrackingTouch(SeekBar seekBar) {
                        }

                        @Override
                        public void onStopTrackingTouch(SeekBar seekBar) {
                        }

                    }
                    );
                }
            }
        }       
    }

Which then causes lint to display this message:

**The id `com.company.R.id.volumeSeekBar` has already been looked up in this method; possible cut & paste error?**

Would it be sensible to keep a list of already looked up (& bound) members and then re-use them during processing stage?

**Comment by yDelouis** [comment]
This is done for most event binding but not for `@SeekBarXXX`. We will fix this as soon as the plugin system is out and the project is not frozen anymore.
Thanks for reporting this.
