### ISSUE TITLE
@Background Thread Pool size

### ISSUE THREAD

**Issue by xmstudio** [excilys/androidannotations#1502]
@Background 只允许有两个任务并行。怎么修改线程池的个数。让超过两个任务可以同时运行？

**Comment by WonderCsabo** [comment]
Please write your problem / request in English.

**Comment by xmstudio** [comment]
Background Allowing only two tasks in parallel. How to modify the number of threads pool. Let more than two tasks can be run simultaneously?

**Comment by xmstudio** [comment]
I have found through BackgroundExecutor.setExecutor ();

**Comment by WonderCsabo** [comment]
Thanks for the translation. I am glad you resolved the issue.
