### ISSUE TITLE
@UiThread annotation doesn't seem to run code on the ui thread

### ISSUE THREAD

**Issue by smac89** [excilys/androidannotations#1504]
I have the following code:
```java

private void downloadData() {
    DownloadListener listener = new DownloadListener() {
        @Override
        @UiThread
        public void onContentReceived(long size) {
            Log.d(TAG, "Is on UI thread: " +
                    (Looper.getMainLooper().getThread() == Thread.currentThread()));
            infoDialog.setMaxProgress((int) size);
            infoDialog.setContent(R.string.please_wait);
        }
    };

    Call call = new OkHttpClient().newCall(...);
    call.enqueue(new Customcallback(listener) {
        private DownloadListener listener;
        public Customcallback(DownloadListener l) { listener = l; }
        @Override public void onFailure(Request r, IOException e) {}
        @Override public void onResponse(Request r) throws IOException{
            ...
            listener.onContentRecieved(...);
        }
    });
}
```

Whenever this code is ran, it always crashes and the log output indicates that it is actually not being run on the ui thread. I'm not sure if this is a bug or I might be missing something about the way this annotation should be used.

I tried looking at the generated code for this class and it doesn't seem to me that any code is being generated (which might explain the error)

I also made sure I was using ```org.androidannotations.annotations.UiThread``` not ```android.support.annotation.UiThread```

**Comment by yDelouis** [comment]
`@UiThread`, like all the annotations of AndroidAnnotations must be used in a class annotated with `@EXxxxx` like `@EActivity`, `@EFragment` or `@EBean`.

**Comment by WonderCsabo** [comment]
yDelouis is right. Moreover, please note you cannot use our annotations in anonymous classes. AFAIK they are not subject to annotation processing. If they would, you could get a compilation error added by AA, because of users and this annotation in the wrong place.

**Comment by smac89** [comment]
I solved this by making the activity implement the interface needed and now I can annotate those methods and it works.
Thanks for the reminder

**Comment by groverankush** [comment]
Can you please tell, which interface is to be implemented to work with @UiThread annotation. I recently started working on MVP pattern. I have created an interface, whose methods are called based on different conditions in a Thread, which tends to change the View. I am aware that a handler is required to communicate with the worker thread and Main thread. 

As a resolution, in the implementation of each interface method in the activity I am using runOnUiThread() like:

`@Override
    public void onRemoteConnected() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                setRemoteStatus(true);
                Toast.makeText(BTMusicPlayerActivity.this, "Remote Connected", Toast.LENGTH_SHORT).show();
            }
        });

    }`

It seems to me using @UiThread annotation will simplify this. Please help me with that.
