### ISSUE TITLE
String resource id support for @DefaultString

### ISSUE THREAD

**Issue by LouisCo** [excilys/androidannotations#1505]
Hi,

Could you add support for string resource ids in `@DefaultString` annotations so I can localize some preferences default values without having to call getOr()?

Best regards, and thanks for this awesome library

**Comment by WonderCsabo** [comment]
You can use @DefaultRes.

**Comment by WonderCsabo** [comment]
I assume this works for you.

**Comment by LouisCo** [comment]
Yes, it works flawlessly, thank you!
