### ISSUE TITLE
how to request https with androidannotations?

### ISSUE THREAD

**Issue by GunleyChan** [excilys/androidannotations#1506]
Excuse me . I am a Chinese. My English is not so good.  So , I may make some grammar mistakes. Now , I want to request https with androidannotations. How can I do this? Thank you !

**Comment by WonderCsabo** [comment]
This has been asked several time: #1347, #1074. also on [stackoverflow](http://stackoverflow.com/search?q=AndroidAnnotations+https).

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by GunleyChan** [comment]
@WonderCsabo thx
