### ISSUE TITLE
UI update after switching to main thread via @UiThread gives FATAL EXCEPTION (CalledFromWrongThreadException)

### ISSUE THREAD

**Issue by egornemov** [excilys/androidannotations#1511]
Simple snippet (see below) with UI update after switching from worker to main thread causes :boom: FATAL EXCEPTION :boom: **android.view.ViewRootImpl$CalledFromWrongThreadException** ("Only the original thread that created a view hierarchy can touch its views"):

```
@Background
void doBackgroundWork() {
    updateUi();
}

@UiThread
void updateUi() {
    myTextView.append("\nBackground work is DONE ");
}
```

**P.S.:** 
* Android Annotations v. 3.3.2
* Compile SDK v. 22
* AndroidStudio v. 1.3

**Comment by dodgex** [comment]
have you ensured that you are using the correct `@UiThread` annoatation? google has added an annotation with the same name to thier android-support-annotations library. so if you are using/importing that annotation you have to change it to the android annotation one

**Comment by egornemov** [comment]
You are right. It was due to **android.support.annotation.UiThread** import instead of suitable one. For now UI update works without any issues.

**Comment by mayurnemade** [comment]
Thanks fix my issue also
