### ISSUE TITLE
Android Studio 1.3 can't use data binding

### ISSUE THREAD

**Issue by codingplusplus** [excilys/androidannotations#1512]
If use androidannotations, data binding will error.

**Comment by dodgex** [comment]
more details.

**Comment by codingplusplus** [comment]
/Users/chenchao/Downloads/dell/StudyBind/app/src/main/java/study/chenchao/studybind/MainActivity.java
Error:(9, 44) 错误: 程序包study.chenchao.studybind.databinding不存在
"不存在" means no exist.
I write "hello, world" app by Android Studio 1.3, use data binding, it works fine.
But if I configure build.gradle by https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle, error was generated.

my project https://github.com/codingplusplus/StudyBind

**Comment by dodgex** [comment]
The [Data Binding Guide](https://developer.android.com/tools/data-binding/guide.html) mentions
> To use data binding, Android Plugin for Gradle 1.3.0-beta4 or higher is required.

but your top level [build.gradle](https://github.com/codingplusplus/StudyBind/blob/master/build.gradle#L8) uses `1.0.0` and your app/module [build.gradle](https://github.com/codingplusplus/StudyBind/blob/master/app/build.gradle#L36) uses `1.2.2`

try to upgrade the plugin version and also you should reference the plugin only once.

**Comment by WonderCsabo** [comment]
I assume this is not an AA error. In the other case please reopen.
