### ISSUE TITLE
Error while building project.

### ISSUE THREAD

**Issue by shivamsingh** [excilys/androidannotations#1513]
Error:(18, 8) error: Something went wrong: Unexpected error in AndroidAnnotations 3.2!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=com.sun.tools.javac.code.Symbol%24CompletionFailure&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.8.0
Javac processors options: androidManifestFile=C:\project10\app\build\intermediates\manifests\full\debug\AndroidManifest.xml, resourcePackageName=com.driveme
Stacktrace: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.support.v4.app.DialogFragment$DialogStyle not found

**Comment by dodgex** [comment]
you should upgrade to AA 3.3.2 and/or use the 22.2.1 of android support libraries.

**Comment by dodgex** [comment]
see https://github.com/excilys/androidannotations/issues/1435
