### ISSUE TITLE
Wrong code sample in documentation

### ISSUE THREAD

**Issue by agentges** [excilys/androidannotations#1515]
In this section
https://github.com/excilys/androidannotations/wiki/Rest-API#post

Doc says:
>MultiValueMap<String, Object> data = new LinkedMultiValueMap<>();
>...
>data.put("image", image);
>data.put("description", description);
>data.put("title", title);

Due to MultiValueMap put() method accepts List<> as second parameter, we have to use set() method instead.

Should be:
>data.set("image", image);
>data.set("description", description);
>data.set("title", title);

**Comment by WonderCsabo** [comment]
Thanks for pointing out the problem! Maybe the add() method would be even better. Wanna contribute to the wiki?

**Comment by yDelouis** [comment]
The wiki has been fixed.
