### ISSUE TITLE
AndroidAnnotations Truck Factor

### ISSUE THREAD

**Issue by gavelino** [excilys/androidannotations#1516]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **AndroidAnnotations** and obtained a value of **2**.

The developers responsible for this TF are:

Pierre-Yves Ricau - author of 42% of the files
yDelouis - author of 25% of the files

To validate our results, we would like to ask **AndroidAnnotations** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **AndroidAnnotations**?

(b) Do you agree that **AndroidAnnotations** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **AndroidAnnotations** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by yDelouis** [comment]
I give my opinion about your question and I will let other people complete the answer with their thoughts.

(a) I would have added @DayS and @WonderCsabo as main developers. @pyricau and @DayS are no longer maintaining the project but their contributions were very important.

(b) @pyricau has already left the project. If I leave the project, I think that @WonderCsabo will be able to maintain it (with the help of a new developer).

(c) The wiki explains well how to contribute. And the architecture makes it easy to add some new features. Changing the architecture would be quite difficult for a new developer though.

**Comment by pyricau** [comment]
@gavelino I guess you just found a counter example :)

**Comment by WonderCsabo** [comment]
@gavelino The final TF value is correct, but the reason is incorrect, as @pyricau and @yDelouis explained. And i also have to note that the percentages maybe not really cover who is the real author of the files. During a big refactor,  @yDelouis moved lots of files which are cannot be detected by `git log`, so in lots of cases he is not really the author of those files (no offense @yDelouis :) ).

Thanks for closing our project, this is a really interesting survey. I am closing this issue now, i hope all your questions were answered.
