### ISSUE TITLE
@EService and @EIntentService doesn't work

### ISSUE THREAD

**Issue by egornemov** [excilys/androidannotations#1517]
**Service** [life cycle events](https://github.com/excilys/androidannotations/wiki/Enhance%20Services) and **IntentService** [action call](https://github.com/excilys/androidannotations/wiki/Enhance%20IntentServices) do nothing (even further: service instance isn't created).

**P.S.:** 
* Android Annotations v. 3.3.2
* Compile SDK v. 22
* AndroidStudio v. 1.3

**Comment by WonderCsabo** [comment]
Please add much more detail. We have lots of projects using these and also automated tests to verify the behavior.

**Comment by egornemov** [comment]
Declare IntentService via annotation, start it from annotated activity via inner builder (or in a canonical way), spectate. Snoppets below:

```
@EIntentService
public class MyIntentService extends IntentService {

    public MyIntentService() {
        super("MyIntentService");
    }

    @ServiceAction
    void mySimpleAction() {
        // ...
    }

    @ServiceAction
    void myAction(String param) {
        // ...
    }

    @Override
    protected void onHandleIntent(Intent intent) {
        // Do nothing here
    }
}
```

Start service from annotated activity:
```
// start service via inner builder
MyIntentService_.intent(getApplication()).mySimpleAction().start();

// start service in canonical way
Intent intent = new Intent(this, NuService_.class);
startService(intent);
```

**Comment by egornemov** [comment]
Fixed (APK logic error). Service was not declared in Manifest:
```
<service android:name=".MyIntentService_"/>
```
