### ISSUE TITLE
`@UiThread` not generated with latest AppCompat

### ISSUE THREAD

**Issue by theoriginalbit** [excilys/androidannotations#1518]
## Description
Using latest version of AndroidAnnotation (at time of creation `3.3.2`) and using latest version of AppCompat v7 (at time of creation `22.2.1`) classes containing the `@UiThread` annotation don't have those methods overridden to force them onto the UI Thread.

The following code was expected to work:
```Java
@EActivity(R.layout.activity_main)
public class MainActivity extends AppCompatActivity {
  @AfterViews
  public void initViews() {
    // ...
    downloadSomething();
  }

  @Background
  public void downloadSomething() {
    // ...
    showError();
  }
  
  @UiThread
  public void showError(String message) {
    new AlertDialog.Builder(this).setMessage(message).create().show();
  }
}
```

## Expected result
The dialog to be displayed fine as the code is run in the UI thread.

## Actual result
The application crashes with `java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()` as the call is still running on the background thread.

## Additional notes
Upon further investigation it seems that the `MainActivity_` class did not have the `showError` method overridden so the call was made on the UI thread, therefore it was always being run on the background thread.

**Comment by dodgex** [comment]
please check your imports. it looks like you are importing the `@UiThread` annotation that is provided by the `android-support-annotions` library and not the one provided by Android Annotations.

**Comment by theoriginalbit** [comment]
Oh I'm sorry, you are correct. The package structures were so similar, and it's such a new addition, I did not even realise it wasn't from android annotations.

**Comment by rafeln** [comment]
nice!
thank you!
