### ISSUE TITLE
@RestService inject time is long

### ISSUE THREAD

**Issue by kaiyan910** [excilys/androidannotations#1519]
Hi guys,

Currently, I have declared three @RestService instances in Application class and turn out it leads to a long opening time of the application (take nearly 2s to open the launch activity). I am quite sure it is related to the @RestService as I used to put those @RestService in the BaseActivity, as a result the opening time of each activity is >1s, so I decided to put all the @RestService in the Application class as a static variables.

Is the inject time normal ? or has a better practice to reduce the time of injection. 

Thanks all.

**Comment by WonderCsabo** [comment]
You should profile it first. AFAIK the service creation is fast, but I am AFK now, cannot check it.

**Comment by kaiyan910** [comment]
How can I profile the application ?

**Comment by WonderCsabo** [comment]
Sorry, I also do not have experience on that. However, our can simply call the rest template constructor and log time before and after it. 

But I am pretty sure this is not an issue.
