### ISSUE TITLE
How can I add annotation in Android Studio 1.3 ?

### ISSUE THREAD

**Issue by los8won** [excilys/androidannotations#1521]
I don't know how to add annotation to my project in Android Studio 1.3, who can help ?

**Comment by dodgex** [comment]
Have you checked the wiki and sample project?

**Comment by Francis0121** [comment]
When I first followed wiki page step, but i didn't compile android annotation.

So I did this.

#### First 
`File -> Setting -> Buil, Execution, Deployment -> Comiler -> Annotation Processor`

![image](https://cloud.githubusercontent.com/assets/3794501/9292419/b1dd5180-4432-11e5-8c5a-4d22104c3a30.png)

#### Second
Checked `Enabled annotation processing`

![image](https://cloud.githubusercontent.com/assets/3794501/9292429/63b2a2e8-4433-11e5-93b0-4f503925c234.png)

When i did this, I succeed android annotation compile.

**Comment by WonderCsabo** [comment]
You do not have to add any configuration in IntelliJ, only in your buildscript. Import the [example](https://github.com/excilys/androidannotations/tree/develop/examples/gradle) project, then extend it to your needs.

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
