### ISSUE TITLE
Spring like configuration

### ISSUE THREAD

**Issue by natami** [excilys/androidannotations#1522]
Is it possible to do something similar to Spring Framework, when configuring a specific bean?:

```java
@Configuration
public class BeansConfiguration {

@Bean 
public ConfiguredBeanToReturnWhenInjecting() {
return new ConfiguredBeanToReturnWhenInjecting("configdata");
}

}
```

**Comment by dodgex** [comment]
Not yet. 

See https://github.com/excilys/androidannotations/issues/1520

**Comment by natami** [comment]
Are there any temporary workarounds before #1520 is implemented?

**Comment by dodgex** [comment]
create a `@EBean` class with getter methods for your stuff to configure and inject that bean and use the getters.

**Comment by WonderCsabo** [comment]
Closing this in favor of the other issue.
