### ISSUE TITLE
ProGuard strips out classes.

### ISSUE THREAD

**Issue by westito** [excilys/androidannotations#1523]
I get "java.lang.NoClassDefFoundError: Failed resolution of: Lorg/androidannotations/api/view/OnViewChangedNotifier;" logcat error when using proguard. 

Gradle plugin: 1.3.1
Build tools: 22.0.1
API: 22

This wan't problem before.

**Comment by WonderCsabo** [comment]
Can you provide an example project?

**Comment by WonderCsabo** [comment]
Closing this bug due to lack of response. Please reopen if you still experience it.
