### ISSUE TITLE
How send Large File with @POST?????

### ISSUE THREAD

**Issue by teoSalvetti** [excilys/androidannotations#1524]
I'm using ```@Rest``` and  ```@Post``` annotation to send a file from my Android app to a webserver.... It works for a bit time, but now the file reach **8MB**, and I obtain OutOfMemory erro when I try to send it....

**How can I send that file?? **

This is my Rest Client:

```
@Rest(converters = {FormHttpMessageConverter.class, MappingJackson2HttpMessageConverter.class})
public interface DbRestClient  extends RestClientErrorHandling{

	........
	
	@Post("dbSynk/postNew")
	Integer postDb(MultiValueMap file);
}
```

And this is a piece of my service:

```
try{
	File fileZip = FileUtils.zipFile(new String[]{FileConfig.DB_PATH});
	MultiValueMap<String, Object> parts = new LinkedMultiValueMap<String, Object>();
	parts.add("file", new FileSystemResource(fileZip.getAbsoluteFile()));
	dbRestClient.postDb(parts);
}catch(Exception e){
	MyLog.d(LOG_TAG, "Elapsed for DB send " + ((System.currentTimeMillis() - currentMillis)/1000f));
}
```

**Comment by teoSalvetti** [comment]
I post a question on stackoverflow too: http://stackoverflow.com/questions/32072717/how-send-large-file-with-post-outofmemory-error

**Comment by WonderCsabo** [comment]
This question should be raised against the upstream Spring for Android project, since we have no control of this.
