### ISSUE TITLE
copy javadoc for Activity @Extra and @FragmentArg to thier builder

### ISSUE THREAD

**Issue by dodgex** [excilys/androidannotations#1525]
if it is possible to read javadoc comments from processed elements/fields it would be nice to copy the javadoc for Activity `@Extra` and `@FragmentArg` to the related builder. that allows to have a documented "api".

e.g.
```java
/**
 * [any javadoc]
 */
@Extra("MY_EXTRA_KEY")
protected String myExtra;
```
-> 
```java
/**
 * [any javadoc]
 */
public MyActivity_.IntentBuilder_ myExtra(long myExtra) {
    return super.extra(MY_EXTRA, myExtra);
}
```

dependeing on the possibilities of the code generation extend the javadoc to be valid:
```java
/**
 * [any javadoc]
 *
 * @param myExtra The value to set
 * @return The IntentBuilder to chain calls
 */
```

thoughts?

**Comment by dodgex** [comment]
maybe even generate the javadoc all the time, but add the text from the field ?

```java
/**
 * [optional: copy field javadoc]
 *
 * Intent/Extra Key: "MY_EXTRA_KEY".
 * 
 * @param myExtra The value to set
 * @return The IntentBuilder to chain calls
 */
```

**Comment by yDelouis** [comment]
Shall we count on you to submit a PR as soon as the project is not frozen due to the plugin refacto any more ?

**Comment by dodgex** [comment]
If this enhancement is welcome i'll try to get a PR up. Any eta on the plugin refactoring?

**Comment by yDelouis** [comment]
It's hard to give an ETA for the plugin refacto but I think we are close to the end. All it remains, I think, is to define the API for plugins.

**Comment by dodgex** [comment]
Okay, so I still got some time for this PR. ;)

**Comment by WonderCsabo** [comment]
Before you get too excited: I am not sure the processing API passes the doc
at all. Does it?

**Comment by dodgex** [comment]
@WonderCsabo it passes. 
```java
String comment = processingEnv.getElementUtils().getDocComment(element);
```

**Comment by dodgex** [comment]
is there another annotation beside `@Extra` and `@FragementArg` that creates a method for a builder?

**Comment by WonderCsabo** [comment]
ServiceAction?

**Comment by dodgex** [comment]
`@ServiceAction` uses the same code to generate the methods as `@Extra` so there is the javadoc with the `@param` and `@return` already. only having additional custom javadoc text is not possible there as the setter methods are generated by parameters

**Comment by WonderCsabo** [comment]
Great, thanks for looking into this!

**Comment by WonderCsabo** [comment]
Implemented.
