### ISSUE TITLE
gradle-experimental can't use apt

### ISSUE THREAD

**Issue by chenzj-king** [excilys/androidannotations#1527]
as title.my project must use ndk.but ndk need gradle-experimental instead 
'com.android.tools.build:gradle'.but the apt plugin can't work.i see that apt author talk about that.
https://bitbucket.org/hvisser/android-apt/issues/46/support-for-experimental-plugin#comment-None
how can i use androidannotations but not use the apt plugin.please guide me handle this problem.thanks.

**Comment by dodgex** [comment]
while i haven't tested the experimental plugin yet, maybe you could get somehow to work with the old guide: https://github.com/excilys/androidannotations/issues/676

thats how AA was used before the `android-apt` plugin was created. maybe some of the steps there help to get it work with the new experimental plugin.

Good Luck

**Comment by WonderCsabo** [comment]
Sorry, but this is really not our responsibility. From this point of view, we just another annotation processor.

**Comment by ikuriel** [comment]
@WonderCsabo imagine a world where everyone wait to everyone to fix something.
