### ISSUE TITLE
Always call @AfterExtras methods

### ISSUE THREAD

**Issue by m-radzikowski** [excilys/androidannotations#1528]
Hey,
I've an Activity with one extra:
```
	@Extra
	protected Long id;
```

There are two use cases for this activity:
- pass id in extra to edit existing entity,
- don't pass any extra to open activity for new entity creation.

So I've had method:
```
	@AfterExtras
	protected void setupEntity() {
		if (id != null) {
			entity = loadEntityById(id);
		} else { // create new entity with default data
			entity = new Entity();
			// some more initialization of entity
		}
	}
```

But code generated by AA is:
```
    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(ID_EXTRA)) {
                id = ((Long) extras_.getSerializable(ID_EXTRA));
            }
            setupEntity();
        }
    }
```

So my `setupEntity()` method is not called if  in result I'm unable to check if this single extra was passed or not in AA style and perform actions based on this. So I have two propositions:
- [EASY?] change generated code to:
```
    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(ID_EXTRA)) {
                id = ((Long) extras_.getSerializable(ID_EXTRA));
            }
        }
        setupEntity();
    }
```
- [HARD] add required extras to intent builder,
- tell me what is better way to handle this without boilerplate code, AA style?

Tested on AA 3.3.2.

**Comment by dodgex** [comment]
you easily can use `@AfterInject` or `@AfterViews` here. both should be called always and when they are called the extras are already injected (if available).

so simply use one of those annotations on your `setupEntity()` method and your app should work as intended

**Comment by dodgex** [comment]
but... i just remembered... depending on how your activity might be called, this would not work when your activity gets another intent after the first. as only `@AfterExtras` is called for new Intents. but when you are sure that your activity is always newly created it should be no problem

**Comment by dodgex** [comment]
[here](https://github.com/excilys/androidannotations/wiki/%40AfterXXX-call-order#initial-calls-after-creation) you can read a little bit more about when methods with an `@AfterXXX` annotations are called

**Comment by m-radzikowski** [comment]
Ok, using `@AfterInject`solved the problem (I can't use `@AfterViews` in this case as I fill view depending on data from extra).

But I would still this that all `@AfterXXX` methods should be called on start of activity, especially when there is no mechanism to force extra set in intent. Or at least some note in documentation about `@Extra` annotation.

But thanks for quick response and solving my problem.

**Comment by dodgex** [comment]
i'm glad i could help for now :)

@WonderCsabo @yDelouis any thoughts on calling `@AfterExtras` always? i think this is ok.

**Comment by yDelouis** [comment]
I also think so. I think it's a bug.

**Comment by dodgex** [comment]
i'll prepare a PR to always call `@AfterExtras`.

**Comment by WonderCsabo** [comment]
FIxed.
