### ISSUE TITLE
Mocking activity not possible because class is final

### ISSUE THREAD

**Issue by liviuignat** [excilys/androidannotations#1532]
Hi,

Use case I encountered: Let's say you want to mock an Activity and verify a mocked method was called. Currently this is not possible because of the final classes being generated. Is the final really required? I don't see it as a requirement in the generated Activity_ classes to be honest, it's adding just extra unnecessary restrictions.

Thanks,
Liviu.

**Comment by dodgex** [comment]
you might want to use [PowerMock](https://github.com/jayway/powermock/) as it supports mocking [final classes and methods](https://github.com/jayway/powermock/wiki/MockFinal).

**Comment by liviuignat** [comment]
This is still an unnecessary restriction. Final on Activity_ classes don't make any sense.

**Comment by dodgex** [comment]
iirc this is to avoid that users extend from generated classes. but i'm not sure... i think @WonderCsabo  or @yDelouis can say more about that.

**Comment by yDelouis** [comment]
Yes, this is why generated classes are final. I don't know if we should change that.

**Comment by liviuignat** [comment]
Well I have two questions:
1. Would inheriting the Activity_ class would break the code?
2. If yes, why not add the "final class Activity_" option as a configuration option in gradle and let the developers choose if they trust their team or not? Me and my team would prefer not to have final, static, etc classes and I am sure there are others that would prefer not to be forced to have final classes.

Thanks,

**Comment by WonderCsabo** [comment]
I am OK to add an option. However be aware that AA uses lots of final and
static things, maybe you just removing final from the class will not help
you.

**Comment by liviuignat** [comment]
Hi, I am aware of that, but I thing not having final on classes, would still solve a lot.

Thanks,
Cheers,

**Comment by ened** [comment]
An AA processor option to disable the final modifier might also improve unit testing / androidTest capabilities. (That is, if the android-apt plugin supports separate generated sources per build type,  @hvisser ? :-))

**Comment by hvisser** [comment]
@ened Currently it does not directly, but you might be able to pass a function into the configuration closure as a workaround (haven't tried it).  In theory you should be able to configure AA based on the variant, since project and variant are passed into the config block.

**Comment by WonderCsabo** [comment]
OK, then, i am marking this as an enhancement, but we will not pursue this due to other priorities. Contributions are welcomed!

**Comment by WonderCsabo** [comment]
Implemented.
