### ISSUE TITLE
I have problem when setting up environment installation

### ISSUE THREAD

**Issue by Francis0121** [excilys/androidannotations#1534]
Hi

I am very interested in contributing to the project
But I have problems when installing the environment. 
When I tried to import the testing projects(AndroidAnnotations/functional-test-1-5), I got the following error messages. 
I tried cleaning the project and changing the name of the generated source directory, but it did not work.
I did all of thing at this url (https://github.com/excilys/androidannotations/wiki/InstallingEnvironment)
Could you please help me with it? Thanks.

![2015-08-28 00 16 04](https://cloud.githubusercontent.com/assets/3794501/9524959/a9cff892-4d1c-11e5-9947-4bb807707cc2.png)

![2015-08-28 00 14 15](https://cloud.githubusercontent.com/assets/3794501/9524957/a790dcf4-4d1c-11e5-8630-b2c7014304f2.png)

![2015-08-28 00 15 42](https://cloud.githubusercontent.com/assets/3794501/9524956/a78fc2d8-4d1c-11e5-855d-34273c8d217c.png)

**Comment by WonderCsabo** [comment]
Let's continue this on the [mailing list](https://groups.google.com/forum/#!topic/androidannotations/WaP9NzP6888).
