### ISSUE TITLE
@PreferenceXXX should work with support-v7 PreferenceFragmentCompat

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1535]
An [official implementation](https://plus.google.com/+AndroidDevelopers/posts/9kZ3SsXdT2T) just added for `PreferenceFragment` compatibility in the Support Library. Our annotations should support that. See https://github.com/excilys/androidannotations/issues/1396#issuecomment-135756979.

**Comment by dodgex** [comment]
from linked issue:
> Cool! We should just add android.support.v7.preference.PreferenceFragmentCompat as a supported class, and it should work, shouldn't it?

Nope. this compat class uses mostly `.support.v7` classes as `android.support.v7.preference.Preference`. i assume this update will become a little bit harder

**Comment by WonderCsabo** [comment]
You are right. I just quickly looked at the methods, and did not check FQCNs. This complicates things. 😞

**Comment by dodgex** [comment]
Btw there is a v14 PreferenceFragment too.
