### ISSUE TITLE
Annotations Support for R.mipmap.resource_id

### ISSUE THREAD

**Issue by castrojr913** [excilys/androidannotations#1536]
I have tried using @DrawableRes for images on *mipmap* directory (R.mipmap.*resource_id*) and it didn't work; with *resName* attribute neither. I don't know if my position is correct, but I feel that there isn't a implementation to fetch resources with R.mipmap approach.

` @DrawableRes(R.mipmap.ic_drawer_scanned_devices)
    Drawable drawerScannedDevicesIcon;
`

It throws during rebuilding: `error: Resource Id value not found in R.drawable: ...`

Lib version: ` compile 'org.androidannotations:androidannotations-api:3.3.2' `

**Comment by WonderCsabo** [comment]
You are right, this is not implemented, yet. The same methods can be used
to get the mipmap?

**Comment by WonderCsabo** [comment]
BTW, is this feature really needed? Mipmap is only needed for launcher
icons, and it is rare that you have to work with a launcher icon in code.

**Comment by castrojr913** [comment]
@WonderCsabo According to Katherine Kuan on Android Developers blog, all icons should be placed  in *mipmap* folders:  "It’s best practice to place your app icons in mipmap- folders (not the drawable- folders)" [[1]](http://android-developers.blogspot.in/2014/10/getting-your-apps-ready-for-nexus-6-and.html). In my context, I'm building a drawer panel which it needs instances for those icons. Therefore, I'm forced to use the methods, either context.getResources().getDrawable(int, Theme) or ContextCompat.getDrawable(context, int), for this purpose.

**Comment by WonderCsabo** [comment]
In my interpretation, it should be used for launcher icons only, not regular drawables like action bar icons:

> It’s best practice to place your app icons in mipmap- folders (not the drawable- folders) because they are used at resolutions different from the device’s current density. *For example, an xxxhdpi app icon can be used on the launcher for an xxhdpi device.*

I think the emphasized sentence does not hold for regular drawables.

**Comment by castrojr913** [comment]
Excuse me. I had a mistake :S, closing the issue. @WonderCsabo I got it.

**Comment by WonderCsabo** [comment]
No answer on *adt-dev* since a week. :( @castrojr913 can you investigate this? I still think `mipmap` is only for launcher icons.

**Comment by dodgex** [comment]
@WonderCsabo maybe you should have asked on G+. 

Also i think He wanted to close the issue but accidently reopened it with his comment

**Comment by WonderCsabo** [comment]
I asked this on [G+](https://plus.google.com/+AndroidDevelopers/posts/4fPaqYUZ6Uh).

**Comment by castrojr913** [comment]
@WonderCsabo @dodgex I will investigate about that. From my custom perspective, I have used mipmaps for icons and images. Drawables for custom shapes or backgrounds. It will be nice to support this feature, The developer will have freedom to decide how he/she wants to implement its code.

**Comment by castrojr913** [comment]
Here is a discussion about this on [Stack](http://stackoverflow.com/questions/28065267/mipmap-vs-drawable-folders), but it´s truth, there aren't a clear information about this topic.

**Comment by WonderCsabo** [comment]
Sorry, but for me all the referenced pages mean that mipmap is for launcher icons only, or it is mostly useful for those kind of icons only.

All the `@XXXRes` annotation has a clear, structured implementation, and it is not easy to add mipmap to it. So that is why i am reluctant to approve this issue, if this is actually not useful (launcher icons are not likely will be injected).

**Comment by WonderCsabo** [comment]
I am closing this now. Please reopen if you have clear evidence. :) I would not implement this until, because this needs some rework on our architecture for resource injections, which is pretty clear currently.

**Comment by WonderCsabo** [comment]
@castrojr913 You should not put any resources other than launcher icons to the mipmap folders. Check out the latest comments [here](https://plus.google.com/u/0/+AndroidDevelopers/posts/4fPaqYUZ6Uh). So this feature indeed does not really needed in AA.

**Comment by castrojr913** [comment]
@WonderCsabo yeah, thus, it's not required reading those comments. The good thing is that this topic has been explained very clearly to avoid doubts.
