### ISSUE TITLE
M Permissions

### ISSUE THREAD

**Issue by BukT0p** [excilys/androidannotations#1537]
That would be great to add some code generator for new permissions system like they did for https://github.com/hotchemi/PermissionsDispatcher. They did a great job but their lib conflicts with AA.

**Comment by WonderCsabo** [comment]
Are you it is incompatible? I checked the readme and the examples, and it seems it does not create a subclass, but generates another class, which just makes calls to the original `Activity`. This should not conflict with AA. Can you explain?

**Comment by BukT0p** [comment]
they have this issue https://github.com/hotchemi/PermissionsDispatcher/issues/14. They are generating code in the same way - by generating a class with "_" char in the end. So I annotated my fragment with @EFragment and @RuntimePermissions and build failed with error: 

> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> permissions.dispatcher.processor.exceptions.WrongClassException: Annotated class must be finished with 'Activity' or 'Fragment'

Actually I don't want to put their lib just for adding the dispatcher. Instead I want to use AA for this purpose, I can try to create a pull request If you are busy)

**Comment by BukT0p** [comment]
@WonderCsabo I understand the reason of the error and that is completely their bug. I know that AA is reliable and always up to date. That is why I requested this new feature - it would be highly relevant.

**Comment by WonderCsabo** [comment]
@BukT0p you said
> They are generating code in the same way - by generating a class with "_" char in the end.

which is not true.

Sorry, but i see no reason to reimplement a feature which is already created in another project. @yDelouis @dodgex WDYT?

**Comment by dodgex** [comment]
As the issue van easily bei fixed on thier side, i think we have no reason to implement that. 

One can use the plugin API to create a custom plugin. But Not as official Feature

**Comment by hotchemi** [comment]
Oh just realized...
About PermissionsDispatcher, we're gonna fix the problem. Just a minute.

**Comment by WonderCsabo** [comment]
I am closing this bug, because this will be fixed in `PermissionsDispatcher` (hopefully) soon.

**Comment by hotchemi** [comment]
In this week, probably!

**Comment by hotchemi** [comment]
@BukT0p [1.2.1](https://github.com/hotchemi/PermissionsDispatcher/releases/tag/1.2.1) is out. So please check it out.
