### ISSUE TITLE
Multipart Request with Unicode

### ISSUE THREAD

**Issue by maohieng** [excilys/androidannotations#1547]
Here is my code:

    @Rest(rootUrl = ConstantURL.SERVER, converters = {FormHttpMessageConverter.class, GsonHttpMessageConverter.class, StringHttpMessageConverter.class}, interceptors = {HttpInterceptor.class})
    public interface MyRestClient extends RestClientErrorHandling {
        String getHeader(String name);
        void setHeader(String name, String value);
        @Post(ConstantURL.URL_CHANGE_USER_PROFILE)
        @RequiresHeader("Content-Type")
        Response changeUserProfile(MultiValueMap params);
    }

Then send a request:

    String name = "ម៉ៅ ហៀង"; //unicode
    MultiValueMap data = new LinkedMultiValueMap<String, Objects>();
    FileSystemResource image = new FileSystemResource(getSavedImage());
    data.add("image", image);
    data.add("name", name);
    mServer.setHeader("Content-Type", MediaType.MULTIPART_FORM_DATA);
    try {
           mServer.changeUserProfile(data);
    } catch (RestClientException e) {
          e.printStackTrace();
    }

After that, I got data on my server with characters "????"

Please help.

**Comment by dodgex** [comment]
I don't think that this is an AA issue. You might want to ask this the spring-rest-template guys.

**Comment by WonderCsabo** [comment]
@maohieng you can fix this as follows.

Create a custom form converter class, which uses string part converter with the desired character encoding:

```java
public class CustomFormHttpMessageConverter extends FormHttpMessageConverter {

	public CustomFormHttpMessageConverter() {
		List<HttpMessageConverter<?>> partConverters = new ArrayList<HttpMessageConverter<?>>();
		partConverters.add(new ByteArrayHttpMessageConverter());
		StringHttpMessageConverter stringHttpMessageConverter = new StringHttpMessageConverter(Charset.forName("UTF-8"));
		stringHttpMessageConverter.setWriteAcceptCharset(false);
		partConverters.add(stringHttpMessageConverter);
		partConverters.add(new ResourceHttpMessageConverter());
		setPartConverters(partConverters);
	}
}
```

The simply use this converter in your `@Rest` interface:

```java
@Rest(rootUrl = ConstantURL.SERVER, converters = {CustomFormHttpMessageConverter.class, GsonHttpMessageConverter.class, StringHttpMessageConverter.class}, interceptors = {HttpInterceptor.class})
public interface MyRestClient extends RestClientErrorHandling {
  // ...
}
```

**Comment by maohieng** [comment]
@WonderCsabo, you help my life. Thank you. :)

**Comment by WonderCsabo** [comment]
No problem. Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
