### ISSUE TITLE
Abstract Activity Subclass @AfterInject crash

### ISSUE THREAD

**Issue by slidenerd** [excilys/androidannotations#1549]
I am trying something with your awesome library. i have an abstract class that looks like this
![snap 2015-09-14 at 21 06 37](https://cloud.githubusercontent.com/assets/5139030/9854078/9071ed7c-5b24-11e5-8d7c-a568e3b7f92d.png)

Its layout looks like this
![snap 2015-09-14 at 21 07 36](https://cloud.githubusercontent.com/assets/5139030/9854099/a9aa4758-5b24-11e5-9a44-f05db0a66e2f.png)

My sub activity looks like this
![snap 2015-09-14 at 21 08 58](https://cloud.githubusercontent.com/assets/5139030/9854131/d6457120-5b24-11e5-9479-adf894e51a95.png)

Its simple layout looks like this
![snap 2015-09-14 at 21 09 27](https://cloud.githubusercontent.com/assets/5139030/9854143/e72fd048-5b24-11e5-815d-e21a22a990a9.png)

I tried all possible combinations 1) inflate the base layout in the parent, child layout in the child 2) inflate the base layout in both the parent and the child

I keep getting a crash either in the parent saying the child view was null or in the child saying the parent root was null depending on which combination I run
This is the exception I get
![snap 2015-09-14 at 21 12 33](https://cloud.githubusercontent.com/assets/5139030/9854231/5985b5ea-5b25-11e5-853f-bb3231aa8694.png)

1 very important thing to note, I do not have a GENERATED class for the parent
![snap 2015-09-14 at 21 11 15](https://cloud.githubusercontent.com/assets/5139030/9854203/27caedc2-5b25-11e5-9a02-5181935191c0.png)
is this normal in this library? I already referred to #319 and #698 before posting this. Am I missing something? Thanks for your suggestions in advance

**Comment by WonderCsabo** [comment]
Can you paste the code as text instead of images?

**Comment by WonderCsabo** [comment]
Event better, can you share the project? It seems you already have (hopefully not secret :) ) demo project. The easiest way is to push the project to a GitHub repo.

**Comment by slidenerd** [comment]
Thanks for getting back so fast, here is the github project branch https://github.com/slidenerd/Android_Annotations_Demo/tree/afteraa

**Comment by WonderCsabo** [comment]
@slidenerd The problem here that your layout of the `SubActivity` is just the following:

```xml
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/text_message"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="@string/hello_world" />
```

As you can see, there is no view with id `content_frame` in it. That is why the `root` field is `null` (`findViewById()` returns `null` if the view with the specified id cannot be found).

**Comment by slidenerd** [comment]
The content_frame is defined in the parent layout file, I cant get AA to work in a way that the parent has a layout, asks the child to give its layout, and merges both of them. I ll tell you why such a layout is needed. I am planning to use a Navigation Drawer across all my apps, My idea is to have a parent layout file with the DrawerLayout and other components and a FrameLayout that can be filled by the child. How can I achieve such a layout with AA. Before making this demo project I actually tried this on a  LIVE complex application and found out that @AfterInject is not triggered for the base abstract parent activity class. If I dont add the @EActivity annotation then AA does complain about it. If i add it, I am still inflating views manually with the findViewById. If you see my demo example screenshots in this issue you ll notice content_frame in the parent FrameLayout, I want the child s layout to fill that Framelayout, your suggestions are highly appreciated. thanks for your time

**Comment by dodgex** [comment]
the layout of the parent activity is overriden by the child activity. so the parent layout is never loaded.

also i think that NavigationDrawer should be implemented using fragments instead of activities like you try.

**Comment by slidenerd** [comment]
Well the NavigationView has changed the way drawers are implemented :) even if I want to add it in a fragment, this fragment will be a part of the base activity and then i ll be able to have sub activities that simply supply their layout, we dont want a drawerlayout inside every activity, infact with the onset of the design support library, its a pretty complex setup with the coordinatorlayout, would like each activity to simply provide its layout and let the base activity add it to some ViewGroup in its hierarchy, let me know how I can fix this issue :) thanks in advance

**Comment by WonderCsabo** [comment]
I think your code is almost OK. Change `SubActivity` to this:

```java
@EActivity(R.layout.activity_base)
@OptionsMenu(R.menu.menu_sub)
public class SubActivity extends BaseActivity {

    @AfterViews
    void setMessage() {
        message.setText("Hey is this working? "); // message from activity_base.xml
    }

    @Override
    public int getActivityLayout() {
        return R.layout.activity_sub;
    }
}
```
So AA will set the base layout, with the `FrameLayout` `content_frame` in it. Then it will inject the `root` field, and you can add the view of the sub activity as you already do.
Also i removed the `message` field from your `SubActivity`. AA can only inject views which are added via `setContentView()`. So it will able to inject the `TextView` in the parent layout, but not the view which is in the layout you dynamically add.

About `@AfterInject`: that is called after resources, beans are injected, and before views are injected. To work with views, you have to use an `@AfterViews` annotated method.

**Comment by slidenerd** [comment]
Thanks for the insight but I am assuming you are saying its not possible to have your child return a layout, get the parent to find an element from that layout and inflate it, like lets say the parent has a ViewStub and the child has a linearlayout which it wishes to add to the ViewStub, this isnt possible currently? since many people use a base activity for handling stuff like drawers and cloud storage or maps, can you please go ahead and add a snippet of an abstract base class and concrete child class as part of your documentation itself? I mean It would save a lot of time for both library users and you if you did so.

**Comment by WonderCsabo** [comment]
You have to remove the `message` field in the sub Activity, like [this](https://github.com/WonderCsabo/Android_Annotations_Demo/tree/afteraa).

About `@AfterViews`: the most safest way is to create one `@AfterViews` annotated method, then override it in the subclasses and calling `super()`. This is described [here](https://github.com/excilys/androidannotations/wiki/%40AfterXXX-call-order).

**Comment by WonderCsabo** [comment]
Closing because this is not an AA issue.
