### ISSUE TITLE
@Background delay as parameter

### ISSUE THREAD

**Issue by LouisCAD** [excilys/androidannotations#1550]
Hi!

I'm using `@Background` annotation on my methods with a specific delay, but this delay is tied to the source code for now and I can't change the delay before which to run my method at run time. The app I'm working on can download a configuration from a server, specifying varying delays for some actions, but  it implies boilerplate for now...

Could you add support for a `int delay` optional parameter of the method itself, so we aren't forced to provide delay as a constant in `@Background` annotation?

I would be very grateful if you add this little change, expanding again AA possibilities.

Anyway, thanks very much for this awesome library.

Have a nice day!

Louis CAD

**Comment by WonderCsabo** [comment]
You mean the delay should be the parameter of the annotated method, like this?

```java
@Background
void bgMethod(String userParameter, int delay) {
 //...
}
```

**Comment by dodgex** [comment]
i think - *if we want to support that* - the param should not be only identified by its name. it should have some kind of sub annotation like `@Background.Delay`.

```java
@Background
void bgMethod(String userParameter, @Delay int delay) {
 //...
}
```

using only the name can cause unexpected behaviour as other apps may have such a parameter with another meaning.

**Comment by WonderCsabo** [comment]
Actually that is why i planned to move this conversation, but you beat me to it, @dodgex. :)

However even with an annotation which can distinct the delay parameter from other normal parameters, i think this is a bad design. First, it is very ugly and error-prone to mix other parameters and special parameters. The other thing is fundemental to AA: it is an annotation-based, compile-time framework. It means normally you can only add behavior which can be defined at compile time (with constants). If you want to overcome that, you are creating hacky solutions like this.
Sorry @LouisCAD for rejecting you again, but i cannot say i can approve this solution. :(

**Comment by dodgex** [comment]
@LouisCAD BUT there is a chance... you could create a small plugin that adds a new `@Background` annotation with the desired behaviour! :)

**Comment by LouisCAD** [comment]
@WonderCsabo I thought that delay name could clash with other parameters before posting. @dodgex Found the solution, but I have no knowledge in creating annotation processor... How could I build a plugin giving me this behavior?

@WonderCsabo While writing this message, I found a workaround solution to prevent using method params to get the delay:

```java
@EBean
public class MyBean {

    @Pref
    MyPrefs_ prefs;

    public static final MY_BG_TASK_ID = 0;

    @DelayProvider(MY_BG_TASK_ID)
    int getMyTaskDelay() {
        return prefs.delay().get();
    }

    // GET_FROM_PROVIDER would be an AA constant < 0
    @Background(id = MY_BG_TASK_ID, delay = GET_FROM_PROVIDER)
    void delayedbackgroundWork() {
        //...
    }
}
```
It's a little ugly, but I think it doesn't breaks your principles (I hope).

**Comment by WonderCsabo** [comment]
Yeah, this is the other solution, maybe it would be better to inject an `@EBean` as the delay provider like in some `@Rest` parameters.
But sorry, i still think it is a bad idea. 

About plugins: we created the plugin system, so you add new annotations much easier than creating a totally new annotation processor. If you check out the `develop` branch, you can see that some of AA's functionality has been moved to plugins. Of course, creating a new plugin still require some knowledge of codemodel and the javax modelling api.

**Comment by LouisCAD** [comment]
Why do you think it's a bad idea? Do you need examples showing you where it could be useful? Do you want to know why I want to use it in my app?

**Comment by WonderCsabo** [comment]
I am not sure. This seems to be too complicated for `@Background`, which only wants to be a simple background thread, nothing more. @yDelouis WDYT?

**Comment by yDelouis** [comment]
I agree, it's complicated and does not seem to be a common use case to me.

**Comment by WonderCsabo** [comment]
Sorry @LouisCAD but we reached a consensus to reject this one.
