### ISSUE TITLE
Copy JavaDoc to @SharedPref class and @DefaultXXX methods

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1551]
We do not override `@DefaultXXX` annotated methods, but generate a totally new class with new methods. This is why JavaDoc on the original methods cannot be inherited, and needed to be copied to the generated methods.

**Comment by WonderCsabo** [comment]
I assign this issue to @dodgex .

**Comment by dodgex** [comment]
how to handle the user provided `@return` ?

e.g.
```java
	/**
	 * The Age!
	 *
	 * @return the age as int
	 */
	@DefaultInt(42)
	int age();
```
generates:
```java
    /**
     * The Age!
     * 
     *  @return the age as int
     */
    public IntPrefField age() {
        return intField("age", 42);
    }
```
what is actually not correct.

also i'd like to add something like `* Defaults to: 42` but that should be above the `@return` and other tags

**Comment by dodgex** [comment]
i think we should just copy the javadoc and ignore the default value. or we have to add the default value to the top of the javadoc

**Comment by dodgex** [comment]
in my current implementation i add `<p><b>Defaults to</b>: 42</p>` before the given javadoc comment

**Comment by WonderCsabo** [comment]
I think:

```java
  /**
     * The Age!
     * 
     *  @return The PrefField object for chaining calls to work with the preference
     */
    public IntPrefField age() {
```

And for the editor methods:

@return The PrefEditorField object for chaining calls to edit the preference

Otherwise i think your proposal is OK, @dodgex .

**Comment by dodgex** [comment]
the problem is, that depending on compiler/ide configuration the javadoc on the interface has to be valid -> requires `@return`

we would need to remove/replace the `@return` if we want to add that message on the `age()`

**Comment by WonderCsabo** [comment]
You are right. Then stick with your proposal.

**Comment by WonderCsabo** [comment]
I think we should copy the javadoc to the editor methods as well.

**Comment by dodgex** [comment]
oh. i did not realize that there are more methods. :/ i'll add them.

**Comment by dodgex** [comment]
i updated the PR btw :)

**Comment by WonderCsabo** [comment]
Implemented.
