### ISSUE TITLE
A little misspelling in wiki

### ISSUE THREAD

**Issue by KimTaehee** [excilys/androidannotations#1554]
Hi, I'm interested in AA,  
I think the wiki page have a misspelled. 
https://github.com/excilys/androidannotations/wiki/IntelliJIDEA

![image](https://cloud.githubusercontent.com/assets/1901111/9940694/4d65686c-5dac-11e5-80db-26ba89ff99af.png)

How can i edit it? I fixed in my forked wiki already, here. (followed your guide)
https://github.com/KimTaehee/androidannotations/wiki/IntelliJIDEA

**Comment by WonderCsabo** [comment]
Thanks! That's all you have to do to edit our wiki. I merged your changes.
