### ISSUE TITLE
What do you think about adding a AndroidStudio example?

### ISSUE THREAD

**Issue by Francis0121** [excilys/androidannotations#1557]
I use android studio.

First I create project for AndroidStudio.
This project structure have two gradle build script.
So I confused

![image](https://cloud.githubusercontent.com/assets/3794501/9954448/26999e2e-5e24-11e5-8541-8a711fa71857.png)
![image](https://cloud.githubusercontent.com/assets/3794501/9954452/2a26d480-5e24-11e5-9f01-a10ecce954ee.png)

So I suggest you. Add AdroidStudio example in your project like this gradle build setting.

https://github.com/JuranoSaurus/AndroidAnnotationsSampleProject/blob/master/AA_Setting/build.gradle
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:1.3.1"
        classpath "com.neenbedankt.gradle.plugins:android-apt:1.7"
    }
}

allprojects {
    repositories {
        jcenter()
        mavenLocal()
    }
}
```

https://github.com/JuranoSaurus/AndroidAnnotationsSampleProject/blob/master/AA_Setting/app/build.gradle
```gradle
def AAVersion = "4.0-SNAPSHOT" // change this to your desired version, for example the latest stable: 3.3.2

apply plugin: "com.android.application"
apply plugin: "com.neenbedankt.android-apt"

apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
    }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
    }
}

dependencies {
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
}
```

https://github.com/JuranoSaurus/androidannotations/tree/1557_add_androidStudio_exmple/examples/AndroidStudio

What do you think about that?

------------------

Also. What do you think about add many AA API example such as RESTAPI, Threading?

**Comment by WonderCsabo** [comment]
Hey. Thanks for noting this. I am not sure we should create a Gradle submodule, one of the goals of that project is its simplicity. @yDelouis @dodgex WDYT?

We could add more examples of course, actually the `HelloWorldEclipse` project (which was our main example project) has much more annotation usages. We can easily migrate them to the Gradle example.

**Comment by yDelouis** [comment]
I'm sorry, I don't understand what @Francis0121 want us to do...
