### ISSUE TITLE
Inject menu on a listview

### ISSUE THREAD

**Issue by carmas123** [excilys/androidannotations#1564]
Hi all, I've an activity with a listview and I need to inject a menu on item selected.
Can I do this with annotation?

**Comment by WonderCsabo** [comment]
Can you be more specific on what you want to achieve? Maybe you could show it with example code.

**Comment by carmas123** [comment]
Oh yes, I've a simple activity with a listview and I want use 
 @OptionsMenu annotation to handle item selection and display to user a menu item with operation about listitem selected.

**Comment by WonderCsabo** [comment]
You can use the @ItemClick annotation to register for list item click events. You can use @OptionsMenuItem to inject the menu item to a field. Then in the item click handler method, you can manipulate the menu item through the injected field.

**Comment by carmas123** [comment]
Yes but I need to show a contextual ContextMenu...is same?

**Comment by WonderCsabo** [comment]
No, that is not supported. However you can still use @ItemClick and manipulate the menu with the standard way.

**Comment by WonderCsabo** [comment]
ContextMenu support is #1401.

**Comment by carmas123** [comment]
But for now @RegisterContextMenu annotation is not available....or not?

**Comment by dodgex** [comment]
@carmas123 nope. there is not annotation for `ContextMenu` and for now there will be no official.

**Comment by WonderCsabo** [comment]
I guess this can be closed, if you want `ContextMenu` support, please see the other issue.
