### ISSUE TITLE
PreferenceActivity sample

### ISSUE THREAD

**Issue by carmas123** [excilys/androidannotations#1565]
Hi, I'm trying to use PreferenceActivity with SharedPreferencesHelpers and I see in you sample this code: 

```
                // Using your MyPrefs values 
        this.getPreferenceManager().setSharedPreferencesName(PREF_NAME);

                // Opening the layout 
        addPreferencesFromResource(R.xml.prefs);
```

but this.getPreferenceManager() is deprecated and the result is always null.
In PREF_NAME I use the name of inteface with @SharedPref() annotation.
What is my error?

**Comment by WonderCsabo** [comment]
A modern `PreferenceActivity` uses `PreferenceFragment`s to do the actual job. You have to set the preferences name in the fragment. BTW, if you use `SharedPref.Scope.APPLICATION_DEFAULT` as the shared preference scope, you do not have to set the name.

I updated the doc.

**Comment by carmas123** [comment]
Yes, with APPLICATION_DEFAULT all work fine...thank you

**Comment by WonderCsabo** [comment]
Great!
