### ISSUE TITLE
About using @UiThread call itself

### ISSUE THREAD

**Issue by ANDROIDTODO** [excilys/androidannotations#1567]
Hi.

I'm using @UiThread annotation on Fragment like this,

  @UiThread(delay=1000)
    void refreshUi(){
        downloadingAdapter.notifyDataSetChanged();
        refreshUi();
    }

  but i don't know how to cancle the thread after leave this fragment.

 actually, using the handler could control.

**Comment by WonderCsabo** [comment]
Duplicate of #1218, which is already implemented in the `develop` branch.
