### ISSUE TITLE
@PageChange

### ISSUE THREAD

**Issue by ray1984** [excilys/androidannotations#1568]
Annotation for creation viewpager's OnPageChangeListener

**Comment by yDelouis** [comment]
Why not. Do you want to contribute ?

**Comment by ray1984** [comment]
I don't have contributing experience in AA-core

**Comment by domsu** [comment]
I would like to contribute, I will create pull request this weekend.

**Comment by WonderCsabo** [comment]
@domsu great! If you have any difficulties working with the codebase, just ping us in the [Gitter chat room}(https://gitter.im/excilys/androidannotations).

**Comment by WonderCsabo** [comment]
@domsu any update on this one?

**Comment by shiraji** [comment]
It seems no one is working on this issue. I will take case of this. Please let me know if you guys have any progress. 

Before I am going to implement this, I want to make sure I understand this issue correctly.

Here would be the generate code

```java
    @Override
    public void onViewChanged(HasViews hasViews) {
        {
            final ViewPager view = ((ViewPager) hasViews.findViewById(id.viewpager)); // whatever id that passed by value or resName. the same as TextChange
            if (view!= null) {
                view.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
                    @Override
                    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                        MainActivity_.this.pageScrolled(position, positionOffset, positionOffsetPixels); // method that annotated by @PageScrolled
                    }

                    @Override
                    public void onPageSelected(int position) {
                        MainActivity_.this.pageSelected(position); // method that annotated by @PageSelected
                    }

                    @Override
                    public void onPageScrollStateChanged(int state) {
                        MainActivity_.this.pageScrollStateChanged(state); // method that annotated by @PageScrollStateChanged
                    }
                }
                );
            }
        }
    }
```

* There is no `@PageChange` annotation
* This feature is really close with `TextChangeEvents`
* Parameter handling for `@PageSelected` seems the hardest part but algorithm is mostly the same with `@TextChange`

Is it ok that creating test cases that checks only compile code correctly? (No test case for `TextChangeEvents`...) Could anyone point me if there is test cases for this type of annotation?

**Comment by WonderCsabo** [comment]
Implemented.
