### ISSUE TITLE
@ViewById inside @EBean using android annotations #985

### ISSUE THREAD

**Issue by PriyankPandya** [excilys/androidannotations#1569]
This stuff is working fine when i used the anroidannotation 2.7, bt as i update my application with androidannotation 3.3.2 its giving me nullpointer for controls like textview..

so i want clarification what does you people change in your lib, which is not helping me to use 3.3.2

**Comment by dodgex** [comment]
please post the stacktrace and maybe a snipped of code where you use `@ViewById`

**Comment by PriyankPandya** [comment]
Can't get @ViewById to work inside an @EBean.

@EActivity(R.layout.data_layout)
public class MyActivity extends Activity {
@Bean
MyEbean bean;

@AfterViews
public void setupView() {
bean.loadData("Test name");
}
}

@EBean
public class MyEbean {
@RootContext
context;

@ViewById(R.id.name_field)
TextView nameField;

public void loadData(String name) {
name.setText(name); 
}
}

"name" in loadData() is null. At the same time if I do this inside loadData()

name = (TextView)((Activity) context).findViewById(R.id.name_field);

it's all good. So the view is definitely there. Also if I call this method from a retrofit callback (i.e. after a delay) "name" is auto populated. 
I'm using Android Annotations 3.3.2

**Comment by WonderCsabo** [comment]
Your code does not follows our documentation. We clearly say that the injected views are only available first in an `@AfterViews` annotated method. When you call `loadData()`, the view is not injected yet to the bean. it will be only after the Activity `@AfterViews` method is done. You can just pass the String to the bean, then create an `@AfterViews` annotated method in the bean, and set the text in that.
```java
@EBean
public class MyEbean {
    @RootContext
    Context context;

    @ViewById(R.id.name_field)
    TextView nameField;

    private String data;
    
    public void loadData(String name) {
        name.setText(name);
    }
    
    @AfterViews
    void afterViews() {
        nameField.setText(data);
    }
}
```

**Comment by dodgex** [comment]
His last comment is a copy of #985

**Comment by Smeet123** [comment]
Hi,

Yes its the copy of that #985 but the main issue is that, it was working in annotation version 2.7, but once we change the version to 3.3.2 then it stops working.

So is there any changes related to the life cycle of the annotations callback that stops working of this code? Because we just updated the library of annotation and did not do any other changes.

Please suggest us to resolve this issue... Your any help us really appreciated.

Thanks!

**Comment by WonderCsabo** [comment]
Actually i am not sure what changed. But i already proposed a solution, with example code.

Moreover, i would suggest to not use views in beans, because it is a bad architecture. Please note we plan to remove view support from beans in the next major version.

**Comment by Smeet123** [comment]
@WonderCsabo Thank you for the suggestion and quick reply but if you continue annotation support in bean then its really very helpful to the developers and it also reduces some of the coding efforts and it make the code very simple and easy to manage.

However, not sure what you are thinking and what are the advantages to remove the annotation support in Bean. But we are sure that whatever you change in major release, you will always do better and in favor of developers.

Thanks...

**Comment by WonderCsabo** [comment]
If you have concerns about removing view support from ebeans, please comment on #1477.

Was this issue resolved?

BTW, i am a little bit confused: @Smeet123 are you same as the reporter, or you are working together?

**Comment by Smeet123** [comment]
Yes you can mark it as resolved...

:) don't confused, we both are on the same project working together to
resolve this issue.

**Comment by PriyankPandya** [comment]
@WonderCsabo 
Yes we work together, issue can only be resolved by using @AfterViews  in @EBean  class.
Bdw thnx for your support.......
