### ISSUE TITLE
Difference in generated files for Eclipse and Android Studio

### ISSUE THREAD

**Issue by stasgaonkar** [excilys/androidannotations#1570]
Hi,

I have been using AndroidAnnotations 2.7 with Eclipse until now and want to move to Android Studio, but facing an issue. In summary, I have a MainActivity that extends BaseActivity which in turn extends Activity. Both MainActivity and BaseActivity have been annotated using @EActivity.

I also have a MainHandler, which is annotated as @EBean. I have injected this using @Bean in MainActivity. In the MainHandler, I need a reference to MainActivity and hence I have injected @RootContext as follows,

@EBean
public class MainHandler
{
    @RootContext
    protected BaseActivity activity;
}

However, reference activity in MainHandler's functions crashes the app since it is null. When I see the generated sources for the MainHandler_.java, I see a difference in the init_() method. In the Eclipse, I see the following,

    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }

        if (context_ instanceof BaseActivity) {
            activity = ((BaseActivity) context_);
        }
    }

However, the generated file in AndroidStudio is different.

    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

You can see that the activity has been initialised in the first but not in the second. Is there anything that I am overlooking or doing wrong on AndroidStudio.

I have just imported my project from Eclipse into AndroidStudio and build the project. There are no issues when compiling  or running the annotations process.

Thanks
Sushil

**Comment by WonderCsabo** [comment]
Closing in favor of the [Google groups discussion](https://groups.google.com/forum/#!topic/androidannotations/-4eYN5bFlFU).
