### ISSUE TITLE
@Click annotation for buttons is incorrect on InferringIDFromMethodName wiki page

### ISSUE THREAD

**Issue by Franzaine** [excilys/androidannotations#1571]
In the last section of the [wiki for InferringIDFromMethodName](https://github.com/excilys/androidannotations/wiki/InferringIDFromMethodName) the method call is incorrectly formatted. Android annotations does not allow the syntax written:
```
@Click
void loginButtonClick() {

}
```
for the suggested resource id ```R.id.login_button```

This should be changed to 
```
@Click
void loginButtonClicked() {

}
```

**Comment by WonderCsabo** [comment]
Thanks for reporting! You are absolutely correct, i fixed the method name.
