### ISSUE TITLE
FloatPrefField problem with getOr(Float defaultValue) 

### ISSUE THREAD

**Issue by carmas123** [excilys/androidannotations#1572]
This method is not really getOr(default)!!
If in the key preference exist and it's equal to "" (Empty) this method raise an exception and don't return the default value:
Float.parseFloat(value); throw an exception.
Can you solve this problem or introduce a new method like getOrEx(default) that doesn't raise any exception but return always the default value?

**Comment by WonderCsabo** [comment]
@carmas123 i am not sure we should do that. You should remove the preference value, not store an empty string instead of it.

**Comment by carmas123** [comment]
I need to get the default value regardless the stored value.
To do that we have two solution:
1. Change the getOr() method ->
```
			try {
				String value = sharedPreferences.getString(key, "" + defaultValue);
				return Float.parseFloat(value);
			} catch (Exception e2) {
				// our recovery bit failed. The problem is elsewhere. Send the
				// original error
				throw e;  < -- REMOVE THIS AND CHANGE WITH
								return defaultValue;
			}
```

2. Introduce a new method for backword compatibility:
```
	public Float getOrEx(Float defaultValue) {
			try {
				String value = sharedPreferences.getString(key, "" + defaultValue);
				return Float.parseFloat(value);
			} catch (Exception e2) {
				return defaultValue;
			}
}
```

**Comment by WonderCsabo** [comment]
Sorry, but i still do not understand why do you want to store anything under the preference which is not a float or a float value in string form.

I think the current behavior if semantically correct: if the stored value cannot be interpreted as a float, then we assume there is a preference with the same name which is not a float, and we throw `ClassCastException`. This is also what the `SharedPreferences.getFloat()` method does.

**Comment by carmas123** [comment]
It's true...mine was only a request, I do not say that now is wrong....

**Comment by WonderCsabo** [comment]
Sorry, but think this is not needed for most apps. Please catch the exception yourself, and return the default value (you can set the default value to a public static final constant, and use that in the annotation, too).
