### ISSUE TITLE
AA 4.0?

### ISSUE THREAD

**Issue by LouisCAD** [excilys/androidannotations#1573]
Hi!

Is Android Annotations 4.0 release  out, as the docs is saying [here](https://github.com/excilys/androidannotations/wiki/Rest%20API#responseerrorhandler), or it is just a mistake? Or maybe the doc of a future addition in upcoming 4.0 release?

All the best

**Comment by WonderCsabo** [comment]
Hey,

No 4.0 is not out yet, but you can try it out as a SNAPSHOT. We always add the latest information in the wiki, sorry if it is confusing.

**Comment by WonderCsabo** [comment]
BTW, please use other channels for these kind of questions, the mailing list or the chat is much better suited than the issue tracker.
