### ISSUE TITLE
The URL is broken on the Examples wiki page. 

### ISSUE THREAD

**Issue by Francis0121** [excilys/androidannotations#1575]
Hi, I'm interested in AA,
I found broken url in wiki page.

https://github.com/excilys/androidannotations/wiki/Examples
![image](https://cloud.githubusercontent.com/assets/3794501/10304035/9c55eec4-6c52-11e5-92fc-0718aeb8d8f1.png)

How can i edit it? I fixed in my forked wiki already, here. (followed your guide)
https://github.com/JuranoSaurus/androidannotations/wiki/Examples

**Comment by WonderCsabo** [comment]
Thanks very much! No further action required from you, i will merge your changes soon.

**Comment by WonderCsabo** [comment]
I merged your changes, thanks!
