### ISSUE TITLE
Provide original Intent in @EIntentService

### ISSUE THREAD

**Issue by m-radzikowski** [excilys/androidannotations#1576]
It would be nice if we would have access to original Intent in annotated IntentService. Why? For example to use `GoogleCloudMessaging.getInstance(this).getMessageType(intent)`. Unfortunatelly this method:

```
@ServiceAction(ACTION_C2DM_RECEIVE)
public void actionReceive(Intent intent) {
}
```
creates
```
        if (ACTION_RECEIVE.equals(action)) {
            Bundle extras = intent.getExtras();
            if (extras!= null) {
                Intent intentExtra = extras.getParcelable(INTENT_EXTRA); // INTENT_EXTRA = "intent"
                super.actionReceive(intentExtra);
                return ;
            }
        }
```
which is completly understandable, but doesn't help in this case.

Maybe some annotation to inject Intent?

**Comment by WonderCsabo** [comment]
I think the most suitable way would be creating an annotation, for example `@ServiceAction.Intent`. If one of the parameters is marked with this annotation, we will pass the original `Intent` to it and not as an extra.

But i am not sure we want to support this. This is not a general use-case for `@EIntentService`, and you can easily get the original `Intent` with minimal code:

```java
@EIntentService
public class MyService extends IntentService {

    public MyService() {
        super("MyService");
    }

    private Intent lastIntent;

    @Override
    protected void onHandleIntent(Intent intent) {
        lastIntent = intent;
    }

    @ServiceAction
    public void myAction(int extra) {
        // use lastIntent here
    }
}
```

@yDelouis @dodgex WDYT?

**Comment by WonderCsabo** [comment]
@m-radzikowski can you use this workaround?

**Comment by m-radzikowski** [comment]
Yes, thank you.

**Comment by WonderCsabo** [comment]
I am closing this, because it is not very common, and the workaround is trivial.
