### ISSUE TITLE
Support new types in bundles

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1577]
While checking #1559 i noticed that some classes are not supported by us which now can be added to a bundle. We should also allow those types.

**Comment by ened** [comment]
This means adjusting `org.androidannotations.helper.BundleHelper` and its associated tests, plus checking `org.androidannotations.helper.ValidatorHelper#canBePutInABundle`?

**Comment by WonderCsabo** [comment]
Exactly!

**Comment by shiraji** [comment]
What AA is missing:

* CharSequence[]
* java.util.ArrayList<java.lang.CharSequence>
* android.util.SparseArray<T extends android.os.Parcelable>

Are there any other types missing?

**Comment by WonderCsabo** [comment]
ArrayList is already handled, only the other two are missing i think.

**Comment by WonderCsabo** [comment]
CharSequence ArrayList is missing.

**Comment by shiraji** [comment]
I didn't notice but `<java.lang.CharSequence>` was dissappered. Here is the list.

* `CharSequence[]`
* `java.util.ArrayList<java.lang.CharSequence>`
* `android.util.SparseArray<T extends android.os.Parcelable>`

**Comment by WonderCsabo** [comment]
Yep!

**Comment by WonderCsabo** [comment]
Implemented.
