### ISSUE TITLE
Inject Fragment arguments in onAttach

### ISSUE THREAD

**Issue by xbao** [excilys/androidannotations#1579]
Currently, Fragment arguments are injected in `onCreate`. The first lifecycle callback for Fragments is `onAttach`. It would be nice if the arguments were available to the Fragment during this call. 

If a code sample would help, let me know and I'll make one.

**Comment by WonderCsabo** [comment]
You have a point, but I think this is not a general case. Fragment arguments are mostly used during in onCreate. I am no sure we should change this, that may break existing code silently. 

@yDelouis @dodgex?

**Comment by dodgex** [comment]
@WonderCsabo not sure why this could break existing code?

but also: @xbao why do you need/want the arguments be set in onAttach?

**Comment by WonderCsabo** [comment]
@dodgex it not should, but i would never do this kind of silent changes without a pretty good reason.

**Comment by xbao** [comment]
Yip, I have no issue with anything said above. The problem I see is that it's unnecessarily prescriptive and (at least to me) unintuitive. I assumed that anywhere I would normally be able to get the arguments without AA, they would be available. This includes `onAttach`

**Comment by WonderCsabo** [comment]
@yDelouis should we change this?

**Comment by yDelouis** [comment]
I don't think it is really needed and add complexity since `onAttach(Context context)` has been added in API 23 so we will have to handle different versions of the Android SDK.

Let's wait other people to ask for this feature.

**Comment by WonderCsabo** [comment]
Actually i did not know `onAttach(Context)`. But anyway, i agree.

We still accept comments on these, but i am closing for now.

**Comment by xbao** [comment]
Understandable, thanks for considering it
