### ISSUE TITLE
HowItWorks and OnActivityResult Document Improvement

### ISSUE THREAD

**Issue by Francis0121** [excilys/androidannotations#1580]
Hi~~
When I used `startForResult` method, I didn't know that exist `OnActivityResult Annotation`. So I implemented all override method.

I think that HowItWorks page will give this annotation info, many people will use this.

So I change documentation HowItWorks page like this link. 

[https://github.com/JuranoSaurus/androidannotations/wiki/HowItWorks#starting-an-annotated-activity](https://github.com/JuranoSaurus/androidannotations/wiki/HowItWorks#starting-an-annotated-activity)
**Before**
![image](https://cloud.githubusercontent.com/assets/3794501/10358493/dba7f9aa-6dc9-11e5-968d-d7ade3d22518.png)

**After**
![image](https://cloud.githubusercontent.com/assets/3794501/10358484/cbb3ef9a-6dc9-11e5-81e6-42dd67ccac57.png)

--------------------------------

Also `OnActivityResult` page gave example like this.
```java
@OnActivityResult(REQUEST_CODE)
void onResult(int resultCode, Intent data, @Extra String value) {
}
```
![extra noo applicable to parameter]
(https://cloud.githubusercontent.com/assets/3794501/10358420/131491f6-6dc9-11e5-9b0f-0c329841a05e.png)

But it didn't work. So I change this `@Extra` -> `@OnActivityResult.Extra`
```java
@OnActivityResult(REQUEST_CODE)
void onResult(int resultCode, Intent data, @OnActivityResult.Extra String value) {
}
```
[https://github.com/JuranoSaurus/androidannotations/wiki/OnActivityResult](https://github.com/JuranoSaurus/androidannotations/wiki/OnActivityResult)

**Comment by Francis0121** [comment]
And I found `@Extra`. And I update `OnActivityResult.Extra` in javadoc document.
Could i ask you may i create new pull request?

https://github.com/JuranoSaurus/androidannotations/tree/1580_onActivityResult_javadoc_update

**Comment by WonderCsabo** [comment]
In the wiki, I would use this:

Note that you can use the @OnActivityResult annotation...

**Comment by WonderCsabo** [comment]
Sure, submit the pull request, please. I would change the commit message
though, because you are not adding, but refining the JavaDoc.

**Comment by Francis0121** [comment]
Oh i'm sorry...
I know that .. but i copied and pasted your commit message.. i missed it

And I modified wiki page like this : 
`Note that you can use the @OnActivityResult annotation to get result code and extra value.`

**Comment by WonderCsabo** [comment]
I squashed two of your commits, so you may have to hard reset your wiki repo instead of merging:
```sh
git fetch upstream
git reset upstream/master --hard
```
But if you have changes do not do that, commit them and rebase your branch to `upstream/master`.

Thanks for these fixes to our doc, it really needs concern. Keep it up! :)
