### ISSUE TITLE
Copy paste error in Receiver.Extra javadoc

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1582]
The JavaDoc [talks about](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Receiver.java#L154) `@ReceiverAction` instead of `@Receiver` in two places.

**Comment by WonderCsabo** [comment]
@Francis0121 would you like to fix this? :)

**Comment by Francis0121** [comment]
I check it. Ok I do this.

**Comment by WonderCsabo** [comment]
Fixed.
