### ISSUE TITLE
IntelliJIDEA Document Improvement

### ISSUE THREAD

**Issue by Francis0121** [excilys/androidannotations#1584]
`File -> Settings -> Build, Execution, Deployment -> Compiler -> Annotation processor` path don't have annotation processor in **Android Studio**

![image](https://cloud.githubusercontent.com/assets/3794501/10365672/0f9f048e-6e00-11e5-8496-33d13d1e39cb.png)

Android Studio only have setting info at this path. `File -> Other Settings -> Default Settings... -> Build, Execution, Deployment -> Compiler -> Annotation processors`

![image](https://cloud.githubusercontent.com/assets/3794501/10365725/67f6edae-6e00-11e5-9f51-67cafa1b6480.png)

So I update wiki page like this.
https://github.com/JuranoSaurus/androidannotations/wiki/IntelliJIDEA

**Comment by WonderCsabo** [comment]
I am not sure we should do this. Your new description written by you is incorrect for IntelliJ, and this article is mostly aimed for IntelliJ users with no command line build tools. 99% of Android Studio users are using Gradle, where no manual annotation processor config is needed in the IDE.

**Comment by Francis0121** [comment]
Um.... Sorry..
When I used Android Studio 1.3.1 version. Annotation processor didn't work.
So I checked `Enable annotation processing`.

But I recently updated Android Studio 1.4 version.. it did well...

Bye.. close this issue

**Comment by WonderCsabo** [comment]
But you are using the Gradle build system , right?

**Comment by Francis0121** [comment]
Yes I use grade build system.
