### ISSUE TITLE
Revise logging severities

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1586]
We are logging lots of things with `WARNING`priority, which maybe not reasonable. For example we log the found manifest and content; claimed annotations and elements; and generated classes with `WARNING` log level. I think this should be definitely not `WARNING` (but `INFO`), since there is nothing to warn about, these are happening always normally.

**Comment by WonderCsabo** [comment]
Actually we used bad name for the log level in the functional test projects... 0a23034ccee Since there was no log level with such name, we fall back to the default, `DEBUG`. However, i do not think it is fair to pollute the clients terminal with debug messages by default. I opened #1588 for that. @yDelouis WDYT?

**Comment by yDelouis** [comment]
I agree and merged your PR.
Please, provide a new PR to fix the code where we used wrong log levels.

**Comment by WonderCsabo** [comment]
It turned out we log with appropriate severities, the problem was  0a23034.
