### ISSUE TITLE
AndroidAnnotations and Dagger2

### ISSUE THREAD

**Issue by Rainer-Lang** [excilys/androidannotations#1590]
Does anyone use this?
I have found the wiki-tutorial for Dagger1, but there is nothing for Dagger2.

**Comment by WonderCsabo** [comment]
I did not try Dagger2 yet, but i think you can apply the same pattern just i wrote in the Dagger1 doc.

**Comment by WonderCsabo** [comment]
I tried Dagger2, the [example project](https://github.com/google/dagger/tree/master/examples/android-simple). Fortunately, the integration is even easier than Dagger1, you can use AA annotated activities etc out of the box with Dagger2, no change is required from the Dagger side! I will write a wiki page later.

**Comment by Rainer-Lang** [comment]
Awesome - I'm looking forward.

**Comment by WonderCsabo** [comment]
BTW, i just saw this note on the Dagger2 example Android project:

> Note: The app is in transition to Dagger 2 and may not reflect recommended patterns. Before we release Dagger 2.0 it will, but until this note is removed, please do not rely on this example as a strong recommendation.

So if anybody has experience with the recommended usage of Android projects with Dagger2, all comments are really welcome.

**Comment by WonderCsabo** [comment]
Guide is [here](https://github.com/excilys/androidannotations/wiki/Dagger2Integration)
