### ISSUE TITLE
BackgroundExecutor.cancelAll can't kill the @Background Thread

### ISSUE THREAD

**Issue by chenzj-king** [excilys/androidannotations#1593]
As title.i find it can't kill the Thread when i execute BackgroundExecutor.cancelAll("test",false)
such like this.
![qq 20151014143218](https://cloud.githubusercontent.com/assets/11900696/10476429/65c3bd12-7280-11e5-9f0e-7a389b623056.jpg)

in my apps.@Background i will get some message by network.but when i finish this Act.It can't kill the task.can you guide me to handle with this problem.Thanks.

**Comment by WonderCsabo** [comment]
If you pass `true` in the second parameter, the executor will interrupt the thread if the task is still running. That means you will jump into the catch block. Did you check that? However, you will iterate towards. So you should also check `Thread.currentThread().isInterrupted()` in the loop condition to see whether to task was cancelled or not.

**Comment by chenzj-king** [comment]
when i catch the InterruptedException.and then i execute Thread.currentThread().interrupt(); it can finish this task.but such like i run a drop-dead halt.It can't jump into the catch block.how can i finish this task?

**Comment by WonderCsabo** [comment]
The interruption is just a flag, which you handle as you want. For example, you could put it into the loop condition as i already said:
```java
for (int i = 0; i < 10000 && !Thread.currentThread().isInterrupted();i++) {

}
// the loop either finished now or the task was cancelled
```
I did not tell you to call `Thread.currentThread().interrupt()`.

**Comment by dodgex** [comment]
please not that the `isInterrupted()` flag is often (if not always?!) resetted when the `InterruptedException` exception is thrown (see e.g: [Thread.sleep(long)](http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#sleep(long))) or [Object.wait()](http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#wait()) javadoc)

**Comment by WonderCsabo** [comment]
That is true! So in case of `sleep()` (which i hope is only a demo), you have to return from the catch block, or set an own variable and check that in the loop etc.

**Comment by chenzj-king** [comment]
@WonderCsabo It just a demo to test. I know that you tell me ```Interrupted()```to check the flag.```Thread.currentThread().interrupt()``` just a method to kill this Thread. but i use the rest to get some message by my server.when didn't callback result.but i finish the act/fra and ```BackgroundExecutor.cancelAll("test", true);``` in onStop.can i kill this task success?Can i get the Task by @ Background  id and check the thread status?I can't find method in BackgroundExecutor.

**Comment by WonderCsabo** [comment]
You have to call `Thread.currentThread().isInterrupted()` to check wether the `Thread` was interrupted or not. Forget `Thread.currentThread().interrupt()`.

**Comment by chenzj-king** [comment]
get it.Thanks.
