### ISSUE TITLE
No option:  Compiler > Annotation Processors   in Android Studio 1.4

### ISSUE THREAD

**Issue by xmlspy** [excilys/androidannotations#1595]
How to config AA in Android Studio 1.4 ?

**Comment by dodgex** [comment]
checkout the [gradle example project](https://github.com/excilys/androidannotations/blob/develop/examples/gradle/build.gradle) it contains everything that is necessary to get AA working in Android Studio.

**Comment by WonderCsabo** [comment]
> Please next time for usage questions post to other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations), [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
