### ISSUE TITLE
Add @IgnoreWhenViewDestroyed

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1597]
Now AndroidAnnotations clears injected view fields in `onDestroyView()` by setting each to `null`. However background tasks can be completed later. To avoid NPE-s, currently the client has to check wether the views are `null` or not. We could create a new annotation just like `@IgnoreWhenDetached` to remove that boilerplate. This was already [suggested](https://github.com/excilys/androidannotations/pull/1165#issuecomment-57061775) by @nbelikov.

**Comment by WonderCsabo** [comment]
@yDelouis @dodgex WDYT?

**Comment by WonderCsabo** [comment]
Or maybe we could generalize the `@IgnoreWhenXXX` annotations, like `@IgnoreWhen(DETACHED)` or `@IgnoreWhen(VIEW_DESTROYED)`. I am not sure.

**Comment by dodgex** [comment]
i'd prefer the `@IgnoreWhen(XXX)` approach.

**Comment by yDelouis** [comment]
What would be the generated code ?

**Comment by WonderCsabo** [comment]
I thought about the following:

```java
boolean viewDestroyed;

View onCreateView() {
  ...
  viewDestroyed = false;
}

void onDestroyView() {
  ...
  viewDestroyed = true;
}

void methodIgnoredWhenViewDestroyed() {
  if (!viewDestroyed) {
    super.methodIgnoredWhenViewDestroyed();
  }
}
```

**Comment by yDelouis** [comment]
Okay. Why not.

**Comment by WonderCsabo** [comment]
So can we rename the `@IgnoreWhenDetached` annotation to `@IgnoreWhen` and add an option to it?

**Comment by yDelouis** [comment]
Yes.

**Comment by shiraji** [comment]
I am taking care of this one. Here is TODO

* Create `@IgnoreWhen` that takes DETACHED or VIEW_DESTROYED (or DESTROY_VIEW?)
* Based on the parameter, viewDestroyed is set to true at `onDestroyView` or `onDetach`
* New annotation is accepted the method that has `@UiThread` annotation.

**Comment by WonderCsabo** [comment]
I vote for `VIEW_DESTROYED`.

`viewDestroyed` is only needed if `VIEW_DESTROYED` is used. For `DETACHED`, we can use the old method (`getActivity() == null`), there is no need to create a variable.

`@UiThread` is not mandatory for this.

**Comment by shiraji** [comment]
Could you check if I understand this issue correctly?

# Generated Code

## `@IgnoreWhen(DETACHED)`

```java
void methodIgnoredWhenViewDestroyed() {
  if (getActivity() != null) {
    super.methodIgnoredWhenViewDestroyed();
  }
}
```

## `@IgnoreWhen(VIEW_DESTROYED)`

```java
boolean viewDestroyed;

View onCreateView() {
  ...
  viewDestroyed = false;
}

void onDestroyView() {
  ...
  viewDestroyed = true;
}

void methodIgnoredWhenViewDestroyed() {
  if (!viewDestroyed) {
    super.methodIgnoredWhenViewDestroyed();
  }
}
```

# TODO

* Create `@IgnoreWhen` that takes DETACHED or VIEW_DESTROYED
* Based on the parameter, generated codes are above.
* New annotation is acceptable if there is at least one more annotation.

# Quetion

* No default value for this annotation?
* Is DETACHED required to put inside `Fragment` not `Activity`?
* Is VIEW_DESTROYED required to put inside `Fragment` or `Activity`?

**Comment by WonderCsabo** [comment]
In `onCreateView()`, you should set the variable to `false` ( i guess that is a copy paste error).
Also, this variable should be `volatile` (since the decorated method maybe does not run on the main thread).

> New annotation is acceptable if there is at least one more annotation

What do you mean?

There is no default value.
This annotation can be only used in `@EFragment`s.

**Comment by dodgex** [comment]
> > New annotation is acceptable if there is at least one more annotation

> What do you mean?

i think he means that the new `@IgnoreWhen` annotations requires at least one other annotation like `@UiThread`. but i'd say no. this annotation should also work. a method annotated with this could be called from any thread/method so it should be ensured that it always work

**Comment by shiraji** [comment]
Oh I got it. Thanks @dodgex 

I'm not sure about this

> In onCreateView(), you should set the variable to false ( i guess that is a copy paste error).

```java
private volatile boolean viewDestroyed;

View onCreateView() {
  ...
  viewDestroyed = false;
}

void onDestroyView() {
  ...
  viewDestroyed = true;
}

void methodIgnoredWhenViewDestroyed() {
  if (!viewDestroyed) {
    super.methodIgnoredWhenViewDestroyed();
  }
}
```

**Comment by WonderCsabo** [comment]
@shiraji this last snippet is correct.

**Comment by shiraji** [comment]
Cool! Thanks for reviewing requirement, guys.

**Comment by shiraji** [comment]
What about enum name?

`@IgnoreWhen(After.DETACHED)`
`@IgnoreWhen(Timing.DETACHED)`
`@IgnoreWhen(IgnoreWhen.DETACHED)`

I didn't come up with good one...

**Comment by dodgex** [comment]
what about `@IgnoreWhen(IgnoreWhen.State.DETACHED)` or short `@IgnoreWhen(State.DETACHED)`

**Comment by dodgex** [comment]
having
```java
@interface IgnoreWhen {

  //code

  enum State {
    // fields
  }
}

**Comment by shiraji** [comment]
I like short one!

**Comment by dodgex** [comment]
you can do both, but if you for example have another `State` class you might want to use the "long" version.

**Comment by shiraji** [comment]
You are right. I will put enum inside the annotation.

**Comment by WonderCsabo** [comment]
Indeed, we should do the same as with `EBean.Scope`.

**Comment by shiraji** [comment]
Yea. I will avoid conflict.

**Comment by WonderCsabo** [comment]
Implemented.
