### ISSUE TITLE
Add support for setSharedPreferencesName in @PreferenceScreen

### ISSUE THREAD

**Issue by clay-to-n** [excilys/androidannotations#1599]
Using the [@PreferenceScreen annotations](https://github.com/excilys/androidannotations/wiki/PreferenceHelpers) are useful, but it isn't obvious how to get them to work when you have multiple shared preferences files.

Before using AA, I was calling the following in onCreate:
```java
getPreferenceManager().setSharedPreferencesName("preferences_user");
addPreferencesFromResource(R.xml.preferences_user);
```
which is necessary when using multiple shared preferences files.

The @PreferenceScreen annotation injects the addPreferencesFromResource function into onCreate, but doesn't call setSharedPreferencesName.  To make sure they were called in the right order, I had to call setSharedPreferencesName in onCreate while using @PreferenceScreen (NOT in @AfterPreferences, which doesn't work, because the order is wrong).

I know most apps only use one set of shared preferences, but sometimes you need multiple.  Is this something that can be supported from the @PreferenceScreen annotation itself, maybe as a second parameter?

Usage would be as follows:
```java
/* Annotated code: */
@PreferenceScreen(R.xml.preferences_admin, R.string.preferences_admin_name)
@EFragment
public class AdminPrefsFragment extends PreferenceFragment {

}

/* Generated code: */
public final class AdminPrefsFragment_
    extends com.stasislabs.vitalsmonitor.fragments.AdminPrefsFragment
{

@Override
    public void onCreate(Bundle savedInstanceState) {
        // All the other AA stuff, plus:
        super.onCreate(savedInstanceState);
        getPreferenceManager().setSharedPreferencesName(getString(R.string.preferences_admin_name));
        addPreferencesFromResource(xml.preferences_admin);
    }
}
```

**Comment by WonderCsabo** [comment]
Sorry, but i do not think it is worth adding a new parameter to `@PreferenceScreen`. Also, the syntax you    are proposing is incorrect, it should be like this:
```java
@PreferenceScreen(value = R.xml.preferences_admin, sharedPreferencesName = R.string.preferences_admin_name)
```

I think your workaround adding this single line call in `onCreate` is reasonable.

**Comment by solokop** [comment]
The good solution should be provided for adding flexible [key, value] is passed to @PreferenceScreen as original support from Android SDK.

**Comment by WonderCsabo** [comment]
@solokop could you elaborate?

**Comment by WonderCsabo** [comment]
I am closing this one, because i do not think we should add a new annotation parameter to replace a single method call.
