### ISSUE TITLE
Collection objects need to be parameterized unless you use a custom serializer

### ISSUE THREAD

**Issue by xmlspy** [excilys/androidannotations#1600]
@Post("/mgz/category/read_lst")
 List<Category> getCategoryList();

AA generated a class List_Category.class.

Blow is exception: 
Collection objects need to be parameterized unless you use a custom serializer. Use the com.google.gson.reflect.TypeToken to extract the ParameterizedType.

**Comment by WonderCsabo** [comment]
I guess you shod use List<Category> as return type.
