### ISSUE TITLE
@OptionsMenu for custom, non actionbar Toolbar, and NavigationView

### ISSUE THREAD

**Issue by LouisCAD** [excilys/androidannotations#1601]
Hi!

I found myself wanting to use `@OptionsMenu` and other menu related annotations for a toolbar that would show at the bottom of the screen (similar to Google Keep), but I didn't found a way to make it work on my non actionbar [Toolbar](https://developer.android.com/reference/android/support/v7/widget/Toolbar.html).

Correct me if I'm wrong, but it doesn't work for other menu enabled views as well, such as [NavigationView](https://developer.android.com/reference/android/support/design/widget/NavigationView.html)

Do you think adding it to a future release would be possible?

BTW, thank you very much to you all, you save a lot of time to many Android Developers, like me :smiley: 

All the best!

**Comment by WonderCsabo** [comment]
I definitely think we will not support it in the core module. Thanks to the plugin system, these annotations can be added by anyone easily.

**Comment by LouisCAD** [comment]
Ok, but for now, I didn't find where to start to develop plugins for AA and I have no experience in using apt under the hood, or using standard Annotation Processing. :disappointed: 

After some recent research on apt gurus, such as Jake Warthon, I found his slides on SpeakerDeck, and the [related video](https://youtu.be/dOcs-NKK-RA). Should I watch this talk and try to figure out how I can use it to create an AA plugin, or is there any documentation or (apt) beginner understandable example?

**Comment by WonderCsabo** [comment]
You should definitely check those, also [this](http://hannesdorfmann.com/annotation-processing/annotationprocessing101/) article. However our plugin system leverage most of the tasks needed for writing a new annotation processor, so creating a new annotation is easier. But to do that, we need to add documentation on our framework. I will do that later. But you can get the picture buy checking out develop and poking around the already existing plugins.

**Comment by LouisCAD** [comment]
The scrollbar on the article you gave me is so small!! :open_mouth:
I think it will take me longer to watch, read and understand all this, than you to get the plugin documentation ready to release :grimacing:
Anyway, thank you for the information, I'll try to find the time to understand all this.

Just a last question: Will future AA plugins developed by third party guys like me, suited for specific use cases, such as this one, be on this repo, as for the rest-plugin, but in a separate maven artifact (I think it's  how we call what you get with a single dependency line in your build.gradle), or will we have to put it on our own repo?

I hope you get my question, sorry for my bad-french-complex english

**Comment by WonderCsabo** [comment]
No problem, i guess my Hungarian affected English has even worse patterns. :smile: 

Currently we do not have plans to add new core plugins, but it is possible of course if a serious need arises. But the main purpose is enabling third parties to write new plugins for AA.

**Comment by LouisCAD** [comment]
Okay! Thank you very much!
