### ISSUE TITLE
Add @Body and require annotations on all REST method parameters

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1602]
Now we have multiple REST annotations to be added on method parameters (`@Part`, `Field`, `@Path`) and more to come (`@QueryParam`, `@QueryMap`). But we do not have a dedicated annotation for the request body. Currently we are assuming that if the one method parameter not annotated with anything is the request body. This is complicated in the validation and generation code, and also confusing in the client-side annotated code.

We should have a dedicated `@Body` annotation and require annotations on all method parameter in REST methods.

**Comment by yDelouis** [comment]
I'm okay with that.

**Comment by shiraji** [comment]
Is this issue talking about this [code](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyService.java#L144-L148)?

This method generates

```java
    @Override
    public Event addEvent(Event event) {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setAccept(Collections.singletonList(MediaType.parseMediaType("application/json")));
        HttpEntity<Event> requestEntity = new HttpEntity<Event>(event, httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/events/"), HttpMethod.POST, requestEntity, Event.class).getBody();
    }
```

So now what you guys want is 

```java
	@Post("/events/")
	@Accept(MediaType.APPLICATION_JSON)
	Event addEvent(@Body SomeClass body);
```

```java
    @Override
    public Event addEvent(SomeClass body) {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setAccept(Collections.singletonList(MediaType.parseMediaType("application/json")));
        HttpEntity<SomeClass> requestEntity = new HttpEntity<SomeClass>(body, httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/events/"), HttpMethod.POST, requestEntity, Event.class).getBody();
    }
```

And after creating `@Body`, AA won't accept parameter without REST method annotations.

**Comment by WonderCsabo** [comment]
@shiraji exactly!
