### ISSUE TITLE
@ColorRes should use ContextCompat.getColor if available

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1604]
Currently we use `Resources.getColor()`, but it was deprecated in API 23. The `ContextCompat.getColor()` method should be used instead, but only if it is available.

**Comment by WonderCsabo** [comment]
The same applies to `@ColorStateListRes`.

Also, we should not just call `ContextCompat`, but apply the same logic as we did in `@DrawableRes`.

**Comment by ened** [comment]
I'll take care of this. There will be some duplicated code first, which we might want to refactor (or not).

**Comment by WonderCsabo** [comment]
Implemented.
