### ISSUE TITLE
@HierarchyViewerSupport in Services

### ISSUE THREAD

**Issue by LouisCAD** [excilys/androidannotations#1605]
Hi!
I'm currently using WindowManager in an app, and unfortunately, I don't have a HierarchyViewer supporting device. I would like to debug my Views I add from a Service in WindowManager.

Do you think it could be easily achievable on Services? If not, do you have an idea about which approach (by ApplicationContext, WindowsManager,EViewgroup annotations, etc?) would be the best?

**Comment by WonderCsabo** [comment]
We cannot achieve this via the annotation. However, you can still use the `ViewServer`, just pass your root view to `ViewServer.addWindow(view, name)`.

**Comment by LouisCAD** [comment]
Thank you very much, I thought that ViewServer only supported Activities. It's pretty straightforward in fact.
