### ISSUE TITLE
Gradle library projects are not recognized

### ISSUE THREAD

**Issue by hxchen** [excilys/androidannotations#1609]
1、After I use androidannotations finish developping my sdk, I build a jar package。
2、Then i write a project to test my sdk：i copy jar and res to my test project.
3、I found the Annotations is Invalid。Such as：
@EActivity(resName = "lib_librarysdk_activity_main")
@Click(resName = "tv_sdk_descp")

**Comment by WonderCsabo** [comment]
Sorry, i cannot really understand your problem. However it is already a problem that you copy things. You should use a build system (i recommend the official Gradle way), and proper dependency management.

**Comment by hxchen** [comment]
Sorry~
Actually, after i finish my work(project  named LibrarySDK),I use gradle build my code into a jar.
Then i want to test my jar(SDK,without errores ,i will give others to use it).
My test steps are:
1、copy jar to libs of Project LibraryDemo.
2、copy res directory  of LibrarySDK to res directory  of LibraryDemo.
Then i found the Annotations  in LibrarySDK  is invalid。

**Comment by WonderCsabo** [comment]
What do you mean by invalid? What is the error message you are getting?

**Comment by hxchen** [comment]
@Click(resName = "tv_sdk_descp")
    void sdkDescpClick(){
        Log.i("SDK UI", "sdkDescpClick");
    }
when i trigger a function above,i found it doesnt print a log when i build it into a jar。

Also code below：
@EActivity(resName = "lib_librarysdk_activity_main")
public class MainActivity extends Activity{
    ...
}
I cannot use lib_librarysdk_activity_main layout to render my Avtivity.

I think when i build a jar.the Annotion:resName cannot access the res

**Comment by WonderCsabo** [comment]
If the original jar was compiled, it means the resources can be accessed. I guess you are just not using the generated classes.

**Comment by dodgex** [comment]
you should not copy the jar + res but you should build the project as AAR library. those contain the code and resources

**Comment by hxchen** [comment]
Instead of direct access layout files by R.layout.lib_librarysdk_activity_main in my jar

I use code：
context.getResources().getIdentifier(“lib_librarysdk_activity_main”, "layout", context.getPackageName())
I can access layout/lib_librarysdk_activity_main.xml file.

But when i use resName Annotion i cannot access it.
So May it probably resName errors?
Maybe i should build the SDK project as AAR

**Comment by hxchen** [comment]
I think i got the reasons,when i write code like this:
@EActivity(resName = "lib_librarysdk_activity_main_login")
public class MainActivity extends Activity{
}
It complie into：
public final class MainActivity_
    extends MainActivity
    implements HasViews, OnViewChangedListener{
     @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.lib_librarysdk_activity_main_login);
    }
}
Actually when you use jar+res modal，You should use 
context.getResources().getIdentifier(“lib_librarysdk_activity_main_login”, "layout", context.getPackageName());

**Comment by WonderCsabo** [comment]
@hxchen you are right. We use an [outdated method](https://github.com/excilys/androidannotations/blob/4e2bccfca60d3875dd22d157f5ff88e84a2dfe8a/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java#L65) to decide whether a project is a library project or not.

@dodgex is there a way to extract the `library` property in Gradle builds?

**Comment by dodgex** [comment]
@WonderCsabo unfortunately i have no idea. I'm not into library projects with gradle yet.

**Comment by WonderCsabo** [comment]
@yDelouis any ideas?

**Comment by WonderCsabo** [comment]
BTW @hxchen the library thing should not effect you. We should be able to access `R.layout.lib_librarysdk_activity_main`, since it is generated with library project, too. You just did not include the `R` class in your jar i guess. You should really do this properly with AARs...
