### ISSUE TITLE
Update ViewServer

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1610]
[Our version](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/ViewServer.java) is really old, we should update to the latest and greatest from the [original repo](https://github.com/romainguy/ViewServer/blob/master/viewserver/src/main/java/com/android/debug/hv/ViewServer.java).

Thanks for @LouisCAD for bringing attention.

**Comment by yDelouis** [comment]
Updated.
