### ISSUE TITLE
Passing eviegroup as genric

### ISSUE THREAD

**Issue by mishkaowner** [excilys/androidannotations#1611]
@EViewgroup(r.layout.id)
class CustomView extends RelativeLayout{
}

class main<T>{
      T getCustomView(){
               return T_.build();
       }
}

This code is pseudo code. 
But my idea is that
main<CustomView.class> mMain =new main<>();
CustomView view = mMain.getCustomView();
Is this possible? 
Thank you.

**Comment by mishkaowner** [comment]
Hate writing code on mobile...

**Comment by simopete** [comment]
If I understand you would like to create a wrapper class to yours `ViewGroup`s.
Yes it is possible. Show an example on wiki: 
https://github.com/excilys/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder

**Comment by mishkaowner** [comment]
Ofcourse viewwrapper is a option but more likely i want to create eviewgroup directly without using static build method. As far as i have researched i found this https://github.com/excilys/androidannotations/issues/883
Its very similar to what im looking for.
But it seems too much work for just creating an instance....any simpler approach? Thank you

**Comment by mishkaowner** [comment]
Thank you for a comment simopete

**Comment by WonderCsabo** [comment]
@mishkaowner Unfortunately it is not possible to add a super builder class for views, because views can have different constructors and superclass cannot decide which one will exist i the subclass.
