### ISSUE TITLE
[@UiThread] warn that propagation=REUSE is not available when using delay

### ISSUE THREAD

**Issue by dodgex** [excilys/androidannotations#1612]
i just started a small project and played a bit with the `propagation` and `delay` parameters for `@UiThread` and found that when `delay != 0` the propagation (in term of `REUSE`) is ignored.

i think this should at least emit a warning on the annotated element that the propagation is ignored.

@WonderCsabo @yDelouis what do you think?

**Comment by yDelouis** [comment]
You're right, we should add a warning, even if it makes no sense to use `REUSE` with a delay.

**Comment by yDelouis** [comment]
Implemented.
