### ISSUE TITLE
how to run RoboGuiceExample? 

### ISSUE THREAD

**Issue by kamilwlf** [excilys/androidannotations#1614]
i have:

Error:Could not find org.androidannotations:roboguice:3.3.2.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.pom
    https://repo1.maven.org/maven2/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.jar
    file:/C:/Users/Kamil/.m2/repository/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.pom
    file:/C:/Users/Kamil/.m2/repository/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.jar
    file:/D:/sdk/extras/android/m2repository/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.pom
    file:/D:/sdk/extras/android/m2repository/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.jar
    file:/D:/sdk/extras/google/m2repository/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.pom
    file:/D:/sdk/extras/google/m2repository/org/androidannotations/roboguice/3.3.2/roboguice-3.3.2.jar
Required by:
    :RoboGuiceExample:unspecified

**Comment by dodgex** [comment]
currently the artifact `org.androidannotations:roboguice` is only available as `4.0-SNAPSHOT`

you could either use  `4.0-SNAPSHOT` or if you dont want to use a snapshot but the `3.3.2` release, just remove these two lines from the build.gradle and it should work
```
    apt "org.androidannotations:roboguice:$AAVersion"
    compile "org.androidannotations:roboguice-api:$AAVersion"
```

**Comment by kamilwlf** [comment]
I use RoboGuiceExample from repo.
I did not change anything 
i have:
Error:Could not find org.androidannotations:androidannotations:4.0-SNAPSHOT.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.0-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.pom
    https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.jar
    file:/C:/Users/Kamil/.m2/repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/maven-metadata.xml
    file:/C:/Users/Kamil/.m2/repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.pom
    file:/C:/Users/Kamil/.m2/repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.jar
    file:/D:/sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/maven-metadata.xml
    file:/D:/sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.pom
    file:/D:/sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.jar
    file:/D:/sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/maven-metadata.xml
    file:/D:/sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.pom
    file:/D:/sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.jar
Required by:
    :RoboGuiceExample:unspecified

**Comment by WonderCsabo** [comment]
You have to add the Sonatype snapshot repo to your repositories block.

**Comment by dodgex** [comment]
@WonderCsabo maybe we should add the snapshot repository to the sample build.gradle?

**Comment by dodgex** [comment]
@kamilwlf or you run `mvn clean install` inside the `AndroidAnnotations` folder to install a current copy of AA SNAPSHOT to your local maven repository

**Comment by WonderCsabo** [comment]
@dodgex snapshot repositories are not used to be in the example project. Moreover, we clearly communicate that the version should be substituted by the latest stable version. The current problem is we split the project, but did not release a stable version, yet. But that will go away hopefully soon.
