### ISSUE TITLE
AA starts, but doesn't seem to complete, and build fails.

### ISSUE THREAD

**Issue by markymc** [excilys/androidannotations#1616]
Hi everyone, I'm sorry if this is not appropriate for the issues board, but it looks like something is either not working properly in AA with my particular setup, my Gradle setup is plain wrong, or perhaps that an error isn't being logged by AA when it should?

I tried to migrate from an Eclipse project to Android Studio recently, but am having trouble getting AA to generate the necessary classes. It was working fine with Eclipse, and I have four other AS-created projects using AA that are building and working fine.

Processing seems to start, as `init(ProcessingEnvironment processingEnv)` of `AndroidAnnotationProcessor` looks like it's called, because I'm seeing the following in my "Messages" log window of AS:

```
<<< CROPPED OUTPUT
:android:processDebugJavaRes UP-TO-DATE
:android:compileDebugJavaWithJavac
Note: Resolve log file to /Users/marky/myapp/android/build/generated/source/apt/androidannotations.log
Note: Initialize AndroidAnnotations 3.3.2 with options {androidManifestFile=/Users/marky/myapp/android/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=com.me.myapp, logLevel=TRACE}
Warning:The following options were not recognized by any processor: '[androidManifestFile, logLevel, resourcePackageName]'
/Users/marky/myapp/android/src/com/me/myapp/MyActivity.java
Error:(25, 25) error: cannot find symbol class Preferences_
Error:(86, 2) error: cannot find symbol class Preferences_
Error:(25, 25) error: cannot find symbol class Preferences_
Error:(86, 2) error: cannot find symbol class Preferences_
CROPPED OUTPUT >>>
```

I'm not very experienced with annotations processing etc, but it looks like Gradle seems to think that AA finished what it needed to do and went on trying to build the app, but of course couldn't get the generated classes that were being referenced? However, shouldn't I see a line saying `Start processing for {} annotations...`?

Is it because of me specifying `java.srcDirs` etc in my build file? Is AA not finding anything to process?

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'

        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```
```
apply plugin: 'android'
apply plugin: 'android-apt'
def AAVersion = '3.3.2'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // Move the tests to tests/java, tests/res, etc...
//        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
//        debug.setRoot('build-types/debug')
//        release.setRoot('build-types/release')
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')

    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"

    compile 'joda-time:joda-time:2.8.2'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'

    compile 'org.springframework.android:spring-android-core:1.0.1.RELEASE'
    compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.1.3'

    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'

    compile 'com.android.support:support-v4:23.1.0'
}

apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        // if you have multiple outputs (when using splits), you may want to have other index than 0

        // you should set your package name here if you are using different application IDs
         resourcePackageName "com.me.myapp"

        // You can set optional annotation processing options here, like these commented options:
         logLevel 'TRACE'
        // logFile '/var/log/aa.log'
    }
}
```
However, I did trying removing the srcDirs entries, and rearranging my source files to be in the same structure as an AS-created project, but it didn't work.

Again, please accept my apologies if this isn't the place for this. If so, I'll happily delete this. But if anyone can provide some guidance I'd be hugely grateful!

**Comment by WonderCsabo** [comment]
Unfortunately these kind of problems are not strictly related to AA. It seem no annotations are passed us, so we cannot do anything. The problem may come from the `android-apt` plugin. However if you are able to share the project, i can take a look.

**Comment by markymc** [comment]
Hi @WonderCsabo thanks so much for your quick reply. I see what you mean about no annotations being passed. In that case, I guess I should ask on the android-apt issues board. 

Unfortunately I don't think I'll be able to share the project as it's a client's property, and I doubt they'd be OK with the code being shared. But I appreciate the offer.

**Comment by WonderCsabo** [comment]
@markymc maybe you can reduce the project down to a skeleton which still reproduces the issue?

**Comment by WonderCsabo** [comment]
@markymc is there any update on this one?

**Comment by WonderCsabo** [comment]
I am closing this issue due to lack of response. @markymc if you have updates please reopen.

**Comment by markymc** [comment]
@WonderCsabo I'm sorry for not responding sooner. Unfortunately I've had to divert my attention to some other issues. I'll try to get back to you on this when I have a chance. Thanks.

**Comment by markymc** [comment]
@WonderCsabo I'm ready to send you a cut down project. Where would be good to send it to? Email?

**Comment by WonderCsabo** [comment]
If it is not private, just upload to GitHub and share the repo here.
Otherwise you can send me an email (you can see it in my commits).

**Comment by markymc** [comment]
@WonderCsabo So... I started to cut the project down to the basics to send over to you, and then it started building properly! TBH I'm still not exactly sure why, but I'll try to find out when I have more time and will let you know.

**Comment by PauloCella** [comment]
Hello @markymc , i have a same problem. Can you explains about this solution?

**Comment by markymc** [comment]
@PauloCella I'm sorry I don't really know what the solution is, just that by cutting down my project it somehow started working.
