### ISSUE TITLE
4.0-SNAPSHOT doesn't have the package  'org.androidannotations.annotations.rest'

### ISSUE THREAD

**Issue by likieyes** [excilys/androidannotations#1617]
I try to use 4.0-SNAPSHOT with gradle , and i actually downloaded the jar , i wanted to use @POST @Field annotation, but i can't even find the   package  'org.androidannotations.annotations.rest' and 
'org.androidannotations.api.rest' , so i was really confused.  

and this is the snapshot of Android studio. Please help! Thanks
![2e284830-1ff7-488c-8325-9ca2801232da](https://cloud.githubusercontent.com/assets/1448612/10997785/ec1124c0-84ca-11e5-96e3-2f4e9edccd2d.png)

**Comment by WonderCsabo** [comment]
We split the library in 4.0. You have to declare `org.androidannotations:rest-spring-api:4.0-SNAPSHOT` and `org.androidannotations:rest-spring:4.0-SNAPSHOT` dependencies, too. Also the package name changed for rest annotations to  `org.androidannotations.rest.spring.annotations`.

**Comment by likieyes** [comment]
@WonderCsabo this really solves my problem. thank you so much!     And you should add these to the document so that anybody else who wants to try 4.0 can see this.    thank you for create such an amazing project.

**Comment by WonderCsabo** [comment]
I will add this when we release 4.0, but you are right.

**Comment by WonderCsabo** [comment]
Yeah, i already wanted to add this to somewhere, you are right.
