### ISSUE TITLE
@AfterInject work incorrect in 4.0-SNAPSHOT

### ISSUE THREAD

**Issue by OlegDokuka** [excilys/androidannotations#1618]
## PROBLEM

Create simple service object like next
``` java
  @EBean
  public class WebService {
    @RootContext
    protected Context context;

    @Bean
    protected Token token;

    @RestService
    AuthenticationRepository authenticationRepository;


    @AfterInject
    protected void init() {
         authenticationRepository.toString() //here null pointer exception
    }

 }
```
### Caused by incorrect apt generation 

Generated `init_()` method looks like this:

``` java
    private void init_() {
        token = Token_.getInstance_(context_);
        context = context_;
        init(); //why it here???? whyyyyyyy?
        authenticationRepository = new AuthenticationRepository_(context_);
    }
```

I think `@RestService` is injection too and should be before `init()` method

**Comment by WonderCsabo** [comment]
You are right, this is indeed a problem. It was already reported in #1466 and will be fixed by #1585.

**Comment by OlegDokuka** [comment]
Oh, sorry I haven't find this issue before! Thank you for fast answer, I believe in you and I`m waiting for new updates with pleasure

**Comment by WonderCsabo** [comment]
No worries.

**Comment by WonderCsabo** [comment]
@OlegDokuka it should be fixed now. Can you try the latest snapshot?
