### ISSUE TITLE
AA in library with custom views

### ISSUE THREAD

**Issue by WarrenFaith** [excilys/androidannotations#1620]
I have a general question about the best approach for the following situation:

I am currently doing a library which I want to use as a skeleton for my app development. The skeleton should already use some other libraries like AA and include stuff that needs to be done in nearly all projects.

Now I am struggling if I should run APT on the library to create the underscore classes within the library or if I should only do that in my real app project.

With code generation in the library:
Pro:
- I can use underscore classes like custom viewgroups within the library. So I can create layouts that uses these classes within my lib/res/layout folder
Con:
- I can't extend these views as the underscore classes are final
- underscore classes are in most cases just dead code

Without code generation in the library but in the app project:
Pro:
- I don't have dead code in form of generated underscore classes within the library
Con:
- I can't use custom views from the library within the library

I am not sure if I made myself clear, but how would you proceed in this setup? Any tips or additional pro/cons to consider?

**Comment by WonderCsabo** [comment]
This is not really an issue. Can you move this to the mailing list instead?

**Comment by WarrenFaith** [comment]
When you tell me where to find that list...
