### ISSUE TITLE
Extend the @DefaultRes annotation to support string arrays

### ISSUE THREAD

**Issue by athkalia** [excilys/androidannotations#1625]
As discussed in https://github.com/excilys/androidannotations/pull/1555#issuecomment-156751925, it would be handy if the @DefaultRes annotation also provided support for a Set of Strings, with a default value of arrays of Strings passed by it's R.array.id value.

**Comment by WonderCsabo** [comment]
Implemented.

**Comment by athkalia** [comment]
damn you are fast lol

**Comment by WonderCsabo** [comment]
Thanks to @dodgex.
