### ISSUE TITLE
@SystemService for WifiManager causes a memory leak

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1628]
Given I have an Activity with a `@SystemService` reference to WifiManager:

```
@SystemService
WifiManager wifiManager;
```

Then AA will generate this code:
```
wifiManager = ((WifiManager) this.getSystemService(Context.WIFI_SERVICE));
```

Which in turn might cause a memory leak (Eclipse MAT):
![screen shot 2015-11-17 at 18 50 25](https://cloud.githubusercontent.com/assets/269860/11209454/174679d0-8d5c-11e5-89c3-39f0edbfccf2.png)

Once I researched and found this page:
https://code.google.com/p/android/issues/detail?id=43945

And then proceeded to change the code in `onCreate` like this:
```
wifiManager = ((WifiManager) getApplicationContext().getSystemService(Context.WIFI_SERVICE));
```

The leak disappeared. Should've known this a few hours ago.

Therefore, I suggest that AA generates the `@SystemService` code for WifiManager as above. (perhaps good to add a comment into the generated code as well).

**Comment by WonderCsabo** [comment]
Good catch! Wanna contribute?

**Comment by ened** [comment]
OK.

**Comment by ened** [comment]
We might need to do the same thing with AudioManager.

http://stackoverflow.com/questions/20244288/audiomanagergetsystemservicecontext-audio-service-causing-memory-leak

https://android-review.googlesource.com/#/c/140481/1
