### ISSUE TITLE
ViewById scoping and camelToSnailCase transformation

### ISSUE THREAD

**Issue by slomo** [excilys/androidannotations#1630]
I have an android project using aa with defines two TextViews (in different Activities). One of them is using using the id `status_text` and the other one `statusText`. In both Activities I have the following annotated snippets:

```java
@ViewById
TextView statusText
```

This causes the activity with the `status_text` id  to crash, when the view is loaded. In my opinion I the following two issues arise:

- it is not document that AA also looks up snail cased names when the `@ViewById` notation is on a camel cased member
- upon doing this translation it seems to look up if a camel cased id exists, but while doing so doesn't value the view scope (which is with in a single xml ressource file) 

I guess best would to always look up `status_text` and `statusText` and notify the user about potential conflicts.

**PS**: Also don't argue that it is bad style to mix camel and snail case, but it happened and failed very late in the development process. 

**EDIT**: The two activities are also using different layouts.

**Comment by dodgex** [comment]
you can use
```java
@ViewById(R.id.status_test)
TextView statusText
```
or
```java
@ViewById(resName = "status_test")
TextView statusText
```

**Comment by slomo** [comment]
I fixed it by renaming the both to snail case (I guess camel case should do as well).

**Comment by WonderCsabo** [comment]
@slomo the ID resolution works this way

1. If the id is added as an annotation parameter use that
2. If the there is no annotation parameter
  1. If the field name can be found as an id as is, use that
  2. else if the field name converted to snake case name can be found, use that
3. else the id cannot be found

**Comment by slomo** [comment]
@WonderCsabo 

But than there seems to be an issue with the check performed in 2.i  because it doesn't value the scope of the view ids. Which I guess will be difficult since you don't have that scope anymore when accessing the `R` class. Hence my proposal to change id resolution to check always both appearances.

**Comment by WonderCsabo** [comment]
Sorry but i do not understand what do you mean by scope.

**Comment by slomo** [comment]
If you look at the android javadocs [`findViewById`](http://developer.android.com/reference/android/app/Activity.html#findViewById(int)) is described as follows

> Finds a view that was identified by the id attribute from the XML that was processed in onCreate(Bundle).

Meaning that it will search only lookup views within the layout given with either `setContentView` or the corresponding annotation. Hence findViewById operates with a specific layout as scope. One might use conflicting ids in other layouts without issues.

The error I observed can only be explained if the annotation processor is not valuing those scopes, while checking for the existence of the camel cased name.

**Comment by WonderCsabo** [comment]
The annotation processor runs during compile-time, so we cannot use `findViewById` to check the existence of the ID... We just check wether the ID can be found in the R class or not.

**Comment by slomo** [comment]
I know. And the lack of emulation of the `findViewById` behavior in the compile time processor to together with this automated case conversion behavior breaks my otherwise correct code.

I agree that this is an edge case, because it only happens if you mix camel and snake case.

**Comment by WonderCsabo** [comment]
OK, but we cannot really do anything about this. BTW i suggest not to rely on the field name and always use the annotation parameter. This way the value stays correct even if you refactor the ID name. Also this fixes your problem regarding to cameCase vs snake_case. Moreover, i suggest to not mix cameCalse and snake_case resource ids.
