### ISSUE TITLE
BackgroundExecutor cancelSerial

### ISSUE THREAD

**Issue by andrewlord1990** [excilys/androidannotations#1632]
At the moment you can specify an `id` and a `serial` for your background tasks. However, you can only cancel with `cancellAll(id)`. This means if you want a group of tasks with a serial, but want to be able to cancel them, you also need to add the `id` to them all as well.

Would be nice to cancel by serial.

**Comment by WonderCsabo** [comment]
While i understand it is a little bit inconvenient to add and id always, but i would rather not change this. ID and serial are totally different concepts, and i do not want to mix the two by adding the ability to cancel by serial.

**Comment by andrewlord1990** [comment]
Why is it mixing the two? One is cancel a particular task with that ID. The
other is to cancel a serial group. Otherwise to cancel the group easily you
have to give them the same ID.

I guess I don't see what the problem would be with having cancelling a
serial group?

**Comment by WonderCsabo** [comment]
Serial group serial is not intended to be a cancellation identifier. It is intended to mark tasks which should be executed serially. If we would allow to cancel by serial, we actually state the serial is not just a serial execution group id, but a cancellation identifier, too. This would also raise the problem that the serial execution group ids plus all the cancellation identifier must be unique. Not just the the cancellation ids and the serial ids, in separate sets.
Moreover, `BackgroundExecutor` was not designed to allow this, so implementing this is not just adding two lines.

**Comment by andrewlord1990** [comment]
Thanks for your explanation. I understand now.

**Comment by WonderCsabo** [comment]
No problem. I hope it is OK for you to add the cancellation ID as well in your annotations.
