### ISSUE TITLE
It seams that androidannotations have issue with floatingactionbutton in android api22 or later

### ISSUE THREAD

**Issue by romanitalian** [excilys/androidannotations#1634]
I don't know how to resolve this issue: 
1-st case:
if add in manifest genereted activity with posfix "_", for example "TActivity_", the button android.support.design.widget.FloatingActionButton doesn't respond.

2-nd case:
But if in manifest set "TActivity" - the button android.support.design.widget.FloatingActionButton works normaly.

I describe my question with screnshots in stackoverflow:
http://stackoverflow.com/questions/33857848/android-support-design-widget-floatingactionbutton-vs-org-androidannotationsand

**Comment by WonderCsabo** [comment]
I answered on the SO question.
