### ISSUE TITLE
Build issues with AA 3.3.2 and Instant Run / Gradle 2.0.0 alpha1

### ISSUE THREAD

**Issue by WarrenFaith** [excilys/androidannotations#1637]
I just wanted to try the new and already famous Instant Run feature and just updated Android Studio to 2.0 and gradle to 2.0.0.

With that my project can't be built anymore. I verified that is seems to be related to gradle version 2.0.0 because using gradle 1.3.0 in Android Studio 2.0 works as expected.

Here is my build log: http://pastebin.com/dy6YxhpB

**Comment by WonderCsabo** [comment]
I know one problem related to the application class. Please read the recent discussion [here](https://gitter.im/excilys/androidannotations).

**Comment by WarrenFaith** [comment]
Ok here is a short summarize of what you need to do to make it work:

1. make sure that you use the snapshot version or 4.0 (if it is released when you read this)
2. add in the `apt { arguments {...}}` part an option: `library 'true'`
3. also run a build with the --refresh-dependencies flag to make sure you have the latest snapshot

With that it should work again.

**Comment by githubdoramon** [comment]
@WarrenFaith shouldn't this "Library 'true'" intruction be here? https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle

**Comment by dodgex** [comment]
@githubdoramon why shuold it? the reason why the `library 'true'` was required in his case has been fixed by google in instant run feature. if you use the android build plugin 2.0-beta6 or higher AA powerd apps should run without this flag

**Comment by githubdoramon** [comment]
@dodgex you are right... I got confused here!!! Please everyone, forget what I said!!!!

**Comment by italobb** [comment]
@WarrenFaith How to configure `Android Studio` to run the build with the `--refresh-dependencies`?

**Comment by WarrenFaith** [comment]
I am not sure and can't remember anymore but adding this at the bottom of my build.gradle works for snapshot dependencies:

```groovy
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
```

**Comment by WonderCsabo** [comment]
@italobb you no longer should use the snapshot, as 4.0.0 stable was released. Moreover, the `@EApplication` problem was fixed in AS itself.
