### ISSUE TITLE
Issue with Android Studio 2.0, Gradle version 2.0

### ISSUE THREAD

**Issue by slidenerd** [excilys/androidannotations#1638]
I upgraded now to Android Studio 2.0 and my app won't compile saying the application class was not found.

Here is the full stack trace
Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugAndroidTestSources]
:app:clean
:app:incrementalDebugBuildInfoGenerator
:app:preBuild UP-TO-DATE
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAfollestadMaterialDialogsCore0830Library
:app:prepareComAndroidSupportAppcompatV72311Library
:app:prepareComAndroidSupportDesign2311Library
:app:prepareComAndroidSupportMediarouterV72220Library
:app:prepareComAndroidSupportMultidex101Library
:app:prepareComAndroidSupportRecyclerviewV72311Library
:app:prepareComAndroidSupportSupportV42311Library
:app:prepareComFacebookAndroidFacebookAndroidSdk481Library
:app:prepareComGoogleAndroidGmsPlayServices830Library
:app:prepareComGoogleAndroidGmsPlayServicesAds830Library
:app:prepareComGoogleAndroidGmsPlayServicesAnalytics830Library
:app:prepareComGoogleAndroidGmsPlayServicesAppindexing830Library
:app:prepareComGoogleAndroidGmsPlayServicesAppinvite830Library
:app:prepareComGoogleAndroidGmsPlayServicesAppstate830Library
:app:prepareComGoogleAndroidGmsPlayServicesAuth830Library
:app:prepareComGoogleAndroidGmsPlayServicesBase830Library
:app:prepareComGoogleAndroidGmsPlayServicesBasement830Library
:app:prepareComGoogleAndroidGmsPlayServicesCast830Library
:app:prepareComGoogleAndroidGmsPlayServicesDrive830Library
:app:prepareComGoogleAndroidGmsPlayServicesFitness830Library
:app:prepareComGoogleAndroidGmsPlayServicesGames830Library
:app:prepareComGoogleAndroidGmsPlayServicesGcm830Library
:app:prepareComGoogleAndroidGmsPlayServicesIdentity830Library
:app:prepareComGoogleAndroidGmsPlayServicesLocation830Library
:app:prepareComGoogleAndroidGmsPlayServicesMaps830Library
:app:prepareComGoogleAndroidGmsPlayServicesMeasurement830Library
:app:prepareComGoogleAndroidGmsPlayServicesNearby830Library
:app:prepareComGoogleAndroidGmsPlayServicesPanorama830Library
:app:prepareComGoogleAndroidGmsPlayServicesPlus830Library
:app:prepareComGoogleAndroidGmsPlayServicesSafetynet830Library
:app:prepareComGoogleAndroidGmsPlayServicesVision830Library
:app:prepareComGoogleAndroidGmsPlayServicesWallet830Library
:app:prepareComGoogleAndroidGmsPlayServicesWearable830Library
:app:prepareJpWasabeefRecyclerviewAnimators200Library
:app:prepareMeZhanghaiAndroidMaterialprogressbarLibrary114Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:processDebugManifest
:app:injectDebugBootstrap
Instrumented slidenerd.vivz.fpam.Fpam_ with fast deploy
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugResources
:app:generateDebugSources
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportMultidexInstrumentation101Library
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestAssets UP-TO-DATE
:app:mergeDebugAndroidTestAssets
:app:generateDebugAndroidTestResValues UP-TO-DATE
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources
:app:compileDebugJavaWithJavac
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/background/TaskFragmentDeletePosts.java
Error:(35, 34) error: cannot find symbol class MyPrefs_
Error:(63, 5) error: cannot find symbol class MyPrefs_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/background/TaskFragmentLoadPosts.java
Error:(28, 34) error: cannot find symbol class MyPrefs_
Error:(49, 5) error: cannot find symbol class MyPrefs_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/ui/ActivityBase.java
Error:(36, 38) error: cannot find symbol class TaskFragmentLoadPosts_
Error:(37, 34) error: cannot find symbol class MyPrefs_
Error:(44, 36) error: cannot find symbol class SettingsActivity_
Error:(60, 13) error: cannot find symbol class TaskFragmentLoadPosts_
Error:(61, 13) error: cannot find symbol class FragmentDrawer_
Error:(67, 12) error: cannot find symbol class MyPrefs_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/settings/SettingsFragmentGeneral.java
Error:(22, 34) error: cannot find symbol class MyPrefs_
Error:(30, 5) error: cannot find symbol class MyPrefs_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/settings/SettingsFragmentGroups.java
Error:(29, 34) error: cannot find symbol class MyPrefs_
Error:(42, 5) error: cannot find symbol class MyPrefs_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/ui/ActivityLogin.java
Error:(32, 38) error: cannot find symbol class TaskLoadAdminAndGroups_
Error:(51, 13) error: cannot find symbol class TaskLoadAdminAndGroups_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/ui/ActivityMain.java
Error:(20, 38) error: cannot find symbol class TaskFragmentDeletePosts_
Error:(32, 13) error: cannot find symbol class TaskFragmentDeletePosts_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/ui/FragmentDrawer.java
Error:(29, 34) error: cannot find symbol class MyPrefs_
Error:(46, 5) error: cannot find symbol class MyPrefs_
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/ui/FragmentPosts.java
Error:(44, 34) error: cannot find symbol class MyPrefs_
Error:(71, 5) error: cannot find symbol class MyPrefs_
Note: Resolve log file to /Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/build/generated/source/apt/androidannotations.log
Note: Initialize AndroidAnnotations 3.3.2 with options {androidManifestFile=/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=slidenerd.vivz.fpam}
Note: Start processing for 19 annotations on 93 elements
Note: AndroidManifest.xml file found with specified path: /Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/build/intermediates/manifests/full/debug/AndroidManifest.xml
Warning:The class application declared in the AndroidManifest.xml cannot be found in the compile path: [com.android.tools.fd.runtime.BootstrapApplication]
Note: AndroidManifest.xml found: AndroidManifest [applicationPackage=slidenerd.vivz.fpam, componentQualifiedNames=[com.facebook.FacebookActivity, slidenerd.vivz.fpam.ui.ActivityLogin_, slidenerd.vivz.fpam.settings.SettingsActivity_, slidenerd.vivz.fpam.ui.ActivityMain_, slidenerd.vivz.fpam.settings.ActivityKeywords_, com.google.android.gms.ads.AdActivity, com.google.android.gms.ads.purchase.InAppPurchaseActivity, com.google.android.gms.auth.api.signin.internal.SignInHubActivity, slidenerd.vivz.fpam.background.FpamService, com.google.android.gms.measurement.AppMeasurementService, com.google.android.gms.measurement.AppMeasurementReceiver, com.google.android.gms.measurement.AppMeasurementContentProvider], permissionQualifiedNames=[android.permission.RECEIVE_BOOT_COMPLETED, android.permission.INTERNET, android.permission.WAKE_LOCK, android.permission.ACCESS_NETWORK_STATE, android.permission.WRITE_EXTERNAL_STORAGE, com.google.android.c2dm.permission.RECEIVE, android.permission.GET_ACCOUNTS, android.permission.USE_CREDENTIALS], applicationClassName=null, libraryProject=false, debugabble=false, minSdkVersion=15, maxSdkVersion=-1, targetSdkVersion=23]
Note: Found project R class: slidenerd.vivz.fpam.R
Note: Found Android class: android.R
Note: Validating elements
Note: Validating with EApplicationHandler: [slidenerd.vivz.fpam.Fpam]
/Users/vivz/Desktop/Examples/AndroidExamples/FacebookSpam/app/src/main/java/slidenerd/vivz/fpam/Fpam.java
Error:(29, 1) error: No application class registered in the AndroidManifest.xml
Warning:(30, 8) Element EApplicationHandler unvalidated by
Note: Validating with EActivityHandler: [slidenerd.vivz.fpam.settings.ActivityKeywords, slidenerd.vivz.fpam.settings.SettingsActivity, slidenerd.vivz.fpam.ui.ActivityBase, slidenerd.vivz.fpam.ui.ActivityLogin, slidenerd.vivz.fpam.ui.ActivityMain]
Note: Validating with EFragmentHandler: [slidenerd.vivz.fpam.background.TaskFragmentDeletePosts, slidenerd.vivz.fpam.background.TaskFragmentLoadPosts, slidenerd.vivz.fpam.background.TaskLoadAdminAndGroups, slidenerd.vivz.fpam.settings.SettingsFragmentGeneral, slidenerd.vivz.fpam.settings.SettingsFragmentGroups, slidenerd.vivz.fpam.ui.FragmentDrawer, slidenerd.vivz.fpam.ui.FragmentPosts, slidenerd.vivz.fpam.ui.FragmentStats]
Note: Validating with SharedPrefHandler: [slidenerd.vivz.fpam.extras.MyPrefs]
Note: Validating with PrefHandler: [mPref, mPref, mPref, mPref, mPref, mPref, mPref]
Note: Validating with ViewByIdHandler: [mToolbar, mInputKeyword, mRecycler, mCbxDelete, mTextSummaryCache, mTextEmpty, mRecyclerGroups, mProgress, mTextError, mDrawer]
Note: Validating with ClickHandler: [onClickAdd(), onClickCacheSize(), onClickDeleteMultiple(), onClickKeywords(), login(), onClickSettings(), onClickLogout()]
Note: Validating with CheckedChangeHandler: [onCheckDeleteMultiple(android.widget.CompoundButton,boolean)]
Note: Validating with EditorActionHandler: [onActionDone()]
Note: Validating with ResHandler: [mCacheSizes, mScanFrequencyTitles]
Note: Validating with ResHandler: [mScanFrequencyValues]
Note: Validating with AppHandler: [mApplication, mApplication, mApp, mApp, mApplication]
Note: Validating with OptionsMenuHandler: [slidenerd.vivz.fpam.ui.ActivityLogin, slidenerd.vivz.fpam.ui.ActivityMain]
Note: Validating with OptionsItemHandler: [onHomeSelected(), onSettingsSelected(), onExportDatabaseSelected(), onCacheSelected()]
Note: Validating with InstanceStateHandler: [mGroupId]
Note: Validating with ReceiverHandler: [onDeleteRequest(android.content.Context,android.content.Intent), onBroadcastSelectedGroup(android.content.Context,android.content.Intent), onDeleteResponse(android.content.Context,android.content.Intent)]
Note: Validating with AfterViewsHandler: [onCreateView(), onViewCreated(), onViewCreated(), onViewCreated()]
Note: Validating with UiThreadHandler: [onDelete(boolean,int), onPostsLoaded(), onAdminAndGroupsLoaded()]
Note: Validating with BackgroundHandler: [deletePostsAsync(com.facebook.AccessToken,int,java.lang.String), loadPostsAsync(java.lang.String,com.facebook.AccessToken), loadAdminAndGroupsInBackground(com.facebook.AccessToken)]
Note: Processing root elements
Note: Processing root elements EActivityHandler: [slidenerd.vivz.fpam.settings.SettingsActivity, slidenerd.vivz.fpam.ui.ActivityBase, slidenerd.vivz.fpam.settings.ActivityKeywords, slidenerd.vivz.fpam.ui.ActivityLogin, slidenerd.vivz.fpam.ui.ActivityMain]
Note: Processing root elements EFragmentHandler: [slidenerd.vivz.fpam.background.TaskLoadAdminAndGroups, slidenerd.vivz.fpam.ui.FragmentPosts, slidenerd.vivz.fpam.settings.SettingsFragmentGroups, slidenerd.vivz.fpam.background.TaskFragmentDeletePosts, slidenerd.vivz.fpam.ui.FragmentStats, slidenerd.vivz.fpam.settings.SettingsFragmentGeneral, slidenerd.vivz.fpam.ui.FragmentDrawer, slidenerd.vivz.fpam.background.TaskFragmentLoadPosts]
Note: Processing root elements SharedPrefHandler: [slidenerd.vivz.fpam.extras.MyPrefs]
Note: Processing enclosed elements
Note: Processing enclosed elements with PrefHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@7007d6c7, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@770a21a3]
Note: Processing enclosed elements with AppHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@efa2292, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@20d1832c]
Note: Processing enclosed elements with OptionsItemHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@5fad3f1b, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@73490f21, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@7c554f2c, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@500aaa61, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@fbbf7b6, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@755b2304]
Note: Number of files generated by AndroidAnnotations: 13
Note: Writting following API classes in project: []
Note: Generating class: slidenerd.vivz.fpam.background.TaskFragmentDeletePosts_
Note: Generating class: slidenerd.vivz.fpam.background.TaskFragmentLoadPosts_
Note: Generating class: slidenerd.vivz.fpam.background.TaskLoadAdminAndGroups_
Note: Generating class: slidenerd.vivz.fpam.ui.ActivityLogin_
Note: Generating class: slidenerd.vivz.fpam.ui.ActivityMain_
Note: Generating class: slidenerd.vivz.fpam.ui.FragmentDrawer_
Note: Generating class: slidenerd.vivz.fpam.ui.FragmentPosts_
Note: Generating class: slidenerd.vivz.fpam.ui.FragmentStats_
Note: Generating class: slidenerd.vivz.fpam.settings.ActivityKeywords_
Note: Generating class: slidenerd.vivz.fpam.settings.SettingsActivity_
Note: Generating class: slidenerd.vivz.fpam.settings.SettingsFragmentGeneral_
Note: Generating class: slidenerd.vivz.fpam.settings.SettingsFragmentGroups_
Note: Generating class: slidenerd.vivz.fpam.extras.MyPrefs_
Note: Time measurements: [Whole Processing = 262 ms], [Generate Sources = 103 ms], [Process Annotations = 70 ms], [Extract Annotations = 36 ms], [Validate Annotations = 25 ms], [Find R Classes = 14 ms], [Extract Manifest = 7 ms], 
Note: Finish processing
Note: Processing class Admin
Note: Processing class Comment
Note: Processing class Comments
Note: Processing class Group
Note: Processing class Post
Note: Processing class Dailytics
Note: Processing class Keyword
Note: Processing class Spammer
Note: Processing class TopKeyword
Note: Processing class TopSpammer
Note: Creating DefaultRealmModule
Note: Start processing for 0 annotations on 0 elements
Note: Time measurements: [Whole Processing = 1 ms], 
Note: Finish processing
2 warnings
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 8.951 secs
Information:24 errors
Information:2 warnings
Information:See complete output in console

Here is my app s build.gradle file
apply plugin: 'com.android.application'
apply plugin: 'android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "slidenerd.vivz.fpam"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        // Enabling multidex support.
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }
}
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName "slidenerd.vivz.fpam"
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'jp.wasabeef:recyclerview-animators:2.0.0'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:8.3.0'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.facebook.android:facebook-android-sdk:4.8.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'io.realm:realm-android:0.85.0'
    compile 'org.apache.commons:commons-lang3:3.4'
    apt "org.androidannotations:androidannotations:3.3.2"
    compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'org.androidannotations:androidannotations-api:3.3.2'
    compile 'com.android.support:multidex:1.0.1'
    compile('com.afollestad.material-dialogs:core:0.8.3.0@aar') {
        transitive = true
    }
}
repositories {
    maven { url "https://jitpack.io" }
}

And this would be my project's build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-alpha1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        jcenter()
    }
}

Thanks in advance for your suggestions

Update 1

Same thing works perfectly with Gradle version 1.3

**Comment by WonderCsabo** [comment]
Please read https://github.com/excilys/androidannotations/issues/1637.

**Comment by slidenerd** [comment]
Thank you for the info, will reopen the issue if something goes wrong.

**Comment by couchcrew-thomas** [comment]
What did you do to fix the problem? Since upgrading to Android Studio 2.1 and build tools 2.1.0-beta1 the classes are not generated anymore.

The attached issue did not fix it for me. Regardless on how I set the library parameter.

**Comment by WonderCsabo** [comment]
@couchcrew-thomas the library parameter is not needed anymore. Google fixed the plugin. Please see details on https://github.com/excilys/androidannotations/pull/1716/commits/7b7a55ebacb58e26988a2f8f8adf0eb6e0b56d2f . It does work in the stable 2.0.0 plugin, i do not know about newer versions, although i think it should work on those as well.

**Comment by couchcrew-thomas** [comment]
I've removed the library parameter but it does not work.
The last Android Studio version I can compile in is 2.1 Preview 4 with the respective build tools 2.1.0-alpha4.
Every newer version fails when building the generated classes.

**Comment by WonderCsabo** [comment]
Did you try the stable AS and the stable plugin?

**Comment by couchcrew-thomas** [comment]
Not yet since it also did not work with the Preview 5 version that was released prior to the stable.
I'll try it later on and report back.

**Comment by couchcrew-thomas** [comment]
It is working in Android Studio 2.0 Stable. (As expected since it works with 2.1 Preview 4)
But it does also not compile with the latest beta (2.1 Beta 3).
The same errors occur as in the OP. It cannot find any generated classes.

**Comment by WonderCsabo** [comment]
Can you check the full manifest file which is is used by AA, under the build folder? Maybe they are changing the application class in it again.

**Comment by couchcrew-thomas** [comment]
It doesn't seem to get this far. There are no generated manifests inside the intermediate or generated folders.

**Comment by WonderCsabo** [comment]
That is weird...

**Comment by couchcrew-thomas** [comment]
Aside from AA only Android's Databinding is generating classes?
Could it be possible that the both clash since Preview 5?

Did you already test the compatibility?

I cannot test this in my project since there will be classes missing when disabling databinding.
I could create a new test project though to test the compatibility of the two but that will take some time.

**Comment by WonderCsabo** [comment]
Sorry, but i do not have time testing unstable AS versions with AA, i have very limited time, actually it is even not enough for "normal" support.

**Comment by couchcrew-thomas** [comment]
I can understand this. I'll still look into it and create a test project.
Because if it is indeed a conflict between AA and Databinding it might cause trouble when the current betas become stable.

**Comment by dodgex** [comment]
I just got back on my android app and also updated to 2.1 RC (from 21st April '16). For me AA 4.0.0 generates code as expected (using `2.1.0-rc1` gradle plugin)

**Comment by dodgex** [comment]
even instant run does work in an acceptable speed! :smile:

**Comment by dodgex** [comment]
as there is a final release of Android Studio 2.1.0 -> this works for me too.

**Comment by couchcrew-thomas** [comment]
Even with Android Studio 2.1 Stable it does not work for me. As stated above every version above 2.1 Preview 4 fails.
Neither AA nor databinding generates any classes.
@dodgex are you using only AA to generate classes?

**Comment by dodgex** [comment]
@couchcrew-thomas yes. only AA with ormlight plugin.

**Comment by dodgex** [comment]
have you tried to let one processor run alone? e.g. only AA?

also you might want to build a small test project with both processors and as less code as possible. to check if you can get it to work there. often obvious issues are no issues at all - only for the specific project configuration. a working test project might help to fix actual project. :)

and if the minimal test project fails too, one can check if it is an AA issue or not. :)

**Comment by couchcrew-thomas** [comment]
I did that and everything works. Both AA and databinding :(
I was hoping that it fails since I have no idea how to fix this with my actual app. Its a huge project. Do you have any idea how to approach this?

**Comment by couchcrew-thomas** [comment]
I've found the culprit. Caused by an abstract EApplication class inside a library. I've opened a new issue #1761

**Comment by appsbeedip** [comment]
Go to your "Build" option in your android studio and then go for "clean project" and then you can build your gradle. In this way you can solve your issue, may be it will be work.
