### ISSUE TITLE
@EApplication is not available in gradle:2.0.0-alpha1, upgrade to androidannotations3.3.1 is not useful either.

### ISSUE THREAD

**Issue by cby0310** [excilys/androidannotations#1639]
Android Studio 2.0 Preview was released recently, I want to experience the Instant the Run function,and I used gradle: 1.3.0, it let me upgrade to gradle: 2.0.0-alpha1, after upgrading “@EApplication” is report the "Element UiThreadHandler unvalidated by" mistake, and "@UiThread" report mistakes also. I recover to gradle: 1.3.0, there is no mistake. My English is poor, can you understand? Looking forward to your reply, thank you!

Error message：
Error:(57, 8) 警告: Element EApplicationHandler unvalidated by
Error:(145, 14) 警告: Element UiThreadHandler unvalidated by
Error:(150, 14) 警告: Element UiThreadHandler unvalidated by

**Comment by linwoain** [comment]
also mistake when use Fragment_$FragmentBuilder_ in as2.0 pre with aa3.3.2

**Comment by zxy198717** [comment]
+1

**Comment by WonderCsabo** [comment]
There is a workaround for the EApplication problem.  https://github.com/excilys/androidannotations/issues/1637

**Comment by sunhao91** [comment]
java.lang.VerifyError:xxx

**Comment by sunhao91** [comment]
java.lang.VerifyError: cc/sunhao/virgo/ui/fragments/MeiTuFragment_$FragmentBuilder_

gradle:2.0.0-alpha1

**Comment by WonderCsabo** [comment]
Sorry guys, but do not expect AndroidAnnotations developers to investigate this problem. Instant Run is an alpha software, which obviously has bugs and is subject to change. Moreover, it does not support the data binding library which itself is an annotation processor (sort of).

I am leaving this ticket open though, so you can share workarounds if found.

**Comment by cby0310** [comment]
thanks

**Comment by carmas123** [comment]
+1

**Comment by WonderCsabo** [comment]
In the AA chat someone mentioned it does not work on Android 4, but does work on Andorid 6. What Android version do you use?

**Comment by erishforG** [comment]
thanks

**Comment by Nexen23** [comment]
Well, spend about 2 days to realise it is IDE problem, not me broke something :+1:

**Comment by cshalysongoncalves** [comment]
Hello @WonderCsabo,

I'm running on the Nexus 4 emulator with Kit Kat. After returning to gradle plugin version (classpath 'com.android.tools.build:gradle:2.0.0-alpha2') to (classpath 'com.android.tools.build:gradle:1.3.0') functioned normally

**Comment by kosiara** [comment]
@WonderCsabo 
Thanks wonder. The fix (#1637) you linked to solved my problem @EApplication problem on gradle:2.0.0-alpha2 and Android Studio 2.0 Preview 3b.

### Steps:
Add repository for AA snapshots:

```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
```

Change AA version to 4.0-SNAPSHOT

```
dependencies {
   compile "org.androidannotations:androidannotations-api:4.0-SNAPSHOT"
   apt "org.androidannotations:androidannotations:4.0-SNAPSHOT"
}
```

Add library:true to apt argument:

```
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName android.defaultConfig.applicationId

        //only for Android Annotations 4.0-SNAPSHOT 
        library 'true'
    }
}
```

**Comment by LouisCAD** [comment]
@kosiara Note that you don't need to specify `androidManifestFile` attribute anymore in AA 4.0

**Comment by WonderCsabo** [comment]
Also `resourcePackageName` is not needed if it is the same as the manifest package name. :)

**Comment by kosiara** [comment]
@LouisCAD 

Thanks. I didn't know that.

**Comment by WonderCsabo** [comment]
I added info about this workaround in the [wiki](https://github.com/excilys/androidannotations/wiki/FAQ#instantrun).

**Comment by rexi1r** [comment]
@kosiara 
i got Error:(61, 6) error: cannot find symbol class OrmLiteDao after change dependences from 3.3.2 to 4.0-SNAPSHOT.

**Comment by WonderCsabo** [comment]
@rexi1r AA 4.0 is modularized, this means you have to add a couple of more dependencies:
```groovy
dependencies {
  apt "org.androidannotations:ormlite:4.0-SNAPSHOT"
  compile "org.androidannotations:ormlite-api:4.0-SNAPSHOT"
}
```

Then you have to change to imports for the `@OrmLiteDao` annotation.

**Comment by WonderCsabo** [comment]
Hey everyone, good news: the [latest](http://tools.android.com/recent/androidstudio20beta6available) Android Studio Beta supports AA with Instant Run out of the box. Please update your IDE.

**Comment by LouisCAD** [comment]
Hurrah!!!

Le mer. 2 mars 2016 10:46 AM, Csaba Kozák <notifications@github.com> a
écrit :
