### ISSUE TITLE
Android 6.0 release removes support for the Apache HTTP client.

### ISSUE THREAD

**Issue by han361769045** [excilys/androidannotations#1640]
Android 6.0 release removes support for the Apache HTTP client。use the HttpURLConnection class instead。
I think it is necessary to add Androidannotations @HttpUrlConnection instead of @HttpsClient

**Comment by han361769045** [comment]
https://developer.android.com/intl/zh-cn/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

**Comment by WonderCsabo** [comment]
There is no way to inject `HttpUrlConnection` as it is can be done with `HttpClient`, because `HttpUrlConnection` is obtained via calling `URL.openConnection()` on a specific `URL` instance.

**Comment by dodgex** [comment]
@WonderCsabo but maybe we want to emit a warning or even error when using those with android 6 target?

**Comment by WonderCsabo** [comment]
Yeah, we could add a warning when `targetSdkVersion >= 23`.

**Comment by WonderCsabo** [comment]
And we should issue an error if the `HttpClient` class is not on the compile classpath.

... or we could just remove `@HttpsClient`...

**Comment by dodgex** [comment]
+1 for removing it.

**Comment by WonderCsabo** [comment]
@yDelouis should we remove this annotation?

**Comment by dodgex** [comment]
@WonderCsabo @yDelouis if we decide to remove this, we should do it before 4.0 to not have a post-4.0 breaking change due to removing an annotation
