### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by gushoubang** [excilys/androidannotations#1645]
too slow

**Comment by WonderCsabo** [comment]
What is too slow?

**Comment by gushoubang** [comment]
it take me 1 minute to  run the project

**Comment by WonderCsabo** [comment]
Which project?

**Comment by gushoubang** [comment]
Gradle build finished in 1m 51s 283ms
The project is mine

**Comment by WonderCsabo** [comment]
And what was the clean build time before AA? It has some compilation
overhead, but not that much. And you can benefit from writing less code.

**Comment by WonderCsabo** [comment]
We log AA execution time in the build log. You should check that instead of
just looking the full build time.

**Comment by gushoubang** [comment]
OK，I think there are some resons is the Android studio 2.0

**Comment by WonderCsabo** [comment]
I am closing this bug because i cannot really do anything about this, and also it seems this is not really a problem.
