### ISSUE TITLE
BackgroundExecutor singleThread

### ISSUE THREAD

**Issue by badoualy** [excilys/androidannotations#1650]
Hi,

For simple apps, I would like to only have a singleThreadPool BackgroundExecutor, I saw issue #309 and the possibility to call `BackgroundExecutor.setExecutor` but I still have the following questions:
- When the app is created, we'll still by default create too many threads due to the following code in BackgroundExecutor class (unless threads are really created only when needed ?)
```java
public static final Executor DEFAULT_EXECUTOR = Executors.newScheduledThreadPool(2 * Runtime.getRuntime().availableProcessors());
```
- When would be the best time to call setExecutor method ? In Application.onCreate ?

If 1. is true and we really create all those threads for nothing, before calling setExecutor, wouldn't it be nice to be able to parametrized this statically somewhere ?

Thanks

**Comment by WonderCsabo** [comment]
It would be the best to call `setExecutor()` when you first use a a `@Background` method. If it is not easy to add there, then you can just call it in `Application.onCreate()`.

Actually, the thread pool is not created when the application is started. Classes are lazily loaded in Java, so the thread pool is actually created when you first access the `BackgroundExecutor` class - normally, when you first call a `@Background` annotated method.

Moreover, thread pools in Java create the threads lazily, so there will be no unnecessary thread creation in your case.

**Comment by badoualy** [comment]
Ok, I was not sure about the lazy part! Thanks for your response!
