### ISSUE TITLE
Unnecessary waring when running test cases

### ISSUE THREAD

**Issue by shiraji** [excilys/androidannotations#1652]
While I was working another issue, I found unnecessary warning that I created before.

```
[WARNING] /home/travis/build/excilys/androidannotations/AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/PageChangeListenerActivity.java:[26,1] The component PageChangeListenerActivity_ is not registered in the AndroidManifest.xml file.
```

aa63925df29bbfe6b7a580c7807ba911f5ac828b is the commit that I should have registered PageChangeListenerActivity_ in the AndroidManifest.xml

**Comment by WonderCsabo** [comment]
So not the warning is unnecessary, but we forgot to add that `Activity` in the manifest. :)

**Comment by shiraji** [comment]
Yea.

**Comment by WonderCsabo** [comment]
Thanks for noticing and fixing this.

**Comment by shiraji** [comment]
No problem! (Although, I was the one who put this problem...)
