### ISSUE TITLE
click  intercept

### ISSUE THREAD

**Issue by foxundermoon** [excilys/androidannotations#1654]
can i define  the  interceptor for  @click 、@Touch  and so on..  to chek user status do some thing before  method   ?

**Comment by WonderCsabo** [comment]
Sorry, I do not understand, can you elaborate?

**Comment by erishforG** [comment]
I think something like this.

    public void changeClickListener(final View.OnClickListener test) {
        View.OnClickListener result =  new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //pre-click function here
                test.onClick(view);
            }
        };
    }

**Comment by shiraji** [comment]
Why don't you add method call at the beginning of the onClick method?

```java
@Click
void onClick() {
    preClick();
    // whatever you want to do for click event
}

void preClick() {
    // whatever you want to do before click event
}
```

**Comment by WonderCsabo** [comment]
@foxundermoon i hope you got your answer, please reopen otherwise.
