### ISSUE TITLE
FOREIGN KEY constraint failed (code 787)

### ISSUE THREAD

**Issue by markymc** [excilys/androidannotations#1655]
Hi all! I've just updated my app from to use AA 3.1.0-SNAPSHOT via Gradle from a library version from late 2012 (without making any edits to my models or the config) and I'm suddenly getting loads of `FOREIGN KEY constraint failed (code 787)` errors being thrown.

I can't seem to find any documentation referring to this. What should I do to my models to fix this without having to change any of my non-model code?

Any help would be greatly appreciated!

Here is an example model if it helps:

```
@Table(name = "subproducts")
public class ContentItem extends Model implements Serializable {

	@Column(name = "subproduct_id", unique = true, onUniqueConflict = ConflictAction.REPLACE)
	public Long id;
	
	@Column(name = "title_en")
	public String title_en;

	@Column(name = "content")
	public String content;

	@Column(name = "url")
	public String url;

	@Column(name = "title_ja")
	public String title_ja;

	@Column(name = "number")
	public int number;

	@Column(name = "sl_product_id")
	public long sl_product_id;
	
	@Column(name = "product_id")
	public Product product;
	
	@Column(name = "description_en")
	public String description_en;

	@Column(name = "description_ja")
	public String description_ja;

	@Column(name = "is_not_new")
	private boolean is_not_new;

	@Column(name = "p_order")
	public int order;

	@Column(name = "cover_image")
	public Image cover_image;

	@Column(name = "details_image")
	public Image details_image;

	@Column(name = "banner_image")
	public BannerImage banner_image;
	
	@Column(name = "type")
	public String type;
}
```

Thanks!

**Comment by WonderCsabo** [comment]
Why are you using 3.1.0-SNAPSHOT? That is an obsolete version.

You are using `@OrmLiteDao`, right? I suggest to try to obtain the `Dao` object by manual coding, and not using `@OrmLiteDao`. If this way it is working, our generated code is maybe broken.

**Comment by markymc** [comment]
@WonderCsabo I'm so sorry, in my stupidity (and tiredness) I posted here instead of ActiveAndroid's repo! Apologies! I'll delete this.

**Comment by markymc** [comment]
Ah, I can't delete it. Are you able to close?

**Comment by WonderCsabo** [comment]
There is no way to delete issues on GH. But you could also close it. :)
