### ISSUE TITLE
@Receiver support for @EView/@EViewGroup

### ISSUE THREAD

**Issue by KenVanHoeylandt** [excilys/androidannotations#1656]
It would be nice to have broadcast receiver support for Views.

I currently register/unregister them manually during `onAttachedToWindow()`/`onDetachedFromWindow()`, but it would be nice if the `@Receiver` annotation would work and do this for me.

This could be practical in a setup where the service/data layer can broadcast updates and views can listen to those events to update themselves.

**Comment by WonderCsabo** [comment]
Yeah, this could be done. Contributions are always welcome. :)

**Comment by kenvanhoeylandt** [comment]
I'll consider adding it myself once I'm done with Advent of Code.
(offtopic: Android Annotations has been my favorite Android project for years! <3)
