### ISSUE TITLE
otto plugin is not working on classes which are not enhanced components

### ISSUE THREAD

**Issue by simonz** [excilys/androidannotations#1657]
I created a simple class like this
```
package com.kakao.ottotest;

import android.util.Log;

import com.squareup.otto.Subscribe;

public class MyClass {
    @Subscribe
    public void observe(Event event) {
        Log.i("MyClass", "event");
    }
}
```
When compiling, the waring occurs and source generation is stopped.
it seems the validations for `@Subscribe` and `@Produce` apply to the class
```
warning: Element observe(com.kakao.ottotest.Event) invalidated by SubscribeHandler
    public void observe(Event event) {
```

**Comment by dodgex** [comment]
yeah sounds like a defect. @WonderCsabo for otto annotations we should skip processing when used on a non-enhanced class?

**Comment by WonderCsabo** [comment]
Yes. We should only invalidate and process these annotation if they are in an enhanced class.

Interesting that this bug only came up now. :)

**Comment by WonderCsabo** [comment]
Fixed. @simonz can you check the [snapshot build](https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle#snapshots)?

**Comment by simonz** [comment]
It works, now I can use "Instance Run". Thank you
