### ISSUE TITLE
A new scope for EBean: Context

### ISSUE THREAD

**Issue by kenvanhoeylandt** [excilys/androidannotations#1663]
A bean with the scope`Scope.Context` is a bean that is bound to 1 specific context, like an `Activity`, an `Application` or a `Service`. When this bean is linked within other beans/fragments of this context, it will re-use the original bean of that context rather than instantiate a new bean.

For example, imagine this setup:

*MyActivity.java*
```java
@EActivity
class MyActivity extends Activity
{
  @Bean
  protected ContentNavigator mContentNavigator;
}
```

*ContentFragment.java*
```java
@EFragment
class ContentFragment extends Fragment
{
  @Bean
  protected ContentNavigator mContentNavigator;
}
```

*ContentNavigator.java*
```java
@EBean
class ContentNavigator
{
}
```

In this situation, there would be 2 instances of `ContentNavigator`, because it gets instantiated everywhere it is injected.

However, if you would introduce the scope `Scope.Context`, it will only be instantiated once (for the `Activity` in this case) and then gets *referenced* in the `ContentNavigator` bean.

*ContentNavigator.java*
```java
@EBean(scope = Scope.Context)
class ContentNavigator
{
}
```

**Comment by WonderCsabo** [comment]
Duplicated of #205, #1488.

**Comment by kenvanhoeylandt** [comment]
Sorry about that. I only searched "scope context" for open issues.

**Comment by WonderCsabo** [comment]
No problem. Feel free to comment your idea to the other issue.
