### ISSUE TITLE
AA generates call to ContextCompat.getColor even if it does not exist

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1665]
If the `support-v4` is on the classpath, but an older version of the library is used and the `ContextCompat.getColor()` method is not available, AA still generates a call to it, hence creating a compilation error.

**Comment by dodgex** [comment]
iirc we decided to assume that the user should have the latest support-v4 dependency?

**Comment by WonderCsabo** [comment]
I do not remember. :S

**Comment by dodgex** [comment]
looks like i'm wrong? https://github.com/excilys/androidannotations/pull/1424

**Comment by WonderCsabo** [comment]
But i remember that in some point, we handled that the user can have an older version of support library. At least we handle that in the Activity options.

**Comment by dodgex** [comment]
also, have you tried AA 4.0? there we have a `ContextAwareResHandler` that is used for ColorRes

**Comment by WonderCsabo** [comment]
Yes, i tried AA 4.0.

**Comment by WonderCsabo** [comment]
So the problem here that we handle that case if the whole `ContextCompat` class is missing, but we not handle that case when `ContextCompat` is present but lack the method we want to call.

**Comment by dodgex** [comment]
ah, thats possible yeah
