### ISSUE TITLE
support multiple preference resources with @PreferenceScreen

### ISSUE THREAD

**Issue by dodgex** [excilys/androidannotations#1669]
it would be nice to support multiple resource ids for `@PreferenceScreen`.

I have a situation where i want to add an extra preferences xml for my debug build (and have a empty copy for release build). currently i have to override `onCreate` and call `super.addPreferencesFromResource`. it's not possible without calling `super` as the generated class overrides the `addPreferencesFromResource` method and tries to inject the preference related fields on each call (also it calls the `@AfterPreferences` methods each time).

@WonderCsabo WDYT?

**Comment by WonderCsabo** [comment]
Quite frankly i do not really understand what you are suggesting here. Can you elaborate?

**Comment by dodgex** [comment]
currently i have to do (minified sample):
```java
@EFragment
@PreferenceScreen(R.xml.preferences)
public class PreferencesFragment extends PreferenceFragment {
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		super.addPreferencesFromResource(R.xml.development_preferences);
	}
}
```
but it would be nice to have
```java
@EFragment
@PreferenceScreen({R.xml.development_preferences, R.xml.preferences})
public class PreferencesFragment extends PreferenceFragment {
}
```

this allows to have some special preferences per flavour or as in my case for build type `debug`.
the `development_preferences.xml` is empty for release build and has some settings that i only want to have/see for development builds. while i could use a extended copy my `preferences.xml` this would mean that i also need to update both for new common settings.

**Comment by WonderCsabo** [comment]
I do not see the point of this. AFAIK, `addPreferencesFromResource()` sets the whole screen, so basically it removes the result of the previous call.

**Comment by dodgex** [comment]
nope, it does not. it **adds** the preferences as the name suggests. with the code above, my debug build has the preferences given in my `development_preferences.xml` (if not empty as in release build) first and then the common preferenfces of `preferences.xml`.

I'd not suggest it without testing if it could work ;)

and the point? i have a toggle to set the debug build to use my local api instead of the live one. and also for chromecast to change the cc app id to use a locally hosted dev cc app.

also this would make sense for e.g pro/free or amazon/play store flavour apk.

**Comment by WonderCsabo** [comment]
OK. It would make sense to be able to add multiple preference xml. However, please note AA always supports the most common and most simple case. Also, i am concerned how we could implement preference injection and `@AfterPreferences` in your case... I am not sure we should do this. @yDelouis WDYT?
