### ISSUE TITLE
java.lang.NoClassDefFoundError: org.springframework.web.util.UriTemplate

### ISSUE THREAD

**Issue by han361769045** [excilys/androidannotations#1670]
12-28 21:40:28.755 28469-28469/com.zczczy.leo.fuwuwangapp E/dalvikvm: Could not find class 'org.springframework.web.util.UriTemplate', referenced from method org.springframework.web.client.RestTemplate.execute

12-28 21:40:29.045 28469-28504/com.zczczy.leo.fuwuwangapp E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
                                                                            Process: com.zczczy.leo.fuwuwangapp, PID: 28469
                                                                            java.lang.NoClassDefFoundError: org.springframework.web.util.UriTemplate
                                                                                at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:498)
                                                                                at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
                                                                                at com.zczczy.leo.fuwuwangapp.rest.NewMyRestClient_.getFirstClass(NewMyRestClient_.java:432)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.IndexActivity.getCategory(IndexActivity.java:71)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.IndexActivity_.access$401(IndexActivity_.java:35)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.IndexActivity_$5.execute(IndexActivity_.java:169)
                                                                                at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:401)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by dodgex** [comment]
not sure if this is an AA issue. looks more like a issue in your dependencies configuration.

**Comment by han361769045** [comment]
it works before,but just now it broke, and then it works again

**Comment by dodgex** [comment]
what? i do not understand what you mean.

**Comment by han361769045** [comment]
this project works OK, but just now I tested it on the phone , it told me that

**Comment by WonderCsabo** [comment]
@dodgex is right, you have wrong dependency configuration. Please post the relevant part of your build script.

**Comment by han361769045** [comment]
thanks for your answer I 'll  check it again.

**Comment by han361769045** [comment]
apply plugin: 'com.android.application'
apply plugin: 'android-apt'

def AAVersion = '3.3.2'


buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        resourcePackageName 'com.zczczy.leo.fuwuwangapp'
    }
}


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.zczczy.leo.fuwuwangapp"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 9
        versionName "1.1"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }

}

dependencies {
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.springframework.android:spring-android-rest-template:2.0.0.M3'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.squareup.okhttp:okhttp:2.6.0'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.squareup:otto:1.3.8'
    compile 'me.himanshusoni.quantityview:quantity-view:1.1.1'
    compile 'com.daimajia.slider:library:1.1.5@aar'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.6.3'
    compile 'com.flyco.dialog:FlycoDialog_Lib:1.2.2@aar'
    compile 'com.flyco.animation:FlycoAnimation_Lib:1.0.0@aar'
    compile 'com.marshalchen.ultimaterecyclerview:library:0.3.18'
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'com.j256.ormlite:ormlite-core:4.48'
    compile project(':infiniteautoscroolviewlibrary')
    compile project(':zxingcapturelibrary')

}

**Comment by WonderCsabo** [comment]
This seems to be okay. Make sure you do not have other jars in your *libs* folder.
Also can you post the result of `./gradlew :app:dependencies`?

**Comment by han361769045** [comment]
#!/usr/bin/env bash

##############################################################################
##
##  Gradle start up script for UN*X
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*"
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched.
if $cygwin ; then
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
fi

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >&-
APP_HOME="`pwd -P`"
cd "$SAVED" >&-

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
        CHECK2=`echo "$arg"|egrep -c "^-"`                                 ### Determine if an option

        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
            eval `echo args$i`=`cygpath --path --ignore --mixed "$arg"`
        else
            eval `echo args$i`="\"$arg\""
        fi
        i=$((i+1))
    done
    case $i in
        (0) set -- ;;
        (1) set -- "$args0" ;;
        (2) set -- "$args0" "$args1" ;;
        (3) set -- "$args0" "$args1" "$args2" ;;
        (4) set -- "$args0" "$args1" "$args2" "$args3" ;;
        (5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
        (6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
        (7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
        (8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
        (9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
    esac
fi

# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
function splitJvmOpts() {
    JVM_OPTS=("$@")
}
eval splitJvmOpts $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
JVM_OPTS[${#JVM_OPTS[*]}]="-Dorg.gradle.appname=$APP_BASE_NAME"

exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

**Comment by han361769045** [comment]
@SharedPref(value = SharedPref.Scope.UNIQUE)
public interface MyPrefs {
    @DefaultString("")
    String picture();
}

Thank U! I've found the mistake, if the method is "picture"  in MyPrefs ,the problem will appear

**Comment by han361769045** [comment]
I  close this issue Thanks.

**Comment by kot331107** [comment]
Sorry guys, but I've stucked with the same issue... :(
Oh, and BTW thanks a lot for an amazing lib!

**Comment by WonderCsabo** [comment]
Sorry, but this is not an AA issue. Please consult the Spring or Picasso libraries for conflicting dependencies.

**Comment by kot331107** [comment]
@WonderCsabo 
Sure, it was written just for your info and your knowledgebase. I'm trying to get with it right now.
