### ISSUE TITLE
Make FragmentBuilder Serializable/Parcelable

### ISSUE THREAD

**Issue by AntekM** [excilys/androidannotations#1672]
Sometimes it would be useful to pass initiated FragmentBuilder (eg. when fragment should be displayed by another activity, which doesn't need to know what kind of fragment it will display), but FragmentBuilder is not Serializable/Parcelable (even though the only argument it has is Bundle). 
Currently in such case I need to pass some fragment ID for a factory and a bundle with fragment arguments and can't use AA method to instantiate fragment (while with builder being serializable I could just pass it and call build() in receiving activity)

**Comment by WonderCsabo** [comment]
These builder classes are not designed to store and persist information. Instead, they are providing a fluent interface to build and start your component.

However with a very simple workaround, you can extract the built `Bundle` to be saved, then restore the builder from it:
```java
FragmentBuilder builder = ...;

Bundle bundle = builder.args();
// save bundle

Bundle restored = ...;

FragmentBuilder restoredBuilder = ...;
restoredBuilder.arg(restored);
```
