### ISSUE TITLE
unexpected generation code by AA

### ISSUE THREAD

**Issue by wangfuda** [excilys/androidannotations#1674]
who can explan this:
my piece code in MainActivity.java:
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            moveTaskToBack(false);
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
unexpected generation code by AA in MainActivity_.java:
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by dodgex** [comment]
What android version do you have as `minSdk`? Afaik this should only be generated for Android <= 2.0

**Comment by dodgex** [comment]
Also what Android Annotations version do you use? I'm not even sure if this should still be generated in a current version. @WonderCsabo any idea? searching for "onBackPressed" only finds a comment in the samples for gradle & maven...

**Comment by WonderCsabo** [comment]
This is an old [feature](https://code.google.com/archive/p/androidannotations/issues/46). This feature was removed in 4.0, https://github.com/excilys/androidannotations/pull/1170.

**Comment by WonderCsabo** [comment]
Anyway, i am closing the ticket, since we dropped this in the latest version.

**Comment by wangfuda** [comment]
@dodgex my minSdk is 15, and Android Annotations version is 3.3.2

**Comment by wangfuda** [comment]
@WonderCsabo the version of Android Annotation i use is the latest version:3.3.2,and this problem  still exists

**Comment by WonderCsabo** [comment]
@wangfuda 4.0, is not released yet, but the this was already removed from the codebase.

**Comment by wangfuda** [comment]
@WonderCsabo when i see the detail code changed by AA , i feel so terriable.
and i found some other strange problem caused by AA.

**Comment by WonderCsabo** [comment]
@wangfuda when you will update to AA 4.0 this "strange code" will disappear, because this feature was already removed in the upcoming 4.0 version

What other strange code did you find?

**Comment by wangfuda** [comment]
@WonderCsabo i have resolve two strange problem i found, and  the problem cause by myself ,not by AA (matter with AA, but not cause by AA).
now ,i still look forward to AA 4.0, thanks for your great efforts,thanks for AA!!

**Comment by LouisCAD** [comment]
@wangfuda If your dare and a possible crash in your app wouldn't matter (didn't crash in apps I built with latest snapshot), you can switch to 4.0 SNAPSHOT right now by following [this guide](https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle#snapshots)

**Comment by wangfuda** [comment]
@LouisCAD thanks for your guide.
