### ISSUE TITLE
Otto is now deprecated

### ISSUE THREAD

**Issue by shiraji** [excilys/androidannotations#1680]
While I'm not sure how to move Otto to RxJava/RxAndroid, Otto is now [deprecated](https://github.com/square/otto#deprecated). I think AA should remove Otto supports in near future.

**Comment by dodgex** [comment]
I  think if we consider that, when should do it with 4.0?

**Comment by shiraji** [comment]
Not sure exactly when. I'm kinda afraid if Square people change their mind. But definitely, at least AA must stop adding more features for Otto supports from now on.

**Comment by WonderCsabo** [comment]
I do not think we should remove the Otto plugin. I think there will be still lots of Otto users, and AA breaks Otto. So if somebody want to switch to AA 4.0 but still wants to keep Otto, he cannot do that.

However i am pretty sure Square will not will change their mind.
