### ISSUE TITLE
How to use androidannotation in simple class

### ISSUE THREAD

**Issue by mchenani** [excilys/androidannotations#1681]
Hey there,
How can I use AA in a simple class?

**Comment by WonderCsabo** [comment]
Do you mean [this](https://github.com/excilys/androidannotations/wiki/Enhance-custom-classes)?

**Comment by mchenani** [comment]
Thanks was helpful, another question, @ViewById will inflate another layout?

**Comment by WonderCsabo** [comment]
`@ViewById` does not inflate anything, it injects views from an already existing layout.
