### ISSUE TITLE
Can android-annotations process the annotations in generated sources?

### ISSUE THREAD

**Issue by luyangkk** [excilys/androidannotations#1682]
I write my own annotation processor to generate customize sources. In those sources, some class was annotated with @EBean. Does android-annotations resolve those annotations in my generated classes?

**Comment by dodgex** [comment]
As far as i know the compiler runs all annotations processors until no files get generated anymore. So i think that those files that got generated should be handled too if necessary. have you already tried it?

**Comment by WonderCsabo** [comment]
Yes, these are called processing rounds. A little bit more description [here](http://hannesdorfmann.com/annotation-processing/annotationprocessing101/).

**Comment by luyangkk** [comment]
```java
@Bean
protected Foo foo;
```

In above code, the `Foo` class is generated by my processor. And it is annotated with `@Bean`, which requires that the definition of `Foo` class should be annotated with `@EBean`. 

Here is the problem. At the first round, `Foo` has not been generated. But android-annotation's processor validates the usage of `Foo` (`@Bean` marked it).  Then this error comes out:

> Error:(42, 4) Gradle: error: @org.androidannotations.annotations.Bean can only be used on an element annotated with @org.androidannotations.annotations.EBean

**Comment by WonderCsabo** [comment]
Yes, we are not handling error types. See #402.

**Comment by luyangkk** [comment]
Oh... I know... Thank you!
