### ISSUE TITLE
How to keep the generated class's method in a same sequence

### ISSUE THREAD

**Issue by ghalong** [excilys/androidannotations#1683]
Hi,
    I use the https://github.com/alibaba/AndFix  to fix bugs without release new apk,I found it parse the dex and collect class info,such as methods,fields and so on,but if it found the new apk has the field that didn't appeared in the old apk,it would throw an exception,like 
java.lang.RuntimeException: can,t add new Field:val$text....
when I did some change in my code(like TestActivity.java) to fix bugs,and try to generate new signed apk,i found the AA generated code's(MainActivity_.java) method sequence was changed,even though I am not change the corresponding orgnal class(MainActivity.java),so the AndFix sometimes thought the anonymity class's field in MainActivity is changed.Here's the MainActivity code pieces
@UiThread
    public void methodA(final int a){
        new Runnable(){
            @Override
            public void run() {
                System.out.println(a);
            }
        };
    }
    @UiThread
    public void methodB(final int b){
        new Runnable(){
            @Override
            public void run() {
                System.out.println(b);
            }
        };
    }
In this time,methodA's anonymity class's compiled name is MainActivity_$1,it has a field named a,and methodB's anonymity class's compiled name is MainActivity_$2,it has a field named b.
when I did some change in the code,event not the MainActivity,then the AA generated MainActivity's class method sequence might be changed,like
@UiThread
    public void methodB(final int b){
        new Runnable(){
            @Override
            public void run() {
                System.out.println(b);
            }
        };
    }
@UiThread
    public void methodA(final int a){
        new Runnable(){
            @Override
            public void run() {
                System.out.println(a);
            }
        };
    }
In this time,methodA's anonymity class's compiled name is MainActivity_$2,it has a field named a,and methodB's anonymity class's compiled name is MainActivity_$1,it has a field named b.So the AndFix thought not only MainActivity_$1 add new field b,but also  MainActivity_$2 add new field a,this is not allowed in the AndFix.
So who can tell me how to keep the AA generated methods in the same sequence,I am so appreciate with your kindness. : )  : )

**Comment by dodgex** [comment]
Unfortunately it is not possible in AA to ensure a the order of generated methods.

**Comment by WonderCsabo** [comment]
@dodgex is right, it is not possible in our architecture. The main problem is that the processing environment returns the list of methods/annotations in a random order.

**Comment by ghalong** [comment]
@dodgex @WonderCsabo Hi,thank you for your reply,I will try other ways for this.Thank you.
