### ISSUE TITLE
Documentation for using and creating plugins with AA 4

### ISSUE THREAD

**Issue by cs-victor-nascimento** [excilys/androidannotations#1688]
For wider testing and troubleshooting it would be nice to have a quick guide on using and creating plugins. Currently, the only way of doing so is looking through test code.

So, this is a feature request for:
- Documentation on how to use plugins in a project. Could be included in the configuration part of the wiki.
- Documentation on how to create a plugin using Maven and Gradle. 

I will start playing with a project to understand how this can be achieved but it would help a lot if you guys provided some documentation up front for us to check this new and awesome feature present in the snapshots. 

Thanks for this awesome framework!

**Comment by WonderCsabo** [comment]
You are absolutely right, and this is planned. Actually this is the one of the few things which is blocking the 4.0 release.
Unfortunately i lack the time to do this currently.

**Comment by cs-victor-nascimento** [comment]
I am trying to set it up locally. If I can manage to make it work I will PR it (new verb around the web these days). But it might take some time... this issue is also to make more people aware of it and share any progress on the requests!

**Comment by WonderCsabo** [comment]
Yes, it is a good thing you opened this task, as you can see i also amended it and assigned to myself. Thanks!

**Comment by dodgex** [comment]
Here is a first Version of the guide: https://github.com/excilys/androidannotations/wiki/Creating-an-AndroidAnnotations-plugin
