### ISSUE TITLE
Create EBean without adding it as a dependency

### ISSUE THREAD

**Issue by VedavyasBhatNomadly** [excilys/androidannotations#1692]
I'm using a pub-sub approach in my app (<a href="https://github.com/greenrobot/EventBus">EventBus</a>) and I have an `EBean` which has subscriber functions. The subscriber callbacks are not happening because the bean is not being created since I don't add the dependency anywhere. Is there any way I can create a bean without adding it as a dependency?

**Comment by dodgex** [comment]
you can use `YourBean_.getInstance(context);`. `YourBean_` should be the name of your class with the `@EBean` annotation with an underscore `_` appended.

You should do that in your `Application` class or use the application context `context.getApplicationContext()`. If you use an `Activity` or `Service` you most likely will cause a memory leak.

**Comment by VedavyasBhatNomadly** [comment]
I don't want to add the dependency because it defeats the concept of a Subscriber.

**Comment by dodgex** [comment]
well then a `@EBean` is not for you. there is no *magic* way of instantiating the class.

what is your issue with having a oneliner call in your app entrypoint (`Application.onCreate`)?

**Comment by VedavyasBhatNomadly** [comment]
That is what I'm currentl()y doing, adding a dependency and never specifically using it. I thought there could be a cleaner way to do it.
Wouldn't it be a useful feature to have, though? Being able to specify that an `EBean` should be created (with some given `Context`, maybe `Application`)?

**Comment by dodgex** [comment]
I dont think so. Imho this is not a common usecase and the effort to implement that is not worth the saving of having one call to `getInstance()` or adding a dependency to the `Application` class.

**Comment by WonderCsabo** [comment]
I really do not understand what are you want to achieve @VedavyasBhatNomadly . If you do not want to access an instance of the bean, how do you want to use it?

Anyway, AA beans are really simple ones, and basically support only injecting them with the `@Bean` annotation. If you want to do more sophisticated solution, you have to code it yourself.

**Comment by VedavyasBhatNomadly** [comment]
My EBean is a singleton, and I need it to simply exist (I don't need to call its function explicitly) because some functions in it are callbacks. Specifically, they are `Subscribers` from <a href="https://github.com/greenrobot/EventBus">EventBus</a>.

My class is an EBean so I do not have to manage its lifecycle.

**Comment by WonderCsabo** [comment]
You can create them by calling the `getInstance_()` method explicitly. For example `SomeBean_.getInstance_(appContext)`. There is no other way to create the bean (other than injecting it of course).
