### ISSUE TITLE
Documentation for getting AndroidManifest out of date

### ISSUE THREAD

**Issue by dalewking** [excilys/androidannotations#1693]
Documentation show example of doing this:

    androidManifestFile variant.outputs[0]?.processResources?.manifestFile

This is accessing internal classes and the names have changed. It is now processResourcesTask

**Comment by WonderCsabo** [comment]
Are you sure? It works for me even with the latest `2.0.0-beta2` version.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.

**Comment by dalewking** [comment]
Was using Kapt with Kotlin, so it appears to be a Kotlin thing.

**Comment by WonderCsabo** [comment]
Well, i do not think that Kotlin is related, because the `variant` object is coming from the Android plugin itself.

**Comment by dalewking** [comment]
But due to issues with Kapt, I ended switching back from Kotlin to Java :-( and had to switch it back

**Comment by WonderCsabo** [comment]
@dalewking if you can share your project or a reduced project, we can took a look!
