### ISSUE TITLE
Add a setType method to org.androidannotations.api.builder.IntentBuilder class

### ISSUE THREAD

**Issue by federicoiosue** [excilys/androidannotations#1694]
When using IntentBuilder to start another activity I'm adding some extras to the intent itself by I'm lacking the ability to add a type to it.
The reason of this is that on my receiving activity I have a mimetype based filter.

**Comment by WonderCsabo** [comment]
Well, you can get the built `Intent` object from the builder, and manipulate it directly:
```java
Intent intent = MyActivity_.intent(this).get();
intent.setType("something");

startActivity(intent);
```

Obviously, we cannot replicate every method of `Intent` in `IntentBuilder`.

**Comment by federicoiosue** [comment]
I'm getting your point.
I was thinking about that because I really like the IntentBuilder elegance and I'd really prefer to write 
```Java
AttachmentsActivity_
	.intent(getActivity())
	.action(Intent.ACTION_SEND)
	.extra(Intent.EXTRA_STREAM, uris.get(0))
	.type("image/jpg")
	.start();
```
instead the the bloated regular version 
```Java
Intent sendIntent = new Intent(getActivity(), AttachmentsActivity_.class);
sendIntent.setAction(Intent.ACTION_SEND);
sendIntent.putExtra(Intent.EXTRA_STREAM, uris.get(0));
sendIntent.setType("image/jpg");
startActivity(sendIntent);
```

**Comment by WonderCsabo** [comment]
OK, it does not hurt to adding `type()`, `category()` and `data()` methods to `IntentBuilder`. Wanna contribute?

**Comment by federicoiosue** [comment]
Here you have my [pull request](https://github.com/excilys/androidannotations/pull/1698)
