### ISSUE TITLE
AA 4 not support RestService

### ISSUE THREAD

**Issue by spysoos** [excilys/androidannotations#1696]
org.androidannotations.annotations.rest.RestService

not found, what is wrong?

**Comment by WonderCsabo** [comment]
AndroidAnnotations 4 has been modularized, you have to add more dependencies and change the package name. But it is not released yet, documentation on this will be added when it will become stable release.

**Comment by spysoos** [comment]
Thank you for reply

**Comment by WonderCsabo** [comment]
You have to add these two dependencies:

```groovy
org.androidannotations:rest-spring:4.0-SNAPSHOT
org.androidannotations:rest-spring-api:4.0-SNAPSHOT
```

And you have to change the REST annotation imports to `org.androidannotations.rest.spring.annotations`.
