### ISSUE TITLE
Add instantRun processing parameter

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#1697]
When using *Instant Run*, it changes the user-provided application class to a special one in the full manifest, which application can instrument the bytecode to enable *Instant Run*.

For use this means we cannot validate the application class with `@EApplication`. The current workaround in #1639 is to turn of all validations for components in manifests. However this is not a good solution, because it can lead to more developer errors.

Maybe we could introduce a new processing parameter which only turns off validation for `@EApplication`.

@dodgex @yDelouis WDYT?

**Comment by dodgex** [comment]
maybe it is possible to disable the warning when the Application class for *Instant Run* builds is replaced. at least if it is possible to be sure that it is the instant run class (i.e. if registred application is `com.android.instantrun.Application` do not warn/error)

**Comment by WonderCsabo** [comment]
Hmm, so you are suggesting if the application in the manifest is `com.android.instantrun.Application` then we should just skip the error? That is great, so in that case we will do not have to add the processing option.

**Comment by dodgex** [comment]
`com.android.instantrun.Application` was just an example for a possible name of the class. we first would need to check if it is a name where we can assume that it is actually the Instant Run `Application` class.

but yeah, if that is possible i'd suggest that as it is the less intrusive solution. for normal builds we still validate and for instant run we can ignore this specific error.

**Comment by WonderCsabo** [comment]
Oh, i see. I will try out Instant Run and check the real application class name. I wanted to try that anyway. :)

**Comment by WonderCsabo** [comment]
OK, the real classname is `com.android.tools.fd.runtime.BootstrapApplication`.

**Comment by WonderCsabo** [comment]
Good news: it seems the full manifest still contains the original application class name:
```xml
<application
        name="org.androidannotations.sample.MyApp_"
        android:name="com.android.tools.fd.runtime.BootstrapApplication"
        android:icon="@drawable/icon"
        android:label="@string/app_name" >
```

So we can still validate even with instant run!

**Comment by dodgex** [comment]
nice. so they copy the original `andorid:name` attribute to `name` and then set thier own... most probably so that they can read it in thier `BootstrapApplication`. should be an easy fix now?

**Comment by WonderCsabo** [comment]
Yep, I already have a fix in my mind, hopefully I can implement it tonight.
