### ISSUE TITLE
Variable length parameter not applied to super call

### ISSUE THREAD

**Issue by couchcrew-thomas** [excilys/androidannotations#1702]
I've just stumbled upon this rather important bug: When using methods with variable argument lengths, the argument is stripped of the super call in the generated code. I am using the 4.0 Snapshot version.

Annotated code:

    @SupposeBackground
    public void foo(Object... bar) {
        Log.d("foo", String.valueOf(bar.length));
    }

Generated code:

    @Override
    public void foo(Object... bar) {
        BackgroundExecutor.checkBgThread();
        AdConfig_.super.foo();
    }

Expected generated code:

    @Override
    public void foo(Object... bar) {
        BackgroundExecutor.checkBgThread();
        AdConfig_.super.foo(**bar**);
    }

**Comment by WonderCsabo** [comment]
Indeed, this is a bug. Thanks for reporting!
