### ISSUE TITLE
Too much output on Android Studio Gradle console

### ISSUE THREAD

**Issue by fqborges** [excilys/androidannotations#1710]
Currently, I find it hard to see the warnings on the console output. There are a lot of lines with 'Note:' and I could not find anything related on the docs.

Is there a way to suppress those notes lines? Is it possible to make this an option?

And thanks for making this amazing tool!

![capture](https://cloud.githubusercontent.com/assets/2059053/13409414/b8b6de70-df11-11e5-80dd-e67fc134012e.PNG)

**Comment by WonderCsabo** [comment]
You should really read the wiki. You can [change](https://github.com/excilys/androidannotations/wiki/CustomizeAnnotationProcessing#loglevel) logging level. Yeah, AA logs too much by default currently, but this is fixed in AA 4.0.

**Comment by fqborges** [comment]
Thanks for your answer.
I did read the wiki, but changing the log level does not make any difference on those 'Note:' lines, that is why I opened the issue.
Once again, Thanks. This tool is amazing.

**Comment by WonderCsabo** [comment]
Oh, you should be more specific about the issue, then.

This should be fixed in AA 4.0-SNAPSHOT, if you want, you can check it out.
