### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by TianLiJun** [excilys/androidannotations#1711]
I can`t use it in fragment.I don`t know how to use @ViewById  in fragment.
![Uploading image.png…]()

**Comment by WonderCsabo** [comment]
From our [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (linked on the top of the new issue form):

> Please note GitHub issue tracker is not a user support forum, we discuss development here. If you have questions about just using AA, please go to [our mailing list](http://groups.google.com/group/androidannotations) or [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or [Gitter](https://gitter.im/excilys/androidannotations?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).
