### ISSUE TITLE
doesn't androidannotations support gradle2.0?

### ISSUE THREAD

**Issue by yubaokang** [excilys/androidannotations#1713]
doesn't androidannotations support gradle2.0?

**Comment by WonderCsabo** [comment]
It does. Actually AA and Gradle are totally unrelated.

**Comment by WonderCsabo** [comment]
From our [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (linked on the top of the new issue form):

> Please note GitHub issue tracker is not a user support forum, we discuss development here. If you have questions about just using AA, please go to [our mailing list](http://groups.google.com/group/androidannotations) or [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or [Gitter](https://gitter.im/excilys/androidannotations?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).

**Comment by snailrobert** [comment]
how config it with gradle2.0? and i take miss of it...

**Comment by WonderCsabo** [comment]
I guess you mean the Android Gradle Plugin 2.0 . But please read the wiki.
