### ISSUE TITLE
4.0-SNAPSHOT not found

### ISSUE THREAD

**Issue by Urkman** [excilys/androidannotations#1720]
I tried to use the 4.0-SNAPSHOT, but it is not found:

> 
> Gradle sync failed: Could not find org.androidannotations:androidannotations:4.0-SNAPSHOT.
>          Searched in the following locations:
>          file:/Applications/Development/Android Studio.app/Contents/gradle/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/maven-metadata.xml
>          file:/Applications/Development/Android Studio.app/Contents/gradle/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.pom
>          file:/Applications/Development/Android Studio.app/Contents/gradle/m2repository/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.jar
>          https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.0-SNAPSHOT/maven-metadata.xml
>          https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.pom
>          https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.0-SNAPSHOT/androidannotations-4.0-SNAPSHOT.jar

When I use 3.3.2 everything is fine...

**Comment by WonderCsabo** [comment]
You did not follow the steps correctly, you must [add the snapshot repo](https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle#setup) as well.

BTW from our [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (linked on the top of the [new issue form](https://github.com/excilys/androidannotations/issues/new)):

> Please note GitHub issue tracker is not a user support forum, we discuss development here. If you have questions about just using AA, please go to [our mailing list](http://groups.google.com/group/androidannotations) or [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or [Gitter](https://gitter.im/excilys/androidannotations?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).
