### ISSUE TITLE
cut and limit auto generated Log tag length to 23 chars long

### ISSUE THREAD

**Issue by delta2wye** [excilys/androidannotations#1721]
Getting some lint errors because of auto generated log tags in generated subclasses because of long class names. 

Would be nice to cut longer names to max 23 chars to comply with android lint. 

Here's an example:

```
if (context_ instanceof ActionBarActivity) {
            activity = ((ActionBarActivity) context_);
        } else {
            Log.w("ActivityActionBarHelper_", (("Due to Context class "+ context_.getClass().getSimpleName())+", the @RootContext ActionBarActivity won't be populated"));
        }
```

**Comment by WonderCsabo** [comment]
I suggest to turn off all Lint checks for generated classes.

*lint.xml:*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
    <issue id="all">
        <ignore regexp="build/generated/source/apt/.*/.*_.java"/>
    </issue>
</lint>
```

**Comment by WonderCsabo** [comment]
OK, actually we do [cut the tag to 23 chars](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/TraceHandler.java#L239).

**Comment by delta2wye** [comment]
@WonderCsabo I think the relevant code is here :
https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/RootContextHandler.java#L85

**Comment by WonderCsabo** [comment]
Oh, I thought you are talking about the `@Trace` annotation. You are right, this can be an issue.
