### ISSUE TITLE
if add productFlavors, XXX_ class can not be found

### ISSUE THREAD

**Issue by FrancisShi** [excilys/androidannotations#1722]
if I add a flavor:
`    productFlavors {
        gray {
            applicationId "com.abc.gray"
        }
    }`

 The class generated by Android Annotations , for example, named CaptureActivity_ , can not be found:
`CaptureActivity_.intent(overviewView.getViewContext())
                        .qrCodeMode(CaptureActivity.QRCODE_COUPON_VERIFICATION)
                        .titleResId(R.string.title_verification)
                        .startForResultCaptureActivity.REQUEST_CAPTURE);
`

**Comment by WonderCsabo** [comment]
You must add your manifest package name parameter, so AA can find your R class:
```groovy
apt {
  arguments {
    resourcePackageName "your.manifest.package.name"
  }
}
```
