### ISSUE TITLE
Instant Run and "Generating code should be avoided as much as possible"

### ISSUE THREAD

**Issue by stcdalyc** [excilys/androidannotations#1723]
well, i don't know if it's related to [androidannotation always generate code](https://github.com/excilys/androidannotations/wiki/FAQ#generating-code-why), the new feature Instant Run always need to run so long time(such as 2 minutes, but rebuild the project also takes 2 minutes, so it seems to the Instant Run rebuild the whole project)

**Comment by WonderCsabo** [comment]
AndroidAnnotations is a code generation framework, so i do not really know what do you expect from us... We do support incremental compilation, and we cannot do anything about how Instant Run calls us.
