### ISSUE TITLE
the ver  is 4.0.0  or  4.0?

### ISSUE THREAD

**Issue by han361769045** [excilys/androidannotations#1724]
https://github.com/excilys/androidannotations/wiki/4.0-migration-guide

**Comment by dodgex** [comment]
It's 4.0.0 We decided to use the long Version after @WonderCsabo had written the wiki. I think He just forgot to update the wiki pages.

**Comment by WonderCsabo** [comment]
Thanks for noticing, you are right. I changed the version number everywhere to 4.0.0 in the wiki.
