### ISSUE TITLE
RestService how to use? 

### ISSUE THREAD

**Issue by wxkcoder** [excilys/androidannotations#1729]
4AA RestService how to use? I can't understand

**Comment by WonderCsabo** [comment]
Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

Moreover, you can find [detailed documentation](https://github.com/excilys/androidannotations/wiki/Rest%20API) in the wiki.

**Comment by wxkcoder** [comment]
I'm so sorry,I will
