### ISSUE TITLE
Have problems using @EActivity and @viewbyid,@Click

### ISSUE THREAD

**Issue by sentox** [excilys/androidannotations#1731]
It is my first time that I use the AA. while I coding as the sample,  @Click a button, the button never onclick,and I try to @viewbyid this button ,find out that it is null,my mainActivity extends a BaseActivity, is that a problem?how can I fix the problem? please read my code.

@EActivity
public class MainActivity extends BaseActivity {
@Click(R.id.btn_waterwave)
	void btn_waterwave(){
		Intent intent = new Intent(MainActivity.this,GewalaActivity.class);
		startActivity(intent);
	}
@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
LayoutInflater inflater = (LayoutInflater) this
				.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
		inflater.inflate(R.layout.activity_main, mLayout_body);
	}
}

ps:in the BaseActivity,i will setContentView

`@EActivity
public class BaseActivity extends Activity implements IBaseActivity {

public LinearLayout mLayout_body;
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        // TODO Auto-generated method stub
        requestWindowFeature(Window.FEATURE_NO_TITLE); // 窗口模式
        super.onCreate(savedInstanceState);
        setContentView(R.layout.base_module_view);
        mLayout_body = (LinearLayout) findViewById(R.id.Layout_body);
}

}`

Please tell me how to fix my problem because All my projects has BaseActivity

**Comment by WonderCsabo** [comment]
Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by WonderCsabo** [comment]
AndroidAnnotations hooks into view injection when the `setContentView()` method is called. You are adding your mainactivity view by inflating it directly into the already existing content view. So no `setContentView()` is called, and AA is not injecting any view.

**Comment by sentox** [comment]
I am sorry that I used a wrong way to ask a question ,It is my first time using github,can you tell me how to fix this problem? thank you  million times,or,it is won't fix?

**Comment by WonderCsabo** [comment]
You cannot fix this easily. You can duplicate the whole layout for each activity, and just call `setContentView()` or `@EActivity(R.layout.main`. But that would be a bad solution because all of the layouts would be duplicated.
Or you can use one Activity, and use Fragments instead of inflating sublayout in the child Activites

**Comment by sentox** [comment]
ok,thank you for answering my question,it taught me a lot,  really appreciate AA.
