### ISSUE TITLE
AndroidAnnotations 4.0 not accepting Spring android 

### ISSUE THREAD

**Issue by Harshakanthgd** [excilys/androidannotations#1732]
I am facing problem to use AA 4.0 with org.springframework.android:spring-android-rest-template:1.0.0.RELEASE. 

Is their any compatibility issue that i am missing. Kindly throw some light on this as i am working on this for past 2 days.

Its throwing a DuplicateFileException as below:

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/license.txt
	File1: \.gradle\caches\modules-2\files-2.1\org.springframework.android\spring-android-rest-template\1.0.0.RELEASE\154e9b979594dc064eaa2c07ca1a045634537cf4\spring-android-rest-template-1.0.0.RELEASE.jar
	File2: \.gradle\caches\modules-2\files-2.1\org.springframework.android\spring-android-core\1.0.0.RELEASE\7ee66d6bd7af44b40fba9017dfd436e72f93d3ac\spring-android-core-1.0.0.RELEASE.jar

**Comment by dodgex** [comment]
this is nto an AA issue. it is that you have to jars containing `META-INF/licensetxt`. you can remove that error by adding the following snipped inside your `android {}` block in your build.gradle

```
	packagingOptions {
		exclude "META-INF/LICENSE"
		exclude "META-INF/NOTICE"
		exclude "LICENSE.txt"
	}
```

**Comment by WonderCsabo** [comment]
@dodgex is right. But you also have to exlclude the `notice.txt` file inside the `android` block:
```groovy
packagingOptions {
   exclude "META-INF/license.txt"
   exclude "META-INF/notice.txt"
}
```

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by Harshakanthgd** [comment]
Thanks @dodgex  and @WonderCsabo made the changes and works like a charm
