### ISSUE TITLE
How to get the specific error message  如何获取具体的报错信息

### ISSUE THREAD

**Issue by 401885064** [excilys/androidannotations#1737]
My tools is android studio ，all is well, sometime i change somethings   and  when i  build  ，have a error ， but  android studio do not telll me what  error？？

what can i  do  have  error info??

**Comment by WonderCsabo** [comment]
Please add more information per the [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue), which is already referenced on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by WonderCsabo** [comment]
Closing due to lack of response and information.
