### ISSUE TITLE
kapt, AA and package-info doesn't work together

### ISSUE THREAD

**Issue by egslava** [excilys/androidannotations#1740]
I've reported bug to JetBrains, but I don't know where's right place - JetBrains Tracker or AA-tracker :-)
JetBrains post:
https://youtrack.jetbrains.com/issue/KT-11730

Github project with error:
https://github.com/egslava/bug-kotlin-kapt-package-info

**Comment by WonderCsabo** [comment]
This is out of AA's scope. Hopefully `kapt` guys will respond.
