### ISSUE TITLE
Fragments not working

### ISSUE THREAD

**Issue by Looooooka** [excilys/androidannotations#1741]
Pretty much doing the same as this sample:
http://deploythoughts.blogspot.si/2016/01/android-tabs-with-viewpager-and.html
```java
@EFragment(R.layout.fragment_test)
public class TestFragment extends Fragment
{
    public TestFragment()
    {
    }

    @AfterInject
    public void calledAfterInjection()
    {
    }

    @AfterViews
    public void calledAfterViewInjection()
    {
    }
}
```
The view gets injected just fine...but the afterviews and afterinjection calls are never raised.
Any ideas on how to fix this?

**Comment by WonderCsabo** [comment]
Can you post the generated class? What AA version you are using?

**Comment by Looooooka** [comment]
MainView:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="si.intech.nudge.MainActivity">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways"
            app:popupTheme="@style/AppTheme.PopupOverlay">

        </android.support.v7.widget.Toolbar>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </android.support.design.widget.AppBarLayout>
    <android.support.v4.view.ViewPager xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:background="@drawable/backdrop_resource">
    </android.support.v4.view.ViewPager>
</android.support.design.widget.CoordinatorLayout>`

class:
`package si.intech.nudge;

import android.os.Build;
import android.support.design.widget.TabLayout;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.os.Bundle;
import android.transition.Fade;
import android.view.Menu;
import android.view.MenuItem;

import android.view.ViewTreeObserver;

import org.androidannotations.annotations.*;


@EActivity(R.layout.activity_main)
public class MainActivity extends AppCompatActivity
{
    private SectionsPagerAdapter mSectionsPagerAdapter;
    
    @ViewById(R.id.container)
    public android.support.v4.view.ViewPager mViewPager;

    @ViewById(R.id.toolbar)
    public Toolbar mToolbar;
    @ViewById(R.id.tabs)
    public TabLayout tabLayout;
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ActivityCompat.postponeEnterTransition(this);
        setupWindowAnimations();
    }

    private void setupWindowAnimations() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Fade transition = new Fade();
            transition.setDuration(1000);
            getWindow().setEnterTransition(transition);
        }
    }

   @AfterViews
    void setupView() {
        setSupportActionBar(mToolbar);
        SectionsPagerAdapter mSectionsPagerAdapter = new SectionsPagerAdapter(this,getSupportFragmentManager());
        mViewPager.setAdapter(mSectionsPagerAdapter);
        mViewPager.setOffscreenPageLimit(1);
        mViewPager.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
            public boolean onPreDraw() {
                mViewPager.getViewTreeObserver().removeOnPreDrawListener(this);
                ActivityCompat.startPostponedEnterTransition(MainActivity.this);
                return true;
            }
        });

       tabLayout.setupWithViewPager(mViewPager);
   }

    @Override
    public void onPause() 
    {
        super.onPause();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) 
    {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();

        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
`
pageadapter code:
`package si.intech.nudge;

import android.content.Context;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import si.intech.nudge.views.TestFragment_;


public class SectionsPagerAdapter extends FragmentPagerAdapter {
    Context context;
    public SectionsPagerAdapter(Context context,FragmentManager fm) {
        super(fm);
        this.context=context;
    }
    @Override
    public Fragment getItem(int position) {
        Fragment fragment;
        switch (position) {
            default:
            case 0:
                fragment = TestFragment_.builder().build();
                break;
        }
        return  fragment;
    }

    @Override
    public int getCount() {
        return 1;
    }

    @Override
    public CharSequence getPageTitle(int position) {
        int resId;
        switch (position) {
            default:
            case 0:
                resId = R.string.fragmentTitleTest;
                break;
        }
        return context.getString(resId);
    }
}
`
using org.androidannotations:androidannotations:4.0.0

**Comment by WonderCsabo** [comment]
So in yout `MainActivity`, `setupView()` is not called? Can you post the generated java class (`MainActivity_.java`).

**Comment by Looooooka** [comment]
No no main activity works fine. But in TestFragment calledAfterInjection and calledAfterViewInjection are never called even though @EFragment(R.layout.fragment_test) seems to have worked since the fragment is rendered inside the tabs content as expected.

**Comment by WonderCsabo** [comment]
Then can you share your fragment and the corresponding generated fragment class?

**Comment by Looooooka** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".views.TestFragment_" android:id="@+id/TestFragment"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">
    <RelativeLayout
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">

        <Button
            android:text="test"
            android:id="@+id/btnTest"
            android:layout_width="200dp"
            android:layout_height="60dp"
            android:layout_centerHorizontal="true"
            android:layout_marginBottom="100dp"
            android:layout_above="@+id/gap" />
        <View android:id="@+id/gap"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_alignParentBottom="true" />
    </RelativeLayout>
</FrameLayout>
`
`package si.intech.nudge.views;

import android.content.Context;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.widget.Button;

import org.androidannotations.annotations.*;
import si.intech.nudge.R;

@EFragment(R.layout.fragment_test)
public class TestFragment extends Fragment
{
    @ViewById(R.id.btnTest)
    Button btnTest;

    @AfterInject
    public void calledAfterInjection()
    {
    }

    @AfterViews
    public void calledAfterViewInjection()
    {
    }
    @Click(R.id.btnTest)
    void On_btnTest_Click()
    {

    }
}
`

**Comment by WonderCsabo** [comment]
Please, share the generated file, from the build folder.

**Comment by Looooooka** [comment]
`//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.0.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package si.intech.nudge.views;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import si.intech.nudge.R;

public final class TestFragment_
    extends si.intech.nudge.views.TestFragment
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        contentView_ = null;
        btnTest = null;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        calledAfterInjection();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static TestFragment_.FragmentBuilder_ builder() {
        return new TestFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.btnTest = ((Button) hasViews.findViewById(R.id.btnTest));
        if (this.btnTest!= null) {
            this.btnTest.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    TestFragment_.this.On_btnTest_Click();
                }
            }
            );
        }
        calledAfterViewInjection();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<TestFragment_.FragmentBuilder_, si.intech.nudge.views.TestFragment>
    {

        @Override
        public si.intech.nudge.views.TestFragment build() {
            TestFragment_ fragment_ = new TestFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }
    }
}
`

**Comment by WonderCsabo** [comment]
As you can see, we call your method in the generated class. Add a statement to those methodds, and put a breakpoint on them. When you debug, you will see those are called. Or you can just add a Log statement.

**Comment by Looooooka** [comment]
Ah rookie mistake.
Had to clean the project, close android studio...even though the code was clearly working (put some code to hide the button as you advised) for some reason only the breakpoints on the fragment classes were not being hit. I was sure there was something wrong because the breakpoints in the constructor got hit just fine.
WEIRD but...thank you. Would have probably wasted a couple more hours being sure there was something wrong with the fragment injection itself.

**Comment by WonderCsabo** [comment]
I glad the problem was resolved.
