### ISSUE TITLE
Android annotation Encoding Problem

### ISSUE THREAD

**Issue by CrazyClownSola** [excilys/androidannotations#1746]
in case of Android annotation 3.2

if I write like this 

MyActivity.class
```

/**
 * 获取布局
 */
@Extra("menu")
int menu_id;

```

then in MyActivity_.class 
```

public MyActivity_.IntentBuilder_ menu_id(int menu_id) {
       return super.extra(MENU_ID_EXTRA, menu_id);
}

```

But in Android annotation 4.0

the same code

but in MyActivity_.class 
```
  /**
         * 
         * ���ݴ�����
         * @param menu_id
         *     the value for this extra
         * @return
         *     the IntentBuilder to chain calls
         */
        public DetailListActivity_.IntentBuilder_ menu_id(int menu_id) {
            return super.extra(MENU_ID_EXTRA, menu_id);
        }

```
and this cause some error in Android Studio 
like this

```
Error:(188, 12) 错误: 编码UTF-8的不可映射字符
Error:(188, 13) 错误: 编码UTF-8的不可映射字符
Error:(188, 14) 错误: 编码UTF-8的不可映射字符
Error:(188, 16) 错误: 编码UTF-8的不可映射字符
Error:(188, 17) 错误: 编码UTF-8的不可映射字符
Error:(188, 18) 错误: 编码UTF-8的不可映射字符
Error:(188, 19) 错误: 编码UTF-8的不可映射字符
Error:(188, 20) 错误: 编码UTF-8的不可映射字符
8 个错误
:main:compileRetrolambdaDebug
Error:Execution failed for task ':main:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Could I do something to deal with this problem?
Thanks

**Comment by dodgex** [comment]
looks like Android Annotations does not generate UTF-8 files or has some other problems with your UTF-8 comments.

as a workarounnd it should be able to fix the issue when you change your comment to
```
/*
 * 获取布局
 */
@Extra("menu")
int menu_id;
```
note that there is only one star in the first line of the comment. so it is just a multiline comment and no javadoc comment and AA should not try to copy the value to the generated class.


@WonderCsabo any idea how we could fix that?

**Comment by WonderCsabo** [comment]
First, @CrazyClownSola you should try the following:
```groovy
android {
    ...
    compileOptions {
        encoding "UTF-8"
        ...
    }
}
```

**Comment by CrazyClownSola** [comment]
@WonderCsabo  

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        encoding "UTF-8"
    }
}
```
I do like this 
But it still cause some error in Android Studio 
```
Error:(154, 12) 错误: 编码UTF-8的不可映射字符
Error:(154, 13) 错误: 编码UTF-8的不可映射字符
Error:(154, 14) 错误: 编码UTF-8的不可映射字符
Error:(154, 15) 错误: 编码UTF-8的不可映射字符

```

**Comment by WonderCsabo** [comment]
@dodgex i recall there was a similar issue to this, but i cannot find it. I think there i suggested to add a new processing flag, which modifies the encoding of the generated source files. Currently we [use](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/generation/SourceCodeWriter.java#L48) the platform default encoding, but that can be problematic, like in this case.

**Comment by dodgex** [comment]
i can't remember of such an issue. but maybe use UTF-8 instead of the default? i think UTF-8 should be used for source files.

**Comment by WonderCsabo** [comment]
@dodgex i totally agree, but if somebody uses `encoding "something"`, then the generated UTF-8 files will not be properly recognised by the compiler.
Maybe we should set the default to UTF-8, and add the option to change it.

**Comment by dodgex** [comment]
that sounds like a good solution

**Comment by WonderCsabo** [comment]
@CrazyClownSola as a workaround, you can try to change your platform default encoding to UTF-8. Not sure if it is possible in your case.

**Comment by WonderCsabo** [comment]
Implemented. @CrazyClownSola you can try the snapshot build.
