### ISSUE TITLE
Plugin annotations on classes with inheritance cause annotation generation to fire twice

### ISSUE THREAD

**Issue by chpasha** [excilys/androidannotations#1747]
consider following code:
```
@EBean
@ERoboguiceBean
@ContextSingleton
public class MyCustomBean
{
}
```

and

```
@EBean
@ERoboguiceBean
@ContextSingleton
public class MyAnotherCustomBean extends MyCustomBean 
{}
```

@ERoboguiceBean is my custom plugin it just slightly extends code generated by EBean (adds annotation to constructor and rewrites factory method). Actually what it does is not important. Interesting is the fact, that generation is called twice for MyAnotherCustomBean class and unless I check if generation was done already, some code will be generated twice. The question primarily is if it is an expected behaviour - because I don't get it, why it is called twice. 

P. S. I would be happy to contribute my plugin to the AA if you find it useful. Like I said, it generates classes like this

```
@ContextSingleton 
public final class MyCustomBeanImpl extends MyCustomBean
{
    private Context context_;

    @Inject
    private MyCustomBeanImpl(Context context) {
        context_ = context;
        init_();
    }

    public static MyCustomBeanImpl getInstance_(Context context) {
        RoboInjector injector;
        injector = RoboGuice.getInjector(context);
        return injector.getInstance(MyCustomBeanImpl.class);
    }

    private void init_() {
        this.context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }
}
```

the benefit is - such extended beans can be injected anywhere both with @Inject and with @Bean and use AA features. But it's not so important, the main reason I created this ticket - is multiple generation rounds which I worked around but maybe I'm doing something wrong

**Comment by WonderCsabo** [comment]
Good to know somebody is using the plugin system. :)

Can you share the source of your plugin?

**Comment by chpasha** [comment]
Sure, here is a plugin part without annotation, since it is trivial
[robo-plugin.zip](https://github.com/excilys/androidannotations/files/213649/robo-plugin.zip)
it is not optimal in terms of code reuse (I was in hurry for a working sample, so there are a couple of copy pastes from AA source code ) and it is for a roboguice 2.0 since I still use this version, but the change to 3.0 is also trivial. I was using the modified AA version until 4.0.0 and it worked for me much better then stock @RoboGuice annotation, since like I said, I wanted AA+Roboguice stuff injected in different places, not only EActivity. But this implementation via plugin system is definitely cleaner ... but not yet tested much :)

**Comment by WonderCsabo** [comment]
Please share a fully working example which i can import, build and test w/o any further effort. Creating the necessary files is taking too much time.

**Comment by chpasha** [comment]
I will make a working sample tomorrow, I though you just want to look at code ;)

**Comment by WonderCsabo** [comment]
OK, i checked the code. You should definitely inherit from `BaseGeneratingAnnotationHandler`. Please check out the original `EBeanHandler`.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.
