### ISSUE TITLE
Where to download the jar package

### ISSUE THREAD

**Issue by ZhanRu** [excilys/androidannotations#1751]
I downloaded from the Maven jars can't use： androidannotations-4.0.0.jar  androidannotations-api-4.0.0.jar

**Comment by WonderCsabo** [comment]
What do you mean you cannot use those?

**Comment by Wxy1** [comment]
i want download 4.0 jar

**Comment by WonderCsabo** [comment]
You can download it from Maven Central, as always.

Also, please be more polite.
