### ISSUE TITLE
Delteted  unUsed XML file   Case ERROR

### ISSUE THREAD

**Issue by 401885064** [excilys/androidannotations#1758]
I have deleted some XML files, these files are no longer used, then AS Rebuild error, the error is shown as follows:

Error:(24, 40) 错误: 找不到符号   Cannot find symbol

All use the Androidannotations where are reported to be wrong and the same mistake!

I would like to ask how to view the specific error information and the location of the error in the AS tool

**Comment by 401885064** [comment]
If I do not delete these files, everything is running normally , but these files are really redundant files

**Comment by WonderCsabo** [comment]
Sorry, but it it not clear what you are try to reporting. Please rephrase and add much more information.

**Comment by 401885064** [comment]
Do you have QQ?    I can show you the distance ，   I'll send you a message later, tell me the details.

**Comment by WonderCsabo** [comment]
No, i am not using QQ, but anyways, but do not PM me. Report the bug correctly here.

**Comment by WonderCsabo** [comment]
Closed due to lack of response.
