### ISSUE TITLE
Option to disable Clean injected View fields in Fragment#onDestroyView()

### ISSUE THREAD

**Issue by bluef** [excilys/androidannotations#1759]
As we got too many NullPointerException caused by delayed UI updating issues after upgrading Android Annotation to 4.0.0, is it possible providing an option in the configuration to disable that feature at the setup phrase? It would be too many lines of code to migrate to adopt 4.0.0

Thanks.

**Comment by dodgex** [comment]
Currently there is no way to disable this feature. It should work if you add ` @IgnoreWhen(IgnoreWhen.State.VIEW_DESTROYED)` (see [wiki](https://github.com/excilys/androidannotations/wiki/IgnoredWhenDetached#ignorewhen)) to the methods. with this annotation AA overrides the method and skips the actual call if the Fragments view has been destroyed.

As this feature has been introduced to avoid possible memory leaks i'm not sure if we want to add an option to disable this feature. @WonderCsabo what do you think?

**Comment by bluef** [comment]
@dodgex The @IgnoreWhen annotation may help, but it would be too much work to migrate the code as we have a 200k lines code base.

Actually we don't have any memory leaks issues related to Android Annotation (over 10M users in China), so we think it's ok to leave those references alone and wait for the GC to do its work.

**Comment by WonderCsabo** [comment]
GC will not do its work, because you have strong references to the views. They will not be GC'd until the Fragment object is removed, or the views are reinjected. 

I do not think it makes sense to add an option to disable this feature.

**Comment by WonderCsabo** [comment]
I am closing this issue. The view cleaning is necessary, because it causes a serious memory hold. Yep, it is a breaking change, but we clearly noted this on the relevant pages.
