### ISSUE TITLE
abstract EApplication of library is required in AndroidManifest

### ISSUE THREAD

**Issue by couchcrew-thomas** [excilys/androidannotations#1761]
This issue is related to #1363 

Example project structure:
- Library Module
  - `@EApplication abstract class BaseApplication ...`
- App
  - `@EApplication class App extends BaseApplication`

The build fails with the messages:
> 10:45:12.618 [Daemon worker Thread 8] INFO  o.a.i.p.ModelValidator:46 - Validating elements
> 10:45:12.618 [Daemon worker Thread 8] DEBUG o.a.i.p.ModelValidator:66 - Validating with EApplicationHandler: [foo.BaseApplication, channels]
> 10:45:12.618 [Daemon worker Thread 8] ERROR o.a.i.p.ModelValidator:74 - No application class registered in the AndroidManifest.xml

Since BaseApplication is abstract and a library class it must not be required to be registered inside the AndroidManifest, because registering abstract classes throws an error.

I've attached an example project that causes the build failure:
[AATestApplication.zip](https://github.com/excilys/androidannotations/files/240159/AATestApplication.zip)

**Comment by WonderCsabo** [comment]
Are you using the `library` [processing parameter](https://github.com/excilys/androidannotations/wiki/CustomizeAnnotationProcessing#library)?

```groovy
library "true"
```

**Comment by couchcrew-thomas** [comment]
Adding the parameter changes nothing.

Only the following a warning appears:
> Warning:The following options were not recognized by any processor: '[library]'

My updated `build.gradle` of the testlibrary:

    apply plugin: 'com.android.library'
    apply plugin: 'android-apt'
    apply from: '../common_android.gradle'
    apply from: '../common_android_aa.gradle'

    apt {
        arguments {
            library "true"
        }
    }

    android {
        defaultConfig {
            versionCode 1
            versionName "1.0"
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: '*.jar')
        compile 'com.android.support:appcompat-v7:23.2.1'
        compile 'com.android.support:cardview-v7:23.2.1'
        compile 'com.android.support:gridlayout-v7:23.2.1'
        compile 'com.android.support:design:23.2.1'
        //compile project(':external:Smartstream')
        compile 'com.appnexus.opensdk:appnexus-sdk:[2,3)'
        // Audience Network
        compile 'com.facebook.android:audience-network-sdk:4.9.0'
    }

**Comment by WonderCsabo** [comment]
Well, there were two errors in your project:

First, you did not add the AA api dependencies, in common_android_aa.gradle:
```groovy
dependencies {
    apt "org.androidannotations:androidannotations:$project.ext.androidAnnotationsVersion"
    compile "org.androidannotations:androidannotations-api:$project.ext.androidAnnotationsVersion"
    apt "org.androidannotations:rest-spring:$project.ext.androidAnnotationsVersion"
    compile "org.androidannotations:rest-spring-api:$project.ext.androidAnnotationsVersion"
    apt "org.androidannotations:ormlite:$project.ext.androidAnnotationsVersion"
    compile "org.androidannotations:ormlite-api:$project.ext.androidAnnotationsVersion"
}
```

Second, as is said, you must add the `library "true"` option in testlibrary/build.gradle:
```groovy
apt {
    arguments {
        library "true"
    }
}
```

Add these changes and your app will compile.

**Comment by couchcrew-thomas** [comment]
The API dependencies are already added via the file `common_android_aa.gradle`

And as written in the post before, setting or removing `library "true"` does not change anything.
The project compiles fine if I remove the custom application classes. But once the abstract library application class is added it fails.

**Comment by WonderCsabo** [comment]
@couchcrew-thomas no, they are not added, only the processor dependencies are added.

I do not speak without clue, i just did these changes and your project compiled.

**Comment by couchcrew-thomas** [comment]
Sorry about the missing dependencies. I was testing if some of my projects other dependencies might cause the error and the api depencencies got deleted in the process.
You are right about the test projject. After a clean build the test build now success.

My actual project however fails with the same error as before. I've attached the `androidannotations.log` There still seems to be an error caused by the validation of the @EApplication annotation.

[androidannotations.txt](https://github.com/excilys/androidannotations/files/240437/androidannotations.txt)

**Comment by WonderCsabo** [comment]
The problem is that you accidentally annotated a field with `@EApplication`, buy you should use `@App` for that. That problem is completely unrelated to the problem in the test project.

**Comment by couchcrew-thomas** [comment]
I have only 3 occurences of `@EApplication` in my code:

- `@EApplication public class DemoPlayerApplication extends MultiDexApplication`
- `@EApplication abstract public class BaseApplication extends MultiDexApplication`
- `@EApplication public class TALApplication extends BaseApplication`

`@App` is used nowhere because I'm not injecting the application anywhere.

**Comment by WonderCsabo** [comment]
Are you sure? Because the stacktrace clearly says this. Please search for `@EApplication` string in the whole project.

**Comment by couchcrew-thomas** [comment]
Yes I am very sure:

![results](https://cloud.githubusercontent.com/assets/572560/14885335/237575de-0d4b-11e6-8015-4cadeecbf175.PNG)
![search](https://cloud.githubusercontent.com/assets/572560/14885336/238cd698-0d4b-11e6-9867-b7961384e24b.PNG)

**Comment by WonderCsabo** [comment]
That is very strange, because the error clearly says this. Maybe you can share the project privately?

**Comment by couchcrew-thomas** [comment]
I'll ask for permission to share it with you but it will take some time.

In the meantime I've commeded every Annotation from my abstract application class. It how fails during EActivity validation:
[androidannotations.txt](https://github.com/excilys/androidannotations/files/241884/androidannotations.txt)

As written in the related issue: The code compiles fine with `gradle:2.1.0-alpha4` build tools.
The only line I've changed since is the build tools version, which is now `gradle:2.1.0`.
There has to be something gradle does different now.

**Comment by WonderCsabo** [comment]
Hmm, so you are saying gradle 2.1.0 broke it? Can you reproduce it in the test project?

**Comment by couchcrew-thomas** [comment]
The bulid fails with any build tools version above 2.1-alpha4.
I had no success to make the test project build fail, yet.

**Comment by couchcrew-thomas** [comment]
Are there any ways to better debug the compilation from my side?

**Comment by WonderCsabo** [comment]
Not really. :(

**Comment by couchcrew-thomas** [comment]
Ok I'm still trying to find a way to test code parts with the test project so I can tighten the count of classes that maybe cause the error. But this has proven difficult because the project's modules rely on each other a lot.

Sharing the project with you is currently discussed by our executives. Would it eventually be an option to send you a zip to your github profile's e-mail address?

**Comment by WonderCsabo** [comment]
Yep.

**Comment by couchcrew-thomas** [comment]
Great. Thanks for not giving up on me here :)
I'll be back once things have been discussed here.

**Comment by couchcrew-thomas** [comment]
I've just went for hours through each of my java files and found the cause of the build failure:<br>
The annotation `org.antlr.v4.runtime.misc.NotNull;` does not exist in build tools above 2.1-preview4.<br>
So the actual error had nothing to do with androidannotations at all. It just seemed to be according to the logs.

**Comment by dodgex** [comment]
good that you found the issue! :)
