### ISSUE TITLE
After updating to 4.0.0 @Path is mandatory for @Get annotated method

### ISSUE THREAD

**Issue by giannign1** [excilys/androidannotations#1762]

**Comment by dodgex** [comment]
what is your issue with that? (it is [menitoned in the migration guide](https://github.com/excilys/androidannotations/wiki/4.0.0-migration-guide#all-method-params-require-annotation-in-rest-clients))

**Comment by giannign1** [comment]
Sorry i missed that paragraph of the migration guide.

Maybe you can update the wiki (https://github.com/excilys/androidannotations/wiki/Rest-API#path-annotation) and specify that "you MUST annotate your method parameters..." since 4.0.0

Thank you

**Comment by dodgex** [comment]
I'm currently busy with a private project. feel free to fork the repository and update the wiki in your fork. @WonderCsabo will then merge your changes into the official repo wiki. :)

**Comment by giannign1** [comment]
ok thank you
