### ISSUE TITLE
Customise _init behaviour

### ISSUE THREAD

**Issue by lyptt** [excilys/androidannotations#1764]
In my application I've got a configuration slightly out of the norm. I have an activity with a bunch of fragments you can switch between, which I'm managing with a FragmentManager. 

All of my fragments and activities are enhanced, but I'm experiencing an issue due to the nature of how I'm managing fragments. I call `replace` to swap between them, which in turn calls `onCreate` on the fragment even when it already exists. 

This is then handled by EFragment in such a way that it reinitialises all of its dependencies, and one of those happens to be a ListAdapter which I want to preserve.

Is there any way of altering the behaviour of the _init method in that it only initialises the dependencies once? Otherwise if you have any advice on workarounds for this issue that would be greatly appreciated.

**Comment by WonderCsabo** [comment]
You can use singleton for that. It is not a best solution, but AA uses a very simple dependency system, which will not be upgraded.
