### ISSUE TITLE
@RestService not generated

### ISSUE THREAD

**Issue by jonathangerbaud** [excilys/androidannotations#1765]
Hello guys,

I'm facing a weird issue after upgrading from 3.3.2 to 4.0.0. Here is the code :

```
import org.androidannotations.annotations.Bean;
import org.androidannotations.annotations.EBean;
import org.androidannotations.rest.spring.annotations.RestService;
import org.springframework.web.client.RestTemplate;

import fr.lum.... /*other classes */

@EBean
public class RestClientProxy extends AbstractRestClientProxy {

	@RestService
	RestClient restClient;

	@Bean
	LanguageHelper languageHelper;

	@Override
	protected RestTemplate getRestTemplate() {
		return restClient.getRestTemplate();
	}

	public WeatherDTO getMoutainWeather(final Long sourceId) throws RestException {
		return execute(new RestExecutor<WeatherDTO>() {
			@Override
			public ResultDTO<WeatherDTO> execute() {
				return restClient.getMoutainWeather(sourceId);
			}
		}).getData();
	}
}
```

```
import org.androidannotations.rest.spring.annotations.Get;
import org.androidannotations.rest.spring.annotations.Rest;
import org.springframework.web.client.RestTemplate;

import fr.lum.../*other classes*/

@Rest(rootUrl = "serverURL", converters = { CustomJacksonHttpMessageConverter.class })
public interface RestClient {

	@Get("/modulemountainweather/{soucreId}")
	ResultDTO<WeatherDTO> getMoutainWeather(Long soucreId);

	RestTemplate getRestTemplate();

}
```

So this piece of code was working in 3.3.2. In 4.0.0, the RestClient_ class is not generated. So it generates a NullPointerException when I tries to access the restClient field.

At first, I thought that because RestClientProxy was extending an abstract EBean (AbstractClientRestProxy), I could not add some AA beans anymore in version 4.0.0. But then I added LanguageHelper and it is generated in RestClientProxy_, but not RestClient.

So I've spend several hours, trying everything coming into mind :

- Trying AA 4.0.0, 4.0-SNAPSHOT, 4.1.0
- Getting back to Spring 1.0.1
- Moving the RestService into another class
- ...

I've read multiple times the documentation, the breaking changes, the migration guide but so far, nothing useful. I'm sure I've missed something but what ? I can't tell.

This is the code that was generated in RestClientProxy_ with 3.3.2 :

```
private void init_() {
        this.baseHttpRequestFactory = BaseHttpRequestFactory_.getInstance_(this.context_);
        this.commonHeadersInterceptor = CommonHeadersInterceptor_.getInstance_(this.context_);
        this.restClient = new RestClient_(this.context_);
        this.context = this.context_;
        this.configureRestClient();
    }
```

And now, with 4.0.0

```
private void init_() {
        this.commonHeadersInterceptor = CommonHeadersInterceptor_.getInstance_(context_);
        this.baseHttpRequestFactory = BaseHttpRequestFactory_.getInstance_(context_);
        this.context = context_;
        configureRestClient();
    }
```

As you can see there is one line missing.

If you have any ideas what to do to fix this issue, I'm all ears open.

**Comment by dodgex** [comment]
You should check out the Migration guide in the wiki. There you'll see that for Rest api you need another dependency due to the new plugin system. Cant post you the link as i'm on mobile

**Comment by jonathangerbaud** [comment]
I've already added the new dependencies (I don't think it would compile otherwise) :

```
 compile "org.androidannotations:rest-spring-api:4.0.0"
 apt "org.androidannotations:rest-spring:4.0.0"
```

**Comment by dodgex** [comment]
Yeah, you are right. I'm sorry. Most of similar  issue reports are due to wrong or missing dependencies. 

I'm not using the Rest api myself so i'm not farmilar with it. Can you reproduce this issue in a small test project?

**Comment by jonathangerbaud** [comment]
I'll try to do that.

**Comment by sperochon** [comment]
Got the same here...

**Comment by jonathangerbaud** [comment]
Unfortunately in my case, I haven't succeeded to reproduce the issue in a test project.

Still haven't found out why it doesn't work on my real project, and have given up the idea of migrating to 4.0.0.

**Comment by sperochon** [comment]
Like you a small test project works fine. I'll try to make my project smaller and keeps the bug...
But no need to wait a new AA release! :-) Here is a workaround that works for me:

  @RestService
  MyRestClient myRestClient;

  @AfterInject
  void afterInject() {
    myRestClient = new MyRestClient_(this);
  }

**Comment by sperochon** [comment]
Here is a minimal project (app+lib) that reproduces the bug.

The init_ method of the generated file:
testRestService/myApp/build/generated/source/apt/debug/com/example/MainActivity_.java

    private void init_(Bundle savedInstanceState) {
        this.myErrorHandler = ClientErrorHandler_.getInstance_(this);
        afterInject();
    }

Should be:

    private void init_(Bundle savedInstanceState) {
        this.myErrorHandler = ClientErrorHandler_.getInstance_(this);
        this.myRestClient = new MyRestClient_(this);
        afterInject();
    }

[testRestService.zip](https://github.com/excilys/androidannotations/files/258708/testRestService.zip)

Thanks.

**Comment by dodgex** [comment]
@sperochon you are missing the rest plugin in your `myApp/build.gradle`
```
    apt "org.androidannotations:rest-spring:$AAVersion"
    compile "org.androidannotations:rest-spring-api:$AAVersion"
```

in `myLib` it is required to generate the `MyRestClient_` class
and in `myApp` it is required to do the injection.

@jonathangerbaud can you check if you have a similar case (app + lib)?

**Comment by jonathangerbaud** [comment]
I have the dependencies in both apps and test project

**Comment by sperochon** [comment]
@dodgex thanks a lot! works well!

**Comment by dodgex** [comment]
@jonathangerbaud as i assume you are not allowed to share the project that i can check if i find the error... could you give some more information on your configuration? do you have multiple modules (e.g. app + lib) and where is the activity and where the rest interface. maybe the build files for those modules? best chance for easy help would be the project or a striped down project that can reproduce the issue similar to the one @sperochon provided.


@sperochon i'm glad i could help you :)

**Comment by WonderCsabo** [comment]
@jonathangerbaud please double check. The symptoms indicate that you do not have the REST processor somewhere,  or it is not called for some reason.

**Comment by jonathangerbaud** [comment]
I've checked many times. Anyway, I've already rolled back to 3.3.2 and the migration to 4.0.0 will wait for a few months now (project management decisions...)

**Comment by WonderCsabo** [comment]
Sorry to hear that.

**Comment by mayankzen123** [comment]
Got the same here I solved it by using like this

    annotationProcessor "org.androidannotations:androidannotations:$AASnapshotVersion"
    compile "org.androidannotations:androidannotations-api:$AASnapshotVersion"
    annotationProcessor "org.androidannotations:rest-spring:$AASnapshotVersion"
    compile "org.androidannotations:rest-spring-api:$AASnapshotVersion"

Hope this will help you :-)
