### ISSUE TITLE
in 4.0.0 @Rest annotations not provide converters ? 

### ISSUE THREAD

**Issue by mrljdx** [excilys/androidannotations#1766]
when i update androidannotations to version 4.0.0 found that there is no available converters such as **FormHttpMessageConverter.class** and **StringHttpMessageConverter.class** ， how to get the converters ?

**Comment by WonderCsabo** [comment]
This did not change with AA 4.0.0, it was always the situation. You have to add the REST Spring Android Rest Template dependency as well.
