### ISSUE TITLE
FileResource is missing

### ISSUE THREAD

**Issue by webexpert4rv** [excilys/androidannotations#1769]
FileResource class is missing for @Part annotation. Please let me know which library or dependency I have to add to access this class.

Thanks,

**Comment by WonderCsabo** [comment]
Spring Android REST Template provides that class of course. You may have to
use the 2.0 version, but I think it was available in 1.0 as well.

**Comment by webexpert4rv** [comment]
@WonderCsabo, Thanks for your quick response!
I am using following versions:-
def AAVersion = '4.0.0'
    compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
    apt "org.androidannotations:rest-spring:$AAVersion"
    compile "org.androidannotations:rest-spring-api:$AAVersion"

But it is not there :(
Could you please let me know complete name(with package) of this class ?

**Comment by WonderCsabo** [comment]
Sorry, the correct name is `org.springframework.core.io.FileSystemResource` . I will update the wiki.

**Comment by webexpert4rv** [comment]
@WonderCsabo I am using FileSystemResource currently, but getting error :(

Could you please provide an example with form fields and image file, how to write function with both @Body and @Part annotation. So that I can request to server with form fields and image (e.g. User Register).
