### ISSUE TITLE
AA Plugins: Generating file with custom name

### ISSUE THREAD

**Issue by chpasha** [excilys/androidannotations#1770]
Hi, I would like to be able to generate files with custom names or at least custom suffixes but defined per class, not for the whole module (I'm aware of classSuffix option). The question is
1) is it possible now in any (maybe unorthodox) way?
2) is it thinkable to implement such a feature for plugin system or AA core (I know, every single AA-Anotation will possibly have to have a new parameter since they cannot be inherited, so I guess the answer is "no")
I think it would be cool for the code quality to be able to choose a generated class name per class

For now I'm just generating a new file inside my custom annotation handler but the aa-generated classes  would still stick around (not a huge problem but anyway)

**Comment by chpasha** [comment]
ok, I found how to get rid of AA-generated classes, just need call generatedClass.hide() in Handler :)

**Comment by WonderCsabo** [comment]
Sorry, but this is not something we would like to support. AA plugins should fit into the AA conventions.
