### ISSUE TITLE
@RestService can be  created   before  @Bean setMyErrorHandler()  

### ISSUE THREAD

**Issue by han361769045** [excilys/androidannotations#1776]
![image](https://cloud.githubusercontent.com/assets/8857329/15451798/4abf0f9a-2008-11e6-82a5-b401c914d3b2.png)

![image](https://cloud.githubusercontent.com/assets/8857329/15451805/5dac9f0a-2008-11e6-9bb4-c6a8ef1f47bf.png)

**Comment by dodgex** [comment]
not sure if i undersand your issue correctly. you want that your RestClient is created before the setMyErrorHandler is called? this is not possible as the core annotations are processed before those provided by plugins. (`@RestService` is a plug in annotation)

**Comment by WonderCsabo** [comment]
Yes, this is not possible. But you should always touch the injected things first in an `@AfterInject` annotated method:
```java
@RestService
MyRestClient client;

@Bean
MyErrorHandler errorHandler;

@AfterInject
void afterInject() {
  client.setRestErrorHandler(errorHandler);
}
```

**Comment by han361769045** [comment]
Thanks
