### ISSUE TITLE
@SharedPref can not   use  UTF-8

### ISSUE THREAD

**Issue by han361769045** [excilys/androidannotations#1777]
@SharedPref(value = SharedPref.Scope.UNIQUE)
public interface MyPrefs {
    /**
     * 注释
     * @return
     */
    @DefaultString("")
    String token();

    @DefaultString("测试")
    String test();
}

public final class MyPrefs_
    extends SharedPreferencesHelper
{

    public MyPrefs_(Context context) {
        super(context.getSharedPreferences("MyPrefs", 0));
    }

    public MyPrefs_.MyPrefsEditor_ edit() {
        return new MyPrefs_.MyPrefsEditor_(getSharedPreferences());
    }

    /**
     * <p><b>Defaults to</b>: </p>
     * ע��
     *  @return
     * 
     */
    public StringPrefField token() {
        return stringField("token", "");
    }

    /**
     * <p><b>Defaults to</b>: ����</p>
     * 
     * 
     */
    public StringPrefField test() {
        return stringField("test", "\u6d4b\u8bd5");
    }

    public final static class MyPrefsEditor_
        extends EditorHelper<MyPrefs_.MyPrefsEditor_>
    {

        MyPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        /**
         * ע��
         *  @return
         * 
         */
        public StringPrefEditorField<MyPrefs_.MyPrefsEditor_> token() {
            return stringField("token");
        }

        public StringPrefEditorField<MyPrefs_.MyPrefsEditor_> test() {
            return stringField("test");
        }
    }
}

**Comment by han361769045** [comment]
error:
![image](https://cloud.githubusercontent.com/assets/8857329/15451843/a1eece08-2009-11e6-8e4a-464836e8052b.png)

**Comment by dodgex** [comment]
Duplicate of already implemented issue #1746. The fix will be released with a future version

**Comment by han361769045** [comment]
Thanks  ！
