### ISSUE TITLE
how to getAdapterPosition in RecyclerView ViewHolder

### ISSUE THREAD

**Issue by saikiranpsq** [excilys/androidannotations#1780]
how to getAdapterPosition in RecyclerView ViewHolder? http://stackoverflow.com/questions/37384089/how-to-getadapterposition-in-recyclerview-viewholder-with-android-annotations

**Comment by WonderCsabo** [comment]
Sorry but this question is not related to AndroidAnnotations, and not in topic of a bug tracker anyway.
