### ISSUE TITLE
When building app, verify validity of annotations before cleaning all generated code

### ISSUE THREAD

**Issue by AntekM** [excilys/androidannotations#1781]
Currently AA will delete all generated files and then will validate if annotations were used correctly (eg. if you don't place them on private method etc.) - so if there's any error compiler will return lots of errors ("can's find class XXX_") - in bigger project it can be dozens. This makes the actual error very hard to find. 

Is it possible to validate correctness of using AA before old classes get deleted? Or at least add another phase (like prevalidation) if those classes need to be deleted to validate them fully?

**Comment by WonderCsabo** [comment]
We do not delete anything, this is coming from the Java compiler, it does not see the old generated classes if they are supposed to be re-generated.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.
