### ISSUE TITLE
Robust handling for onResume/onPause broadcast handlers

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1787]
Given I have code like this in an `Activity`:
``` java
@Receiver(actions = {Intent.ACTION_LOCALE_CHANGED},
    registerAt = Receiver.RegisterAt.OnResumeOnPause)
protected final void localeChanged() {
}
```

Then AA generates code like this:

``` java
private final IntentFilter intentFilter1_ = new IntentFilter();
private final BroadcastReceiver localeChangedReceiver_ = new BroadcastReceiver() {

    public void onReceive(Context context, Intent intent) {
        HomeActivity_.this.localeChanged();
    }
}
;

private void init_(Bundle savedInstanceState) {
    intentFilter1_.addAction("android.intent.action.LOCALE_CHANGED");
}


@Override
public void onResume() {
    super.onResume();
    this.registerReceiver(localeChangedReceiver_, intentFilter1_);
}

@Override
public void onPause() {
    this.unregisterReceiver(localeChangedReceiver_);
    super.onPause();
}
```

So far, so good.
However, there seem to be errors/ conditions where onResume or onPause are unequally called, or perhaps during state restore etc, which leads to `RuntimeException` like this:

```
Fatal Exception: java.lang.RuntimeException
Unable to pause activity {com.company/com.company.HomeActivity_}: java.lang.IllegalArgumentException: Receiver not registered: com.company.HomeActivity_$1@12810058
```

Should AA add some further checks and cleanup routines to prevent this issue (it might be a Android implementors or related error source)? For example, the receivers could be created and setup in `onResume`, while the `onPause` method would set them to `null` after unregistering.

**Comment by WonderCsabo** [comment]
I am not sure we want to fix this. Actually i am using this extensively in my app, and everything is working fine. `onResume` and `onPause` should be called in pairs.

**Comment by ened** [comment]
OK. Will re-open if ever reproducible.
