### ISSUE TITLE
A bug with "ViewsById"

### ISSUE THREAD

**Issue by 793383996** [excilys/androidannotations#1788]
Hi I'm Zhenyu.
use version 3.3.2
 apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"

When I was in use Found by index for changes in order

Before
   ![image](https://cloud.githubusercontent.com/assets/9602218/15737806/ae65313e-28da-11e6-83a0-3c40949c7947.png)
Use
![image](https://cloud.githubusercontent.com/assets/9602218/15737832/c9424e10-28da-11e6-9ecc-75a7e6c9af29.png)
 
PIC
![image](https://cloud.githubusercontent.com/assets/9602218/15737826/c3025aea-28da-11e6-91a6-bae5168fb0e7.png)

There are some models will appear index is not correct.
Simulator and mi phone the performance is not the same as above.
I suspect that is more than five or more order will appear inconsistent problem, lead to obtain control index of different position.

When I was in the test found that the amount and the order of control index shows the other values, before I use 'annotations are normal.

After:
![image](https://cloud.githubusercontent.com/assets/9602218/15738525/4fa0a86e-28de-11e6-8925-64d21fedbf83.png)

  
use
       The same

That's ok:
![image](https://cloud.githubusercontent.com/assets/9602218/15738026/dafba5a6-28db-11e6-861f-8160ab2f4809.png)

My Email:
scarecrow_wzy@163.com

**Comment by 793383996** [comment]
userTextView=new ArrayList<>();
        userTextView.add((TextView) find(R.id.txtusername));
        userTextView.add((TextView) find(R.id.txtphone));
        userTextView.add((TextView) find(R.id.txtaddress));
        userTextView.add((TextView) find(R.id.txtnote));

**Comment by WonderCsabo** [comment]
I just checked the generator code, and the order is correct. Please provide a self-contained example project, where the issue can be reproduced.

Moreover, if you are handling the views separately like you do in `loadAddresses`, you should inject the views into separate fields with `@ViewById`.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.
