### ISSUE TITLE
Is there any test case like googlesample/to-do-mvp

### ISSUE THREAD

**Issue by mrljdx** [excilys/androidannotations#1789]
Recently in the use of AndroidAnnotations structures, the structure of the MVP development framework requires a similar to Google's test cases, but it seems difficult to achieve.Anyone can write a test case according to AndroidAnnotaitons, like Google.
Url：[todo-mvp](https://github.com/googlesamples/android-architecture/tree/todo-mvp/)
Needing Test case : JUnit、Mockito、Espresso
@WonderCsabo  i just search the stackoverflow , cann't solve the test problem above. 
can androidannotaitons provide some test samples ?
best regards~

**Comment by WonderCsabo** [comment]
AndroidAnnotations is not an MPV framework, and it does not enforces any coding structure for the application. You can do anything you would do without using AA. Hence, such a test application sample is not really needed. You can read about testing [here](https://github.com/excilys/androidannotations/wiki/Unit-test-your-application), though, and you could also check out the functional tests in the AndroidAnnotations project itself.

**Comment by mrljdx** [comment]
thanks
