### ISSUE TITLE
Does using AA increase the size of the app?

### ISSUE THREAD

**Issue by rohitshampur** [excilys/androidannotations#1790]

**Comment by dodgex** [comment]
From the Wiki:
> AndroidAnnotations provide those good things and even more for less than 150kb, without any runtime [perf impact](https://github.com/excilys/androidannotations/wiki/FAQ#wiki-perf-impact)!

Yes it slightly increases your app. The runtime JAR is less than 150kb in size (last time i checked was right before 4.0.0 release) and some classes are generated. all in all i think those few additional kb that AA brings are worth the code you do not have to write yourself.

**Comment by rohitshampur** [comment]
Thank you for the clarification
