### ISSUE TITLE
@EViewGroup w/o ressource name + @ViewById - no error message

### ISSUE THREAD

**Issue by HermannK** [excilys/androidannotations#1792]
Hello team,

We made the mistake of annotating a class named AbcView this way:

@EViewGroup
public class AbcView extends LinearLayout

The resource file was R.layout.abc_view. Naturally, AA cannot link to the resource because of the difference in names. 
While I understand that it may be reasonable annotating a view class with @EViewGroup without having an XML file at all (Reason could be that the views will be generated programmatically), I do not understand the following: 

We did inject some views using 
@ViewById
TextView someTextView; 

Consequentially the views couldn't be injected and remained null. However, we did not see any error. The app was build properly. Again, I do understand that AA is tolerant if @EViewGroup does not refer to a layout and does not find any matching layout resource but in that case @ViewById should raise some error.

For our project the issue is fixed. We found our mistake and added (R.layout.abc_view) and everything works fine now. However, I do see some improvement potential here. 

Kind regards
Hermann

**Comment by dodgex** [comment]
when you are not providing a resource to `@EViewGroup` we assume you are handling the layout inflation yourself -> no error when there is no layout given

and `@ViewById` can not check on compile time if a view would be available at runtime. we check if a view with the given id exists *somehwere* in *any* of your layouts (-> it is available in `R`) but we can not check if you have inflated an layout with the given view.

that means: we can't do anything more that we do right now.

**Comment by WonderCsabo** [comment]
Thanks @dodgex for the explanation!
