### ISSUE TITLE
Cannot resovle symbol

### ISSUE THREAD

**Issue by 89lovelc** [excilys/androidannotations#1793]
cannot resovle sysmbol
` java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference`

`  public abstract Object getSystemService(@ServiceName @NonNull String name);`
this cannot resovle sysmbol tag

**Comment by WonderCsabo** [comment]
I do not understand this issue. Cannot resolve symbol is a runtime error, but cannot resolve symbol is compile time. Please add much more detail per the contribution guide.

**Comment by 89lovelc** [comment]
sorry  it is my mistake.

**Comment by WonderCsabo** [comment]
No problem.
