### ISSUE TITLE
Parceler issue

### ISSUE THREAD

**Issue by Allsimon** [excilys/androidannotations#1796]
If you use the `@ParcelClass(Foo.class)` annotation Parceler on an annotated `@EApplication` or  `@EActivity` the build will fail with `Attempt to recreate a file for type com.example.Foo$$Parcelable` (see issue  johncarl81/parceler#184) 

The issue here is that AndroidAnnotations copy the `@ParcelClass(Foo.class)`: Parceler's annotation processor will find 2 copy of this annotation and fail

A quick work-around is to put this annotation on a class not annotated by AA

**Comment by WonderCsabo** [comment]
The problem here is that we could exclude `ParcelClass` from copying, however it is not trivial because it is done in the framework, not in the core AA plugin.

Is adding the workaround in the FAQ a good solution for you?

**Comment by johncarl81** [comment]
@WonderCsabo, I'm going to fix this on Parcler directly.  The fix is to avoid processing classes identified by the `@ParcelClass` more than once.  I prefer that we don't have a special case for Parceler :wink: 

See: https://github.com/johncarl81/parceler/pull/208

**Comment by WonderCsabo** [comment]
Great, thanks @johncarl81 !
