### ISSUE TITLE
@SystemService FingerprintManager not compiling

### ISSUE THREAD

**Issue by nishal** [excilys/androidannotations#1797]
Using Android Studio with Gradle and get this error when I try to @SystemService inject the FingerprintManager service.

Error:(18, 5) error: Unknown service type: android.hardware.fingerprint.FingerprintManager
Warning:(19, 24) Element fingerprintManager invalidated by SystemServiceHandler

Any help appreciated. TIA

**Comment by dodgex** [comment]
currently `@SystemService` does not support the FingerprintManager. you have to use [`getSystemService()`](https://developer.android.com/reference/android/content/Context.html#getSystemService(java.lang.String)) directly

**Comment by WonderCsabo** [comment]
@nishal API 23 services are not added, yet, but i will add them shorty.

**Comment by WonderCsabo** [comment]
Actually it is a bug, too, we define `android.service.fingerprint.FingerprintManager` instead of `android.hardware.fingerprint.FingerprintManager`.

**Comment by WonderCsabo** [comment]
The bug is due to renaming the hidden service class and exposing it under a new package in API 23 (we supported the old one as a hidden service). The same happened with `NetworkStatsManager`.
