### ISSUE TITLE
Is this framework compatible with Instant run?

### ISSUE THREAD

**Issue by cbriseno** [excilys/androidannotations#1798]
Hi, I really love this framework but, I was wondering if this is compatible with the instant run feature of Android Studio, I mean, should we choose to only one of these tools for our projects?

**Comment by WonderCsabo** [comment]
This is a standard annotation processor, just like Dagger, ButterKnife, FragmentArgs, Parceler, etc. Basically there is nothing special for instant run, you can use it just like without AA.

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).
