### ISSUE TITLE
androidannotations does not support startActivityforResult from fragment & get callback in fragment directly

### ISSUE THREAD

**Issue by chow890115** [excilys/androidannotations#1802]
Hi Team:
when androidannotation applied in my app, i found that when declare in a fragment like this :XXXActivity_.intent(getActivity()).startForResult(requestCode), i get callback in the activity which the fragment belong to, but this is not what i really want. I'd like to get callback in the fragment itself,just like the function  XXXFragment.startActivityForResult(requestCode) provided by Android system.Hope u can fix it ASAP.

**Comment by WonderCsabo** [comment]
You are using it wrong, you should call like this in the `Fragment`:
```java
XXActivity_.intent(this).startForResult(requestCode)
```
Where `this` is the `Fragment` itself.

**Comment by chow890115** [comment]
I really appreciate for your help ^^

**Comment by chow890115** [comment]
Thanks a lot ^^
