### ISSUE TITLE
Could not identify launch activity: Default Activity not found!

### ISSUE THREAD

**Issue by FDoubleman** [excilys/androidannotations#1804]
HI ;
    when i use androidAnnotantion ,I usually get like this issue ：
![image](https://cloud.githubusercontent.com/assets/16278122/16174801/10869d24-3607-11e6-8f10-73c9e054508b.png)

   i   also clisk this butten:
![image](https://cloud.githubusercontent.com/assets/16278122/16174802/21ccdd28-3607-11e6-82e1-25d60c23f083.png)

but MainActivity_ text colos is red.

![image](https://cloud.githubusercontent.com/assets/16278122/16174807/6aab0768-3607-11e6-9155-3188b9bcbfdf.png)

how fix this issue ?  thanks .

**Comment by WonderCsabo** [comment]
You should hit the `Make` button first. It is the ones and zeros with the little green arrow pointing downwards, next to the launch configuration selector (app). This will compile the project and generate the AA generated classes, such as your `Activity`. After it you can run the project.
