### ISSUE TITLE
Background annotated method with serial run in parallel 

### ISSUE THREAD

**Issue by LouisCAD** [excilys/androidannotations#1806]
Hi,

I am using the `@Background` annotation in an app to perform network requests. I added a `serial` in the annotation parameters, but my backend developer and me discovered that multiple requests are made at once.

I then discovered that this part of the doc:

> If you want execute some background methods **SEQUENTIALLY**, you should simply use `serial()` field. All task with the same serial key will be executed sequentially.

is not respected. Any running `@Backround` annotated method will make them run in **PARALLEL**.

I made sample, which didn't reproduce the issue at first. I then added another background job, and I saw tasks with same serial starting concurrently from the logs.

[Here's the sample](https://drive.google.com/open?id=0B59c-Qkht7tYcG1GS0wwZ3RrUFE)

You can look at `MainActivity.class` where there's a dummy Background job, which disturbs the one in `MyBean.class` which is started as soon as you press the pink Floating Action Button.

The implementation is absolutely straightforward, and the short  classes I quoted are the only classes that matters.

Expected output:

```shell
Hello from 1282!
Goodbye from 1282!
Hello from 1279!
Goodbye from 1279!
Hello from 1279!
Goodbye from 1279!
Hello from 1279!
Goodbye from 1279!
Hello from 1278!
Goodbye from 1278!
Hello from 1281!
Goodbye from 1281!
Hello from 1277!
Goodbye from 1277!
Hello from 1274!
Goodbye from 1274!
Hello from 1283!
Goodbye from 1283!
Hello from 1280!
Goodbye from 1280!
```

Actual output:

```shell
Hello from 1314!
Hello from 1307!
Hello from 1315!
Hello from 1311!
Hello from 1316!
Hello from 1313!
Hello from 1317!
Hello from 1312!
Goodbye from 1314!
Goodbye from 1307!
Goodbye from 1315!
Goodbye from 1316!
Goodbye from 1313!
Goodbye from 1317!
Goodbye from 1311!
Hello from 1307!
Hello from 1315!
Goodbye from 1312!
Goodbye from 1315!
Goodbye from 1307!
```

**Comment by WonderCsabo** [comment]
Duplicated of #1775 ?

**Comment by LouisCAD** [comment]
It seems! I'm sorry... I'm moving this to #1775
