### ISSUE TITLE
@OptionsItem isn't called when actionLayout is set for menu item.

### ISSUE THREAD

**Issue by shushant** [excilys/androidannotations#1808]
Here is my code

 ```
@OptionsItem(R.id.gotocart)
    void cart() {
      // open activity
    }
```
and layout is
```
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item         android:id="@+id/gotocart"         android:showAsAction="always"
        android:actionLayout="@layout/action_cart_badge"
 />
</menu>
```
But when i remove actionLayout it works fine.

**Comment by dodgex** [comment]
Could you please provide auch small sample project?

**Comment by shushant** [comment]
Of course here is the sample project https://drive.google.com/file/d/0BxIV7n6X2xeeLUZZTGItTG9IVEE/view?usp=docslist_api

**Comment by WonderCsabo** [comment]
This is because `onOptionsItemSelected()` is not called in this case. You have to [add the listener](http://stackoverflow.com/a/11628492/747412) yourself if you use an action layout. This is not AA specific.

**Comment by vancentvan** [comment]
Is there anyone who can heIp me? I have just imported projects ActionBarShelock, libsuperuser and AwitchCompatLibrary, copy and paste commons-lite-1.14.jar and volley.jar to libs. No error was shown. But when I run the full project, "Could not find DroidPHP.apk!" Are there any packages I have lost in it? Thanks...
