### ISSUE TITLE
Failed to try to build the example/gradle

### ISSUE THREAD

**Issue by pieterguo** [excilys/androidannotations#1809]
There are two errors ,  It's appreciate that any suggestion.
```
`error: Could not find the AndroidManifest.xml file `
:compileDebugJavaWithJavac FAILED
```
Here is total logs.
```

processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:compileDebugJavaWithJavac
Note: Resolve log file to /home/guoping/Downloads/androidannotations/examples/gradle/build/generated/source/apt/androidannotations.log
Note: Initialize AndroidAnnotations 3.2 with options {}
Note: Start processing for 18 annotations on 5 elements
error: Could not find the AndroidManifest.xml file, going up from path [/home/guoping/Downloads/androidannotations/examples/gradle/build/generated/source/apt/debug] found using dummy file [] (max atempts: file:///home/guoping/Downloads/androidannotations/examples/gradle/build/generated/source/apt/debug/dummy1466735142041)
Note: Time measurements: [Whole Processing = 8 ms], [Extract Annotations = 5 ms], [Extract Manifest = 1 ms], 
Note: Finish processing
Note: Start processing for 0 annotations on 0 elements
Note: Time measurements: [Whole Processing = 1 ms], 
Note: Finish processing
1 error
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.521 secs

```

**Comment by pieterguo** [comment]
BTW the base code is the develop branch. 
`git clone https://github.com/excilys/androidannotations.git`

**Comment by WonderCsabo** [comment]
You have to use AA `4.0.0` for this, which can automatically infer the manifest path. You are still using AA version `3.2` .

**Comment by pieterguo** [comment]
I don't find the way to get AA 4.0.0 release from wiki.  So I changed the SNAPSHOT version.
Would you tell me how to get that?  I have read the Get Start doc , and don't find it .

**Comment by WonderCsabo** [comment]
https://github.com/excilys/androidannotations/wiki/ReleaseNotes#4.0.0

"Releases are available via Maven or Gradle."

**Comment by pieterguo** [comment]
What I need is the library jar files.  Sorry I am newer about it.

**Comment by WonderCsabo** [comment]
We no longer support the bundled jars. You should use Gradle or Maven.
However you can download the [jars](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.androidannotations%22%20AND%20v%3A%224.0.0%22) yourself from Maven Central. You will also need [this jar](http://search.maven.org/remotecontent?filepath=com/helger/jcodemodel/2.8.0/jcodemodel-2.8.0.jar) in the annotation processor path.

However i strongly suggest to use a dependency management system, so you do not have to add those deps manually.

**Comment by pieterguo** [comment]
got it. thanks very much.
