### ISSUE TITLE
How to apply xml properties to the <merge> tag of a EViewGroup

### ISSUE THREAD

**Issue by martinbonnin** [excilys/androidannotations#1811]
I'm using this patter a lot where I would like to apply xml properties to the root `<merge>` node od a EViewGroup.

    <?xml version="1.0" encoding="utf-8"?>
    <merge xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="fill_parent"
        android:foreground="?android:attr/selectableItemBackground"
        android:layout_height="wrap_content">

In that case, the `foreground` attribute will not be applied. I can still do it programmatically but it's a bit painful. I was just wondering if anyone had a better way to handle this.

**Comment by WonderCsabo** [comment]
There is no way to add properties to `<merge>`, you have to do it programatically, it is a plain Android thing.

**Comment by truefedex** [comment]
@martinbonnin  if you just want to see how it will look like in android studio design editor then use tools namespace for merge layout like this:
    tools:parentTag="android.widget.LinearLayout"
    tools:orientation="horizontal"
