### ISSUE TITLE
Overwriting a super method in AfterViews creates double method calls in generated code

### ISSUE THREAD

**Issue by grenzfrequence** [excilys/androidannotations#1812]
Buggy generated code:

```
public class SearchResultFragment_ extends SearchResultFragment implements HasViews, OnViewChangedListener {
   ...
   @Override
   public void onViewChanged(HasViews hasViews) {
   ... 
   initViews();
   initViews();
   }
}
```

initViews()  is called here two times.

This is the code what creates this bug:

```
@EFragment
public abstract class SearchResultBaseFragment {
...
    @AfterViews
    protected void initViews() {
       ...
    }
...
} // class

@EFragment(R.layout.search_result_fragment)
public class SearchResultFragment extends SearchResultBaseFragment {
...
    @AfterViews
    protected void initViews() {
       ...
       ...
       super.initViews();
   }

} // class
```

Method what overwrites super method is called two times in generated androidannotation code. This bug is not easy to find out. Therefore it should be fixed.

**Comment by WonderCsabo** [comment]
I think this is [documented in the wiki](https://github.com/excilys/androidannotations/wiki/Injecting-Views#warning). You can also find the [solution](https://github.com/excilys/androidannotations/issues/810#issuecomment-31218529) linked there.

**Comment by grenzfrequence** [comment]
Hey, thanks a lot. I will now remove @AfterViews from base class and call that method from inheritating class. I think that is the most safe solution. Or do you have another proposal?

**Comment by WonderCsabo** [comment]
You should just remove the `@AfterViews` annotation from the method on the child class! As you can see in the example i linked.
