### ISSUE TITLE
send and Receive intents

### ISSUE THREAD

**Issue by nawinkhatiwada** [excilys/androidannotations#1813]
how do i send data in intent and receive in another activity using annotation: For example; i want to replace the following;

Intent intent = new Intent(ctx,RegisterActivity.class);
intent.putExtra("key",username);
startActivity(intent);

and after that i want to receive the intent in next Activity. That is RegisterActivity. Is there any way to do using Annotation?

**Comment by dodgex** [comment]
hav you read the [wiki](https://github.com/excilys/androidannotations/wiki/HowItWorks#starting-an-annotated-activity)?
