### ISSUE TITLE
cancel @UIThread annotated methods in onPause

### ISSUE THREAD

**Issue by szijpeter** [excilys/androidannotations#1814]
Hi,

So for a long time I was under the wrong impression, that in a @UIThread annotated method it's safe to use @ViewById annotated fields. But recently I have found out, that in a pretty usual scenario like getting some data on a background thread and displaying them on a uithread can easily lead to NPE-s if for example the user navigates to another screen before the background thread gets to the point of calling the @UIThread annotated method. 
Of course there are a couple of ways around the problem, like checking in every @UIThread call whether the caller isAdded (at least in case of Fragments), but obviously it isn't a real solution. Another approach would be to create a parent to all of your Fragments like this:

```
public abstract class BaseFragment extends Fragment {

    protected String TAG = "";

    protected abstract void setTAG();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTAG();
    }

    @Override
    public void onPause() {
        super.onPause();
        UiThreadExecutor.cancelAll(TAG);
    }
}

@EFragment(R.layout.fragment_child)
public class ChildFragment extends BaseFragment {

    protected final String TAG = "ChildFragment";

    @Override
    protected void setTAG() {
        super.TAG = this.TAG;
    }

    @UiThread(id = TAG)
    protected void doSomeThingOnTheUIThread() {
        ...
    }
}
```
Well, at least that's the most elegant way I could come up with, but I am open to any better ideas :)
Still in this case, there is code duplication because you have to implement setTAG() in every fragment exactly the same way.

Anyway, I would like check if you think it would be a good idea to modify some annotation (namely @EActivity and @EFragment) to cancel every @UIThread calls **added by the caller** in the generated classes onPause()? Or do you have any other solution to this problem? Maybe I am doing something fundamentally wrong :D

Thanks for the feedback!

**Comment by dodgex** [comment]
first of all. i think it would not make sense to cancel those invocations as they would have to be called with delay to be cancelable and as you said you are doing background work to get a result and then call the `@UiThread` method. so when `onPause` is called and the network request is still going on you would not be able to cancel the ui thread method as it has not been called yet.


BUT... i think there is an easy fix (at least for fragments): you can use [`@IgnoreWhen`](https://github.com/excilys/androidannotations/wiki/IgnoredWhenDetached#ignorewhen) on your method.

**Comment by szijpeter** [comment]
Nice, exactly what I was looking for :) Somehow I missed it... Thank you for the quick reply!

**Comment by dodgex** [comment]
No problem, could you close the issue then=?

**Comment by szijpeter** [comment]
yeah, thanks again. next time I try to read the documentation more carefully :)
