### ISSUE TITLE
Could you add Retrofit and RxJava support?

### ISSUE THREAD

**Issue by JackRo** [excilys/androidannotations#1816]
Thanks to you for providing to us the  powerful and great annotations library. But lately, in android development , the Retrofit and RxJava is very popular, could you add Retrofit and RxJava support?

**Comment by dodgex** [comment]
can you elaborate what exactly you want to see in AA?

**Comment by JackRo** [comment]
Sorry, but I want to see the http request can use the Retrofit and can support RxJava, so we can use RxJava and Retrofit to operate our http request.

**Comment by dodgex** [comment]
I think for using Retrofit you wont need a special AA support as Retrofit is already easy to use (in comparision to Spring-Rest).

and about RxJava i think this is something that Retrofit has to support in this case. not sure if it does?

could you post some (pseudo-)code how you would like to work with this feature? how you would like your code to look when AA would have implemented this feature request?

**Comment by WonderCsabo** [comment]
Retrofit support does not make sense, as we have the same solution with the REST annotations.
RxJava support would be great.

**Comment by JackRo** [comment]
But Retrofit is base on the okhttp, I feel the okhttp will work better.

**Comment by WonderCsabo** [comment]
But how we should support Retrofit? It does not need any support, it already works.

**Comment by JackRo** [comment]
Well, i also think it works great. I'm sorry to say that maybe i don't understand the AA code how to work, so when i have free time, i will review your AA source code and then show you my thoughts that how to support Retrofit.

**Comment by mmotorniy** [comment]
@JackRo AndroidAnnotations really works good with Retrofit 2.0+ and RxJava.

**Comment by mdumrauf** [comment]
@WonderCsabo based on @JackRo comment, maybe you can provide a way to change the strategy on which is the underlying HTTP library (okhttp in this case).

**Comment by WonderCsabo** [comment]
You can easily use okhttp with our rest client. Just change the Spring REST template version to the latest milestone of 2.0 and set the request factory in your @Rest annotation to okhttp request factory.

**Comment by JackRo** [comment]
@WonderCsabo OK, I try to do it

**Comment by WonderCsabo** [comment]
Closed in favor of #1842.
