### ISSUE TITLE
Could you add ExpirableDiskLruCache support?

### ISSUE THREAD

**Issue by sytolk** [excilys/androidannotations#1817]
Thanks for the great Android annotations library. I use this library wrapper for DiskLruCache
https://github.com/vijayrawatsan/ExpirableDiskLruCache
I think that it can be easy done cache annotations for example like spring with EhCace in Java.
```java
@Cacheable(value = "getAdBlock", key = "{#root.methodName,#adBlocksId,#companiesId}", unless = "#result == null")
public List<Ads> getAdBlock(Integer adBlocksId, List<Integer> companiesId) {

}

@Caching(evict = {@CacheEvict(value = "getAdBlock", allEntries = true), @CacheEvict(value = "getAds", allEntries = true), @CacheEvict(value = "getAllAds", allEntries = true), @CacheEvict(value = "getAdBlockOrder", allEntries = true)})
 public Integer insert(Ads ads) {
        return adsDAO.insert(ads);
 }
```

**Comment by dodgex** [comment]
I think this is not going to become part of the android annotations core. But you could [create a plugin](https://github.com/excilys/androidannotations/wiki/Creating-an-AndroidAnnotations-plugin) for that

**Comment by sytolk** [comment]
If its possible with plugin is better. I will try to write plugin for this. Thanks!
