### ISSUE TITLE
JavaDoc for ItemSelect Annotation is outdated

### ISSUE THREAD

**Issue by chpasha** [excilys/androidannotations#1818]
According to documentation and source code any ItemSelect annotated method must have one boolean parameter as first param. The Example in JavaDoc states something different
```java
Example :
 * 
 * <pre>
 * &#064;ItemSelect(R.id.myList)
 * public void itemSelectedOnMyList() {
 * 	// ...
 * }
 * 
 * &#064;ItemSelect(R.id.myList)
 * public void myListItemPositionSelected(int position) {
 * 	// ...
 * }
 * 
 * &#064;ItemSelect
 * public void myListItemSelect(MyItem clickedItem) {
 * 	// ...
 * }
 * 
 * &#064;ItemSelect(R.id.myList)
 * public void myListItemPositionSelected(boolean selected, int position) {
 * 	// ...
 * }
```

**Comment by dodgex** [comment]
i just checked the code and you are right. but i wonder why the methods are [always called with true](https://github.com/excilys/androidannotations/blob/558b9088fdc2cd82988445ed86d60340b143a95f/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ItemSelectHandler.java#L80)... any idea @WonderCsabo ?

**Comment by chpasha** [comment]
since AdapterView.OnItemSelectedListener has two methods onItemSelected and onNothingSelected maybe the intention was to unite both method in one handler sending selected=false when onNothingSelected is fired
