### ISSUE TITLE
Shared preference double data type

### ISSUE THREAD

**Issue by kkrishnan90** [excilys/androidannotations#1820]
Hi, 
I've created a preference (shared preference) interface. But it does not support saving a double data typed preference. Like I can use string, long, stringres etc. But when I try to save a variable with double data type , it gives me a compile time error. 
Does your annotations support double data type in shared preference interface ?

**Comment by WonderCsabo** [comment]
It does not support `double`, because the underlying Android `SharedPreferences` is not supporting it. You have to remember that AA is a convenience wrapper around the Android API, we usually do not add new stuff.
