### ISSUE TITLE
Attach log4j to show all Rest Template activity

### ISSUE THREAD

**Issue by nishal** [excilys/androidannotations#1826]
There is one line mentioned in the Cookbook about using interceptors or log4j to enable Rest Template logging.

Does anyone know how to get log4j working with an Android app built using Gradle and AndroidStudio to log all Rest Template activity? This will make debugging a lot easier, and hopefully it logs the standard stuff like Retrofit and other networking libraries.

Interceptors are a problem in that @SetsCookie and @RequiresCookie seem to consume the cookie headers and displaying request and response headers only shows the other cookies that are not consumed. Writing ones own logging interceptor is great, but the ideal solution would be to have a good default logger that does't interfere with other Rest Template annotations and comes out of the box.

**Comment by WonderCsabo** [comment]
Please raise this issue to the upstream spring rest template project. However i suggest to use OkHttp as your request factory, which comes with a nice logger.
