### ISSUE TITLE
Add Runtime Permission Request for Android M

### ISSUE THREAD

**Issue by poovarasanvasudevan** [excilys/androidannotations#1831]
We needed this feature,Android M introduced Runtime Permission Request..

**Comment by dodgex** [comment]
as you can see in [this](https://github.com/excilys/androidannotations/issues/1537) we are not going to support permission requests. you could use [PermissionsDispatcher](https://github.com/hotchemi/PermissionsDispatcher/) for requesting runtime permissions.
