### ISSUE TITLE
AS does not recognize @Rest

### ISSUE THREAD

**Issue by hopewise** [excilys/androidannotations#1837]
In Android Studio, @Rest looks in red color, then it suggests to create annotation 'Rest':
![screen shot 2016-08-22 at 2 24 07 pm](https://cloud.githubusercontent.com/assets/1061157/17853284/290114c0-6874-11e6-9654-f3f2ac2a8620.png)

The same for @Post & @Get, can you please tell me how to solve this?
I am already using retrofit, and I can simply do `import retrofit2.http.POST;` but what shall I import incase of this library? also, why AS does not recognize the annotations of Rest?

**Comment by dodgex** [comment]
do you have the dependencies of the AndroidAnnotations rest plugin added?

**Comment by dodgex** [comment]
should be
```
    apt "org.androidannotations:rest-spring:$AAVersion"
    compile "org.androidannotations:rest-spring-api:$AAVersion"
```

**Comment by hopewise** [comment]
I've missed that, thanks,  it worked 👍
