### ISSUE TITLE
How to pass a constant to @Rest ?

### ISSUE THREAD

**Issue by hopewise** [excilys/androidannotations#1838]
How would I use a constant var in `@Rest` ?
Like for example:

```
@Rest(Service.BASE_API_URL)
public interface UserClient { 
```

where `BASE_API_URL` is a constant defined as: 

`public static final String BASE_API_URL = "http://192.168.1.34:9907/";`

Currently, I get this error:
![screen shot 2016-08-22 at 4 13 36 pm](https://cloud.githubusercontent.com/assets/1061157/17855846/6f3f8ec6-6883-11e6-8b3d-340166b3c726.png)

**Comment by WonderCsabo** [comment]
Check out the [wiki](https://github.com/excilys/androidannotations/wiki/Rest%20API#root-url).

Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by hopewise** [comment]
Sure, ok, thanks
