### ISSUE TITLE
Error:The generated com.example.testparsers.R class cannot be found

### ISSUE THREAD

**Issue by pashko00710** [excilys/androidannotations#1840]
Good afternoon. Faced with such a problem that flies the mistake , tried to substitute and
apt {
    arguments {
        androidManifestFile variant.outputs [ 0 ] .processResources.manifestFile
        resourcePackageName android.defaultConfig.applicationId
    }
} , But there is further crashes another error Error: ( 34 , 0 ) Can not get property 'processResources' on null object. Help me, please.

**Comment by dodgex** [comment]
when you are using Android Annotations 4.0+ you should no longer need the `androidManifestFile variant.outputs [ 0 ] .processResources.manifestFile` line.

**Comment by pashko00710** [comment]
So I run it without error and crashes
Error: The generated com.example.testparsers.R class can not be found

**Comment by dodgex** [comment]
could you post the full build log?

**Comment by pashko00710** [comment]
The main point is that it is basically a complete log . I do rebuild the project and simply takes off two errors .

**Comment by dodgex** [comment]
when you run `gradlew build` only the error that it can't find the R class appears?!

is it possible that you share the project so that we can try to reproduce it?

**Comment by WonderCsabo** [comment]
You can try to add 

`androidManifestFile variant.outputs[0]?.processResources?.manifestFile`

However @dodgex is right, AA 4 should infer the path of the manifest and the R class. Something is wrong there.

**Comment by pashko00710** [comment]
Observed package id 'add-ons;addon-google_apis-google-22' in inconsistent location '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-22-1' (Expected '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-22')
Already observed package id 'add-ons;addon-google_apis-google-22' in '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-22'. Skipping duplicate at '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-22-1'
Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-23')
Already observed package id 'add-ons;addon-google_apis-google-23' in '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-23'. Skipping duplicate at '/Users/pashko00710/Library/Android/sdk/add-ons/addon-google_apis-google-23-1'


It logs when adding
androidManifestFile variant.outputs [ 0 ] ? . processResources? .manifestFile

Mistakes are the same .

**Comment by pashko00710** [comment]
I found a mistake , why is gradle wrong way prescribed , sorry to trouble you .

**Comment by WonderCsabo** [comment]
What was the problem?

**Comment by pashko00710** [comment]
Path to applicationId was not right ( part time ) , I have not changed , the first time with this encounter .

**Comment by rafa0809** [comment]
Hello @pashko00710 ! Can you explain in detail your problem or post your gradle file?

**Comment by ARaqeeb** [comment]
@pashko00710  can you please explain what you really did?

**Comment by ARaqeeb** [comment]
https://blog.jayway.com/2014/12/19/androidannotations-setup-android-studio/ 

The solution here. Remember to suffix _ after the name of the activity in the Manifest. Don't both if its showing red. Cheers!

**Comment by econBabar** [comment]
Getting Error:The generated xyz.R class cannot be found? My activity is extending from a base activity which is abstract? Please help.

**Comment by gillesbraun** [comment]
I didn't understand what @pashko00710  meant at first, but you need to use the correct applicationId in your app's build.gradle file
