### ISSUE TITLE
Method injection. Error: cannot find symbol variable resources_

### ISSUE THREAD

**Issue by optisamit** [excilys/androidannotations#1847]
If there are no `@XXXRes` annotated fields, method-based resource injection gives the error mentioned in the title

**Comment by dodgex** [comment]
Hey there, thanks for the report. I'll try to check what happens there. I hope to get tomorrow evening a hand on this. :)

**Comment by dodgex** [comment]
small update... just got a few minutes to check the issue and it was an easy fix. there should be a new snapshot available soon. could you try it please?

**Comment by WonderCsabo** [comment]
Snapshots are only deployed from the development branch, but i am checking the PR right now.
