### ISSUE TITLE
Firebase Crash reporting issue

### ISSUE THREAD

**Issue by TomboCZ** [excilys/androidannotations#1852]
Hello, 
my app use android annotations, firebase crash reporting and default proguard. But not even after uploading mapping file i see nothing. (cz.company.appname).

```
Exception java.lang.SecurityException: Requires READ_PHONE_STATE: Neither user 10054 nor current process has android.permission.READ_PHONE_STATE.
android.os.Parcel.readException (Parcel.java:1465)
android.os.Parcel.readException (Parcel.java:1419)
com.a.a.a.a$a$a.a (SourceFile:242)
cz.company.appname.b.a.b (SourceFile:151)
cz.company.appname.b.c.b (SourceFile:24)
cz.company.appname.b.i.a (SourceFile:122)
b.a.a.a$a.run (SourceFile:405)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:422)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 (ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
```

```
`-dontwarn com.squareup.**
-keepclassmembers class ** {
    @com.squareup.otto.Subscribe public *;
    @com.squareup.otto.Produce public *;
}
# Add this global rule
-keepattributes Signature`
```

**Comment by dodgex** [comment]
this has absolutely nothing to do with android annotations.

your issue is that you have to request the `READ_PHONE_STATE` permission in your manifest (or at runtime for android 6+)

and if i understand you post correctly you uploaded the bottom snippet to firebase as proguard mapping? if yes this is wrong, that is your proguard configuration. you can find the mapping in `%app_module_path%/build/outputs/mapping/release/`  it should be the mapping.txt

**Comment by TomboCZ** [comment]
The error it self is not issue. Issue is that i cant read my stacktrace becose of android annotations. Even stacktrace analyze tool in android studio cant do that. Crashlytics and firebase crash reporting tool show same stacktrace even after uploading mapping file. 

I use this configiration in gradle for release build.

```
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```

I just want to be able read crash report.

**Comment by dodgex** [comment]
I'm pretty sure that it is not an AA issue. I have AA in my App with proguard too and i can deopfuscate the stacktraces. I'm using crashlytics/fabric instead of firebase. The Mapping is uploaded by the fabric plugin.

**Comment by TomboCZ** [comment]
Ok, thanks. I am strating to think this is problem with proguard/mapping file.
