### ISSUE TITLE
[Question] How to configure androidannotations with Jack?

### ISSUE THREAD

**Issue by optisamit** [excilys/androidannotations#1853]
Hi,
android-apt has become obsolete recently, since Android Gradle plugin 2.2 was released in stable channel.
Could you please update your _Getting Started_ docs to show how to do a setup with Jack?
Thanks.

**Comment by WonderCsabo** [comment]
`android-apt` is not obsolete, becasuse the Jack toolchain is still experimental and disabled by default.

However you use it with AA. It is described [here](http://tools.android.com/tech-docs/jackandjill) how to enable annotation processing with Jack.

**Comment by optisamit** [comment]
@WonderCsabo Thanks for your help, but I still can't do it. Could you help me please?
I've added Jack, commented out every occurrence of apt and replaced `apt` dependencies with `annotationProcessor`. And then, if I try gradle syncing, I get this error:

> https://fabric.io/dog-advisor/android/apps/com.advisor.advisor.advisor/issues/57d5c6250aeb16625b0faeb5

Could it be a bug on Jack's side?

**Comment by WonderCsabo** [comment]
Yes, that error is coming from the Gradle build, AA is not even called at that point.

**Comment by niusounds** [comment]
In Gradle 2.2, AA works with only these codes:

```
dependencies {
    annotationProcessor 'org.androidannotations:androidannotations:4.1.0'
    compile 'org.androidannotations:androidannotations-api:4.1.0'
}
```

`android-apt` and `classpath 'com.neenbedankt.gradle.plugins:android-apt:1.+'` are not needed.

**Comment by WonderCsabo** [comment]
AFAIK the Jack toolchain is still experimental, we will add support and documentation when it will be stable.

**Comment by solgems** [comment]
any updates on this? 

even without using JACK, we can do:

```
annotationProcessor "org.androidannotations:androidannotations:4.1.0"
compile "org.androidannotations:androidannotations-api:4.1.0"
```

instead of 

```
apt "org.androidannotations:androidannotations:4.1.0"
compile "org.androidannotations:androidannotations-api:4.1.0"
```


but how do we pass the path of the manifest file to the new annotation processor?

```
apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        resourcePackageName android.defaultConfig.applicationId
        // if you have multiple outputs (when using splits), you may want to have other index than 0

        // you should set your package name here if you are using different application IDs
        // resourcePackageName "your.package.name"

        // You can set optional annotation processing options here, like these commented options:
        // logLevel 'INFO'
        // logFile '/var/log/aa.log'
    }
}
```

from http://tools.android.com/tech-docs/jackandjill we can do something like,
but how do we handle all the different variants like the trick above (documented by https://bitbucket.org/hvisser/android-apt)

```
android {
...
    defaultConfig {
    ...
        javaCompileOptions { 
            annotationProcessorOptions {
                className 'com.example.MyProcessor'

		// Arguments are optional.
                arguments = [ foo : 'bar' ]
            }
        }
    }
    ...
}
```

**Comment by WonderCsabo** [comment]
We still not support Jack, as it is experimental and has lots of bugs.

You cannot add per-variant annotation processing options with the new DSL, i reported this [issue](https://code.google.com/p/android/issues/detail?id=210753) to Google a while ago. However, you can have an ugly workaround, as can be seen in the issue description:

```groovy
android.applicationVariants.all { variant ->
  variant.variantData.variantConfiguration.javaCompileOptions.annotationProcessorOptions.arguments =
    ['androidManifestFile': variant.outputs[0]?.processResources?.manifestFile?.absolutePath]
}
```

**Comment by solgems** [comment]
cool, thanks for highlighting the ticket! 👍
