### ISSUE TITLE
Synchronous API call made in @Background method not executing

### ISSUE THREAD

**Issue by btrautmann** [excilys/androidannotations#1855]
@Background
    void logUserInBackground(@Nonnull final String userLogin, @Nonnull final String userPassword) {
        Log.d(LOG_TAG, "Logging user in on background thread...");
        LoginService loginService = new LoginService();
        Response genericResponse = loginService.login(userLogin, userPassword);
        Log.d(LOG_TAG, genericResponse.toString());
        logUserInForeground(genericResponse);
    }

This method will not execute on Jellybean devices (the Log doesn't even print). When I step through it, the `execute()` method within the `Task` created in `BackgroundExecutor` does not even get hit. Have there been any issues with Jellybean with `@Background` annotation?

It should be noted that another method that does not make any API calls runs fine with the `@Background` annotation on the same device.

**Edit:** I actually took all code out of this method except for a log that prints "Hello world" and it still isn't executing. So, why would a `@Background` method not execute on Jellybean?

**Comment by btrautmann** [comment]
Ok I realized that this issue was caused by another method that had a `wait()` in it, which seems to keep this method from running. Is it true that only one `@Background` thread can be run at a time? If so, is this a limitation on Jellybean and prior devices? KitKat and above run fine with this same implementation.

**Comment by WonderCsabo** [comment]
You can [set your executor](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java#L225) which handles how it executes the parallel tasks. By default, we use [this one](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java#L36).
