### ISSUE TITLE
Android Manifest Issue

### ISSUE THREAD

**Issue by stankowalczyk** [excilys/androidannotations#1858]
Hi There,

I've started a new project using a new clean install of Android Studio 2.2, and I've added in all the necessary stuff into my `build.gradle` as per your guide [here](https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle).

However I've encountered an issue, I get an error saying:

```
Error: Cannot read packageName from ###\src\main\AndroidManifest.xml
```

But as it turns out my manifest file is under `###\app\src\main\AndroidManifest.xml` and not `###\src\main\AndroidManifest.xml`.

Now I have a feeling that there is something I'm missing, or haven't configured correctly - if so please let me know what to change.

Please let me know if you need any more information!

**Comment by WonderCsabo** [comment]
The `androidManifestFile` option is no longer needed, because AA is inferring it from the project. Can you remove it? Besides, that should not point to the manifest from the source, but to the full, merged manifest, which has the `packageName` node.

**Comment by stankowalczyk** [comment]
Apologies for the delay - I've removed `androidManifestFile` as asked, however I still have the same issue. Just in case I've made a mistake elsewhere I decided to open a new clean project and try again - same result.

**Comment by WonderCsabo** [comment]
Can you share the project so we can check?

**Comment by stankowalczyk** [comment]
No problem. Please find it here: https://github.com/stankowalczyk/gleam

**Comment by WonderCsabo** [comment]
@stankowalczyk your project had several errors, most of them unrelated to AA. I fixed everything in [my fork](https://github.com/WonderCsabo/gleam).

The *Cannot read packageName* was not coming from AA, it was coming from the Android Gradle plugin - because you applied that plugin to your root project, which is not an android app.

**Comment by stankowalczyk** [comment]
Apologies!  Thank you for taking the time to correct my mistakes - I greatly appreciate it. Please feel free to remove your fork.
