### ISSUE TITLE
Creating Plugin Problem: AnnotationHandlers processing order

### ISSUE THREAD

**Issue by smaugho** [excilys/androidannotations#1859]
Hi,

A big limitation with the new Plugins, is that all AndroidAnnotations Handlers are executed before the Plugins. In my case, this was a big issue for creating a plugin, where the process should be executed before the @After Injects methods. 

A good solution in my case was to  add a getBeforeTarget to the AnnotationHandler interface, and add the AnnotationHandlers in a sorted way, following the getBeforeTarget (or normal order when this method returns NULL). 

There's of course different ways to implement this. 

Please, if you see this fix important for AndroidAnnotations, I can try to make a Pull Request from this commit https://github.com/smaugho/androidannotations/commit/cf42770934d4588652e29a9e2d290da272964416

I'm just not sure of this, cause' I've been doing several modifications to AndroidAnnotations in order to use it in a different Framework.

Regards

**Comment by WonderCsabo** [comment]
Can you elaborate on why it is a problem in your case?

**Comment by smaugho** [comment]
This is a big problem in my framework, a Wrapper for AndroidAnnotations, that I started before the existence of Plugins (now, maybe I can create it as a plugin).  But I will build an example that will be an issue in AndroidAnnotations Plugins.

Let's say that I use a [@Populator](https://github.com/smaugho/declex/wiki/Populating%20Views), this is an annotation to automatically populate a complete user interface from within an @EBEan, matching the Id's in the Layouts with the Fields of the @EBean object. I use it in my framework also for Pupulating ListViews and RecycleViews (getting rid of the annoying Adapters):

>This automatically loads a list of objects from SQLite, and fills a ListView with id `users`
```java
@Model  //This is similar to @Bean 
@Populator
List<User> users;
```

Let's say now that I want to animate the list to the last element once that is shown, a good way will be in the @AfterViews, use the inferred ListView class to call a softScroll, to the end, but in the way that it is by default in AndroidAnnotations right now, I'm not able to use AndroidAnnotations methods to do this, so I should create my own @AfterPopulate, to handle this situation. In fact, since the @Model Handler is executed after all the Core Handlers, all the methods inserted in the code will be at the end, so, it is impossible to insert "functions" between the "Life Cicle" of AndroidAnnotations. 

See that if the Framework gives support to Insert the @Model at the same level that @Bean, so that the injection is done where it should, @Populator, after the Injection of Views has taken place, then the created plugin will be more AndroidAnnotations-friendly, permitting a full integration of the Plugin with the AndroidAnnotations methods. 

I hope to have explained correctly with this example the situation. As this, there's a huge amount of situations in which this can become a mandatory functionality.

Thanks ;).

**Comment by smaugho** [comment]
I will Fork again the project and I will prepare better 2 features that I programmed and I think will be very useful (this one above, and also the AndroidManifestFinder extracts "meta-data" fields from the Manifest, this is completely necessary for any plugin that needs this data; for example, to integrate with Third Party libraries (Facebook, Google) or any library that uses meta-data in the manifest.

**Comment by WonderCsabo** [comment]
If i understand well, the problem is that you cannot add new injection annotations, which will inject code before `@AfterInject` and co., because the your handlers are being called after core AA handlers.

This was indeed an issue, but we addressed this in a way that order of the handlers does not matter any more.

For injections, you have to use `holder.getInitBodyInjectionBlock()`. This block is guaranteed to be before the after inject method calls, so order of your handler is not a problem.

**Comment by smaugho** [comment]
Ok, yes, it works then... but of course, it applies only to this specific example... 

Maybe in the future will be much more useful (for instance, I permit in my own copy to replace annotation handlers, @AfterViews by my own Handler which permits to make injection of the views in the method, very useful:

```java

@AfterViews
void initSomething(ListView myList) }
    //DO SOMETHING WITH THE VIEW
}
```

Not sure if you are willing to add something like this for next versions. I will make some suggestions anyway :), maybe some of them are useful in a later stage.

**Comment by WonderCsabo** [comment]
Yep, this is just an example, but the order really does not matter for most of the annotations.

We considered sorting the handlers, but decided not to do so when implementing the plugin system. General sorting needs more complicated logic then your commit, we have to do a topological sort.
