### ISSUE TITLE
Reading the Meta-Data information from AndroidManifest

### ISSUE THREAD

**Issue by smaugho** [excilys/androidannotations#1860]
For the creation of some plugins, it is very useful to be able to read the Meta-Data information from the AndroidManifest file.

For instance, in the implementation of a plugin that integrates with Facebook SDK, it is very useful to validate the correct configuration of the Application:

```java

		final String FACEBOOK_APP_ID_NAME = "com.facebook.sdk.ApplicationId";
		final String facebookAppIdValue = getEnvironment().getAndroidManifest().getMetaDataQualifiedNames().get(FACEBOOK_APP_ID_NAME);
		if (facebookAppIdValue == null) {
			valid.addError( 
					"Your application must include the meta-data named " + FACEBOOK_APP_ID_NAME + "." + 
					"\nEx. <meta-data android:name=\"com.facebook.sdk.ApplicationId\"" +
					"\n				android:value=\"<Your Facebook App Id>\"/>"
				);
		}
		
		final String FACEBOOK_LOGIN_ACTIVITY_NAME = "com.facebook.LoginActivity";
		if (!getEnvironment().getAndroidManifest().getComponentQualifiedNames().contains(FACEBOOK_LOGIN_ACTIVITY_NAME)) {
			valid.addError( 
					"Your application must declare " + FACEBOOK_LOGIN_ACTIVITY_NAME + " activity." + 
					"\nEx. <activity android:name=\"com.facebook.LoginActivity\"/>"
				);
		}

```

I did already an implementation for this feature, adding a getMetaDataQualifiedNames method to the AndroidManifest  https://github.com/excilys/androidannotations/commit/86f6f18dfcbdf0407460f2296c72c925ddc5d742

There's many 3rd parties libraries that check for Meta-Data information, this would facilitate the integration and validations with such libraries.

**Comment by WonderCsabo** [comment]
Feel free to open a pull request with this feature. Thanks.
