### ISSUE TITLE
Blocks and methods in Holders

### ISSUE THREAD

**Issue by smaugho** [excilys/androidannotations#1862]
The current GeneratedClassHolder structure solves all the requirements of AndroidAnnotations, but once that this moves toward Plugins implementations, there's some feature that would help to improve this structure, and will make life easier for Plugins Developers.

Currently, each GeneratedClassHolder holds all the JBlock and JMethod objects that it requires for the current AndroidAnnotations implemented in the CorePlugin

Ex.
```java
	private JMethod onViewChanged;
	private JBlock onViewChangedBody;
	private JBlock onViewChangedBodyInjectionBlock;
	private JBlock onViewChangedBodyAfterInjectionBlock;
	private JBlock onViewChangedBodyBeforeInjectionBlock;
	private JVar onViewChangedHasViewsParam;
	protected Map<String, FoundHolder> foundHolders = new HashMap<>();
	protected JMethod findNativeFragmentById;
	protected JMethod findSupportFragmentById;
	protected JMethod findNativeFragmentByTag;
	protected JMethod findSupportFragmentByTag;
```

If a new method is inserted from within AndroidAnnotations Core Plugin, a new field is added to the GeneratedClassHolder, and this will solve the problem of interaction with the same JMethod or JBlock between different Annotation Handlers.

But when you are from within a Plugin, the GeneratedClassHolder cannot be modified with this purpose. I propose to create a Map<String, JBlock>  in the BaseGeneratedClassHolder to solve this issue, the key will reference the method or block name.

For instance, I have a Plugin that creates an initializer for an EBean. This basically creates a method, right now, when I'm from within a different Handler, I should check the existence of the method before creating it, if it doesn't exists it's created:

For instance
```java
		String fieldName = element.getSimpleName().toString();
		JMethod putModelMethod = holder.getGeneratedClass().getMethod(
				"_put_" + fieldName,
				new AbstractJType[] {getClasses().STRING, getClasses().STRING, getJClass(Runnable.class)}
			);
		if (putModelMethod == null) {
			putModelMethod = createPutModelCall(element, holder);
		}
```

with this I'm solving the Lack of storing the generated methods in the GeneratedClassHolder.. but when it is a block, then the solution is much more dirty, I should save Globally (or exchange between Handlers in the creation process), a Map<Holder, JBlock>, for each one of the blocks that I want to implement....  if the Holder had by default this Map that I suggested, the implementation has only to share the "key" for the new method or block, something compatible with create a new method in the Holder (since that new method is the key for sharing this information). 

I hope to have been able to transmit the issue.

**Comment by WonderCsabo** [comment]
We already addressed this issue by the *plugin holder* concept. Please check out [how does it work](https://github.com/excilys/androidannotations/blob/fd5527a037d4523eab0e0ac40611ce9f5f0522ac/AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/handler/OrmLiteDaoHandler.java#L89).

**Comment by smaugho** [comment]
Yes, very good. Perfect!.
