### ISSUE TITLE
CorePlugin Annotation Handlers Replacements

### ISSUE THREAD

**Issue by smaugho** [excilys/androidannotations#1863]
It can be very useful in the framework, to be able to Replace the Core Annotation Handlers, with a different implementation. This will add much more dynamic in the Plugin System, and it is a feature very simple to implement.

Basically, the AnnotationHandler interface can define a method (let's say, replacedTarget), by default the method can return NULL, but if it returns a Target name, then that specific Target is searched in the CorePlugin, and instead of inserting this one, a new one is inserted.

Of course, there's some programmers that if they do a bad job, this can make the Lib don't to work correctly, but that's not a problem of AndroidAnnotations, but of the specific plugin, things like Plugin Statibility and Conflicts between plugins can be address in the future.

For instance, I'm making an implementation that permits the Full Injection of any view in any annotated method, this by default has not to be the behavior of AndroidAnnotations, but can be very useful for other programmers, that prefer inject directly in the method the views

Ex.
```java
@Click
public btnSetTextView(TextView textView) {
    textView.setText("Hello World");
}
```

Even if AndroidAnnotations has a @ViewById, to have something like this is really useful, specially in @AfterViews, where some times, is only needed to configure some specific Views in the interface, and that object is not modified anywhere else (so a @ViewById field is really an unnecessary aggregate in such case).

In general, this will give wings to Plugin Developers to make a much more powerful AndroidAnnotations in the future ;).

**Comment by WonderCsabo** [comment]
I do not really understand why this feature is needed? You can just add a new annotation handler, and the user should import your annotation (he/she does it anyway). It does not really matter that the default handler is there.

Moreover, i think it can be really confusing to replace the behavior of core AA annotations.

**Comment by smaugho** [comment]
Ok, I will explain you an idea that I have, that will be really a good Plugin, but without something like this, will require reimplementation of many things...

I will be focus in near future in the implementation of plugins for Third Parties, I was thinking in implementing a Plugin for Google Analytic. In general, in this Analytics platforms, the programmer have to implement through all the system, every time the User clicks or make an action, a message is sent to the Analytic platform... If a programmer is able to subclass the normal Handlers, and add a method to include by default Analytics, only adding the Plugin to the Build Path will be enough to have automatically Google Analytics implemented by default in whole the application, using all what was programmed, in each @Click, or @EActivity will be inserted the Analytics code.. of course, the programmer can disable this behavior, have specific Annotations to say what he wants to register and so on... but only to be able to change the Handlers in this situation, will give to programmers a very powerful tool, to implement third party libraries through AndroidAnnotations...

```gradle
dependencies {
    apt "org.androidannotations:google-analytics:$AAVersion"
    compile "org.androidannotations:analytics-api:$AAVersion"
}
```

This will be enough to integrate a third party library!!...

**Comment by smaugho** [comment]
I hope to make sense :)... it is not the same to say: This Plugin add Google Analytics but you have to go through all your code to put this annotation (this is exactly what a programmer have to do when implementing Analytics, go through all the code to add some lines of code, very annoying for big apps).... Than instead to say, Add this in the build.gradle file, and you have Google Analytics implemented out of the box ;)

**Comment by WonderCsabo** [comment]
@smaugho yes, it can work for your plugin, if you replace all of the core annotations. However, what if multiple plugins want to replace the same annotation? Anyway, an annotation's behavior should not be replaced at all. The plugin system was designed to add ability to add new annotations, not change already existing ones. This is something we would not like to change in the future.
