### ISSUE TITLE
AndroidAnnotations crashed when using support:appcompat-v7 version 23 +

### ISSUE THREAD

**Issue by huunam118** [excilys/androidannotations#1867]
All Info I already added in this [stackoverflow link ](http://stackoverflow.com/questions/39910537/androidannotations-crashed-when-using-supportappcompat-v7-version-23). Please give me some suggestions.

**Comment by WonderCsabo** [comment]
I answered the question on SO. (You do not have to report SO questions here, we follow the android-annotations tag on SO and answer those questions.)
