### ISSUE TITLE
Provide constructor injection and setter injection (?)

### ISSUE THREAD

**Issue by pyricau** [excilys/androidannotations#204]
We currently force the users to have at least package private (default) scopes for their fields. Some users might not appreciate that. We could allow constructor injection / setter injection, this way :

```java
@EBean
public class MyBean {
  
  private View myView;

  private MyOtherBean myOtherBean;

  MyBean(@Bean MyOtherBean myOtherBean) {
    this.myOtherBean = myOtherBean;
  }

  void setMyView(@ViewById View myView) {
    this.myView = myView;
  }

}
```

**Comment by dodgex** [comment]
8 months without feedback. I just started to play with method injection for `@Bean`. I have a working  sample. I also tested with multiple values to inject. while that worked, there are issues with the ability to provide a implementation class in the `@Bean.value()` attribute. so i think it is the best to stay with the one injected element per method approach mentioned above.

**Comment by WonderCsabo** [comment]
Sorry, @dodgex i did not saw this issue.

> adding the annotation on the parameter is not a good idea

Why? We already have multiple annotations working just fine, and i just added two more.

**Comment by dodgex** [comment]
@WonderCsabo actualy i'm not sure why i wrote that. iirc there was the discussion if we want to have annotations on a parameter and we decided to have them after this comment.

btw: if you want to see the current implementation you can see it here: https://github.com/dodgex/androidannotations/tree/204_method_injection

**Comment by WonderCsabo** [comment]
@dodgex it is a good idea. :) I see no problems with it. Actually i think it is much more natural then the method annotation. This is used by every DI system.

**Comment by dodgex** [comment]
@WonderCsabo uhm, i'm not sure if i understand your comment. what is more natural? annotation on param?

**Comment by WonderCsabo** [comment]
Yeah, the param, of course. Becase the value actually be injected to the parameter. Just like with `@Receiver.Extra`, or `@Inject` in guice

**Comment by dodgex** [comment]
okay. shall i create something like `@Bean.Impl` as parameter annotation? that way i could implement multiple beans per method injection.

**Comment by WonderCsabo** [comment]
What is the problem with this?
```java
void setBeans(@Bean(MyBeanImpl.class) MyBean bean, @Bean(MyBeanOtherImpl.class) MyBean bean2) {
 this.bean = bean;
 this. bean2 = bean2;
}
```
:confused:

**Comment by WonderCsabo** [comment]
FYI: maybe you should have a look at this branch. https://github.com/excilys/androidannotations/issues/883#issuecomment-41133044.

**Comment by dodgex** [comment]
@WonderCsabo the problem i currently see is that i have no idea how to implement the process. that way we would get two calls to process. one for each parameter. but the result should be only one call to `setBeans`.

**Comment by WonderCsabo** [comment]
Just create a map with setter methods, and create the method lazily in it. This is done by lot of handlers actually.

**Comment by dodgex** [comment]
hu? can you tell me one handler that does that, that i can see how it is done?

**Comment by WonderCsabo** [comment]
You can check out how `@ViewById` and `@Click` works. Actually they are reusing the same `findViewById()` call, if it is possible.

**Comment by dodgex** [comment]
they use the same call/return value. but in this case it is the other way. we would need to have 1 call with multiple parameters. but yeah, that should be doable in a similar way...

**Comment by WonderCsabo** [comment]
Yeah, but the idea is the same about lazy generating the method call itself.

BTW, you can check out google/dagger and transfuse projects to get some ideas.

**Comment by dodgex** [comment]
hmm for some reason the annotations on param only get validated, but not processed. do you have an idea why?

**Comment by WonderCsabo** [comment]
I guess the problem that we already registered the same annotation for fields. For now create a new annotation (`@BeanSetter`), we can solve the architecture issue later.

**Comment by dodgex** [comment]
i debugged it: the problem is that the ModelProcessor is currently not able to handle method parameters.

**Comment by WonderCsabo** [comment]
Eh, sorry. Our current paramter handlers do nothing, the "parent" method handler is doing the processing actually. 

We should modify ModelProcessor. We should also modify it to be able to use the same annotation on different element types.

**Comment by dodgex** [comment]
i quickly hacked it a bit and now it processes the annotations, regardless of thier location (field, method or param)

**Comment by dodgex** [comment]
its working! :)

```java
@Bean
public EmptyDependency dependency;

@Bean
protected void injectDependency(EmptyDependency methodInjectedDependency) {
}

protected void injectDependency2(@Bean EmptyDependency dep) {
}
```

**Comment by dodgex** [comment]
this one works too:
```java
protected void twoDependencies(@Bean EmptyDependency bean1, @Bean(SomeImplementation.class) SomeInterface bean2) {
}
```

currently this generates one instance of the bean per injection...

**Comment by WonderCsabo** [comment]
Great work! :+1: Maybe this is the time to open a WIP PR, because we are not specifying the feature, but the implementation.

**Comment by dodgex** [comment]
doing some rough cleanup before creating PR. some parts of the code are a bit hacky ;)

**Comment by WonderCsabo** [comment]
Setter injection is implemented. Constructor injection only makes sense in case of beans. If there is need for that, we will open a new issue.
