### ISSUE TITLE
Use @TargetApi() annotation to avoid Lint errors

### ISSUE THREAD

**Issue by wurfkeks** [excilys/androidannotations#256]
Calls that need a specific minimum SDK should be marked with @TargetApi(<version>) to avoid Lint errors.

For example the onKeyDown() method checks for SDK version and then calls onBackPressed() if the check is successful.
onBackPressed() requires API level 5, so Lint will mark this call as an error if the project's min SDK level is below 5.
Annotate onKeyDown() with @TargetApi(5) would suppress the Lint error.

**Comment by WonderCsabo** [comment]
It seems it has a low-demand issue. Lint should be ignored in generated classes. We do the best, though.
