### ISSUE TITLE
Custom REST Headers

### ISSUE THREAD

**Issue by nachowski** [excilys/androidannotations#323]
At the moment `@Accept` is the only annotation that allows you to set an Accept-Encoding header on a REST call. It would be great to have a more generic implementation that could set multiple headers. 

I know that this is already possible through a Spring Interceptor or through a custom `HttpComponentsClientHttpRequestFactory` but this is more or less on a global basis and cannot be easily changed for different methods.

I would propose a new annotation that can go inside a `@Rest` interface. Either something like this:
````
@Post
@Header(key="content-type",value="xxx")
@Header(key="authorization",value="yyy")
String foo();
````

or like this: 

````
@Post
@Headers(contentType="xxx",authorization="yyy")
String foo();
````

Since `HttpHeaders` already has all the relevant setters, it should be easy to implement. Thoughts?

**Comment by WonderCsabo** [comment]
Finally this is implemented. :)
