### ISSUE TITLE
Improve OrmLite support by adding helper class

### ISSUE THREAD

**Issue by PerfectCarl** [excilys/androidannotations#335]
I read the proposal for concise ormlite annotations #289, and started wondering if we could also use annotations to generate the boilerplate for orm helper class ?

Let's take a simple example : a simple database with 3 tables (group, user and message).

The annotated code would look like this : 

```java
@OrmLite(config = R.raw.ormlite_config, database = "iome.db", version = 25)
public class DatabaseHelper extends AnnotatedOrmLiteHelper {

	@OrmLiteDao
	Dao<ProviderDb, String> groupDao;
	
	@OrmLiteDao
	UserDao userDao;

	@OrmLiteDao
	Dao<Message, Integer> messageDao;

	@AfterCreate
	private void initProviders() {
		System.out.println("Version : " + getVersion());
		System.out.println("Database : " + getDatabaseName());
	}

	@AfterUpdate
	private void initUsers() {

		AssetManager assetManager = getContext().getAssets();
		... 

	}


	/**
	 * Sample of a specific dao method
	 * @param providerId
	 * @return
	 */
	public User getUserByProviderId(String providerId) {
		try {
			Dao<UserDb, Integer> dao = userDao;
			List<UserDb> result = dao.queryForEq("providerId", providerId);
			if (result.size() > 0)
				return result.get(0).toUser();
		} catch (SQLException e) {
			..
		}
		return null;
	}
}
``` 
The helper above is also used to implement dao specific methods(`getUserByProviderId`)  : sometimes creating a custom dao class to implement just one method could be overkill.

In the example the helper uses a config file: the helper reads the model description from a file (`R.raw.ormlite_config`) that must be regenerated each time that the model is modified.
I think that it would be great that the annotation processor regenerates the ormlite_config file each time it runs (if the config parameter is defined)

More info about ormlite_config there : http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_4.html#SEC42

The class `AnnotatedOrmLiteHelper `  adds the following getters : 
* `getContext()` : returns the android context
* `getVersion()` : returns the database version
* `getDatabaseName()` : returns the database name

As for the generated code, I am not sure but that could be something along the lines of : 
```java
public class DatabaseHelper_ extends OrmLiteSqliteOpenHelper {

	private static final String DATABASE_NAME = "iome.db";
	private static final int DATABASE_VERSION = 25;

	private Dao<ProviderDb, String> groupDao;
	private Dao<UserDb, Integer> userDao;
	private Dao<Message, Integer> messageDao;

	private DatabaseHelper cl ;

	private final Context context;

	public DatabaseHelper(Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION,
				R.raw.ormlite_config);
		this.context = context;
	}

	@Override
	public void onCreate(SQLiteDatabase sqliteDatabase,
			ConnectionSource connectionSource) {
		try {
			TableUtils.createTable(connectionSource, ProviderDb.class);
			TableUtils.createTable(connectionSource, Message.class);
			TableUtils.createTable(connectionSource, UserDb.class);
			cl.initProviders();
		} catch (SQLException e) {
			Log.e(DatabaseHelper.class.getName(), "Unable to create database",
					e);
		}
	}

	@Override
	public void onUpgrade(SQLiteDatabase sqliteDatabase,
			ConnectionSource connectionSource, int oldVer, int newVer) {
		try {
			TableUtils.dropTable(connectionSource, ProviderDb.class, true);
			TableUtils.dropTable(connectionSource, Message.class, true);
			TableUtils.dropTable(connectionSource, UserDb.class, true);
			onCreate(sqliteDatabase, connectionSource);
			cl.initUsers();
		} catch (SQLException e) {
			Log.e(DatabaseHelper.class.getName(),
					"Unable to upgrade database from version " + oldVer
							+ " to new " + newVer, e);
		}
	}

	private void initDaos() throws SQLException {
		if (groupDao == null) {
			groupDao = getDao(ProviderDb.class);
		}
		if (userDao == null) {
			userDao = getDao(UserDb.class);
		}
		if (messageDao == null) {
			messageDao = getDao(Message.class);
		}
	}

	public User getUserByProviderId(String providerId) {
		return cl.getUserByProviderId( providerId ) ;
	}

}

``` 
I don't know how the initialization of the daos must be done. In my sample, I just created a `initDaos()` method that needs to be called at some point. I'm not sure where. 

And I resent the fact that the daos are now initialized even if they're not used. 
A lazy initialisation would have been much better...

Anyway, this is my first time with androidannotations, any feedback is appreciated :)

Cheers,
Carl.

**Comment by WonderCsabo** [comment]
It is too complicated, and we cannot support all use cases. I think the current implementation is *good enough*.
