### ISSUE TITLE
With latest code, my library project is no longer generating files

### ISSUE THREAD

**Issue by rockytriton** [excilys/androidannotations#600]
I switched from 2.7.1 to the 3.0 snapshot after a successful build.  My regular android project builds the apt_generated files but my library project doesn't.  Is there something special I need to do to my library project since 2.7.1?

**Comment by WonderCsabo** [comment]
Since the new Gradle build system, library projects have AndroidManifest.xml R.java and all the goodies. So AA works well with the official way. Unfortunately we have no resources to support other scopes, like non-Android libraries.
