### ISSUE TITLE
@CustomTitle and @ViewById of element in the custom title raises null pointer exception

### ISSUE THREAD

**Issue by tex** [excilys/androidannotations#686]
findViewById of element in the custom title is called in Activity_ before setFeatureInt causing null pointer exception when referenced later.

Any clues how to fix it?

**Comment by WonderCsabo** [comment]
Is this still a problem?

**Comment by WonderCsabo** [comment]
I am closing this because of the lack of response. Plea reopen if you experience this and add detailed info.

**Comment by craone** [comment]
If the kotlin package name contains keywords, it will not be generated, such as `switch`
