### ISSUE TITLE
Add annotation helpers to PreferenceActivity

### ISSUE THREAD

**Issue by pyricau** [excilys/androidannotations#7]
@pyricau, Jan 5, 2011
It might be a good idea to provide helpers for PreferenceActivity. 

Things such as @PreferenceScreen(R.xml.my_preference), and @Preference("key") on a field. 

Some annotations to had ValueChangeListeners might be nice too.

mail.michael.ludwig, Mar 20, 2011
Yes that would be very nice. Also clickHandlers to Preferences would be nice.

@pyricau, Jul 20, 2011
We should look at what RoboGuice already provides, to integrate the same kind of functionalities.

**Comment by WonderCsabo** [comment]
Forgot to close this. :grinning:
