### ISSUE TITLE
[Documentation error] Enhance Fragments - Creation of fragments

### ISSUE THREAD

**Issue by vpratfr** [excilys/androidannotations#720]
Documentation states:

> Please be aware that @FragmentById and @FragmentByTag can only inject fragments, not create them, so they must already exist in the activity (either by defining them in the layout or by creating them programmatically in onCreate().

However, when injecting a fragment in an activity, the injection happens in `MyActivity_.afterSetContentView_` which runs after `MyActivity.onCreate`. Consequence: the fragment member variable is nulled.

One should either create the fragment in 'MyActivity.onPostCreate` or the generated code should only retrieve the fragment if the member variable is null.

Code to reproduce:

    public class MyActivity extends Activity {
        @FragmentByTag("tag")
        MyFragment frag;
    
        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
    
            if (savedInstanceState==null) {
              frag = MyFragment_.builder().build();
              getFragmentManager().beginTransaction().add(R.id.content, frag,     "tag").commit();
            }
    
            // Generated subclass will now run the afterSetContentView_() method
            // which will do: frag = ((MyFragment) findNativeFragmentByTag("tag"));
        }  
    }

Proper code:

    public class MyActivity extends Activity {
        @FragmentByTag("tag")
        MyFragment frag;
    
        @Override
        public void onPostCreate(Bundle savedInstanceState) {
            super.onPostCreate(savedInstanceState);
    
            if (savedInstanceState==null) {
              frag = MyFragment_.builder().build();
              getFragmentManager().beginTransaction().add(R.id.content, frag, "tag").commit();
            }
        }  
    }

**Comment by WonderCsabo** [comment]
I do not think this is an error here. We inject the fragments after we call super.OnCreate().
