### ISSUE TITLE
Activity Annotation to inject the activity into a fragment

### ISSUE THREAD

**Issue by dalewking** [excilys/androidannotations#768]
Would like an @FragmentActivity annotation that can be used to inject the activity that the fragment that has been attached to. I know that you can call getActivity() to get the Activity, but the problem is that you often have to cast the result to expose the added functionality of the actual activity. Would be nice to have it injected and cast to the correct type behind the scenes.

**Comment by WonderCsabo** [comment]
Year passed, and i am starting to thing this annotation is not needed. First it is not a good pattern to couple the `Fragment` with the container `Activity`. One of the main purpose of the `Fragment` that it can be added to various places, but it is also a bad design anyway. It is better to communicate to the `Activity` via an `interface`, as suggested by the Android developer guide.
Moreover, this annotation not really saves lines from the user.
At last, this can be added in a plugin very easily.

@yDelouis @dodgex thoughts?

**Comment by dodgex** [comment]
I don't think that this is needed.

**Comment by WonderCsabo** [comment]
I am closing this for now.

**Comment by WonderCsabo** [comment]
After casting the Activity in Fragments lots of times in my current project, maybe i have to think over... :confused:

**Comment by LouisCAD** [comment]
Be it with an interface or a specific Activity, you always have to cast… I agree @WonderCsabo that being able to inject implemented interfaces or Activities with `@RootContext`would save some boilerplate, especially with activity names such as `EditFullScreenDialogActivity` (Don't worry, it's an abstract base class for [Full screen dialogs](https://www.google.fr/design/spec/components/dialogs.html#dialogs-full-screen-dialogs))

It would be nice to get at least `@RootContext`for `EFragment`s in 4.0 IMHO :smiley:

**Comment by sosite** [comment]
So... any chances to has eg. `@RootInterface` to fast get activity interface? :)

**Comment by WonderCsabo** [comment]
@sosite i do not plan this for now, but you can easily create your AA plugin since 4.0. Or contribute to core AA.
