### ISSUE TITLE
Add Builders generators

### ISSUE THREAD

**Issue by pyricau** [excilys/androidannotations#88]
I already implemented an annotation processor that can generates builders ("Josh Bloch Builders") : https://github.com/pyricau/BuilderGen

I think it could be nice to add these features directly into AA, especially for some data structures.

I'm not sure we need to be so strict for the attributes, maybe using an empty constructor and fields access / setter calls is OK.

Also notice that we could set fields using either setters or direct access if they have public / default / protected scopes and are not final. Do we also need configuration annotations ?

**Comment by rdsubhas** [comment]
Hi, it looks nice, but many of us already use [Project Lombok](https://projectlombok.org/features/index.html) and it already works seamlessly with AndroidAnnotations. It also provides a whole lot more including @Getter, @Setter, @Builder, @NoArgsConstructor, @AllArgsConstructor, auto generated ToString, Equals, HashCode and a whole lot more!

**Comment by WonderCsabo** [comment]
@rdsubhas Thanks for bringing attention to this! I agree, and this is also a bit out of the scope of AA. I am closing this ticket.
