### ISSUE TITLE
@WindowFeature and Sherlock

### ISSUE THREAD

**Issue by naixx** [excilys/androidannotations#898]
As ActionBarSherlock redefines constants of `Window` class using `long`, one can get a compile error using `@WindowFeature` as it accepts `int`

**Comment by WonderCsabo** [comment]
@naixx what class redefines the constants in `AppCompat`? `WindowCompat` uses ints.

**Comment by naixx** [comment]
@WonderCsabo `AppCOmpat` doesn't redefine anything unusual, it seems. So int references could be used. As this issue was actual using ActionbarSherlock.

**Comment by WonderCsabo** [comment]
I know, but you suggested to investigate AppCompat, since ActionBarSherlock is deprecated now.
I guess we can close this now?

**Comment by naixx** [comment]
I haven't checked if AA works well with `WindowCompat`. If it works, then we can close.

**Comment by WonderCsabo** [comment]
Yeah, it works well.
