### ISSUE TITLE
Allow ResponseErrorHandler to be specified for the rest template the same way as intercepters

### ISSUE THREAD

**Issue by jbejar** [excilys/androidannotations#926]
It would be nice to set theErrorHandler in one place at the top with the converters
Interceptors and Converters can be specified for the RestTemplate

https://github.com/excilys/androidannotations/wiki/Rest-API

See also 
http://docs.spring.io/spring/docs/3.0.x/api/org/springframework/web/client/RestTemplate.html#setErrorHandler(org.springframework.web.client.ResponseErrorHandler)

**Comment by WonderCsabo** [comment]
Implemented.
