### ISSUE TITLE
Annotating a varargs method creates an array-param method

### ISSUE THREAD

**Issue by WonderCsabo** [excilys/androidannotations#927]
Consider the following:
```java
@EActivity
public class MainActivity extends Activity
    @UiThread
    protected void varagsMethod(Object... params) {
        //
    }
}
```

The generated class will be this:

```java
public class MainActivity_ extends MainActivity
    @Override
    protected void varagsMethod(Object[] params) {
        //
    }
}
```

This results in the following warning: *Varargs methods should only override or be overridden by other varargs methods*.

**Comment by WonderCsabo** [comment]
It seems this can be implemented:

* we call [`isVarArgs()`](http://docs.oracle.com/javase/7/docs/api/javax/lang/model/element/ExecutableElement.html#isVarArgs%28%29) to decide the method has variable argument list or not
* if it has, we add the last parameter with [`JMethod.varParam()`](https://codemodel.java.net/nonav/apidocs/com/sun/codemodel/JMethod.html#varParam%28java.lang.Class,%20java.lang.String%29) instead of `JMethod.param()`

**Comment by yDelouis** [comment]
Implemented.
