### ISSUE TITLE
Possible Memory Leaks and missing onDestroyView cleanup

### ISSUE THREAD

**Issue by MasterEmit** [excilys/androidannotations#933]
Just read some discussion about the problem with fragments, that a missing cleanup of view references can cause a memory leak. 

http://stackoverflow.com/questions/13421945/retained-fragments-with-ui-and-memory-leaks

I checked the generated classes of android annotations and could not find any place, where views will be cleaned. We are able to see, that just switching fragments increases memory usage. We will try to write a small cleanup ourself shortly, but maybe it would be great to implement it at android annotations.

**Comment by WonderCsabo** [comment]
Finally fixed.
