### ISSUE TITLE
ORMLite Support: release OpenHelperManager?

### ISSUE THREAD

**Issue by LordOfBones** [excilys/androidannotations#943]
In the generated AA class the OpenHelperManager is used to call the method getHelper().

This helper is assigned to a private local member. However, the helper is not released but the ORMLite documentation specifies this should be done in an onDestroy setting.
(see http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_4.html#Use-With-Android) 

How come it isn't released in the generated class?

**Comment by WonderCsabo** [comment]
@yDelouis i just realized `@OrmLiteDao` is available in all component annotations. I think we should not allow it in `@EView` and `@EViewGroup`. WDYT?

**Comment by yDelouis** [comment]
It's quite the same question than removing `View` support from `@EBean`...

**Comment by WonderCsabo** [comment]
On the second thought, we still allow that, because some people are using `View`s instead of `Fragment`s.

I am closing this issue, because we cannot release the helpers in other components. We can revisit this if we ever implement #843.
